Repository bokeh/bokeh, pull requests merged in 2018-08, with the labels that each got.

#8132 Updating the docstring for the dimensions property for Band, Span and Whisker
  bokeh/models/annotations.py
Labels: status: accepted

#8130 Add tilt option to GMapOptions
  bokeh/models/map_plots.py
  bokehjs/src/lib/models/plots/gmap_plot.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
Labels: status: accepted

#8135 Replace use of return_future with gen.coroutine
  bokeh/protocol/receiver.py
Labels: status: accepted

#8127 Allow ability to overwrite existing glyphs in drawing tools
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/point_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
  sphinx/source/docs/user_guide/tools.rst
Labels: status: accepted, status: ready

#8139 initial work to support server selenium tests
  bokeh/_testing/plugins/bokeh.py
  tests/integration/test_server.py
Labels: status: accepted

#8145 Jsnsross/8142 span datetime
  bokeh/models/annotations.py
  bokeh/models/tests/test_annotations.py
Labels: status: accepted

#8147 Added FreehandDrawTool
  bokeh/_testing/util/compare.py
  bokeh/models/tools.py
  bokehjs/src/less/icons.less
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
  bokehjs/src/lib/models/tools/index.ts
  bokehjs/test/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/models/tools/edit/index.ts
  sphinx/source/_images/icons/FreehandDraw.png
  sphinx/source/docs/user_guide/examples/tools_freehand_draw.py
  sphinx/source/docs/user_guide/tools.rst
  tests/integration/tools/test_freehand_draw_tool.py
Labels: status: accepted

#8144 Add context manager and decorator to control property validation
  bokeh/core/properties.py
  bokeh/core/property/bases.py
  bokeh/core/property/tests/test_bases.py
  bokeh/core/tests/test_properties.py
Labels: status: accepted

#8154 Bryanv/more selenium
  bokeh/_testing/util/selenium.py
  tests/integration/widgets/test_button.py
  tests/integration/widgets/test_checkbox_button_group.py
  tests/integration/widgets/test_checkbox_group.py
  tests/integration/widgets/test_div.py
  tests/integration/widgets/test_dropdown.py
  tests/integration/widgets/test_paragraph.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_pretext.py
  tests/integration/widgets/test_radio_button_group.py
  tests/integration/widgets/test_radio_group.py
  tests/integration/widgets/test_select.py
  tests/integration/widgets/test_text_input.py
  tests/integration/widgets/test_toggle.py
Labels: status: accepted, tag: component: tests

#8161 Define {css,js}_resources blocks in the correct order
  bokeh/core/_templates/file.html
Labels: status: accepted

#8114 Add Dash marker glyph
  bokeh/models/glyphs.py
  bokeh/models/markers.py
  bokeh/models/tests/test_glyphs.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/api/typings/models/markers.d.ts
  bokehjs/src/lib/api/typings/plotting.d.ts
  bokehjs/src/lib/models/markers/index.ts
  examples/reference/models/Dash.py
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/reference/models/markers/dash.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/webgl.rst
Labels: status: accepted

#8173 Make TileRenderer smoothing configurable
  bokeh/models/renderers.py
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  examples/integration/tiles/tile_smoothing.py
Labels: status: accepted

#8184 Bryanv/8179 show accumulation
  bokeh/embed/elements.py
  bokeh/embed/notebook.py
  bokeh/embed/server.py
  bokeh/embed/standalone.py
  bokeh/embed/tests/test_elements.py
  bokeh/embed/tests/test_notebook.py
  bokeh/embed/tests/test_standalone.py
  bokeh/embed/tests/test_util.py
  bokeh/embed/tests/test_wrappers.py
  bokeh/embed/util.py
  bokeh/embed/wrappers.py
  bokeh/io/notebook.py
  bokeh/io/showing.py
  bokeh/io/tests/test_notebook.py
  bokeh/io/tests/test_showing.py
  bokeh/model.py
  bokeh/server/views/autoload_js_handler.py
  bokeh/util/string.py
  bokeh/util/tests/test_string.py
  tests/integration/widgets/test_div.py
  tests/integration/widgets/test_paragraph.py
  tests/integration/widgets/test_pretext.py
Labels: status: accepted

#8191 Fix Past & Future Issue with boxplot.py & Pandas 0.23.x
  examples/plotting/file/boxplot.py
  scripts/ci/install
Labels: status: accepted

#8194 remove non-functional arguments parameter
  bokeh/embed/server.py
  sphinx/source/docs/releases/1.0.0.rst
Labels: status: accepted

#8199 issues: none type: bug tag: examples Updated main.py
  examples/app/ohlc/main.py
Labels: reso: completed, status: accepted, tag: component: examples, type: task
