Repository bokeh/bokeh, pull requests merged in 2018-04, with the labels that each got.

#7723 Markdown description for PyPI
  conda.recipe/meta.yaml
  scripts/ci/install:deploy
  scripts/deps.py
  setup.py
Labels: status: accepted, tag: component: build, type: task

#7732 use IPython standard _repr_pretty_ method name
  bokeh/core/has_props.py
  bokeh/model.py
Labels: status: accepted

#7728 process categorical coords properly for multi-glyphs
  bokehjs/src/coffee/models/glyphs/glyph.ts
  examples/integration/glyphs/categorical_multi_glyphs.py
Labels: status: accepted

#7726 add support for rotating group and subgroup categorical tick labels
  .gitignore
  bokeh/core/enums.py
  bokeh/core/tests/test_enums.py
  bokeh/models/axes.py
  bokehjs/src/coffee/core/enums.ts
  bokehjs/src/coffee/models/axes/axis.ts
  bokehjs/src/coffee/models/axes/categorical_axis.ts
  examples/integration/axes/cat_labels_rotate.py
Labels: status: accepted

#7735 don't use --rerun
  conda.recipe/meta.yaml
  scripts/ci/test:unit
Labels: status: accepted

#7737 add missing return to cell editor view validate()
  bokehjs/src/coffee/models/widgets/tables/cell_editors.ts
Labels: status: accepted

#7739 lower bad pong messages to trace
  bokeh/server/views/ws.py
Labels: status: accepted

#7742 better error message if show arg is bad
  bokeh/io/showing.py
  bokeh/io/tests/test_showing.py
Labels: status: accepted

#7743 add option to disable wheel zoom on axes
  bokeh/models/tools.py
  bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.ts
  examples/models/file/dateaxis.py
Labels: status: accepted

#7747 fix error with link highlighting and external links
  sphinx/source/bokeh_theme/static/js/main.js
Labels: status: accepted

#7583 Switched from RBush to FlatBush
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/coffee/api/typings.d.ts
  bokehjs/src/coffee/core/hittest.ts
  bokehjs/src/coffee/core/util/spatial.ts
  bokehjs/src/coffee/external/flatbush.d.ts
  bokehjs/src/coffee/models/glyphs/bezier.ts
  bokehjs/src/coffee/models/glyphs/box.ts
  bokehjs/src/coffee/models/glyphs/image_url.ts
  bokehjs/src/coffee/models/glyphs/multi_line.ts
  bokehjs/src/coffee/models/glyphs/patches.ts
  bokehjs/src/coffee/models/glyphs/quadratic.ts
  bokehjs/src/coffee/models/glyphs/segment.ts
  bokehjs/src/coffee/models/glyphs/xy_glyph.ts
  bokehjs/src/coffee/tsconfig.json
Labels: status: WIP

#7749 Replace RBush with SpatialIndex in glyphs/hex_tile
  bokehjs/src/coffee/models/glyphs/hex_tile.ts
Labels: status: accepted, tag: component: bokehjs, type: task

#7746 Fix "bad file descriptor" error on travis ci
  bokeh/io/export.py
Labels: status: accepted

#7740 make CDS.column_names a read-only property
  bokeh/models/sources.py
  bokehjs/src/coffee/api/typings/models/sources.d.ts
  bokehjs/src/coffee/models/sources/columnar_data_source.ts
  sphinx/source/docs/releases/0.12.16.rst
Labels: status: accepted

#7752 Keep all declarations (d.ts) in external/
  bokehjs/src/coffee/core/util/formatters.d.ts
  bokehjs/src/coffee/external/node.d.ts
  bokehjs/src/coffee/external/numbro.d.ts
  bokehjs/src/coffee/external/proj4.d.ts
  bokehjs/src/coffee/external/timezone.d.ts
  bokehjs/src/coffee/external/typed_arrays.d.ts
  bokehjs/src/coffee/external/underscore.template.d.ts
Labels: status: accepted

#7753 Revert "don't use --rerun"
  conda.recipe/meta.yaml
  scripts/ci/test:unit
Labels: type: task

#7748 make ClientSession a context manager
  bokeh/client/session.py
  bokeh/client/tests/test_session.py
  bokeh/embed/server.py
  examples/embed/server_session/README.md
  examples/embed/server_session/bokeh_app.py
  examples/embed/server_session/serve.py
  sphinx/source/docs/user_guide/embed.rst
  sphinx/source/docs/user_guide/server.rst
Labels: status: accepted

#7755 Bryanv/6699 log filename
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
Labels: status: accepted

#7756 restore old custom.js contents if it exists
  tests/plugins/jupyter_notebook.py
Labels: status: accepted

#7763 Don't reopen temp files to avoid platform specific issues
  bokeh/io/export.py
  bokeh/io/tests/test_export.py
Labels: status: accepted

#7757 add reset signal to plots
  bokehjs/src/coffee/models/plots/plot.ts
  bokehjs/src/coffee/models/plots/plot_canvas.ts
  bokehjs/src/coffee/models/tools/actions/reset_tool.ts
Labels: status: accepted

#7764 Don't report multiple S3 upload errors for PRs submitted from forks
  tests/examples/examples_report_plugin.py
  tests/plugins/upload_to_s3.py
Labels: status: accepted

#7765 added 'pan' to the hexbin example
  examples/plotting/file/hex_tile.py
Labels: reso: completed, status: accepted, tag: component: examples, type: task

#7767 Type core/selection_manager and handle null hit test result
  bokehjs/src/coffee/core/selection_manager.ts
  bokehjs/src/coffee/models/renderers/glyph_renderer.ts
  bokehjs/src/coffee/models/sources/data_source.ts
  bokehjs/src/coffee/models/sources/remote_data_source.ts
Labels: status: accepted

#7760 Move outstanding integration tests to examples/integration
  bokeh/io/export.py
  bokeh/io/tests/test_export.py
  bokehjs/src/coffee/models/tiles/tile_renderer.ts
  examples.yaml
  examples/integration/glyphs/rect_log_axis.py
  examples/integration/plots/no_border_or_background_fill.py
  examples/integration/plots/visible_property.py
  examples/integration/widgets/data_table_preselection.py
  tests/examples/collect_examples.py
  tests/integration/annotations/__init__.py
  tests/integration/annotations/screenshots/base__test_arrow__test_arrow.png
  tests/integration/annotations/screenshots/base__test_band__test_band.png
  tests/integration/annotations/screenshots/base__test_color_bar__test_color_bar_placement_and_render.png
  tests/integration/annotations/screenshots/base__test_color_bar__test_color_bar_with_scale_alpha.png
  tests/integration/annotations/screenshots/base__test_label__test_label.png
  tests/integration/annotations/screenshots/base__test_label_set__test_label_set.png
  tests/integration/annotations/screenshots/base__test_legend__test_legend_powered_by_source.png
  tests/integration/annotations/screenshots/base__test_title__test_the_default_titles_settings_and_ensure_outside_any_axes.png
  tests/integration/annotations/screenshots/base__test_whisker__test_whisker.png
  tests/integration/annotations/test_arrow.py
  tests/integration/annotations/test_band.py
  tests/integration/annotations/test_color_bar.py
  tests/integration/annotations/test_label.py
  tests/integration/annotations/test_label_set.py
  tests/integration/annotations/test_legend.py
  tests/integration/annotations/test_title.py
  tests/integration/annotations/test_whisker.py
  tests/integration/plotting/screenshots/base__test_data_table_preselection__test_data_table_preselection_python.png
  tests/integration/plotting/screenshots/base__test_plot_fill_properties__test_no_border_or_background_fill.png
  tests/integration/plotting/screenshots/base__test_rect_glyph_with_log_axis__test_rect_rendering_with_log_axis.png
  tests/integration/plotting/screenshots/base__test_visible_property__test_visible_property_hides_things_correctly.png
  tests/integration/plotting/test_data_table_preselection.py
  tests/integration/plotting/test_plot_fill_properties.py
  tests/integration/plotting/test_rect_glyph_with_log_axis.py
  tests/integration/plotting/test_visible_property.py
Labels: status: accepted

#7635 Clean up all rendering levels in PlotCanvasView.build_levels()
  bokehjs/src/coffee/models/plots/plot_canvas.ts
Labels: status: accepted

#7778 Remove all deprecations before 0.12.15
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
  bokeh/layouts.py
  bokeh/models/plots.py
  bokeh/models/tools.py
  bokeh/plotting/figure.py
  bokeh/sampledata/population.py
  bokeh/util/_plot_arg_helpers.py
  bokeh/util/notebook.py
  bokeh/util/tests/test__plot_arg_helpers.py
  sphinx/source/docs/releases/0.12.16.rst
Labels: status: accepted, type: task

#7780 Silence deprecation warning from selenium.webdriver.phantomjs
  bokeh/command/subcommands/png.py
  bokeh/command/subcommands/svg.py
  bokeh/io/export.py
  bokeh/io/tests/test_export.py
Labels: status: accepted

#7784 Make detection of a spec more robust
  bokehjs/src/coffee/core/properties.ts
  bokehjs/test/core/properties.coffee
  examples/integration/widgets/tabs_with_multiselect.py
Labels: status: accepted

#7791 Add missing break statements to PlotCanvas.save()
  bokehjs/src/lib/models/plots/plot_canvas.ts
Labels: status: accepted

#7792 Finalize rename bokehjs/src/{coffee->lib}
  .bettercodehub.yml
  bokeh/io/export.py
  bokehjs/src/lib/base.ts
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/test/unit.coffee
  scripts/deploy.py
  sphinx/source/docs/user_guide/bokehjs.rst
  sphinx/source/docs/user_guide/extensions.rst
Labels: status: ready

#7695 Force "use strict" in CustomJS and related models
  bokeh/models/callbacks.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/transforms.py
  bokehjs/src/lib/core/util/string.ts
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/src/lib/models/filters/customjs_filter.ts
  bokehjs/src/lib/models/formatters/func_tick_formatter.ts
  bokehjs/src/lib/models/transforms/customjs_transform.ts
  bokehjs/test/models/callbacks/customjs.coffee
  bokehjs/test/models/filters/customjs_filter.coffee
  bokehjs/test/models/formatters/func_tick_formatter.coffee
  bokehjs/test/models/transforms/customjs_transform.coffee
  examples/app/export_csv/download.js
  examples/app/population.py
  examples/howto/events_app.py
  examples/howto/js_events.py
  examples/howto/layouts/dashboard.py
  examples/howto/using_password_input.py
  examples/models/file/transform_interpolator.py
  examples/plotting/file/color_sliders.py
  examples/plotting/file/customjs_transform.py
  examples/plotting/file/line_select.py
  examples/plotting/file/slider.py
  examples/plotting/file/text.py
  examples/webgl/line_compare.py
  sphinx/source/docs/user_guide/examples/extensions_example_widget.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_hover.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections_lasso_mean.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_widgets.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_js_on_change.py
  sphinx/source/docs/user_guide/examples/js_events.py
Labels: status: accepted

#7798 Add an epilog to 'bokeh --help` regarding subcommands' help
  bokeh/command/bootstrap.py
Labels: status: accepted

#7804 Handle cases where TouchEvent.touches may be empty
  bokehjs/src/lib/core/ui_events.ts
Labels: status: accepted

#7800 Add relative path option and handling to sphinx ext.
  bokeh/sphinxext/bokeh_plot.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#7806 DOM: add class to safely()'s error box
  bokehjs/src/lib/safely.ts
Labels: status: accepted

#7696 Replace flexx.pyscript with pscript
  bokeh/models/callbacks.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/tests/test_formatters.py
  bokeh/models/tests/test_transforms.py
  bokeh/models/transforms.py
  conda.recipe/meta.yaml
  examples/plotting/file/python_callback.py
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/interaction/callbacks.rst
Labels: status: accepted

#7799 Make defaults match between bokeh and bokehjs
  bokeh/application/handlers/tests/test_code.py
  bokeh/colors/tests/test_groups.py
  bokeh/colors/tests/test_named.py
  bokeh/command/subcommands/tests/test_serve.py
  bokeh/core/property/bases.py
  bokeh/document/tests/test_document.py
  bokeh/io/tests/test_showing.py
  bokeh/models/sources.py
  bokeh/models/tests/test_defaults.py
  bokeh/models/tests/test_sources.py
  bokeh/plotting/tests/test_helpers.py
  bokeh/server/tests/test_server.py
  bokeh/server/views/tests/test_ws.py
  bokeh/tests/test_layouts.py
  bokeh/tests/test_objects.py
  bokeh/tests/test_tile_providers.py
  bokeh/util/__init__.py
  bokeh/util/platform.py
  bokeh/util/testing.py
  bokeh/util/tests/test_serialization.py
  bokehjs/src/lib/models/axes/mercator_axis.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/sources/data_source.ts
Labels: status: ready

#7812 Remove ad-supported CGE
  sphinx/source/bokeh_theme/ga.html
  sphinx/source/bokeh_theme/includes/searchbox.html
  sphinx/source/bokeh_theme/layout.html
  sphinx/source/bokeh_theme/search.html
Labels: status: accepted

#7813 add downstream test report
  .travis.yml
  scripts/ci/install:downstream
  scripts/ci/test:downstream
Labels: status: accepted

#7817 remove spurious surface3d color property
  examples/app/surface3d/main.py
  examples/app/surface3d/surface3d.coffee
  examples/app/surface3d/surface3d.py
  sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
Labels: status: accepted

#7816 AjaxDataSource improvements
  bokeh/models/sources.py
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/sources/ajax_data_source.ts
  bokehjs/src/lib/models/sources/remote_data_source.ts
  bokehjs/test/models/sources/index.coffee
  bokehjs/test/models/sources/remote_data_source.coffee
  examples/howto/ajax_source.py
  sphinx/source/_images/ajax_streaming.gif
  sphinx/source/docs/user_guide/data.rst
Labels: status: accepted

#7617 Set a data source's inspected taking multiple renderers into account
  bokeh/models/sources.py
  bokeh/tests/test_objects.py
  bokehjs/src/lib/core/selection_manager.ts
  bokehjs/src/lib/models/selections/interaction_policy.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/tools/util.ts
  bokehjs/test/core/selection_manager.coffee
Labels: status: ready

#7818 fix missing python and data table updates
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
Labels: status: accepted

#7821 Revert "Set a data source's inspected taking multiple renderers into account"
  bokeh/models/sources.py
  bokeh/tests/test_objects.py
  bokehjs/src/lib/core/selection_manager.ts
  bokehjs/src/lib/models/selections/interaction_policy.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/tools/util.ts
  bokehjs/test/core/selection_manager.coffee
Labels: reso: completed, status: accepted, type: task

#7824 update docs for showing apps in notebooks
  bokeh/io/showing.py
Labels: status: accepted

#7829 Update for npm 6
  bokehjs/package-lock.json
  bokehjs/package.json
Labels: reso: completed, status: accepted, tag: component: build, type: task

#7828 use internal slider value for keypress action
  bokehjs/src/lib/models/widgets/abstract_slider.ts
Labels: status: accepted

#7827 support axes at fixed locations
  bokeh/models/axes.py
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/test/models/axes/axis.coffee
  bokehjs/test/models/renderers/index.coffee
  bokehjs/test/models/renderers/renderer.coffee
  examples/plotting/file/fixed_axis.py
Labels: status: accepted

#7833 have expressions respond properly to stream/patch
  bokeh/models/expressions.py
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/expressions/expression.ts
  bokehjs/src/lib/models/expressions/stack.ts
  bokehjs/test/models/expressions/stack.coffee
Labels: status: accepted

#7836 Minor fix in docs
  sphinx/source/docs/user_guide/embed.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: bug
