Repository bokeh/bokeh, pull requests merged in 2018-09, with the labels that each got.

#8200 change all instances of "joy plot" to "ridge plot"
  examples/howto/Categorical Data.ipynb
  examples/plotting/file/ridgeplot.py
  sphinx/source/_images/gallery/ridgeplot.png
  sphinx/source/docs/gallery.json
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/examples/categorical_ridgeplot.py
Labels: status: accepted

#8212 handle vline/hline hover in corner cases
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/src/lib/models/glyphs/utils.ts
Labels: status: accepted

#8206 Add another theme: balanced
  bokeh/themes/__init__.py
  bokeh/themes/caliber.json
  bokeh/themes/theme.py
Labels: status: accepted

#8211 8196 Add .copy method to ColumnDataSource
  bokeh/core/property/containers.py
  bokeh/core/property/tests/test_containers.py
  bokeh/models/sources.py
  bokeh/models/tests/test_sources.py
Labels: status: accepted

#8214 Bryanv/misc cleanup
  bokeh/command/__init__.py
  bokeh/command/bootstrap.py
  bokeh/command/subcommands/info.py
  bokeh/command/subcommands/png.py
  bokeh/command/subcommands/svg.py
  bokeh/command/subcommands/tests/test_html.py
  bokeh/command/subcommands/tests/test_info.py
  bokeh/command/subcommands/tests/test_png.py
  bokeh/command/subcommands/tests/test_svg.py
  bokeh/command/tests/test_bootstrap.py
  bokeh/command/tests/test_util.py
  bokeh/command/util.py
  bokeh/util/session_id.py
  bokeh/util/tests/test_session_id.py
  bokeh/util/tests/test_version.py
  bokeh/util/version.py
Labels: status: accepted

#8218 support specifying representative point from legend items
  bokeh/models/annotations.py
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/annotations/legend_item.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  examples/plotting/file/multi_legend.py
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/examples/plotting_legends_multi_index.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: feature

#8219 don't report unversioned python in deps.py output
  scripts/deps.py
Labels: CRITICAL, tag: component: build, type: task

#8202 Using 'utf-8' codec to open python 3 scripts in bokeh app
  bokeh/application/handlers/script.py
Labels: status: accepted

#8222 account for get_referrers change in python 3.7
  bokeh/document/tests/test_document.py
Labels: status: accepted

#8223 remove dead testing code
  bokeh/_testing/plugins/log_file.py
Labels: status: accepted, type: task

#8217 Added unit/integration tests for python3.7
  .travis.yml
Labels: reso: completed, status: accepted, tag: component: build, tag: component: tests, type: task

#8224 use np.frombuffer instead of deprecated np.fromstring
  bokeh/util/serialization.py
  bokeh/util/tests/test_serialization.py
Labels: reso: completed, status: accepted, type: task

#8228 Improve docs for export functions
  sphinx/source/docs/installation.rst
  sphinx/source/docs/user_guide/export.rst
Labels: status: accepted

#8230 properly use string_types for Instance properties and js_on_event
  bokeh/core/properties.py
  bokeh/model.py
Labels: status: accepted, tag: py2, type: bug

#8234 Bryanv/8232 frombuffer writeonly
  bokeh/util/serialization.py
  bokeh/util/tests/test_serialization.py
  bokeh/util/tornado.py
Labels: status: ready

#8236 typo for plotting_hex_tile_basic.py by ppplinday
  sphinx/source/docs/user_guide/examples/plotting_hex_tile_basic.py
Labels: status: accepted

#8237 Bryanv/8156 bold italic
  bokeh/core/enums.py
  bokeh/core/property_mixins.py
  bokeh/core/tests/test_enums.py
  bokehjs/src/lib/core/enums.ts
  bokehjs/test/core/enums.ts
  examples/plotting/file/text.py
Labels: status: accepted

#8238 add clear method to CDS
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/util/serialization.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/test/core/util/serialization.ts
  bokehjs/test/models/sources/column_data_source.coffee
Labels: status: accepted

#8239 slight range docs improvements
  bokeh/models/ranges.py
  sphinx/source/docs/user_guide/plotting.rst
Labels: status: accepted

#8240 project coords for segment glyphs on gmaps
  bokehjs/src/lib/models/glyphs/glyph.ts
Labels: status: accepted

#8220 Boilerplate for toplevel bokek/bokeh
  bokeh/__init__.py
  bokeh/__main__.py
  bokeh/driving.py
  bokeh/events.py
  bokeh/layouts.py
  bokeh/model.py
  bokeh/palettes.py
  bokeh/resources.py
  bokeh/settings.py
  bokeh/tile_providers.py
  bokeh/transform.py
Labels: status: accepted

#8242 allow pull_session to accept HTTP args
  bokeh/client/connection.py
  bokeh/client/session.py
  bokeh/client/tests/test_connection.py
  bokeh/client/tests/test_session.py
Labels: status: accepted

#8251 update requests min version
  bokehjs/package-lock.json
  bokehjs/package.json
Labels: status: accepted

#8213 Windows platform test corrections
  .gitignore
  bokeh/application/handlers/tests/test_notebook.py
  bokeh/command/tests/test_util.py
  bokeh/core/tests/test_templates.py
  bokeh/io/tests/test_util.py
  bokeh/models/tests/test_sources.py
  bokeh/server/tests/test_server.py
  bokeh/util/compiler.py
  bokeh/util/tests/test_browser.py
Labels: status: accepted

#8249 Ci windows appveyor
  .appveyor.yml
  scripts/ci/appveyor/build.ps1
  scripts/ci/appveyor/install.ps1
  scripts/ci/appveyor/test.ps1
Labels: status: accepted

#8248 Add DocumentLifeCycleHandler and Document.on_session_destroyed
  bokeh/application/handlers/document_lifecycle.py
  bokeh/application/handlers/lifecycle.py
  bokeh/application/handlers/server_lifecycle.py
  bokeh/application/handlers/tests/test_document_lifecycle.py
  bokeh/document/document.py
  bokeh/server/server.py
  sphinx/source/docs/user_guide/server.rst
Labels: status: accepted

#8258 add missing embed tempate
  examples/embed/server_session/templates/embed.html
Labels: status: accepted

#8256 add plumbing to make legends update changes
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/annotations/legend_item.ts
Labels: status: accepted

#8268 let image_url compute bounds
  bokehjs/src/lib/models/glyphs/image_url.ts
  examples/models/file/image_url.py
Labels: status: accepted

#8272 Resolve #8271 by adding ";" to console.log command
  bokeh/core/_templates/try_run.js
Labels: status: accepted

#8255 Adding autoreload based on tornado
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
Labels: status: WIP

#8274 Added ability to define custom tooltip and icon on EditTools
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/button_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/tool_proxy.ts
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/models/tools/edit/point_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_edit_tool.ts
Labels: status: accepted

#8279 Fix {css,js}_resources block mismatch
  sphinx/source/docs/user_guide/embed.rst
Labels: status: accepted

#8283 Add computed_icon getter to ToolProxy
  bokehjs/src/lib/models/tools/tool_proxy.ts
  bokehjs/test/models/tools/toolbar_box.coffee
Labels: status: accepted

#8276 Boilerplate for bokeh/client
  bokeh/client/__init__.py
  bokeh/client/connection.py
  bokeh/client/session.py
  bokeh/client/states.py
  bokeh/client/tests/__init__.py
  bokeh/client/tests/test___init__.py
  bokeh/client/tests/test_connection.py
  bokeh/client/tests/test_session.py
  bokeh/client/tests/test_states.py
  bokeh/client/tests/test_util.py
  bokeh/client/tests/test_websocket.py
  bokeh/client/util.py
  bokeh/client/websocket.py
Labels: status: accepted

#8278 Remove global event listeners when deleting views to prevent memory leaks
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
Labels: status: accepted
