Repository bokeh/bokeh, pull requests merged in 2018-03, with the labels that each got.

#7585 rev CONDA_REQS and ignore built python files for docker images
  docker-tools/.dockerignore
  docker-tools/Dockerfile-py2
  docker-tools/Dockerfile-py3
Labels: reso: completed, status: ready, tag: component: build, type: task

#7588 Sort all sphinx docs by file suffix. 'py' first
  bokeh/sphinxext/bokeh_plot.py
  sphinx/source/docs/releases/0.12.15.rst
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/extensions.rst
  sphinx/source/docs/user_guide/extensions_gallery/latex.rst
  sphinx/source/docs/user_guide/extensions_gallery/ticking.rst
  sphinx/source/docs/user_guide/extensions_gallery/tool.rst
  sphinx/source/docs/user_guide/extensions_gallery/widget.rst
  sphinx/source/docs/user_guide/extensions_gallery/wrapping.rst
  sphinx/source/docs/user_guide/graph.rst
  sphinx/source/docs/user_guide/interaction/callbacks.rst
  sphinx/source/docs/user_guide/interaction/legends.rst
  sphinx/source/docs/user_guide/interaction/linking.rst
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/layout.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/styling.rst
  sphinx/source/docs/user_guide/tools.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#7605 Fix WebDriverException when using export_png
  bokeh/io/export.py
Labels: status: accepted

#7608 Fix typo in docstring
  bokeh/plotting/helpers.py
Labels: status: accepted

#7609 Datetime stream fix
  bokeh/models/sources.py
  bokeh/models/tests/test_sources.py
Labels: status: accepted

#7601 7600 image rgba alpha
  bokeh/models/glyphs.py
  bokeh/models/tests/test_glyphs.py
  bokeh/plotting/helpers.py
  bokehjs/src/coffee/models/glyphs/image_rgba.ts
  examples/plotting/file/image_alpha.py
Labels: status: accepted

#7612 have one unit test job use tornado 4.5
  .travis.yml
  scripts/ci/install:test
Labels: status: accepted

#7614 Fix io_loop paramenter in examples/howto/server_embed/flask_embed.py
  examples/howto/server_embed/flask_embed.py
Labels: reso: completed, tag: component: examples, type: bug

#7604 Address leaking memory
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
  bokeh/document/document.py
  bokeh/server/session.py
  bokeh/server/tests/test_server.py
  bokeh/server/tests/test_session.py
  bokeh/server/tornado.py
Labels: status: accepted

#7620 fix bad logger name configs
  bokeh/application/tests/test_application.py
  bokeh/core/validation/check.py
  bokeh/document/document.py
  bokeh/document/tests/test_document.py
  bokeh/events.py
  bokeh/model.py
Labels: status: accepted

#7625 DOC: BUG: fix typo in user guide docs on embed
  sphinx/source/docs/user_guide/embed.rst
Labels: status: accepted

#7623 handle message send exceptions better
  bokeh/server/views/tests/__init__.py
  bokeh/server/views/tests/test_ws.py
  bokeh/server/views/ws.py
  tests/examples/test_examples.py
Labels: status: accepted

#7628 Fix type errors in models/formatters
  bokehjs/src/coffee/core/util/formatters.d.ts
  bokehjs/src/coffee/models/axes/categorical_axis.ts
  bokehjs/src/coffee/models/formatters/basic_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/categorical_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/datetime_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/func_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/log_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/mercator_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/numeral_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/printf_tick_formatter.ts
  bokehjs/src/coffee/models/formatters/tick_formatter.ts
Labels: status: accepted

#7629 Fix type errors in models/widgets
  bokehjs/src/coffee/core/util/formatters.d.ts
  bokehjs/src/coffee/models/widgets/abstract_button.ts
  bokehjs/src/coffee/models/widgets/abstract_slider.ts
  bokehjs/src/coffee/models/widgets/autocomplete_input.ts
  bokehjs/src/coffee/models/widgets/button.ts
  bokehjs/src/coffee/models/widgets/checkbox_button_group.ts
  bokehjs/src/coffee/models/widgets/checkbox_group.ts
  bokehjs/src/coffee/models/widgets/date_range_slider.ts
  bokehjs/src/coffee/models/widgets/date_slider.ts
  bokehjs/src/coffee/models/widgets/div.ts
  bokehjs/src/coffee/models/widgets/dropdown.ts
  bokehjs/src/coffee/models/widgets/input_widget.ts
  bokehjs/src/coffee/models/widgets/main.ts
  bokehjs/src/coffee/models/widgets/markup.ts
  bokehjs/src/coffee/models/widgets/multiselect.ts
  bokehjs/src/coffee/models/widgets/panel.ts
  bokehjs/src/coffee/models/widgets/paragraph.ts
  bokehjs/src/coffee/models/widgets/password_input.ts
  bokehjs/src/coffee/models/widgets/pretext.ts
  bokehjs/src/coffee/models/widgets/radio_button_group.ts
  bokehjs/src/coffee/models/widgets/radio_group.ts
  bokehjs/src/coffee/models/widgets/range_slider.ts
  bokehjs/src/coffee/models/widgets/selectbox.ts
  bokehjs/src/coffee/models/widgets/slider.ts
  bokehjs/src/coffee/models/widgets/tables/cell_editors.ts
  bokehjs/src/coffee/models/widgets/tables/cell_formatters.ts
  bokehjs/src/coffee/models/widgets/tables/data_table.ts
  bokehjs/src/coffee/models/widgets/tables/table_column.ts
  bokehjs/src/coffee/models/widgets/tabs.ts
  bokehjs/src/coffee/models/widgets/text_input.ts
  bokehjs/src/coffee/models/widgets/toggle.ts
  bokehjs/test/models/widgets/tables/cell_formatters.coffee
  bokehjs/test/models/widgets/tables/data_table.coffee
Labels: status: accepted

#7575 Add node and npm version requirement specification
  bokehjs/gulpfile.js
  bokehjs/package.json
  scripts/ci/install:build
  scripts/ci/install:test
Labels: status: accepted

#7636 Fix type errors in models/tools/toolbar*
  bokehjs/src/coffee/core/build_views.ts
  bokehjs/src/coffee/models/tools/tool_proxy.ts
  bokehjs/src/coffee/models/tools/toolbar.ts
  bokehjs/src/coffee/models/tools/toolbar_base.ts
  bokehjs/src/coffee/models/tools/toolbar_box.ts
Labels: status: accepted

#7630 Fix type errors in models/glyphs/webgl
  bokehjs/src/coffee/models/glyphs/webgl/base.ts
  bokehjs/src/coffee/models/glyphs/webgl/index.ts
  bokehjs/src/coffee/models/glyphs/webgl/line.ts
  bokehjs/src/coffee/models/glyphs/webgl/markers.frag.ts
  bokehjs/src/coffee/models/glyphs/webgl/markers.ts
  bokehjs/src/coffee/models/glyphs/webgl/markers.vert.ts
  bokehjs/src/coffee/models/plots/plot_canvas.ts
Labels: status: accepted

#7634 Bryanv/01215 docs
  bokeh/core/validation/decorators.py
  bokeh/core/validation/warnings.py
  bokeh/models/map_plots.py
  bokeh/models/plots.py
  bokeh/plotting/gmap.py
  bokeh/sphinxext/bokeh_directive.py
  bokeh/sphinxext/bokeh_gallery.py
  bokeh/sphinxext/bokeh_palette_group.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_sitemap.py
  bokehjs/src/coffee/core/has_props.ts
  conda.recipe/meta.yaml
  examples/app/stocks/main.py
  examples/plotting/file/line_select.py
  sphinx/docserver.py
  sphinx/source/_images/animated.gif
  sphinx/source/_images/bargrouped.png
  sphinx/source/_images/barstacked.png
  sphinx/source/_images/bokeh_import.png
  sphinx/source/_images/bokeh_server.png
  sphinx/source/_images/bokeh_server.pxm
  sphinx/source/_images/bokeh_simple_test_notebook.png
  sphinx/source/_images/burtin_novel.png
  sphinx/source/_images/histogram.png
  sphinx/source/_images/iris.png
  sphinx/source/_images/notebook_vector.png
  sphinx/source/_images/scatter.png
  sphinx/source/_images/stocks_applet.png
  sphinx/source/_images/tutorial1.png
  sphinx/source/bokeh_theme/layout.html
  sphinx/source/conf.py
  sphinx/source/docs/dev_guide/models.rst
  sphinx/source/docs/installation.rst
  sphinx/source/docs/reference/models/selections.rst
  sphinx/source/docs/reference/plotting.rst
  sphinx/source/docs/releases/0.12.15.rst
  sphinx/source/docs/user_guide.rst
  sphinx/source/docs/user_guide/bokehjs.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
  sphinx/source/docs/user_guide/examples/extensions_ion_range_slider.coffee
  sphinx/source/docs/user_guide/examples/geo_geojson_source.py
  sphinx/source/docs/user_guide/examples/geo_gmap.py
  sphinx/source/docs/user_guide/examples/geo_tile_source.py
  sphinx/source/docs/user_guide/examples/graph_customize.py
  sphinx/source/docs/user_guide/examples/graph_static_paths.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections_lasso_mean.py
  sphinx/source/docs/user_guide/geo.rst
  sphinx/source/docs/user_guide/interaction/callbacks.rst
  sphinx/source/docs/user_guide/quickstart.rst
  sphinx/source/docs/user_guide/server.rst
  sphinx/source/docs/user_guide/setup.rst
  sphinx/source/docs/user_guide/tutorials.rst
  sphinx/source/index.rst
Labels: status: accepted

#7649 Bug fix: slider keyboard navigation
  bokehjs/src/coffee/models/widgets/abstract_slider.ts
Labels: status: accepted

#7655 Bryanv/deprecate row header
  bokeh/models/widgets/tables.py
  bokehjs/src/coffee/models/widgets/tables/data_table.ts
  bokehjs/src/coffee/models/widgets/tables/table_column.ts
  bokehjs/src/less/widgets/data_table.less
  examples/models/file/data_tables.py
  sphinx/source/docs/releases/0.12.15.rst
Labels: status: accepted

#7658 add support for a hex scatter marker
  bokeh/models/glyphs.py
  bokeh/models/markers.py
  bokeh/plotting/figure.py
  bokehjs/src/coffee/models/glyphs/webgl/markers.frag.ts
  bokehjs/src/coffee/models/glyphs/webgl/markers.ts
  bokehjs/src/coffee/models/markers/index.ts
  examples/models/file/glyphs.py
  examples/plotting/file/glyphs.py
  examples/reference/models/Hex.py
  examples/webgl/marker_compare.py
Labels: status: accepted

#7661 render initial values for multi selects
  bokehjs/src/coffee/models/widgets/multiselect.ts
  bokehjs/test/models/widgets/index.coffee
  bokehjs/test/models/widgets/multiselect.coffee
Labels: status: accepted

#7660 manage checkbox active state more carefully
  bokehjs/src/coffee/models/widgets/checkbox_button_group.ts
  bokehjs/test/models/widgets/checkbox_button_group.coffee
  bokehjs/test/models/widgets/index.coffee
Labels: status: accepted

#7664 Add support for doubletap drawing on BoxEditTool
  bokeh/models/tools.py
  bokehjs/src/coffee/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  sphinx/source/docs/user_guide/tools.rst
Labels: status: ready

#7653 Restore code handling empty array shape tuples
  bokehjs/src/coffee/models/glyphs/image.ts
  bokehjs/src/coffee/models/glyphs/image_rgba.ts
  examples/integration/glyphs/image_non_binary_arrays.py
Labels: status: accepted

#7676 Fix frame clipping with webgl backend
  bokehjs/src/coffee/models/plots/plot_canvas.ts
Labels: status: accepted

#7637 Fix all outstanding type errors
  bokeh/models/annotations.py
  bokehjs/gulp/tasks/scripts.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/coffee/core/layout/layout_canvas.ts
  bokehjs/src/coffee/core/layout/side_panel.ts
  bokehjs/src/coffee/core/ui_events.ts
  bokehjs/src/coffee/core/util/compat.ts
  bokehjs/src/coffee/core/util/serialization.ts
  bokehjs/src/coffee/core/vectorization.ts
  bokehjs/src/coffee/core/visuals.ts
  bokehjs/src/coffee/models/annotations/annotation.ts
  bokehjs/src/coffee/models/annotations/arrow.ts
  bokehjs/src/coffee/models/annotations/band.ts
  bokehjs/src/coffee/models/annotations/box_annotation.ts
  bokehjs/src/coffee/models/annotations/color_bar.ts
  bokehjs/src/coffee/models/annotations/label.ts
  bokehjs/src/coffee/models/annotations/label_set.ts
  bokehjs/src/coffee/models/annotations/legend.ts
  bokehjs/src/coffee/models/annotations/legend_item.ts
  bokehjs/src/coffee/models/annotations/poly_annotation.ts
  bokehjs/src/coffee/models/annotations/span.ts
  bokehjs/src/coffee/models/annotations/text_annotation.ts
  bokehjs/src/coffee/models/annotations/title.ts
  bokehjs/src/coffee/models/annotations/toolbar_panel.ts
  bokehjs/src/coffee/models/annotations/tooltip.ts
  bokehjs/src/coffee/models/annotations/whisker.ts
  bokehjs/src/coffee/models/formatters/categorical_tick_formatter.ts
  bokehjs/src/coffee/models/glyphs/glyph.ts
  bokehjs/src/coffee/models/glyphs/image.ts
  bokehjs/src/coffee/models/glyphs/patches.ts
  bokehjs/src/coffee/models/glyphs/webgl/base.ts
  bokehjs/src/coffee/models/mappers/categorical_color_mapper.ts
  bokehjs/src/coffee/models/mappers/color_mapper.ts
  bokehjs/src/coffee/models/mappers/continuous_color_mapper.ts
  bokehjs/src/coffee/models/mappers/index.ts
  bokehjs/src/coffee/models/mappers/linear_color_mapper.ts
  bokehjs/src/coffee/models/mappers/log_color_mapper.ts
  bokehjs/src/coffee/models/plots/gmap_plot.ts
  bokehjs/src/coffee/models/plots/gmap_plot_canvas.ts
  bokehjs/src/coffee/models/plots/plot.ts
  bokehjs/src/coffee/models/plots/plot_canvas.ts
  bokehjs/src/coffee/models/ranges/data_range1d.ts
  bokehjs/src/coffee/models/ranges/factor_range.ts
  bokehjs/src/coffee/models/ranges/range.ts
  bokehjs/src/coffee/models/ranges/range1d.ts
  bokehjs/src/coffee/models/renderers/glyph_renderer.ts
  bokehjs/src/coffee/models/renderers/renderer.ts
  bokehjs/src/coffee/models/scales/scale.ts
  bokehjs/src/coffee/models/tiles/mercator_tile_source.ts
  bokehjs/src/coffee/models/transforms/interpolator.ts
  bokehjs/src/coffee/models/transforms/transform.ts
  bokehjs/src/coffee/tsconfig.json
  bokehjs/test/models/annotations/legend_item.coffee
  bokehjs/test/models/mappers/categorical_color_mapper.coffee
  bokehjs/test/models/mappers/color_mapper.coffee
  bokehjs/test/models/mappers/linear_color_mapper.coffee
  bokehjs/test/models/mappers/log_color_mapper.coffee
Labels: status: accepted

#7677 Subtract padding when calculating dims for responsive modes
  bokehjs/src/coffee/core/dom.ts
  bokehjs/src/coffee/models/layouts/layout_dom.ts
Labels: status: accepted

#7680 Propagate settings from Bokeh Server to TornadoApplication
  bokeh/server/tornado.py
Labels: status: accepted

#7684 Fix initialization of multiple webgl plots
  bokehjs/src/coffee/models/plots/plot_canvas.ts
  examples/examples.yaml
  examples/integration/webgl/multiple_webgl_plots.py
Labels: status: accepted

#7693 Fix regression in GMapPlotCanvas' initialization code
  bokehjs/src/coffee/models/plots/gmap_plot_canvas.ts
Labels: status: accepted

#7683 Add maintain_focus parameter to WheelZoomTool
  bokeh/models/tools.py
  bokehjs/src/coffee/models/plots/plot_canvas.ts
  bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.ts
Labels: status: accepted

#6595 Add support for image diff in headless chrome
  .travis.yml
  bokehjs/package-lock.json
  bokehjs/package.json
  tests/conftest.py
  tests/examples/collect_examples.py
  tests/examples/examples_report.jinja
  tests/examples/examples_report_plugin.py
  tests/examples/test_examples.py
  tests/plugins/chrome_screenshot.js
  tests/plugins/image_diff.py
  tests/plugins/phantomjs_screenshot.js
  tests/plugins/phantomjs_screenshot.py
  tests/plugins/screenshot.py
  tests/plugins/upload_to_s3.py
Labels: status: accepted

#7697 Fix CSS in examples/howto/{events_app,js_events}
  examples/howto/events_app.py
  examples/howto/js_events.py
Labels: status: accepted

#7698 Always clip frame in _paint_levels() despite output backend
  bokeh/io/tests/test_export.py
  bokehjs/src/coffee/models/glyphs/webgl/markers.frag.ts
  bokehjs/src/coffee/models/glyphs/webgl/markers.ts
  bokehjs/src/coffee/models/plots/plot_canvas.ts
  examples/integration/glyphs/frame_clipping_multi_backend.py
Labels: status: accepted

#7682 Hex Tiling and Binning
  bokeh/models/glyphs.py
  bokeh/models/markers.py
  bokeh/plotting/figure.py
  bokeh/plotting/helpers.py
  bokeh/util/__init__.py
  bokeh/util/hex.py
  bokeh/util/tests/test_hex.py
  bokehjs/src/coffee/models/glyphs/hex_tile.ts
  bokehjs/src/coffee/models/glyphs/index.ts
  bokehjs/src/coffee/models/tools/inspectors/hover_tool.ts
  examples/integration/glyphs/hex_tile.py
  examples/plotting/file/hex_tile.py
  examples/plotting/file/hexbin.py
  examples/reference/models/HexTile.py
  sphinx/source/_images/gallery/hex_tile.png
  sphinx/source/_images/gallery/hexbin.png
  sphinx/source/docs/gallery.json
  sphinx/source/docs/reference/models/glyphs/hex_tile.rst
  sphinx/source/docs/reference/models/markers/hex.rst
Labels: status: accepted

#7704 Make webgl renderer work with log scales
  bokehjs/src/coffee/models/glyphs/webgl/base.ts
  examples/integration/glyphs/frame_clipping_multi_backend.py
  examples/integration/glyphs/log_scale_multi_backend.py
Labels: status: accepted

#7687 Make adding callbacks thread-safe
  bokeh/application/application.py
  bokeh/document/document.py
  bokeh/document/locking.py
  bokeh/document/tests/test_document.py
  bokeh/document/tests/test_locking.py
  bokeh/server/application_context.py
  bokeh/server/callbacks.py
  bokeh/server/tests/test_callbacks.py
  bokeh/server/tests/test_server.py
  bokeh/tests/test_client_server.py
  bokeh/util/tornado.py
  sphinx/source/docs/releases/0.12.15.rst
  tests/examples/test_examples.py
Labels: status: ready

#7686 bokeh server support for running in JupyterHub. (#7685)
  bokeh/io/notebook.py
  bokeh/io/showing.py
Labels: status: accepted

#7673 Enable user_guide examples in image diff tests
  bokeh/io/saving.py
  bokeh/settings.py
  bokehjs/examples/examples.yaml
  examples.yaml
  examples/examples.yaml
  sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
  tests/examples/examples_report_plugin.py
  tests/examples/test_examples.py
Labels: status: accepted

#7712 Fixed typos in palettes.py
  bokeh/palettes.py
Labels: status: accepted

#7714 Fix outstanding tslint errors and enable tslint on travis ci
  bokehjs/gulp/tasks/scripts.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/coffee/api/plotting.ts
  bokehjs/src/coffee/client/connection.ts
  bokehjs/src/coffee/core/bokeh_events.ts
  bokehjs/src/coffee/core/logging.ts
  bokehjs/src/coffee/core/util/data_structures.ts
  bokehjs/src/coffee/core/util/serialization.ts
  bokehjs/src/coffee/document.ts
  bokehjs/src/coffee/models/annotations/legend_item.ts
  bokehjs/src/coffee/models/annotations/toolbar_panel.ts
  bokehjs/src/coffee/models/axes/axis.ts
  bokehjs/src/coffee/models/canvas/canvas.ts
  bokehjs/src/coffee/models/canvas/cartesian_frame.ts
  bokehjs/src/coffee/models/formatters/datetime_tick_formatter.ts
  bokehjs/src/coffee/models/glyphs/glyph.ts
  bokehjs/src/coffee/models/glyphs/image.ts
  bokehjs/src/coffee/models/glyphs/multi_line.ts
  bokehjs/src/coffee/models/glyphs/oval.ts
  bokehjs/src/coffee/models/glyphs/webgl/markers.ts
  bokehjs/src/coffee/models/layouts/spacer.ts
  bokehjs/src/coffee/models/mappers/color_mapper.ts
  bokehjs/src/coffee/models/ranges/factor_range.ts
  bokehjs/src/coffee/models/sources/cds_view.ts
  bokehjs/src/coffee/models/tickers/adaptive_ticker.ts
  bokehjs/src/coffee/models/tickers/categorical_ticker.ts
  bokehjs/src/coffee/models/tickers/composite_ticker.ts
  bokehjs/src/coffee/models/tickers/continuous_ticker.ts
  bokehjs/src/coffee/models/tickers/days_ticker.ts
  bokehjs/src/coffee/models/tickers/fixed_ticker.ts
  bokehjs/src/coffee/models/tickers/log_ticker.ts
  bokehjs/src/coffee/models/tickers/mercator_ticker.ts
  bokehjs/src/coffee/models/tickers/months_ticker.ts
  bokehjs/src/coffee/models/tickers/single_interval_ticker.ts
  bokehjs/src/coffee/models/tickers/years_ticker.ts
  bokehjs/src/coffee/models/tiles/tile_renderer.ts
  bokehjs/src/coffee/models/tools/tool_proxy.ts
  bokehjs/src/coffee/models/widgets/abstract_slider.ts
  bokehjs/src/coffee/models/widgets/date_range_slider.ts
  bokehjs/src/coffee/models/widgets/date_slider.ts
  bokehjs/src/coffee/models/widgets/range_slider.ts
  bokehjs/src/coffee/models/widgets/slider.ts
  bokehjs/src/coffee/models/widgets/tables/cell_editors.ts
  bokehjs/src/coffee/models/widgets/tables/cell_formatters.ts
  bokehjs/test/models/tickers/continuous_ticker.ts
  scripts/ci/test:codebase
Labels: status: accepted

#7721 remove useless botched deprecation code
  bokeh/models/widgets/tables.py
Labels: status: accepted

#7722 publish all release notes on one page
  bokeh/sphinxext/bokeh_index_toctree.py
  bokeh/sphinxext/bokeh_releases.py
  sphinx/source/all_versions.txt
  sphinx/source/conf.py
  sphinx/source/docs/reference/sphinxext.rst
  sphinx/source/docs/releases.rst
  sphinx/source/docs/releases/0.12.15.rst
  sphinx/source/docs/releases/0.12.16.rst
  sphinx/source/index.rst
Labels: status: accepted
