Repository bokeh/bokeh, pull requests merged in 2018-06, with the labels that each got.

#7947 Upgrade to TypeScript 2.9.1
  bokehjs/make/linker.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/src/lib/models/widgets/multiselect.ts
Labels: status: accepted

#7950 Bryanv/build cleanup
  .travis.yml
  scripts/build_upload.py
  scripts/ci/deploy
  sphinx/fabfile.py
Labels: reso: completed, status: accepted, tag: component: build, type: task

#7948 Exposed Range1d initial start/end properties
  bokeh/models/ranges.py
  bokeh/models/tests/test_ranges.py
  bokehjs/src/lib/models/ranges/range1d.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/test/models/ranges/range1d.coffee
Labels: status: accepted

#7954 Ensured the PolyDraw tool correctly handles typed array paths
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
Labels: status: accepted

#7955 add option to set websocket_max_message_size
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
  bokeh/server/server.py
  bokeh/server/tests/test_tornado.py
  bokeh/server/tornado.py
  sphinx/source/docs/releases/0.13.0.rst
Labels: status: accepted

#7956 Changed default line_join from miter to bevel
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
  bokeh/core/property_mixins.py
  bokeh/models/tests/utils/property_utils.py
  bokehjs/src/lib/core/property_mixins.ts
  sphinx/source/docs/releases/0.13.0.rst
Labels: status: accepted

#7958 Replace esprima with TypeScript compiler API
  bokehjs/make/fs.ts
  bokehjs/make/linker.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/transform.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/compile.ts
  bokehjs/src/compiler/dependencies.ts
  bokehjs/src/lib/tsconfig.json
Labels: status: accepted

#7961 add a cumsum transform to cumulatively sum a single column
  bokeh/models/expressions.py
  bokeh/tests/test_transform.py
  bokeh/transform.py
  bokehjs/src/lib/models/expressions/cumsum.ts
  bokehjs/src/lib/models/expressions/index.ts
  bokehjs/test/models/expressions/cumsum.coffee
  bokehjs/test/models/expressions/index.ts
  bokehjs/tslint.json
  examples/plotting/file/pie.py
  sphinx/source/_images/gallery/pie_chart.png
  sphinx/source/docs/gallery.json
  sphinx/source/docs/releases/0.13.0.rst
Labels: status: ready, tag: component: bokehjs, type: feature

#7963 Run `npm install` automatically if package.json changed
  bokehjs/make/index.js
Labels: status: accepted

#7968 Typo fixed in image w parameter (height instead of width)
  bokeh/models/glyphs.py
Labels: status: accepted

#7973 Add new maintainer to the list
  MAINTAINERS
Labels: reso: completed, status: accepted, type: task

#7708 Allow easy customization of HTML templates
  bokeh/core/_templates/autoload_nb_js.js
  bokeh/core/_templates/autoload_tag.html
  bokeh/core/_templates/file.html
  bokeh/core/_templates/macros.html
  bokeh/core/_templates/plot_div.html
  bokeh/core/_templates/root_div.html
  bokeh/core/templates.py
  bokeh/core/tests/test_templates.py
  bokeh/document/document.py
  bokeh/embed/notebook.py
  bokeh/embed/server.py
  bokeh/embed/standalone.py
  bokeh/embed/tests/test_notebook.py
  bokeh/embed/tests/test_server.py
  bokeh/embed/tests/test_standalone.py
  bokeh/embed/tests/test_util.py
  bokeh/embed/util.py
  bokeh/io/export.py
  bokeh/io/saving.py
  bokeh/io/tests/test_saving.py
  bokeh/server/views/autoload_js_handler.py
  bokeh/server/views/doc_handler.py
  bokehjs/examples/anscombe/anscombe.html
  bokehjs/make/linker.ts
  bokehjs/src/less/bokeh.less
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/embed.ts
  bokehjs/src/lib/embed/dom.ts
  bokehjs/src/lib/embed/index.ts
  bokehjs/src/lib/embed/json.ts
  bokehjs/src/lib/embed/notebook.ts
  bokehjs/src/lib/embed/server.ts
  bokehjs/src/lib/embed/standalone.ts
  bokehjs/src/lib/external/jupyter.d.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  examples.yaml
  examples/app/crossfilter/templates/index.html
  examples/app/export_csv/templates/index.html
  examples/app/gapminder/templates/index.html
  examples/app/pivot/templates/index.html
  examples/app/pivot/templates/styles.css
  examples/app/surface3d/description.html
  examples/app/surface3d/main.py
  examples/app/surface3d/templates/index.html
  examples/embed/arguments/flask_server.py
  examples/embed/embed_multiple.py
  examples/embed/embed_multiple_responsive.py
  examples/embed/embed_themed.py
  examples/embed/simple/simple.py
  examples/embed/simple/templates/embed.html
  examples/integration/embed/css_grid_simple.py
  examples/integration/embed/css_grid_simple_no_extend.py
  examples/integration/embed/referencing_roots.py
  examples/integration/layout/axis_label_extra_x_ranges.py
  examples/plotting/file/color_sliders.py
  examples/plotting/file/css_classes.py
  examples/plotting/file/custom_layout.py
  sphinx/source/docs/user_guide/embed.rst
Labels: status: ready

#7839 Add Range Tool
  bokeh/core/validation/errors.py
  bokeh/models/tools.py
  bokehjs/src/less/icons.less
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/src/lib/models/tools/index.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/models/tools/gestures/index.ts
  bokehjs/test/models/tools/gestures/range_tool.coffee
  examples/plotting/file/range_tool.py
  sphinx/source/_images/gallery/range_tool.png
  sphinx/source/_images/icons/Range.png
  sphinx/source/docs/gallery.json
Labels: status: ready

#7975 cache jitter for identical input lengths
  bokehjs/src/lib/models/transforms/jitter.ts
  bokehjs/test/models/transforms/jitter.coffee
Labels: status: accepted

#7980 don't generate detail validation stings for purely internal checks
  bokeh/core/properties.py
  bokeh/core/property/bases.py
  bokeh/core/property/containers.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/tests/test_bases.py
  bokeh/core/tests/test_properties.py
  bokeh/util/serialization.py
Labels: status: accepted

#7982 fix up selection handling
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
Labels: status: accepted

#7979 Rewrite bokehjs' tests in TypeScript (part 2)
  bokehjs/src/lib/document.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/expressions/cumsum.ts
  bokehjs/src/lib/models/expressions/expression.ts
  bokehjs/src/lib/models/expressions/stack.ts
  bokehjs/src/lib/models/sources/column_data_source.ts
  bokehjs/src/lib/models/transforms/jitter.ts
  bokehjs/test/models/axes/axis.coffee
  bokehjs/test/models/axes/axis.ts
  bokehjs/test/models/expressions/cumsum.coffee
  bokehjs/test/models/expressions/cumsum.ts
  bokehjs/test/models/expressions/stack.coffee
  bokehjs/test/models/expressions/stack.ts
  bokehjs/test/models/tools/gestures/range_tool.coffee
  bokehjs/test/models/tools/gestures/range_tool.ts
  bokehjs/test/models/transforms/customjs_transform.coffee
  bokehjs/test/models/transforms/customjs_transform.ts
  bokehjs/test/models/transforms/dodge.coffee
  bokehjs/test/models/transforms/dodge.ts
  bokehjs/test/models/transforms/jitter.coffee
  bokehjs/test/models/transforms/jitter.ts
  bokehjs/test/models/transforms/linear_interpolator.coffee
  bokehjs/test/models/transforms/linear_interpolator.ts
  bokehjs/test/models/transforms/step_interpolator.coffee
  bokehjs/test/models/transforms/step_interpolator.ts
Labels: status: accepted

#7984 temp partial fix allowing scale_both to work in some cases
  bokehjs/src/lib/models/layouts/layout_dom.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: layout, type: bug

#7986 Don't make assumptions on DOM/CSS in LayoutDOM.get_width_height()
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/test/models/plots/plot.coffee
Labels: status: accepted

#7983 Support line annotations like span but with slope
  bokeh/models/annotations.py
  bokeh/models/tests/test_annotations.py
  bokehjs/src/lib/api/typings/models/annotations.d.ts
  bokehjs/src/lib/models/annotations/index.ts
  bokehjs/src/lib/models/annotations/slope.ts
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/examples/plotting_slope.py
Labels: status: accepted

#7996 Using mappers documentation update
  sphinx/source/docs/user_guide/examples/styling_linear_mappers.py
  sphinx/source/docs/user_guide/styling.rst
Labels: status: accepted

#8003 Updated docs for two-way Jupyter communication
  sphinx/source/docs/user_guide/server.rst
Labels: reso: completed, status: accepted, tag: component: docs, tag: notebook, type: task

#7999 Fix hit testing issues for wedge and annular wedge
  bokehjs/src/lib/core/util/math.ts
  bokehjs/src/lib/models/glyphs/wedge.ts
  bokehjs/test/core/util/math.ts
Labels: status: accepted

#8001 Fixes #7401: set range with pandas Series
  bokeh/plotting/helpers.py
  bokeh/plotting/tests/test_helpers.py
Labels: status: accepted

#8004 Corrected docs for `dimensions` parameter to BoxZoomTool
  sphinx/source/docs/user_guide/tools.rst
Labels: status: accepted

#7994 Improve computing of available space for responsive layouts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  examples/plotting/file/custom_layout.py
Labels: status: accepted

#8011 Bryanv/013 docs
  examples/app/dash/README.md
  examples/app/dash/main.py
  examples/app/dash/static/css/custom.min.css
  examples/app/dash/static/vendors/bootstrap/dist/css/bootstrap.min.css
  examples/app/dash/static/vendors/font-awesome/css/font-awesome.min.css
  examples/app/dash/static/vendors/font-awesome/fonts/FontAwesome.otf
  examples/app/dash/static/vendors/font-awesome/fonts/fontawesome-webfont.eot
  examples/app/dash/static/vendors/font-awesome/fonts/fontawesome-webfont.svg
  examples/app/dash/static/vendors/font-awesome/fonts/fontawesome-webfont.ttf
  examples/app/dash/static/vendors/font-awesome/fonts/fontawesome-webfont.woff
  examples/app/dash/static/vendors/font-awesome/fonts/fontawesome-webfont.woff2
  examples/app/dash/templates/index.html
  examples/plotting/file/pie.py
  sphinx/source/docs/user_guide/embed.rst
  tests/test_code_quality.py
Labels: status: accepted

#8017 Added short usage instructions for examples/app/dash
  examples/app/dash/README.md
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#8016 test with minimal packages
  .travis.yml
  bokeh/core/property/tests/test_bases.py
  bokeh/core/tests/test_json_encoder.py
  bokeh/core/tests/test_properties.py
  bokeh/document/tests/test_document.py
  bokeh/document/tests/test_events.py
  bokeh/models/tests/test_mappers.py
  bokeh/models/tests/test_plots.py
  bokeh/models/tests/test_sources.py
  bokeh/plotting/tests/test_figure.py
  bokeh/plotting/tests/test_helpers.py
  bokeh/protocol/messages/tests/test_patch_doc.py
  bokeh/protocol/messages/tests/test_pull_doc.py
  bokeh/protocol/messages/tests/test_push_doc.py
  bokeh/sampledata/tests/test_airport_routes.py
  bokeh/sampledata/tests/test_airports.py
  bokeh/sampledata/tests/test_autompg.py
  bokeh/sampledata/tests/test_autompg2.py
  bokeh/sampledata/tests/test_browsers.py
  bokeh/sampledata/tests/test_commits.py
  bokeh/sampledata/tests/test_daylight.py
  bokeh/sampledata/tests/test_degrees.py
  bokeh/sampledata/tests/test_gapminder.py
  bokeh/sampledata/tests/test_glucose.py
  bokeh/sampledata/tests/test_iris.py
  bokeh/sampledata/tests/test_mtb.py
  bokeh/sampledata/tests/test_perceptions.py
  bokeh/sampledata/tests/test_periodic_table.py
  bokeh/sampledata/tests/test_population.py
  bokeh/sampledata/tests/test_sea_surface_temperature.py
  bokeh/sampledata/tests/test_sprint.py
  bokeh/sampledata/tests/test_unemployment1948.py
  bokeh/sampledata/tests/test_us_marriages_divorces.py
  bokeh/sampledata/tests/test_world_cities.py
  bokeh/server/tests/test_callbacks.py
  bokeh/tests/test_client_server.py
  bokeh/tests/test_objects.py
  bokeh/tests/test_resources.py
  bokeh/tests/test_server.py
  bokeh/tests/test_themes.py
  bokeh/tests/test_widgets.py
  bokeh/util/testing.py
  bokeh/util/tests/test_hex.py
  bokeh/util/tests/test_serialization.py
  bokeh/util/tests/test_session_id.py
  scripts/ci/install:unit
  scripts/ci/test:unit
  tests/test_bokehjs.py
Labels: status: accepted

#8019 make Plot.select compatible with Model.select usage
  bokeh/models/plots.py
  bokeh/models/tests/test_plots.py
  bokeh/util/__init__.py
  bokeh/util/plot_utils.py
  sphinx/source/docs/releases/1.0.0.rst
Labels: status: accepted

#8022 raise validation error on duplicate factor range factors
  bokeh/core/validation/errors.py
  bokeh/core/validation/warnings.py
  bokeh/models/ranges.py
  bokeh/models/tests/test_ranges.py
Labels: status: accepted

#8027 handle Pandas PeriodIndex and Timedelta properly
  bokeh/core/json_encoder.py
  bokeh/core/properties.py
  bokeh/core/property_mixins.py
  bokeh/core/tests/test_json_encoder.py
  bokeh/models/glyphs.py
  bokeh/models/ranges.py
  bokeh/models/tests/test_ranges.py
  bokeh/util/serialization.py
  bokeh/util/tests/test_serialization.py
Labels: status: ready

#8029 move log tick filtering to the very end
  bokehjs/src/lib/models/tickers/log_ticker.ts
  bokehjs/test/models/tickers/log_ticker.ts
Labels: status: accepted

#8030 handle pd.NaT
  bokeh/util/serialization.py
  bokeh/util/tests/test_serialization.py
Labels: status: accepted

#8037 DOC typo (funtion -> function)
  sphinx/source/docs/user_guide/plotting.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#8035 add fixture to re-use webdriver in export tests
  bokeh/io/tests/test_export.py
Labels: status: accepted

#8038 improved support for pyinstaller
  bokeh/core/templates.py
Labels: reso: completed, status: accepted, type: task
