Repository bokeh/bokeh, pull requests merged in 2018-12, with the labels that each got.

#8474 fix for arrow annotation updating on property change
  bokehjs/src/lib/models/annotations/arrow.ts
Labels: status: accepted

#8381 Bokeh export csv example now discovers column heading names
  examples/app/export_csv/download.js
Labels: status: accepted

#8481 DOC: remove extra "to execute" from embed
  sphinx/source/docs/user_guide/embed.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#8470 add method to retrieve sorted columns on DataTable in js
  bokehjs/src/lib/models/widgets/tables/data_table.ts
Labels: status: accepted

#8472 Boilerplates for bokeh/models
  bokeh/models/__init__.py
  bokeh/models/annotations.py
  bokeh/models/arrow_heads.py
  bokeh/models/axes.py
  bokeh/models/callbacks.py
  bokeh/models/expressions.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/glyphs.py
  bokeh/models/graphs.py
  bokeh/models/grids.py
  bokeh/models/layouts.py
  bokeh/models/map_plots.py
  bokeh/models/mappers.py
  bokeh/models/markers.py
  bokeh/models/plots.py
  bokeh/models/ranges.py
  bokeh/models/renderers.py
  bokeh/models/scales.py
  bokeh/models/selections.py
  bokeh/models/sources.py
  bokeh/models/tests/__init__.py
  bokeh/models/tests/test_annotations.py
  bokeh/models/tests/test_axes.py
  bokeh/models/tests/test_callbacks.py
  bokeh/models/tests/test_defaults.py
  bokeh/models/tests/test_formatters.py
  bokeh/models/tests/test_glyphs.py
  bokeh/models/tests/test_graphs.py
  bokeh/models/tests/test_layouts.py
  bokeh/models/tests/test_mappers.py
  bokeh/models/tests/test_plots.py
  bokeh/models/tests/test_ranges.py
  bokeh/models/tests/test_renderers.py
  bokeh/models/tests/test_sources.py
  bokeh/models/tests/test_tools.py
  bokeh/models/tests/test_transforms.py
  bokeh/models/tests/utils/__init__.py
  bokeh/models/tests/utils/property_utils.py
  bokeh/models/tickers.py
  bokeh/models/tiles.py
  bokeh/models/tools.py
  bokeh/models/transforms.py
  bokeh/models/widgets/__init__.py
  bokeh/models/widgets/buttons.py
  bokeh/models/widgets/groups.py
  bokeh/models/widgets/icons.py
  bokeh/models/widgets/inputs.py
  bokeh/models/widgets/markups.py
  bokeh/models/widgets/panels.py
  bokeh/models/widgets/sliders.py
  bokeh/models/widgets/tables.py
  bokeh/models/widgets/tests/__init__.py
  bokeh/models/widgets/tests/test_slider.py
  bokeh/models/widgets/widget.py
  bokeh/tests/test_objects.py
Labels: status: accepted

#8485 update sampledata bucket URL
  bokeh/util/sampledata.py
Labels: reso: completed, status: accepted, type: task

#8494 Disable show_vertices when PolyDrawTool inactive
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
Labels: status: accepted

#8492 Fix typo 'range_rool' in range_tool.py
  examples/plotting/file/range_tool.py
Labels: status: accepted

#8506 Boilerplate for bokeh/plotting directory
  bokeh/plotting/__init__.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  bokeh/plotting/helpers.py
  bokeh/plotting/tests/__init__.py
  bokeh/plotting/tests/test_figure.py
  bokeh/plotting/tests/test_helpers.py
Labels: status: ready

#8510 monitor JS package license usage
  LICENSE.txt
  bokeh/tests/test___init__.py
  bokehjs/package-lock.json
  bokehjs/package.json
  tests/codebase/test_js_license_set.py
Labels: status: accepted

#8372 Extended BAD_COLUMN_NAME error
  bokeh/core/validation/errors.py
  bokeh/models/renderers.py
Labels: reso: completed, status: accepted, type: task

#8516 move BokehJS license details to bokehjs/LICENSE
  LICENSE.txt
  bokeh/tests/test___init__.py
  bokehjs/LICENSE
  tests/codebase/test_js_license_set.py
Labels: status: accepted, tag: component: docs, type: task

#8517 Boilerplate for bokeh/server
  bokeh/server/__init__.py
  bokeh/server/callbacks.py
  bokeh/server/connection.py
  bokeh/server/contexts.py
  bokeh/server/protocol_handler.py
  bokeh/server/server.py
  bokeh/server/session.py
  bokeh/server/tests/__init__.py
  bokeh/server/tests/test_callbacks.py
  bokeh/server/tests/test_contexts.py
  bokeh/server/tests/test_server.py
  bokeh/server/tests/test_session.py
  bokeh/server/tests/test_tornado.py
  bokeh/server/tests/test_util.py
  bokeh/server/tests/utils.py
  bokeh/server/tornado.py
  bokeh/server/urls.py
  bokeh/server/util.py
  bokeh/server/views/__init__.py
  bokeh/server/views/autoload_js_handler.py
  bokeh/server/views/doc_handler.py
  bokeh/server/views/metadata_handler.py
  bokeh/server/views/root_handler.py
  bokeh/server/views/session_handler.py
  bokeh/server/views/static_handler.py
  bokeh/server/views/tests/test_ws.py
  bokeh/server/views/ws.py
Labels: status: accepted

#8383 Attempt to enable downstream tests for holoviews
  bokeh/models/__init__.py
  scripts/ci/install.downstream
  scripts/ci/test.downstream
Labels: status: WIP

#8522 Enable copy paste for datatables
  bokeh/_testing/util/selenium.py
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  tests/codebase/test_code_quality.py
  tests/integration/widgets/tables/test_cell_editors.py
  tests/integration/widgets/test_copy_paste.py
Labels: status: accepted

#8385 Add figure's plot id in DOM structure as well
  bokeh/core/_templates/macros.html
  bokeh/embed/tests/test_standalone.py
Labels: status: ready

#8464 textarea input widget
  bokeh/models/widgets/inputs.py
  bokehjs/src/less/widgets/widgets.less
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/src/lib/models/widgets/text_input.ts
  bokehjs/src/lib/models/widgets/textarea.ts
  sphinx/source/docs/user_guide/examples/interaction_textarea.py
  tests/integration/widgets/test_textarea_input.py
Labels: status: accepted

#8523 Property getter for Model.id
  bokeh/document/document.py
  bokeh/document/tests/test_document.py
  bokeh/document/util.py
  bokeh/embed/server.py
  bokeh/embed/tests/test_standalone.py
  bokeh/embed/tests/test_util.py
  bokeh/embed/util.py
  bokeh/events.py
  bokeh/io/notebook.py
  bokeh/io/tests/test_notebook.py
  bokeh/model.py
  bokeh/tests/test_events.py
  bokeh/tests/test_objects.py
  bokeh/util/callback_manager.py
  bokehjs/package-lock.json
Labels: reso: completed, status: accepted, type: task

#8528 release notes
  sphinx/source/docs/releases/1.0.1.rst
  sphinx/source/docs/releases/1.0.2.rst
  sphinx/source/docs/releases/1.0.3.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task
