Repository bokeh/bokeh, pull requests merged in 2018-07, with the labels that each got.

#8041 add some ticker tests
  bokehjs/src/lib/models/tickers/days_ticker.ts
  bokehjs/test/models/tickers/datetime_ticker.ts
  bokehjs/test/models/tickers/days_ticker.ts
  bokehjs/test/models/tickers/index.ts
  bokehjs/test/models/tickers/months_ticker.ts
  bokehjs/test/models/tickers/years_ticker.ts
Labels: status: accepted

#8045 fix ServerContext.sessions bug
  bokeh/server/contexts.py
  bokeh/server/tests/test_contexts.py
  bokeh/server/tornado.py
  sphinx/source/docs/reference/server/application_context.rst
  sphinx/source/docs/reference/server/contexts.rst
  sphinx/source/docs/releases/1.0.0.rst
Labels: status: accepted

#8048 format Bokeh warnings more nicely
  bokeh/__init__.py
  bokeh/tests/test___init__.py
Labels: status: accepted

#8049 add validation on extra range names
  bokeh/core/validation/errors.py
  bokeh/models/plots.py
  bokeh/models/tests/test_plots.py
  bokeh/models/tests/test_sources.py
Labels: status: accepted

#8044 allow recovery from transient script errors
  bokeh/application/handlers/code.py
  bokeh/application/handlers/code_runner.py
  bokeh/application/handlers/notebook.py
  bokeh/application/handlers/tests/test_code_runner.py
Labels: status: accepted

#8051 Addresses #8050 Change type of the selectable property of DataTable
  bokehjs/src/lib/models/widgets/tables/data_table.ts
Labels: status: accepted

#8025 Ellipse and oval hittesting
  bokehjs/src/lib/core/hittest.ts
  bokehjs/src/lib/models/glyphs/center_rotatable.ts
  bokehjs/src/lib/models/glyphs/ellipse.ts
  bokehjs/src/lib/models/glyphs/ellipse_oval.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/oval.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/test/core/hittest.ts
  bokehjs/test/core/index.ts
Labels: status: accepted

#8056 remove code dependent on IPython pprint machinery
  bokeh/core/has_props.py
  bokeh/core/tests/test_has_props.py
  bokeh/core/tests/test_properties.py
  bokeh/model.py
  bokeh/tests/test_model.py
  sphinx/source/docs/releases/1.0.0.rst
Labels: status: accepted

#8055 remove all deprecations
  bokeh/document/document.py
  bokeh/document/tests/test_document.py
  bokeh/models/plots.py
  bokeh/models/selections.py
  bokeh/models/tests/test_plots.py
  bokeh/server/tests/test_callbacks.py
  bokeh/util/tornado.py
  examples/models/file/transform_jitter.py
  examples/models/file/transform_jitter_coffee.py
  examples/plotting/file/elements.py
Labels: status: accepted, type: task

#8059 fix annulus hit testing with screen units
  bokehjs/src/lib/models/glyphs/annulus.ts
Labels: status: accepted

#8068 clamp bar endpoints to viewport
  bokehjs/src/lib/models/glyphs/box.ts
  bokehjs/src/lib/models/glyphs/hbar.ts
  bokehjs/src/lib/models/glyphs/vbar.ts
Labels: status: accepted

#8067 add header_row property to support hiding table headers
  bokeh/models/widgets/tables.py
  bokehjs/src/lib/models/widgets/tables/data_table.ts
Labels: status: accepted

#8076 Ensure BoxDrawTool does not draw when tool inactive
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
Labels: status: accepted

#8062 feature: add built in themes: dark_minimal and light_minimal
  bokeh/document/document.py
  bokeh/tests/test_themes.py
  bokeh/themes/__init__.py
  bokeh/themes/dark_minimal.json
  bokeh/themes/light_minimal.json
  examples/app/apply_theme.py
  setup.py
Labels: status: accepted

#8057 Added x and y values to the geometries property of cb_data for TapTool
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
Labels: status: accepted

#8080 always use zero angle for marker legends
  bokehjs/src/lib/models/markers/marker.ts
  scripts/ci/install
  scripts/ci/install:unit
Labels: status: accepted

#8087 REF: Simplify pie example #8086
  examples/plotting/file/pie.py
Labels: status: accepted

#8090 REF: Rename ci scripts, use dot (.) instead of colon (:) #8089
  .travis.yml
  docker-tools/Dockerfile-from-travis
  scripts/ci/install.build
  scripts/ci/install.codebase
  scripts/ci/install.deploy
  scripts/ci/install.downstream
  scripts/ci/install.examples
  scripts/ci/install.js
  scripts/ci/install.test
  scripts/ci/install.unit
  scripts/ci/test
  scripts/ci/test.codebase
  scripts/ci/test.docs
  scripts/ci/test.downstream
  scripts/ci/test.examples
  scripts/ci/test.integration
  scripts/ci/test.js
  scripts/ci/test.unit
Labels: status: accepted

#8091 Bryanv/test cleanup
  bokeh/_testing/plugins/integration_tests.py
  conda.recipe/meta.yaml
  conftest.py
  scripts/ci/test.codebase
  setup.cfg
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
  sphinx/source/docs/releases/1.0.0.rst
  tests/codebase/__init__.py
  tests/codebase/test_code_quality.py
  tests/codebase/test_flake8.py
  tests/codebase/test_no_client_server_common.py
  tests/codebase/test_no_ipython_common.py
  tests/codebase/test_no_request_host.py
  tests/codebase/test_no_tornado_common.py
  tests/codebase/test_python_execution_with_OO.py
  tests/codebase/test_windows_reserved_filenames.py
  tests/integration/README.md
  tests/integration/__init__.py
  tests/integration/interaction/__init__.py
  tests/integration/interaction/screenshots/base__test_datatable__test_data_table_selected_highlighting.png
  tests/integration/interaction/screenshots/base__test_hover__test_hover_changes_color.png
  tests/integration/interaction/screenshots/base__test_selection__test_line_rendering_with_selected_points.png
  tests/integration/interaction/test_datatable.py
  tests/integration/interaction/test_hover.py
  tests/integration/interaction/test_pan_tool.py
  tests/integration/interaction/test_patches_preselection.py
  tests/integration/interaction/test_range_min_max.py
  tests/integration/interaction/test_reset_tool.py
  tests/integration/interaction/test_selection.py
  tests/integration/interaction/test_sizing_mode.py
  tests/integration/interaction/test_tap.py
  tests/integration/interaction/test_tools.py
  tests/integration/interaction/test_wheel_zoom.py
  tests/test_flake8.py
  tests/test_no_client_server_common.py
  tests/test_no_ipython_common.py
  tests/test_no_request_host.py
  tests/test_no_tornado_common.py
  tests/test_python_execution_with_OO.py
  tests/test_windows_reserved_filenames.py
Labels: status: accepted

#8098 DOC: clean backticks in .rst docs #8097
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/bokehjs.rst
  sphinx/source/docs/user_guide/layout.rst
Labels: status: accepted

#8101 REF: Use generators inplace of lists #8092
  _setup_support.py
  bokeh/_testing/util/examples.py
  bokeh/core/enums.py
  bokeh/embed/util.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/tools.py
  bokeh/models/transforms.py
  bokeh/plotting/helpers.py
  bokeh/sampledata/autompg2.py
  bokeh/sampledata/us_holidays.py
  bokeh/tests/test_palettes.py
  bokeh/util/compiler.py
  bokeh/util/string.py
  examples/app/fourier_animated.py
Labels: status: accepted

#8095 Fix Karel/7788 rangeslider minmax
  bokeh/core/validation/errors.py
  bokeh/models/widgets/sliders.py
  bokeh/models/widgets/tests/test_slider.py
Labels: status: accepted

#8107 REF: Use .loc instead of .ix in examples
  examples/howto/layouts/words_and_plots.py
  examples/plotting/file/hover_glyph.py
  sphinx/source/docs/user_guide/examples/plotting_box_annotation.py
  sphinx/source/docs/user_guide/examples/styling_glyph_hover.py
Labels: reso: completed, status: accepted, tag: component: examples, type: task

#8125 Fixed Exception raising tests of test_sources
  bokeh/models/tests/test_sources.py
Labels: reso: completed, status: accepted, tag: component: tests, type: task

#8093 Fixes #6770. Flatten pandas columns and index explicitly on CDS creation
  bokeh/models/sources.py
  bokeh/models/tests/test_sources.py
  sphinx/source/docs/user_guide/data.rst
Labels: status: accepted

#8121 Update notebook.rst instructions using JupyterHub + Bokeh.
  sphinx/source/docs/user_guide/notebook.rst
Labels: status: accepted
