Repository bokeh/bokeh, pull requests merged in 2018-02, with the labels that each got.

#7261 Selection model and selection architecture refactor
  bokeh/models/__init__.py
  bokeh/models/selections.py
  bokeh/models/sources.py
  bokehjs/src/coffee/core/hittest.ts
  bokehjs/src/coffee/core/selection_manager.ts
  bokehjs/src/coffee/core/selector.ts
  bokehjs/src/coffee/models/glyphs/annular_wedge.ts
  bokehjs/src/coffee/models/glyphs/annulus.ts
  bokehjs/src/coffee/models/glyphs/bezier.ts
  bokehjs/src/coffee/models/glyphs/box.ts
  bokehjs/src/coffee/models/glyphs/circle.ts
  bokehjs/src/coffee/models/glyphs/glyph.ts
  bokehjs/src/coffee/models/glyphs/line.ts
  bokehjs/src/coffee/models/glyphs/multi_line.ts
  bokehjs/src/coffee/models/glyphs/patches.ts
  bokehjs/src/coffee/models/glyphs/rect.ts
  bokehjs/src/coffee/models/glyphs/segment.ts
  bokehjs/src/coffee/models/glyphs/wedge.ts
  bokehjs/src/coffee/models/glyphs/xy_glyph.ts
  bokehjs/src/coffee/models/graphs/graph_hit_test_policy.ts
  bokehjs/src/coffee/models/index.ts
  bokehjs/src/coffee/models/markers/marker.ts
  bokehjs/src/coffee/models/renderers/glyph_renderer.ts
  bokehjs/src/coffee/models/renderers/graph_renderer.ts
  bokehjs/src/coffee/models/selections/index.ts
  bokehjs/src/coffee/models/selections/interaction_policy.ts
  bokehjs/src/coffee/models/selections/selection.ts
  bokehjs/src/coffee/models/sources/cds_view.ts
  bokehjs/src/coffee/models/sources/columnar_data_source.ts
  bokehjs/src/coffee/models/sources/data_source.ts
  bokehjs/src/coffee/models/tools/edit/box_edit_tool.ts
  bokehjs/src/coffee/models/tools/edit/edit_tool.ts
  bokehjs/src/coffee/models/tools/edit/point_draw_tool.ts
  bokehjs/src/coffee/models/tools/edit/poly_draw_tool.ts
  bokehjs/src/coffee/models/tools/edit/poly_edit_tool.ts
  bokehjs/src/coffee/models/tools/inspectors/hover_tool.ts
  bokehjs/src/coffee/models/widgets/tables/data_table.ts
  bokehjs/test/core/index.ts
  bokehjs/test/core/selection_manager.coffee
  bokehjs/test/core/selector.ts
  bokehjs/test/defaults.ts
  bokehjs/test/models/graphs/graph_hit_test_policy.coffee
  bokehjs/test/models/index.coffee
  bokehjs/test/models/renderers/glyph_renderer.coffee
  bokehjs/test/models/selections/index.ts
  bokehjs/test/models/selections/selection.ts
  bokehjs/test/models/sources/cds_view.coffee
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/point_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_edit_tool.ts
  examples/integration/glyphs/selection_nonselection.py
Labels: status: accepted

#7514 Notify the user if package.json changed and `npm install` is needed
  bokehjs/.gitignore
  bokehjs/gulpfile.js
  bokehjs/package.json
  bokehjs/prepare.js
Labels: status: accepted

#7522 Fix typo
  examples/app/README.md
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#7517 Fix type errors in models/tiles
  bokeh/models/__init__.py
  bokeh/models/images.py
  bokehjs/src/coffee/api/typings.d.ts
  bokehjs/src/coffee/api/typings/models/images.d.ts
  bokehjs/src/coffee/models/tiles/bbox_tile_source.ts
  bokehjs/src/coffee/models/tiles/image_pool.ts
  bokehjs/src/coffee/models/tiles/image_source.ts
  bokehjs/src/coffee/models/tiles/index.ts
  bokehjs/src/coffee/models/tiles/mercator_tile_source.ts
  bokehjs/src/coffee/models/tiles/quadkey_tile_source.ts
  bokehjs/src/coffee/models/tiles/tile_renderer.ts
  bokehjs/src/coffee/models/tiles/tile_source.ts
  bokehjs/src/coffee/models/tiles/tile_utils.ts
  bokehjs/src/coffee/models/tiles/tms_tile_source.ts
  bokehjs/src/coffee/models/tiles/wmts_tile_source.ts
  bokehjs/test/models/tiles/tile_renderer.coffee
  sphinx/source/docs/reference/models/images.rst
Labels: status: accepted

#7533 Fixed FutureWarning in json serialization of floating values
  bokeh/core/json_encoder.py
Labels: status: accepted

#7534 Replace Range1d(start, end) with Range1d({start, end}) in documentation
  sphinx/source/docs/user_guide/bokehjs.rst
Labels: status: accepted

#7530 Add axis names to Scatterplot matrix
  examples/models/file/iris_splom.py
Labels: reso: completed, status: accepted, tag: component: examples, type: task

#7542 Fix typo in Figure.vbar_stack docstring
  bokeh/plotting/figure.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#7539 Clean up tmp files and processes used by bokeh.io.export
  bokeh/command/subcommands/png.py
  bokeh/command/subcommands/svg.py
  bokeh/io/export.py
  bokeh/io/tests/test_export.py
Labels: status: accepted

#7541 Configure side renderers' panels before setting up a toolbar
  bokehjs/src/coffee/models/plots/plot.ts
Labels: status: accepted

#7540 Stream as ndarray if any of old or new is an ndarray
  bokeh/core/property/containers.py
  bokeh/core/property/tests/test_containers.py
Labels: status: accepted

#7551 update docs to install flexx from conda-forge
  bokeh/models/callbacks.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/transforms.py
  sphinx/source/docs/user_guide/interaction/callbacks.rst
Labels: status: accepted

#7547 Implement rollover correctly in non-typed array case
  bokehjs/src/coffee/models/sources/column_data_source.ts
Labels: status: accepted

#7552 Bryanv/2507 grid tick bounds
  bokeh/models/grids.py
  bokehjs/src/coffee/model.ts
  bokehjs/src/coffee/models/grids/grid.ts
  bokehjs/src/coffee/models/tickers/continuous_ticker.ts
  bokehjs/test/models/grids/grid.coffee
  bokehjs/test/models/grids/index.coffee
  bokehjs/test/models/index.coffee
  bokehjs/test/models/tickers/continuous_ticker.ts
  sphinx/source/docs/releases/0.12.14.rst
  sphinx/source/docs/releases/0.12.15.rst
Labels: status: accepted

#7555 Fix type errors in core/ui_events and related code
  bokehjs/src/coffee/core/bokeh_events.ts
  bokehjs/src/coffee/core/dom_view.ts
  bokehjs/src/coffee/core/ui_events.ts
  bokehjs/src/coffee/models/annotations/legend.ts
  bokehjs/src/coffee/models/plots/plot_canvas.ts
  bokehjs/src/coffee/models/tools/edit/box_edit_tool.ts
  bokehjs/src/coffee/models/tools/edit/edit_tool.ts
  bokehjs/src/coffee/models/tools/edit/point_draw_tool.ts
  bokehjs/src/coffee/models/tools/edit/poly_draw_tool.ts
  bokehjs/src/coffee/models/tools/edit/poly_edit_tool.ts
  bokehjs/src/coffee/models/tools/gestures/box_select_tool.ts
  bokehjs/src/coffee/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/coffee/models/tools/gestures/gesture_tool.ts
  bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/coffee/models/tools/gestures/pan_tool.ts
  bokehjs/src/coffee/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/coffee/models/tools/gestures/select_tool.ts
  bokehjs/src/coffee/models/tools/gestures/tap_tool.ts
  bokehjs/src/coffee/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/coffee/models/tools/inspectors/crosshair_tool.ts
  bokehjs/src/coffee/models/tools/inspectors/hover_tool.ts
  bokehjs/src/coffee/models/tools/inspectors/inspect_tool.ts
  bokehjs/src/coffee/models/tools/tool.ts
  bokehjs/src/coffee/tsconfig.json
  bokehjs/test/core/ui_events.coffee
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/point_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_edit_tool.ts
  bokehjs/test/models/tools/edit/utils.ts
  bokehjs/test/models/tools/gestures/box_zoom_tool.coffee
  bokehjs/test/models/tools/gestures/wheel_zoom_tool.coffee
Labels: status: accepted

#7577 Added port parameter to show_app method.
  bokeh/io/notebook.py
Labels: status: accepted

#7570 Alpha for images
  bokeh/models/glyphs.py
  bokeh/models/tests/test_glyphs.py
  bokehjs/src/coffee/models/glyphs/image.ts
  examples/plotting/file/image_alpha.py
Labels: status: accepted

#7556 More generic sphinx doc sorting.
  bokeh/sphinxext/bokeh_plot.py
  sphinx/source/docs/releases/0.12.15.rst
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/extensions.rst
  sphinx/source/docs/user_guide/extensions_gallery/latex.rst
  sphinx/source/docs/user_guide/extensions_gallery/ticking.rst
  sphinx/source/docs/user_guide/extensions_gallery/tool.rst
  sphinx/source/docs/user_guide/extensions_gallery/widget.rst
  sphinx/source/docs/user_guide/extensions_gallery/wrapping.rst
  sphinx/source/docs/user_guide/graph.rst
  sphinx/source/docs/user_guide/interaction/callbacks.rst
  sphinx/source/docs/user_guide/interaction/legends.rst
  sphinx/source/docs/user_guide/interaction/linking.rst
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/layout.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/styling.rst
  sphinx/source/docs/user_guide/tools.rst
Labels: status: accepted

#7581 FuncTickFormatter: expose `index` and `ticks`
  bokeh/models/formatters.py
  bokehjs/src/coffee/models/formatters/func_tick_formatter.ts
  bokehjs/test/models/formatters/func_tick_formatter.coffee
Labels: status: accepted

#7579 Bryanv/7518 ajax data source endpoint undefined
  bokehjs/src/coffee/models/sources/ajax_data_source.ts
  bokehjs/test/models/sources/ajax_data_source.coffee
  bokehjs/test/models/sources/index.coffee
Labels: status: ready

#7567 Add support for JupyterLab comms
  bokehjs/src/coffee/embed.ts
  bokehjs/src/coffee/main.ts
  bokehjs/src/coffee/protocol/index.ts
Labels: status: accepted

#7560 Fail travis ci tests when TS errors are present
  _setup_support.py
  bokehjs/gulp/tasks/scripts.ts
  scripts/ci/install:codebase
  scripts/ci/test:codebase
Labels: status: accepted

#7584 don't repeat base install for external PRs
  scripts/ci/install:test
Labels: reso: completed, status: accepted, tag: component: build, type: task
