Repository bokeh/bokeh, pull requests merged in 2019-08, with the labels that each got.

#9109 Build on Read the Docs
  .readthedocs.yml
  _setup_support.py
  docs.txt
  setup.py
  sphinx/source/_templates/search.html
  sphinx/source/all_versions.txt
  sphinx/source/bokeh_theme/layout.html
  sphinx/source/bokeh_theme/static/css/main.css
  sphinx/source/bokeh_theme/static/js/main.js
  sphinx/source/conf.py
Labels: status: accepted

#9142 compute runtime deps correctly
  conda.recipe/meta.yaml
  scripts/ci/build
  scripts/ci/install
  scripts/deps.py
Labels: reso: completed, status: accepted, tag: component: build, type: bug

#9150 Use BokehJS from CDN when the commit is tagged
  sphinx/source/conf.py
Labels: status: ready

#9138 Allow to integrate bokeh models with ipywidgets
  bokeh/core/_templates/autoload_js.js
  bokeh/core/_templates/autoload_nb_js.js
  bokeh/core/tests/test_templates.py
  bokeh/document/events.py
  bokeh/embed/notebook/__init__.py
  bokeh/embed/notebook/widgets.py
  bokeh/util/compiler.py
  bokehjs/examples/tsconfig.json
  bokehjs/make/main.ts
  bokehjs/make/tasks/compiler.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/tsconfig.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/prelude.ts
  bokehjs/src/compiler/tsconfig.json
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/embed/notebook/index.ts
  bokehjs/src/lib/embed/notebook/widgets.ts
  bokehjs/src/lib/tsconfig.json
  bokehjs/test/tsconfig.json
  examples/howto/Jupyter widgets.ipynb
  tests/codebase/test_python_execution_with_OO.py
Labels: status: accepted

#9163 don't upload to s3 on py27 tests
  .travis.yml
  examples/custom/parallel_plot/parallel_plot.py
  scripts/ci/test.examples
  tests/baselines/examples/custom/parallel_plot/parallel_plot
Labels: reso: completed, status: accepted, tag: component: build, tag: component: examples, type: task

#9166 Bryanv/revert rtd
  .readthedocs.yml
  _setup_support.py
  docs.txt
  setup.py
  sphinx/source/_templates/search.html
  sphinx/source/all_versions.txt
  sphinx/source/bokeh_theme/layout.html
  sphinx/source/bokeh_theme/static/css/main.css
  sphinx/source/bokeh_theme/static/js/main.js
  sphinx/source/conf.py
Labels: status: accepted

#9168 Generate ES6 (ES2015) compatible bundles
  bokeh/io/export.py
  bokehjs/make/paths.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/compile.ts
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/sys.ts
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/lib/index.ts
  bokehjs/src/lib/legacy.ts
  bokehjs/src/lib/polyfill.ts
  bokehjs/src/lib/tsconfig.json
  bokehjs/test/size.ts
Labels: status: accepted

#9176 Make bokeh's tests work with pytest >= 5
  bokeh/application/tests/test_application.py
  bokeh/command/tests/test_util.py
  bokeh/core/property/tests/test_descriptors.py
  bokeh/core/property/tests/test_validation.py
  bokeh/core/tests/test_has_props.py
  bokeh/embed/tests/test_util.py
  bokeh/plotting/tests/test_helpers.py
  bokeh/server/tests/test_contexts.py
  bokeh/server/tests/test_server.py
  bokeh/tests/test_model.py
  bokeh/util/tests/test_dependencies.py
  conda.recipe/meta.yaml
Labels: status: accepted

#9177 Remove the slack notification token from .travis.yml
  .travis.yml
Labels: status: accepted, type: task

#9183 Update all docs links
  bokeh/__init__.py
  bokeh/core/_templates/notebook_load.html
  bokeh/embed/util.py
  bokeh/models/tools.py
  bokeh/server/views/app_index.html
  bokehjs/CONTRIBUTING.md
  bokehjs/README.md
  bokehjs/src/lib/models/tools/actions/help_tool.ts
  bokehjs/src/lib/models/tools/toolbar_base.ts
  examples/README.md
  examples/app/README.md
  examples/app/dash/README.md
  examples/app/faces/templates/index.html
  examples/app/surface3d/surface3d.py
  examples/custom/README.md
  examples/embed/README.md
  examples/embed/autoload_static.py
  examples/embed/server_session/templates/embed.html
  examples/howto/notebook_comms/Jupyter Interactors.ipynb
  examples/howto/notebook_comms/Numba Image Example.ipynb
  examples/howto/server_embed/templates/embed.html
  examples/models/README.md
  examples/models/file/glyphs.py
  examples/models/file/image_url.py
  examples/plotting/README.md
  examples/plotting/file/image_alpha.py
  examples/reference/models/ImageURL.py
  sphinx/source/bokeh_theme/layout.html
  sphinx/source/bokeh_theme/static/js/main.js
  sphinx/source/conf.py
  sphinx/source/docs/releases/0.12.0.rst
  sphinx/source/docs/releases/0.12.2.rst
  sphinx/source/docs/releases/0.12.7.rst
  sphinx/source/docs/releases/0.12.9.rst
  sphinx/source/docs/user_guide/examples/extensions_example_widget.py
  sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
  sphinx/source/docs/user_guide/examples/tools_hover_custom_tooltip.py
  sphinx/source/docs/user_guide/tools.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9184 ensure null values in geoJSON are rendered as NaNs in the data source
  bokehjs/src/lib/models/sources/geojson_data_source.ts
  bokehjs/test/models/sources/geojson_data_source.ts
Labels: status: accepted

#9189 handle angle between 0, 2pi correctly
  bokehjs/src/lib/core/util/math.ts
  bokehjs/test/core/util/math.ts
Labels: status: accepted

#9205 Don't depend on ipywidgets
  .appveyor.yml
  bokeh/embed/notebook/widgets.py
  conda.recipe/meta.yaml
  examples/howto/Jupyter widgets.ipynb
  scripts/ci/appveyor/build.ps1
  scripts/ci/appveyor/install.ps1
  scripts/ci/appveyor/test.ps1
Labels: plat: windows, reso: completed, status: accepted, tag: component: build, type: task

#9206 Outdated sentence removed from docs
  sphinx/source/docs/user_guide/export.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9204 Fix broken link to examples/app
  examples/app/clustering/README.md
Labels: status: accepted

#9200 Fix typos in docs, comments, etc
  bokeh/application/handlers/code_runner.py
  bokeh/client/session.py
  bokeh/command/tests/test_util.py
  bokeh/command/util.py
  bokeh/core/enums.py
  bokeh/core/json_encoder.py
  bokeh/core/property/dataspec.py
  bokeh/document/document.py
  bokeh/io/state.py
  bokeh/models/layouts.py
  bokeh/plotting/figure.py
  bokeh/plotting/helpers.py
  bokeh/sampledata/les_mis.py
  bokeh/server/tornado.py
  bokehjs/src/lib/core/util/refs.ts
  bokehjs/src/lib/models/annotations/label.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/tickers/fixed_ticker.ts
  bokehjs/src/lib/models/tools/tool.ts
  sphinx/source/docs/dev_guide/server.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/releases/0.12.15.rst
  sphinx/source/docs/releases/0.12.5.rst
  sphinx/source/docs/releases/1.1.0.rst
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/server.rst
Labels: status: accepted

#9192 Pillow is already a bokeh dependency
  sphinx/source/docs/user_guide/export.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9188 Finalize support for rotate events
  bokeh/events.py
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/test/core/ui_events.ts
  bokehjs/test/models/tools/edit/box_edit_tool.ts
  bokehjs/test/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/models/tools/edit/point_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/models/tools/edit/poly_edit_tool.ts
  bokehjs/test/models/tools/edit/utils.ts
  examples/custom/custom_tool.py
  examples/custom/parallel_plot/parallel_selection_tool.ts
  sphinx/source/docs/user_guide/examples/extensions_example_tool.py
Labels: status: accepted

#8977 Set crossorigin on images to allow save tool to work
  bokeh/_testing/util/chrome_screenshot.js
  bokehjs/eslint.json
  bokehjs/make/tasks/test.ts
  bokehjs/src/lib/core/util/image.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/src/lib/models/textures/image_url_texture.ts
  bokehjs/src/lib/models/tiles/image_pool.ts
  bokehjs/src/lib/models/tiles/mercator_tile_source.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/tiles/tile_source.ts
  bokehjs/test/models/tiles/tile_renderer.ts
Labels: status: accepted

#9203 Print full stacktrace to console when an error occurs
  bokeh/server/protocol_handler.py
Labels: status: WIP
