Repository bokeh/bokeh, pull requests merged in 2019-01, with the labels that each got.

#8530 Boilerplate for bokeh/sphinxext and bokeh/template
  bokeh/sphinxext/__init__.py
  bokeh/sphinxext/bokeh_autodoc.py
  bokeh/sphinxext/bokeh_color.py
  bokeh/sphinxext/bokeh_directive.py
  bokeh/sphinxext/bokeh_enum.py
  bokeh/sphinxext/bokeh_gallery.py
  bokeh/sphinxext/bokeh_github.py
  bokeh/sphinxext/bokeh_jinja.py
  bokeh/sphinxext/bokeh_model.py
  bokeh/sphinxext/bokeh_options.py
  bokeh/sphinxext/bokeh_palette.py
  bokeh/sphinxext/bokeh_palette_group.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_prop.py
  bokeh/sphinxext/bokeh_releases.py
  bokeh/sphinxext/bokeh_sitemap.py
  bokeh/sphinxext/collapsible_code_block.py
  bokeh/sphinxext/example_handler.py
  bokeh/sphinxext/sample.py
  bokeh/sphinxext/templates.py
  bokeh/themes/__init__.py
  bokeh/themes/_caliber.py
  bokeh/themes/_dark_minimal.py
  bokeh/themes/_light_minimal.py
  bokeh/themes/theme.py
Labels: status: ready

#8535 Boilerplate for bokeh/util
  bokeh/util/__init__.py
  bokeh/util/browser.py
  bokeh/util/callback_manager.py
  bokeh/util/compiler.py
  bokeh/util/datatypes.py
  bokeh/util/dependencies.py
  bokeh/util/deprecation.py
  bokeh/util/future.py
  bokeh/util/hex.py
  bokeh/util/logconfig.py
  bokeh/util/options.py
  bokeh/util/paths.py
  bokeh/util/sampledata.py
  bokeh/util/serialization.py
  bokeh/util/session_id.py
  bokeh/util/string.py
  bokeh/util/terminal.py
  bokeh/util/tests/__init__.py
  bokeh/util/tests/test_browser.py
  bokeh/util/tests/test_callback_manager.py
  bokeh/util/tests/test_compiler.py
  bokeh/util/tests/test_dependencies.py
  bokeh/util/tests/test_deprecation.py
  bokeh/util/tests/test_hex.py
  bokeh/util/tests/test_options.py
  bokeh/util/tests/test_sampledata.py
  bokeh/util/tests/test_serialization.py
  bokeh/util/tests/test_session_id.py
  bokeh/util/tests/test_string.py
  bokeh/util/tests/test_tornado.py
  bokeh/util/tests/test_version.py
  bokeh/util/tornado.py
  bokeh/util/version.py
  bokeh/util/warnings.py
Labels: status: accepted

#8538 Initial boilerplate for bokeh/tests
  bokeh/tests/__init__.py
  bokeh/tests/test___init__.py
  bokeh/tests/test___main__.py
  bokeh/tests/test_client_server.py
  bokeh/tests/test_driving.py
  bokeh/tests/test_events.py
  bokeh/tests/test_layouts.py
  bokeh/tests/test_model.py
  bokeh/tests/test_objects.py
  bokeh/tests/test_palettes.py
  bokeh/tests/test_resources.py
  bokeh/tests/test_server.py
  bokeh/tests/test_settings.py
  bokeh/tests/test_themes.py
  bokeh/tests/test_tile_providers.py
  bokeh/tests/test_transform.py
  bokeh/tests/test_widgets.py
Labels: status: accepted

#8537 Birdsarah/8534 docs tweak
  bokeh/resources.py
  sphinx/source/docs/dev_guide/env_vars.rst
Labels: status: accepted

#8542 use only yaml.safe_load
  bokeh/_testing/util/examples.py
  bokeh/themes/theme.py
  bokeh/util/sampledata.py
Labels: status: accepted

#8544 better error message for nonexistent bokeh serve targets
  bokeh/command/tests/test_util.py
  bokeh/command/util.py
Labels: status: accepted

#8545 remove warning message aboug gulp
  bokehjs/prepare.js
Labels: status: accepted

#8550 Fix-up BOKEH_DEV docs (follow-up)
  bokeh/settings.py
  sphinx/source/docs/dev_guide/env_vars.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#8549 Add documentation on callback policy for slider
  bokeh/models/widgets/sliders.py
Labels: status: accepted

#8539 Preprocessor to strip out IPython magics from notebooks
  bokeh/application/handlers/notebook.py
  bokeh/application/handlers/tests/test_notebook.py
Labels: status: accepted

#8553 add Model, Event, and populate bokeh.models __all__
  bokeh/events.py
  bokeh/model.py
  bokeh/models/__init__.py
Labels: status: accepted

#8556 Correct three minor typos
  bokeh/models/tools.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#8557 1.0.4 release notes
  sphinx/source/docs/releases/1.0.4.rst
Labels: status: accepted

#8558 Safer alternative fix for unicode notebook issue in Python 2
  bokeh/application/handlers/notebook.py
  bokeh/application/handlers/tests/test_notebook.py
Labels: reso: completed, status: accepted, tag: py2, type: bug

#8565 Ensure compilation of custom model works with bokehjs compiled on win
  bokeh/util/tests/test_compiler.py
  bokehjs/make/linker.ts
Labels: status: ready

#8575 force zero padding for fixed axes
  bokeh/util/tests/test_compiler.py
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/test/models/axes/axis.ts
Labels: status: accepted

#8587 pin conda versions with CONDA_REQS on appveyor too
  scripts/ci/appveyor/install.ps1
Labels: plat: windows, reso: completed, status: accepted, tag: component: build, type: task

#8588 adapt to pandas changes
  bokeh/sampledata/commits.py
Labels: status: accepted

#8586 Possible typo in documentation for bokeh.client.session.
  bokeh/client/session.py
Labels: status: accepted

#8590 #8589 Fixes docstring typo in patch method of sources.py
  bokeh/models/sources.py
Labels: status: accepted

#8578 Create custom example to plot parallel plot
  examples/custom/parallel_plot/parallel_plot.py
  examples/custom/parallel_plot/parallel_reset.py
  examples/custom/parallel_plot/parallel_reset.ts
  examples/custom/parallel_plot/parallel_selection_tool.py
  examples/custom/parallel_plot/parallel_selection_tool.ts
Labels: reso: completed, status: accepted, tag: component: examples, type: task

#8594 Invalidate TileSource cache on property changes
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/tiles/tile_source.ts
  bokehjs/test/models/tiles/tile_renderer.coffee
Labels: status: accepted

#8593 Refactor tile_providers to handle multiple documents more intuitively…
  bokeh/tests/test_tile_providers.py
  bokeh/tile_providers.py
  examples/integration/tiles/tile_smoothing.py
  examples/plotting/file/tile_source.py
Labels: status: ready

#8601 Fix CDS callback property callbacks
  bokehjs/src/lib/models/sources/data_source.ts
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections_lasso_mean.py
  tests/integration/models/test_sources.py
Labels: status: accepted

#8602 remove extraneous ctx.fill for bands
  bokehjs/src/lib/models/grids/grid.ts
Labels: status: accepted
