Repository bokeh/bokeh, pull requests merged in 2019-09, with the labels that each got.

#9211 [DOC] Tpyos
  sphinx/source/docs/user_guide/server.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9212 Upgrade to TypeScript 3.6
  bokehjs/.vscode/settings.json
  bokehjs/make/tasks/compiler.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/models/plots/plot_canvas.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: typescript, type: task

#9214 Adding the ability to parse globs in quotes in serve
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/apps/apply_theme.py
  bokeh/command/subcommands/tests/apps/line_on_off.py
  bokeh/command/subcommands/tests/test_serve.py
Labels: status: accepted

#9227 9226: Update license id to use the proper SPDX short license id
  setup.py
Labels: status: accepted

#9229 Bryanv/update docs automation
  .travis.yml
  conda.recipe/meta.yaml
  scripts/build_upload.py
  scripts/ci/deploy
  scripts/ci/install.deploy
  secrets.tar.enc
  sphinx/draw.io/README.md
  sphinx/draw.io/bokeh_serve.xml
  sphinx/draw.io/bokeh_serve_client.xml
  sphinx/draw.io/bokeh_serve_scale.xml
  sphinx/draw.io/document.xml
  sphinx/fabfile.py
Labels: status: ready, tag: component: build, type: task

#9228 Update current year
  LICENSE.txt
Labels: reso: completed, status: accepted, type: task

#9234 clarify selection usage
  bokeh/models/selections.py
  sphinx/source/docs/user_guide/tools.rst
Labels: status: accepted
