Repository bokeh/bokeh, pull requests merged in 2019-12, with the labels that each got.

#9486 update twitter username
  sphinx/source/bokeh/docs-navbar.html
  sphinx/source/docs/user_guide/quickstart.rst
Labels: status: accepted

#9493 Fix WebGL rendering on high DPI displays
  bokehjs/src/lib/models/plots/plot_canvas.ts
Labels: status: accepted

#9488 split override/trait defaults, add tests
  bokeh/plotting/helpers.py
  tests/unit/bokeh/plotting/test_helpers.py
Labels: status: accepted

#9487 Disable option in FileInput not working #9485
  bokehjs/src/lib/models/widgets/file_input.ts
Labels: status: accepted

#9489 More SRI hash work
  bokeh/resources.py
  bokeh/util/version.py
  scripts/sri.py
  sphinx/source/conf.py
  tests/unit/bokeh/util/test_version.py
Labels: status: accepted

#9503 Fix simple typo: ther -> the
  sphinx/source/docs/user_guide/annotations.rst
Labels: status: accepted

#9333 Don't include type when referencing an object
  bokeh/document/util.py
  bokeh/model.py
  bokehjs/make/tasks/generate_defaults.py
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/util/refs.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/util/refs.ts
  bokehjs/test/unit/document/events.ts
  tests/integration/models/test_sources.py
  tests/integration/widgets/tables/test_source_updates.py
  tests/unit/bokeh/test_objects.py
Labels: status: accepted

#9520 Pivot is not a supported app anymore
  examples/app/README.md
Labels: status: accepted

#9526 Fix User Guide documentation errors.
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/concepts.rst
Labels: status: accepted

#9400 W0rdsm1th/master/9064 bokeh command typing
  bokeh/command/bootstrap.py
  bokeh/command/subcommand.py
  bokeh/command/subcommands/__init__.py
  bokeh/command/subcommands/build.py
  bokeh/command/subcommands/file_output.py
  bokeh/command/subcommands/html.py
  bokeh/command/subcommands/info.py
  bokeh/command/subcommands/init.py
  bokeh/command/subcommands/json.py
  bokeh/command/subcommands/png.py
  bokeh/command/subcommands/sampledata.py
  bokeh/command/subcommands/secret.py
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/static.py
  bokeh/command/subcommands/svg.py
  bokeh/command/util.py
  bokeh/document/document.py
  bokeh/ext.py
  bokeh/io/export.py
  bokeh/util/compiler.py
  bokeh/util/hex.py
  setup.cfg
  tests/unit/bokeh/command/subcommands/test_serve.py
Labels: status: accepted

#9534 Add angle brackets to fakesource in order to be ignored by coverage
  bokeh/plotting/helpers.py
Labels: status: accepted

#9513 [WIP] CI Experiments
  .github/workflows/bokeh-ci.yml
  .travis.yml
  bokeh/_testing/util/examples.py
  bokeh/_testing/util/s3.py
  bokeh/_testing/util/travis.py
  tests/baselines/examples/app/dash
  tests/integration/tools/test_point_draw_tool.py
  tests/integration/tools/test_poly_draw_tool.py
  tests/integration/tools/test_poly_edit_tool.py
  tests/integration/widgets/test_autocomplete_input.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_text_input.py
  tests/unit/bokeh/test_resources.py
Labels: status: accepted

#9531 Adding dedicated subsection to docs on Bokeh Server Jinja templating
  sphinx/source/docs/user_guide/server.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9540 Continuing CI Work
  .bettercodehub.yml
  .github/workflows/bokeh-ci.yml
  .lgtm.yml
  README.md
  bokeh/_testing/plugins/examples_report.py
  bokeh/_testing/util/examples.py
  bokeh/util/sampledata.json
  bokeh/util/sampledata.py
  conda.recipe/meta.yaml
  setup.py
  tests/examples.yaml
Labels: status: accepted

#9541 Misc fixes
  .lgtm.yml
  _setup_support.py
  bokeh/_testing/plugins/file_server.py
  bokeh/command/subcommands/secret.py
  bokeh/command/subcommands/svg.py
  bokeh/core/property/either.py
  bokeh/core/property/wrappers.py
  bokeh/embed/bundle.py
  bokeh/embed/util.py
  bokeh/io/export.py
  bokeh/io/util.py
  bokeh/model.py
  bokeh/plotting/helpers.py
  bokeh/settings.py
  bokeh/sphinxext/bokehjs_content.py
  bokeh/sphinxext/example_handler.py
  bokeh/themes/theme.py
  examples/app/spectrogram/audio.py
  examples/embed/embed_themed.py
  examples/howto/server_auth/auth.py
  examples/models/file/gauges.py
  examples/webgl/line_compare.py
  scripts/deploy.py
  scripts/issues.py
  sphinx/docserver.py
  sphinx/source/bokeh/scripts.html
Labels: status: accepted

#9544 flaky selenium tests
  .github/workflows/bokeh-ci.yml
  bokeh/_testing/util/selenium.py
  bokehjs/src/lib/testing.ts
  tests/integration/models/test_datarange1d.py
  tests/integration/tools/test_box_edit_tool.py
  tests/integration/tools/test_box_zoom_tool.py
  tests/integration/tools/test_freehand_draw_tool.py
  tests/integration/tools/test_pan_tool.py
  tests/integration/tools/test_point_draw_tool.py
  tests/integration/tools/test_poly_draw_tool.py
  tests/integration/tools/test_poly_edit_tool.py
  tests/integration/tools/test_range_tool.py
  tests/integration/tools/test_reset_tool.py
  tests/integration/tools/test_wheel_zoom_tool.py
  tests/integration/tools/test_zoom_in_tool.py
  tests/integration/tools/test_zoom_out_tool.py
  tests/integration/widgets/tables/test_copy_paste.py
  tests/integration/widgets/test_range_slider.py
  tests/integration/widgets/test_slider.py
Labels: reso: completed, status: accepted, tag: component: build, tag: component: tests, type: task

#9543 Bryanv/more misc
  .lgtm.yml
  bokeh/sphinxext/_templates/bokehjs_codepen_init.html
  bokeh/sphinxext/theme.py
  bokehjs/examples/electron/renderer.js
  bokehjs/src/lib/core/hittest.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/annotations/band.ts
  bokehjs/src/lib/models/formatters/basic_tick_formatter.ts
  bokehjs/src/lib/models/glyphs/harea.ts
  bokehjs/src/lib/models/glyphs/varea.ts
  bokehjs/src/lib/models/tickers/mercator_ticker.ts
  bokehjs/src/lib/models/tiles/mercator_tile_source.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/widgets/spinner.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#9547 More misc repo work
  .lgtm.yml
  bokeh/_testing/util/filesystem.py
  bokeh/application/handlers/code_runner.py
  bokeh/core/has_props.py
  bokeh/core/query.py
  bokeh/document/document.py
  bokeh/document/locking.py
  bokeh/layouts.py
  bokeh/models/sources.py
  bokeh/server/session.py
  bokeh/settings.py
  bokeh/sphinxext/bokeh_model.py
  bokeh/sphinxext/bokeh_options.py
  bokeh/sphinxext/bokeh_palette_group.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_releases.py
  bokeh/sphinxext/bokeh_settings.py
  bokeh/sphinxext/example_handler.py
  bokeh/sphinxext/util.py
  bokeh/util/deprecation.py
  bokehjs/src/lib/core/ui_events.ts
  scripts/build_upload.py
  tests/unit/bokeh/document/test_locking.py
Labels: reso: completed, status: accepted, type: task

#9548 remove old ad-hoc callback properties
  bokeh/models/layouts.py
  bokeh/models/ranges.py
  bokeh/models/sources.py
  bokeh/models/tools.py
  bokeh/models/widgets/groups.py
  bokeh/models/widgets/inputs.py
  bokehjs/package-lock.json
  bokehjs/src/lib/models/layouts/tabs.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/src/lib/models/sources/data_source.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/widgets/button_group.ts
  bokehjs/src/lib/models/widgets/checkbox_button_group.ts
  bokehjs/src/lib/models/widgets/checkbox_group.ts
  bokehjs/src/lib/models/widgets/input_widget.ts
  bokehjs/src/lib/models/widgets/radio_button_group.ts
  bokehjs/src/lib/models/widgets/radio_group.ts
  bokehjs/test/unit/models/annotations/color_bar.ts
  bokehjs/test/unit/models/plots/plot.ts
  bokehjs/test/unit/models/ranges/data_range1d.ts
  bokehjs/test/unit/models/ranges/factor_range.ts
  bokehjs/test/unit/models/ranges/range1d.ts
  bokehjs/test/unit/models/widgets/checkbox_button_group.ts
  examples/howto/using_password_input.py
  examples/models/file/transform_interpolator.py
  examples/plotting/file/line_on_off.py
  sphinx/source/docs/releases/2.0.0.rst
  sphinx/source/docs/user_guide/examples/extensions_example_widget.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_range_update.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_tools.py
  sphinx/source/docs/user_guide/interaction/callbacks.rst
  tests/integration/models/test_sources.py
  tests/integration/tools/test_reset_tool.py
  tests/integration/widgets/test_checkbox_button_group.py
  tests/integration/widgets/test_checkbox_group.py
  tests/integration/widgets/test_dropdown.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_radio_button_group.py
  tests/integration/widgets/test_radio_group.py
  tests/integration/widgets/test_select.py
  tests/integration/widgets/test_spinner.py
  tests/integration/widgets/test_text_input.py
  tests/unit/bokeh/models/test_plots.py
  tests/unit/bokeh/models/test_ranges.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task
