Repository bokeh/bokeh, pull requests merged in 2019-06, with the labels that each got.

#8961 don't call show in tests
  bokeh/util/tests/test_compiler.py
Labels: reso: completed, status: accepted, tag: component: tests, type: task

#8969 remove last 2.7 and 3.4 bits
  bokeh/application/handlers/code_runner.py
  bokeh/application/handlers/tests/test_code.py
  bokeh/command/subcommands/tests/test_serve.py
  bokeh/io/webdriver.py
  conda.recipe/meta.yaml
  docker-tools/README.md
  setup.py
  sphinx/source/docs/dev_guide/testing.rst
  sphinx/source/docs/installation.rst
  sphinx/source/docs/releases/2.0.0.rst
Labels: landing-2.0, reso: completed, status: accepted, tag: component: build, type: task

#8971 use 'use strict' unconditionally
  bokeh/models/callbacks.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/transforms.py
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/src/lib/models/filters/customjs_filter.ts
  bokehjs/src/lib/models/formatters/func_tick_formatter.ts
  bokehjs/src/lib/models/transforms/customjs_transform.ts
  bokehjs/test/models/callbacks/customjs.ts
  bokehjs/test/models/filters/customjs_filter.ts
  bokehjs/test/models/formatters/func_tick_formatter.ts
  bokehjs/test/models/transforms/customjs_transform.ts
  sphinx/source/docs/releases/2.0.0.rst
Labels: landing-2.0, status: accepted

#8968 Restrict CDS property changes
  bokeh/core/property/bases.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/instance.py
  bokeh/core/property/tests/test_bases.py
  bokeh/core/property/tests/test_instance.py
  bokeh/models/graphs.py
  bokeh/models/sources.py
  bokeh/models/tests/test_sources.py
  examples/integration/glyphs/selection_nonselection.py
  examples/integration/widgets/data_table_preselection.py
  sphinx/source/docs/releases/2.0.0.rst
Labels: landing-2.0, reso: completed, status: accepted, type: task

#8972 remove obsolete sphinxext things
  bokeh/sphinxext/_templates/plot_page.rst
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/templates.py
  sphinx/source/conf.py
  sphinx/source/docs/releases/2.0.0.rst
Labels: landing-2.0, reso: completed, status: accepted, type: task

#8973 execute tile provider deprecations
  bokeh/tests/test_tile_providers.py
  bokeh/tile_providers.py
  examples/integration/tiles/tile_smoothing.py
  examples/plotting/file/airports_map.py
  examples/plotting/file/customjs_hover.py
  examples/plotting/file/tile_source.py
  sphinx/source/docs/releases/2.0.0.rst
  sphinx/source/docs/user_guide/examples/geo_tile_source.py
Labels: landing-2.0, status: accepted

#8975 remove selection compat dict
  bokehjs/examples/donut/donut.ts
  bokehjs/examples/tap/tap.ts
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/test/models/glyphs/rect.ts
  bokehjs/test/models/graphs/graph_hit_test_policy.ts
  sphinx/source/docs/releases/2.0.0.rst
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_hover.py
Labels: landing-2.0, reso: completed, status: accepted, type: task

#8965 Deprecations for 2.0
  bokeh/client/session.py
  bokeh/models/callbacks.py
  bokeh/models/expressions.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/scales.py
  bokeh/models/tests/test_callbacks.py
  bokeh/models/tests/test_formatters.py
  bokeh/models/tests/test_transforms.py
  bokeh/models/tools.py
  bokeh/models/transforms.py
  bokeh/models/widgets/buttons.py
  bokeh/tests/test_client_server.py
  bokeh/util/compiler.py
  bokeh/util/tests/test_compiler.py
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/compile.ts
  bokehjs/src/lib/models/widgets/abstract_button.ts
  bokehjs/src/lib/models/widgets/button.ts
  bokehjs/src/lib/models/widgets/dropdown.ts
  examples/app/export_csv/main.py
  examples/custom/font-awesome/font-awesome.py
  examples/models/file/transform_jitter.py
  examples/plotting/file/python_callback.py
  examples/webgl/line_compare.py
  sphinx/source/docs/installation.rst
  sphinx/source/docs/releases/2.0.0.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/examples/extensions_example_widget.py
  sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
  sphinx/source/docs/user_guide/examples/interaction_callbacks_in_python.py
  sphinx/source/docs/user_guide/extensions.rst
  sphinx/source/docs/user_guide/interaction/callbacks.rst
  sphinx/source/docs/user_guide/styling.rst
  tests/integration/widgets/test_button.py
  tests/integration/widgets/test_toggle.py
Labels: landing-2.0, status: accepted

#8979 Remove Bokeh wire protocol versioning
  bokeh/client/connection.py
  bokeh/client/tests/test_connection.py
  bokeh/io/notebook.py
  bokeh/protocol/__init__.py
  bokeh/protocol/message.py
  bokeh/protocol/messages/__init__.py
  bokeh/protocol/messages/ack.py
  bokeh/protocol/messages/error.py
  bokeh/protocol/messages/event.py
  bokeh/protocol/messages/ok.py
  bokeh/protocol/messages/patch_doc.py
  bokeh/protocol/messages/pull_doc_reply.py
  bokeh/protocol/messages/pull_doc_req.py
  bokeh/protocol/messages/push_doc.py
  bokeh/protocol/messages/server_info_reply.py
  bokeh/protocol/messages/server_info_req.py
  bokeh/protocol/messages/tests/test_patch_doc.py
  bokeh/protocol/messages/tests/test_pull_doc.py
  bokeh/protocol/messages/tests/test_push_doc.py
  bokeh/protocol/messages/tests/test_working.py
  bokeh/protocol/receiver.py
  bokeh/protocol/tests/test_receiver.py
  bokeh/protocol/tests/test_versions.py
  bokeh/protocol/versions.py
  bokeh/server/contexts.py
  bokeh/server/protocol_handler.py
  bokeh/server/tests/test_server.py
  bokeh/server/views/ws.py
  bokeh/tests/test_client_server.py
  bokehjs/src/lib/client/connection.ts
  sphinx/source/docs/reference/protocol.rst
Labels: landing-2.0, reso: completed, status: accepted, type: task

#8985 more explicit hover formatter specs
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/test/core/util/templating.ts
  examples/plotting/file/customjs_hover.py
  sphinx/source/docs/releases/2.0.0.rst
  sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py
  sphinx/source/docs/user_guide/tools.rst
Labels: landing-2.0, reso: completed, status: accepted, type: task

#8996 update classifiers and setup.py
  classifiers.txt
  setup.py
Labels: landing-2.0, reso: completed, status: accepted, type: task

#8997 Documentation: fix typo and duplicate description
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/tools.rst
Labels: status: accepted

#8993 Fix keyboard events on range sliders
  bokeh/_testing/util/selenium.py
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/src/lib/models/widgets/date_range_slider.ts
  bokehjs/src/lib/models/widgets/date_slider.ts
  bokehjs/src/lib/models/widgets/range_slider.ts
  bokehjs/src/lib/models/widgets/slider.ts
  tests/integration/widgets/test_range_slider.py
  tests/integration/widgets/test_slider.py
Labels: status: accepted

#9027 make docs for --dev arg placement clearer
  bokeh/command/subcommands/serve.py
  bokeh/command/subcommands/tests/test_serve.py
Labels: status: accepted

#9028 fix enum doc issues
  bokeh/core/enums.py
  bokeh/core/tests/test_enums.py
Labels: status: accepted

#9034 Filter inspection indices more efficiently
  bokehjs/src/lib/core/util/serialization.ts
  bokehjs/src/lib/external/es2015.d.ts
  bokehjs/src/lib/models/glyphs/webgl/line.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/tsconfig.json
Labels: status: accepted

#9013 implement hover anchor for quad glyphs
  bokehjs/src/lib/models/glyphs/box.ts
  bokehjs/src/lib/models/glyphs/quad.ts
Labels: status: accepted

#9030 replace remote datasource with web datasource
  bokeh/models/sources.py
  bokehjs/src/lib/models/sources/ajax_data_source.ts
  bokehjs/src/lib/models/sources/index.ts
  bokehjs/src/lib/models/sources/remote_data_source.ts
Labels: status: accepted

#9031 Geojson docs
  sphinx/source/docs/user_guide/examples/geo_geojson_source.py
Labels: status: accepted
