Repository bokeh/bokeh, pull requests merged in 2020-03, with the labels that each got.

#9746 differentiate legacy files by filename
  MANIFEST.in
  bokeh/resources.py
  bokehjs/make/paths.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/test/codebase/size.ts
Labels: status: ready

#9754 allow sdist to --install-js
  _setup_support.py
  setup.py
Labels: reso: completed, status: accepted, tag: component: build, type: task

#9732 File input multi2
  bokeh/models/widgets/inputs.py
  bokehjs/src/lib/models/widgets/file_input.ts
Labels: status: accepted

#9759 Switch from git to npm package dependencies
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/less/widgets/slickgrid.less
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/external/numbro.d.ts
  bokehjs/src/lib/external/slickgrid.d.ts
  bokehjs/src/lib/external/timezone.d.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/formatters/numeral_tick_formatter.ts
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/glyphs/webgl/line.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/widgets/range_slider.ts
  bokehjs/src/lib/models/widgets/slider.ts
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/src/lib/models/widgets/tables/row_aggregators.ts
  bokehjs/src/lib/models/widgets/tables/table_column.ts
Labels: status: accepted

#9692 Upgrade to TypeScript 3.8
  bokehjs/make/tasks/lint.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/signaling.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/index.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/markers/marker.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/tsconfig.json
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: typescript, type: task

#9766 DOC: Add missing '@' in HoverTool.formatters example
  bokeh/models/tools.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9740 fix issue #9703
  bokehjs/src/lib/models/glyphs/image_url.ts
Labels: status: ready

#9776 Update setting asyncio event loop policy
  bokeh/server/tornado.py
Labels: status: accepted

#9777 Bryanv/9773 crossorigin
  bokeh/core/_templates/autoload_js.js
  bokeh/core/_templates/js_resources.html
  bokeh/embed/standalone.py
  bokeh/model.py
  bokeh/resources.py
  bokeh/sphinxext/bokeh_releases.py
  bokeh/util/version.py
  sphinx/source/docs/installation.rst
  sphinx/source/docs/user_guide/embed.rst
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/test_resources.py
Labels: status: accepted

#9720 add update docker-tools (resubmit)
  docker-tools/README.md
  docker-tools/alpine/Dockerfile-conda
  docker-tools/alpine/Dockerfile-from-source
  docker-tools/debian/Dockerfile
  docker-tools/debian/Dockerfile-pip
  docker-tools/debian/app.yaml
  docker-tools/debian/environment.yml
  docker-tools/debian/requirements.txt
Labels: status: accepted

#9781 Correct guidance on additional dependencies to export plots
  sphinx/source/docs/user_guide/export.rst
Labels: status: accepted

#9782 Fixes typos and adds missing words to documentation
  bokeh/core/__init__.py
  sphinx/source/docs/dev_guide/server.rst
  sphinx/source/docs/reference/core/properties.rst
Labels: status: accepted

#9780 Fix arrow clipping in plots in complex layouts
  bokehjs/src/lib/models/annotations/arrow.ts
Labels: status: accepted

#9786 Add support for Tool.from_string()
  bokeh/models/tools.py
  bokeh/plotting/_tools.py
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/models/tools/actions/help_tool.ts
  bokehjs/src/lib/models/tools/actions/redo_tool.ts
  bokehjs/src/lib/models/tools/actions/reset_tool.ts
  bokehjs/src/lib/models/tools/actions/save_tool.ts
  bokehjs/src/lib/models/tools/actions/undo_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  tests/unit/bokeh/models/test_tools.py
  tests/unit/bokeh/test_model.py
Labels: status: accepted

#9785 Properly statically type SelectionGeometry.geometry
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/core/geometry.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
Labels: status: accepted

#9791 Allow subclasses of Serve subcommand to modify server_kwargs
  bokeh/command/subcommands/serve.py
Labels: reso: completed, status: accepted, tag: component: server, type: task

#9789 Fix for issue 9724, v2
  bokehjs/src/lib/models/ranges/data_range1d.ts
Labels: status: accepted

#9794 Add support for Bokeh.loader["@bokehjs/module/name"]
  bokehjs/src/compiler/prelude.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#9798 Fix syntax error in autoload js in notebook
  bokeh/core/_templates/autoload_js.js
  bokeh/embed/bundle.py
  bokeh/embed/standalone.py
  bokeh/resources.py
  tests/unit/bokeh/test_resources.py
Labels: status: accepted

#9801 Update deps and resolve audit warnings
  bokehjs/package-lock.json
  bokehjs/package.json
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#9802 Drop tslint in favor of @typescript/eslint
  bokehjs/eslint.json
  bokehjs/make/tasks/lint.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/sys.ts
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/hittest.ts
  bokehjs/src/lib/core/layout/grid.ts
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/external/ie.d.ts
  bokehjs/src/lib/external/jupyter.d.ts
  bokehjs/src/lib/external/underscore.template.d.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/src/lib/models/tools/toolbar_base.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/tslint.json
  bokehjs/tslint/rules/returnTypeRule.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#9804 Use `git ls-files` to collect test files
  setup.py
  tests/codebase/__init__.py
  tests/codebase/test_flake8.py
  tests/codebase/test_isort.py
Labels: status: accepted

#9806 Update dev_guide.rst: BEP 2 retired
  sphinx/source/docs/dev_guide.rst
Labels: status: accepted

#9809 Clean up type situation around buffer handling
  bokehjs/src/lib/core/util/serialization.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/protocol/message.ts
  bokehjs/src/lib/protocol/receiver.ts
  bokehjs/test/unit/core/util/serialization.ts
  bokehjs/test/unit/protocol/message.ts
  bokehjs/test/unit/protocol/receiver.ts
Labels: future, status: accepted

#9790 Fix hover hit on vertical and horizontal segments
  bokehjs/src/lib/models/glyphs/segment.ts
Labels: status: accepted

#9818 fixed typos and git pre-commit hook instructions
  sphinx/source/docs/dev_guide/setup.rst
Labels: status: accepted

#9815 Bokeh server django consumer session id get param
  bokeh/server/django/consumers.py
Labels: status: accepted

#9807 Encode google API key with Base64
  bokeh/core/properties.py
  bokeh/core/property/regex.py
  bokeh/core/property/string.py
  bokeh/models/map_plots.py
  bokeh/plotting/gmap.py
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  tests/unit/bokeh/core/property/test_string_properties.py
  tests/unit/bokeh/core/test_properties.py
Labels: status: accepted

#9819 Allow to send binary buffers by MessageSent
  bokeh/document/events.py
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/document/events.ts
Labels: reso: completed, status: accepted, type: feature

#9822 Update placeholder date in 2.0 release notes
  sphinx/source/docs/releases/2.0.0.rst
Labels: status: accepted

#9826 Docs: clarify that ``DataSource.selected`` is read-only
  bokeh/models/sources.py
Labels: status: accepted

#9825 Updated files to use new String module
  bokeh/core/property/color.py
  bokeh/core/property/visual.py
Labels: status: accepted

#9828 Update bokeh_embed/django README.md
  examples/howto/server_embed/django_embed/README.md
Labels: status: accepted

#9808 Clean separation between models' and properties' responsibilities
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/client/session.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/property_mixins.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/document/events.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/sources/column_data_source.ts
  bokehjs/test/framework.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/properties.ts
  bokehjs/test/unit/defaults.ts
  bokehjs/test/unit/document/document.ts
Labels: future, status: accepted

#9838 Skip painting empty indices when using webgl backend
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/test/baselines/Plot__with_webgl_backend__should_allow_empty_circle_glyphs
  bokehjs/test/baselines/Plot__with_webgl_backend__should_allow_empty_line_glyphs
  bokehjs/test/devtools/template.html
  bokehjs/test/integration/index.ts
Labels: status: accepted

#9829 Don't warn of different variants of the same type of tool
  bokeh/core/has_props.py
  bokeh/plotting/_tools.py
  setup.cfg
  tests/unit/bokeh/plotting/test__tools.py
Labels: status: accepted

#9835 Update current DatePicker value in UI
  bokehjs/src/lib/models/widgets/date_picker.ts
Labels: status: accepted

#9841 First iteration of updated release automation
  .github/workflows/bokeh-ci.yml
  examples/.isort.cfg
  examples/howto/server_embed/django_embed/django_embed/shape_viewer.py
  release/.isort.cfg
  release/__init__.py
  release/__main__.py
  release/build.py
  release/checks.py
  release/config.py
  release/credentials.py
  release/enums.py
  release/git.py
  release/publish.py
  release/stages.py
  release/system.py
  release/ui.py
  scripts/build_upload.py
  scripts/deploy.py
  tests/codebase/test_isort.py
Labels: status: accepted, tag: component: build, type: task

#9839 Fixed some minor docstring typos
  bokeh/plotting/figure.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9832 factor out error handling logic & re-use in FunctionHandler
  bokeh/application/handlers/code_runner.py
  bokeh/application/handlers/function.py
  bokeh/application/handlers/handler.py
  bokeh/server/django/routing.py
Labels: status: WIP, status: accepted

#9850 Fix minor typo in bokeh.transform reference docs
  bokeh/transform.py
Labels: status: accepted

#9852 Bryanv/correct js version full release
  release/config.py
Labels: reso: completed, status: accepted, tag: component: build, type: bug

#9846 Allow to use multiple versions of bokehjs on one page
  bokeh/io/export.py
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/tasks/test.ts
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/prelude.ts
  bokehjs/src/lib/embed/notebook.ts
  bokehjs/src/lib/version.d.ts
  bokehjs/src/lib/version.ts
  release/git.py
Labels: status: accepted
