Repository bokeh/bokeh, pull requests merged in 2020-01, with the labels that each got.

#9445 New attempt to update bokehjs from pop_colors_and_alpha to _pop_visuals
  bokehjs/src/lib/api/plotting.ts
Labels: status: WIP

#9556 fixes typos and makes minor text improvements
  .github/workflows/bokeh-ci.yml
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/layout.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/quickstart.rst
Labels: status: accepted

#9558 don't duplicate helpool
  bokehjs/src/lib/models/tools/toolbar_base.ts
Labels: status: accepted

#9559 warn for CDSView filters and connected glyphs
  bokeh/core/validation/errors.py
  bokeh/models/glyphs.py
  bokeh/models/renderers.py
  tests/unit/bokeh/models/test_renderers.py
Labels: status: accepted

#9422 Review for kwarg-only
  bokeh/io/notebook.py
  tests/unit/bokeh/io/test_notebook__io.py
Labels: status: accepted

#9561 Small misc cleanup
  bokeh/_testing/plugins/project.py
  bokeh/_version.py
  bokeh/models/__init__.py
  bokeh/models/widgets/panels.py
  bokehjs/src/lib/models/formatters/log_tick_formatter.ts
  examples/plotting/file/color_data_map.py
  tests/baselines/examples/plotting/file/color_data_map
Labels: status: accepted

#9566 Update developer documentation
  sphinx/source/docs/dev_guide.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
Labels: status: accepted

#9557 allow env vars to override bundle resources
  bokeh/embed/bundle.py
  tests/unit/bokeh/embed/test_bundle.py
Labels: status: accepted

#9565 fix circular import between glyphs and markers
  bokeh/models/glyph.py
  bokeh/models/glyphs.py
  bokeh/models/markers.py
Labels: status: accepted

#9553 Allow to route comms over bokeh's protocol
  bokeh/document/document.py
  bokeh/document/events.py
  bokeh/events.py
  bokeh/protocol/__init__.py
  bokeh/protocol/messages/event.py
  bokeh/protocol/messages/patch_doc.py
  bokeh/server/protocol_handler.py
  bokeh/server/session.py
  bokehjs/src/lib/client/session.ts
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/document/events.ts
  bokehjs/src/lib/models/layouts/html_box.ts
  bokehjs/test/unit/document/events.ts
  sphinx/source/docs/reference/protocol.rst
  tests/unit/bokeh/document/test_document.py
  tests/unit/bokeh/test_events.py
Labels: status: accepted, type: feature

#9564 Fix #9562
  bokehjs/src/compiler/compile.ts
  tests/unit/bokeh/util/test_compiler.py
Labels: status: accepted

#9573 test on python 3.8
  .github/workflows/bokeh-ci.yml
  bokeh/server/tornado.py
Labels: status: accepted

#9580 FIX #9579
  bokeh/util/dependencies.py
Labels: status: accepted

#9578 Allow to publish dev bokehjs packages
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/version.ts
  bokehjs/test/unit/document/document.ts
  scripts/deploy.py
  scripts/deps.py
Labels: status: accepted, tag: component: bokehjs, tag: component: build, type: task

#9509 Flatpickr
  bokeh/core/enums.py
  bokeh/core/json_encoder.py
  bokeh/core/property/bases.py
  bokeh/core/property/datetime.py
  bokeh/core/property/visual.py
  bokeh/models/widgets/inputs.py
  bokeh/models/widgets/sliders.py
  bokeh/plotting/helpers.py
  bokeh/util/serialization.py
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/less/widgets/flatpickr.less
  bokehjs/src/less/widgets/inputs.less
  bokehjs/src/less/widgets/pikaday.less
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/widgets/date_picker.ts
  bokehjs/src/lib/styles/widgets/flatpickr.ts
  bokehjs/src/lib/styles/widgets/pikaday.ts
  bokehjs/test/codebase/size.ts
  sphinx/source/docs/releases/2.0.0.rst
  tests/integration/widgets/test_datepicker.py
  tests/unit/bokeh/core/property/test_dataspec.py
  tests/unit/bokeh/core/property/test_datetime.py
  tests/unit/bokeh/core/property/test_validation__property.py
  tests/unit/bokeh/core/property/test_visual.py
  tests/unit/bokeh/core/test_enums.py
  tests/unit/bokeh/core/test_json_encoder.py
  tests/unit/bokeh/models/widgets/test_slider.py
  tests/unit/bokeh/util/test_serialization.py
Labels: status: accepted

#9582 added 3 open-source basemap tile providers: OSM, WIKIMEDIA, ESRI_IMAGERY
  bokeh/tile_providers.py
  tests/unit/bokeh/test_tile_providers.py
Labels: status: accepted

#9586 update out-of-date other parameters docs
  bokeh/core/property/bases.py
  bokeh/models/glyph.py
  bokeh/plotting/_decorators.py
  bokeh/plotting/_docstring.py
  bokeh/plotting/_graph.py
  bokeh/plotting/_legends.py
  bokeh/plotting/_plot.py
  bokeh/plotting/_renderer.py
  bokeh/plotting/_stack.py
  bokeh/plotting/_tools.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  bokeh/plotting/helpers.py
  bokeh/sphinxext/bokeh_plot.py
  tests/unit/bokeh/plotting/test__decorators.py
  tests/unit/bokeh/plotting/test__graph.py
  tests/unit/bokeh/plotting/test__lengends.py
  tests/unit/bokeh/plotting/test__plot.py
  tests/unit/bokeh/plotting/test__renderer.py
  tests/unit/bokeh/plotting/test__stack.py
  tests/unit/bokeh/plotting/test_helpers.py
Labels: status: accepted

#9588 Improve devtools test framework
  bokehjs/make/main.ts
  bokehjs/make/task.ts
  bokehjs/make/tasks/clean.ts
  bokehjs/make/tasks/test.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/prelude.ts
  bokehjs/test/devtools/baselines.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/devtools/index.js
  bokehjs/test/devtools/server.ts
  bokehjs/test/devtools/template.html
  bokehjs/test/external.d.ts
  bokehjs/test/framework.ts
  bokehjs/test/integration/index.html
  bokehjs/test/path.ts
  bokehjs/test/setup.ts
Labels: status: accepted

#9591 Detect chromium/chrome executable path
  bokehjs/make/tasks/test.ts
  bokehjs/make/toposort.d.ts
  bokehjs/package-lock.json
  bokehjs/package.json
Labels: status: accepted

#9598 add CI python version check
  .github/workflows/bokeh-ci.yml
Labels: reso: completed, status: accepted, tag: component: tests, type: task

#9601 No need to start headless chrome anymore
  .github/workflows/bokeh-ci.yml
Labels: status: accepted

#9606 Make Glyph._hit_* methods statically typed
  bokehjs/src/lib/core/logging.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/xy_glyph.ts
  bokehjs/test/unit/models/glyphs/glyph.ts
  bokehjs/test/unit/models/glyphs/index.ts
  bokehjs/test/unit/models/sources/column_data_source.ts
Labels: status: ready, tag: component: bokehjs, type: task

#9604 Return a promise with views from embed_item{s}()
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/util/callback.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/embed/index.ts
  bokehjs/src/lib/embed/server.ts
  bokehjs/src/lib/embed/standalone.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  examples/embed/json_item.py
  sphinx/source/docs/user_guide/embed.rst
Labels: status: ready

#9608 Ensure that all AbstractSlider properties are connected to signals
  bokehjs/src/lib/models/widgets/abstract_slider.ts
Labels: status: accepted, tag: component: bokehjs, tag: widgets, type: bug

#9590 Add ipywidgets_bokeh documentation
  setup.cfg
  sphinx/source/docs/user_guide.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/docs/user_guide/server.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#9618 Touch events on iOS 13.x workaround
  bokehjs/src/lib/core/ui_events.ts
Labels: status: accepted

#9617 add ability to define directory app packages
  .github/workflows/bokeh-ci.yml
  bokeh/_testing/util/filesystem.py
  bokeh/application/handlers/code.py
  bokeh/application/handlers/code_runner.py
  bokeh/application/handlers/directory.py
  bokeh/application/handlers/server_lifecycle.py
  examples/app/gapminder/__init__.py
  examples/app/gapminder/main.py
  examples/app/spectrogram/__init__.py
  examples/app/spectrogram/main.py
  examples/app/spectrogram/server_lifecycle.py
  examples/app/surface3d/__init__.py
  examples/app/surface3d/main.py
  sphinx/source/docs/user_guide/server.rst
  tests/unit/bokeh/application/handlers/test_code.py
  tests/unit/bokeh/application/handlers/test_code_runner.py
  tests/unit/bokeh/application/handlers/test_directory.py
  tests/unit/bokeh/application/handlers/test_document_lifecycle.py
  tests/unit/bokeh/application/handlers/test_handler.py
  tests/unit/bokeh/application/handlers/test_server_lifecycle.py
  tests/unit/bokeh/application/test_application.py
  tests/unit/bokeh/client/test_states.py
  tests/unit/bokeh/protocol/test_receiver.py
  tests/unit/bokeh/server/test_auth_provider.py
  tests/unit/bokeh/server/test_contexts.py
  tests/unit/bokeh/server/test_server__server.py
  tests/unit/bokeh/test_client_server.py
Labels: status: accepted
