Repository bokeh/bokeh, pull requests merged in 2020-07, with the labels that each got.

#10250 Fix CanvasView.save() to configure device pixel ratio correctly
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/framework.ts
  bokehjs/test/globals.d.ts
  bokehjs/test/unit/models/canvas/canvas.ts
  bokehjs/test/unit/models/canvas/index.ts
Labels: status: accepted

#10245 Issues script revamp
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  environment.yml
  scripts/issues.py
  scripts/milestone.py
Labels: status: accepted

#10244 Handle type="module" w/o entry point packages
  bokehjs/src/compiler/linker.ts
Labels: status: accepted, tag: component: bokehjs, tag: component: build, type: bug

#10243 ClientSession: Add different error messages (Close #3653)
  bokeh/client/connection.py
  bokeh/client/session.py
  bokeh/client/states.py
  tests/unit/bokeh/test_client_server.py
Labels: status: accepted

#10253 Revert "ClientSession: Add different error messages (Close #3653)"
  bokeh/client/connection.py
  bokeh/client/session.py
  bokeh/client/states.py
  tests/unit/bokeh/test_client_server.py
Labels: reso: completed, status: accepted, type: task

#10254 Descriptive error
  bokeh/client/connection.py
  bokeh/client/session.py
  bokeh/client/states.py
  tests/unit/bokeh/test_client_server.py
Labels: status: accepted

#10255 fix Select.options type
  bokeh/models/widgets/inputs.py
Labels: status: accepted

#10256 Deprecate Oval
  bokeh/models/glyphs.py
  examples/models/file/glyphs.py
  examples/plotting/file/glyphs.py
  sphinx/source/docs/releases/2.2.0.rst
  sphinx/source/docs/user_guide/examples/graph_customize.py
  sphinx/source/docs/user_guide/examples/graph_static_paths.py
  sphinx/source/docs/user_guide/examples/plotting_ovals.py
  sphinx/source/docs/user_guide/graph.rst
  sphinx/source/docs/user_guide/plotting.rst
Labels: status: accepted

#10257 Misc warnings cleanup
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_prop.py
  bokehjs/src/lib/core/util/pretty.ts
Labels: status: accepted, tag: component: docs, type: task

#10260 #8448 Fix typo "do no yet work" -> "do not yet work" in bokeh/sphinx/source/docs/user_guide/interaction/legends.rst
  sphinx/source/docs/user_guide/embed.rst
  sphinx/source/docs/user_guide/interaction/legends.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10270 Unclobber global.Bokeh to avoid initialization failure
  bokehjs/src/compiler/prelude.ts
Labels: status: accepted

#10237 Improve performance of hover tool and tooltips
  bokeh/models/annotations.py
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/annotations/tooltip.ts
  bokehjs/src/lib/models/callbacks/open_url.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/unit/core/util/eq.ts
  bokehjs/test/unit/core/util/templating.ts
  examples/models/file/popup.ts
  sphinx/source/docs/releases/2.2.0.rst
Labels: status: accepted

#10271 fix over-quoting by components
  bokeh/embed/elements.py
  tests/unit/bokeh/embed/test_standalone.py
Labels: status: accepted, tag: regression, type: bug

#10235 Redesign "materialization" of data specs
  bokeh/models/glyph.py
  bokeh/models/glyphs.py
  bokeh/models/markers.py
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/util/projections.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/models/glyphs/bezier.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/harea.ts
  bokehjs/src/lib/models/glyphs/hbar.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/src/lib/models/glyphs/quad.ts
  bokehjs/src/lib/models/glyphs/quadratic.ts
  bokehjs/src/lib/models/glyphs/segment.ts
  bokehjs/src/lib/models/glyphs/varea.ts
  bokehjs/src/lib/models/glyphs/vbar.ts
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/glyphs/xy_glyph.ts
  bokehjs/src/lib/models/graphs/layout_provider.ts
  bokehjs/src/lib/models/graphs/static_layout_provider.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/src/lib/models/textures/texture.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#9879__disallows_to_change_FactorRange_to_a_lower_dimension_with_a_different_number_of_factors.png
  bokehjs/test/baselines/macos/Bug__in_issue_#9879__disallows_to_change_FactorRange_to_a_lower_dimension_with_a_different_number_of_factors.png
  bokehjs/test/baselines/windows/Bug__in_issue_#9879__disallows_to_change_FactorRange_to_a_lower_dimension_with_a_different_number_of_factors.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/properties.ts
  bokehjs/test/unit/core/visuals.ts
  bokehjs/test/unit/models/glyphs/glyph.ts
  bokehjs/test/unit/models/glyphs/image_url.ts
  bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts
  bokehjs/test/unit/models/graphs/static_layout_provider.ts
  tests/unit/bokeh/io/test_export.py
  tests/unit/bokeh/models/_util_models.py
  tests/unit/bokeh/models/test_glyphs.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10272 Improve performance of selections
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/models/sources/cds_view.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: performance, type: task

#10275 Fix minor typos
  sphinx/source/docs/dev_guide/bokehjs.rst
  sphinx/source/docs/dev_guide/server.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/releases/0.12.14.rst
  sphinx/source/docs/releases/0.12.15.rst
  sphinx/source/docs/releases/0.12.4.rst
  sphinx/source/docs/releases/0.12.7.rst
  sphinx/source/docs/releases/0.13.0.rst
  sphinx/source/docs/releases/1.0.0.rst
  sphinx/source/docs/releases/1.2.0.rst
  sphinx/source/docs/releases/2.0.0.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10277 Docs change anaconda install source
  sphinx/source/docs/dev_guide/setup.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10229 Redesign the implementation of CDSView's filters
  bokeh/models/filters.py
  bokehjs/src/lib/core/hittest.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/data_structures.ts
  bokehjs/src/lib/core/util/spatial.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/models/filters/boolean_filter.ts
  bokehjs/src/lib/models/filters/customjs_filter.ts
  bokehjs/src/lib/models/filters/filter.ts
  bokehjs/src/lib/models/filters/group_filter.ts
  bokehjs/src/lib/models/filters/index_filter.ts
  bokehjs/src/lib/models/glyphs/box.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/src/lib/models/markers/marker.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/sources/cds_view.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/unit/core/selection_manager.ts
  bokehjs/test/unit/core/util/data_structures.ts
  bokehjs/test/unit/core/visuals.ts
  bokehjs/test/unit/models/filters/boolean_filter.ts
  bokehjs/test/unit/models/filters/customjs_filter.ts
  bokehjs/test/unit/models/filters/filter.ts
  bokehjs/test/unit/models/filters/group_filter.ts
  bokehjs/test/unit/models/filters/index.ts
  bokehjs/test/unit/models/filters/index_filter.ts
  bokehjs/test/unit/models/glyphs/image_url.ts
  bokehjs/test/unit/models/sources/cds_view.ts
  bokehjs/test/unit/models/transforms/step_interpolator.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10274 Use APIs to collect serialized SVG canvas contents
  bokeh/io/export.py
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/test/unit/models/canvas/canvas.ts
  tests/unit/bokeh/io/test_export.py
Labels: status: accepted

#10269 Fix typos in User Guide
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/bokehjs.rst
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/compat.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/embed.rst
  sphinx/source/docs/user_guide/examples/interaction_callbacks_for_hover.py
  sphinx/source/docs/user_guide/examples/interaction_div.py
  sphinx/source/docs/user_guide/examples/interaction_paragraph.py
  sphinx/source/docs/user_guide/examples/interaction_pretext.py
  sphinx/source/docs/user_guide/examples/js_events.py
  sphinx/source/docs/user_guide/examples/layout_sizing_mode_multiple.py
  sphinx/source/docs/user_guide/examples/plotting_patch_single.py
  sphinx/source/docs/user_guide/examples/styling_axis_properties.py
  sphinx/source/docs/user_guide/export.rst
  sphinx/source/docs/user_guide/extensions.rst
  sphinx/source/docs/user_guide/geo.rst
  sphinx/source/docs/user_guide/graph.rst
  sphinx/source/docs/user_guide/interaction.rst
  sphinx/source/docs/user_guide/interaction/callbacks.rst
  sphinx/source/docs/user_guide/interaction/legends.rst
  sphinx/source/docs/user_guide/interaction/linking.rst
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/docs/user_guide/layout.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/quickstart.rst
  sphinx/source/docs/user_guide/server.rst
  sphinx/source/docs/user_guide/styling.rst
  sphinx/source/docs/user_guide/tools.rst
  sphinx/source/docs/user_guide/webgl.rst
Labels: status: ready

#10285 Change all references of 'py.test' to 'pytest'
  .github/workflows/bokeh-ci.yml
  ci/run_downstream_tests.sh
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
  sphinx/source/docs/releases/1.0.0.rst
Labels: status: accepted

#10286 Change PR target branch recommendation
  .github/CONTRIBUTING.md
Labels: status: accepted

#10288 Avoid excessive rendering of toolbar panels
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
Labels: status: accepted

#10292 autoload only uses necessary bundles
  bokeh/embed/standalone.py
  tests/unit/bokeh/embed/test_standalone.py
Labels: status: accepted

#10291 Don't layout/render axes with invalid ranges
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/test/baselines/Bug__in_issue_#10195__makes_extra_axes_render_with_invalid_data_ranges
  bokehjs/test/baselines/linux/Bug__in_issue_#10195__makes_extra_axes_render_with_invalid_data_ranges.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10195__makes_extra_axes_render_with_invalid_data_ranges.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10195__makes_extra_axes_render_with_invalid_data_ranges.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/ranges/data_range1d.ts
Labels: status: accepted

#10240 Corrected EqHistColorMapper with inverted colormap edge transform
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/src/lib/models/mappers/eqhist_color_mapper.ts
  bokehjs/src/lib/models/mappers/scanning_color_mapper.ts
Labels: status: accepted, tag: component: bokehjs, type: task

#10303 fix bug with selection.get_view
  bokehjs/src/lib/models/glyphs/harea.ts
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/patch.ts
  bokehjs/src/lib/models/glyphs/varea.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/sources/cds_view.ts
Labels: status: accepted

#10307 Use ElementTree instead of deprecated cElementTree.
  bokeh/sampledata/us_counties.py
  bokeh/sampledata/us_states.py
Labels: status: accepted

#10304 Add note about nginx large_client_header_buffers to docs
  sphinx/source/docs/user_guide/server.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10298 Add bokeh logo palette; remove rogue double-quote from template
  bokeh/palettes.py
  bokeh/sphinxext/bokeh_palette_group.py
Labels: reso: completed, status: accepted, type: task

#10308 don't dupe version extension in bokehjs version
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  environment.yml
  release/config.py
Labels: status: accepted

#10312 Make SVG rendering context respect NaN/non-finite arguments
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#10313 update blog links
  bokeh/server/views/app_index.html
  sphinx/source/docs/releases/1.3.0.rst
Labels: status: accepted

#10311 Update `_color_help` url for css colors
  bokeh/core/property_mixins.py
Labels: status: accepted

#10314 rename renderer.scope -> .coordinates
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/band.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/label.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/annotations/slope.ts
  bokehjs/src/lib/models/annotations/span.ts
  bokehjs/src/lib/models/annotations/whisker.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/grids/grid.ts
  bokehjs/src/lib/models/renderers/data_renderer.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  examples/custom/latex_extension_base/latex_label/latex_label.ts
  examples/custom/latex_extension_full/latex_label/latex_label.ts
  examples/models/file/latex_extension.py
  sphinx/source/docs/user_guide/examples/extensions_example_latex.py
  tests/unit/bokeh/embed/latex_label/latex_label.ts
Labels: status: accepted

#10321 Don't use for-in loop in Interpolator.sort()
  bokehjs/src/lib/models/transforms/interpolator.ts
  bokehjs/src/lib/models/transforms/step_interpolator.ts
  bokehjs/test/unit/models/transforms/index.ts
  bokehjs/test/unit/models/transforms/interpolator.ts
Labels: status: accepted

#10338 Replace for-in loop with for-of and keys()/values()/entries()
  bokehjs/eslint.json
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/base.ts
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/logging.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/embed/index.ts
  bokehjs/src/lib/models/sources/ajax_data_source.ts
  bokehjs/src/lib/models/sources/column_data_source.ts
  bokehjs/src/lib/models/sources/geojson_data_source.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/tools/toolbar_base.ts
  bokehjs/src/lib/models/tools/toolbar_box.ts
  bokehjs/test/codebase/size.ts
  bokehjs/test/defaults/index.ts
  bokehjs/test/unit/core/properties.ts
  bokehjs/test/unit/document/document.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10337 Fix typos in Dev Guide
  sphinx/source/docs/dev_guide/bindings.rst
  sphinx/source/docs/dev_guide/bokehjs.rst
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/dev_guide/env_vars.rst
  sphinx/source/docs/dev_guide/models.rst
  sphinx/source/docs/dev_guide/server.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
Labels: status: accepted, tag: component: docs, type: task

#10342 Update bokehjs/package.json
  bokehjs/eslint.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/prelude.ts
  bokehjs/test/integration/regressions.ts
  tests/codebase/test_js_license_set.py
Labels: status: accepted, tag: component: bokehjs, tag: component: build, type: task

#10266 Add DocumentReady event
  bokeh/document/document.py
  bokeh/events.py
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/model.ts
  bokehjs/test/unit/document/document.ts
  tests/unit/bokeh/test_events.py
Labels: status: accepted

#10330 Initial webgl cleanup
  bokeh/embed/bundle.py
  bokeh/resources.py
  bokehjs/make/paths.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/src/lib/bokeh.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/glyphs/webgl/index.ts
  bokehjs/src/lib/models/glyphs/webgl/line.ts
  bokehjs/src/lib/models/glyphs/webgl/main.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/markers/defs.ts
  bokehjs/src/lib/models/markers/marker.ts
  bokehjs/test/codebase/size.ts
  bokehjs/test/devtools/template.html
  release/publish.py
  tests/unit/bokeh/embed/test_bundle.py
  tests/unit/bokeh/test_resources.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: webgl, type: task

#10346 Perform eslint checks on codebase tests
  tests/codebase/test_eslint.py
Labels: status: accepted, tag: component: tests, type: task

#10348 Upgrade to SlickGrid 2.4.27
  bokeh/_testing/util/selenium.py
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/codebase/size.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: widgets, type: task

#10352 Rev pillow version for sec advisory
  setup.py
Labels: dependencies, type: task

#10349 Add more info about BEPs
  sphinx/source/docs/dev_guide.rst
Labels: status: accepted

#10350 Fix bokehjs' legacy bundles
  bokehjs/package.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/polyfill.ts
  bokehjs/test/codebase/size.ts
Labels: plat: ie, status: ready, tag: component: bokehjs, type: task

#10185 Fill in the gaps in bokehjs' property definitions
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/layout/types.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/test/integration/glyphs/markers.ts
  bokehjs/test/unit/core/enums.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10357 Update out of date HoverTool docstring
  bokeh/models/tools.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10354 Code dupe experiements
  bokehjs/src/lib/models/annotations/band.ts
  bokehjs/src/lib/models/annotations/upper_lower.ts
  bokehjs/src/lib/models/annotations/whisker.ts
  bokehjs/src/lib/models/markers/marker.ts
  bokehjs/src/lib/models/markers/scatter.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/transforms/dodge.ts
  bokehjs/src/lib/models/transforms/jitter.ts
  bokehjs/src/lib/models/transforms/range_transform.ts
  bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts
  bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts
Labels: status: accepted, tag: component: bokehjs, type: task
