Repository bokeh/bokeh, pull requests merged in 2020-10, with the labels that each got.

#10554 Pin pytest 6.0*
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  environment.yml
Labels: reso: completed, status: accepted, tag: component: tests, type: task

#10552 Remove overwrite prompt for windows make.bat
  sphinx/make.bat
Labels: status: accepted

#10555 Backports for 2.2.2
  bokehjs/make/tasks/test.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/src/lib/models/sources/cds_view.ts
  bokehjs/test/baselines/Bug__in_issue_holoviews#4589__disallows_rendering_two_glyphs_sharing_a_source_and_view
  bokehjs/test/baselines/linux/Bug__in_issue_holoviews#4589__disallows_rendering_two_glyphs_sharing_a_source_and_view.png
  bokehjs/test/baselines/linux/Widgets__should_allow_DateRangeSlider.png
  bokehjs/test/baselines/linux/Widgets__should_allow_DateSlider.png
  bokehjs/test/baselines/linux/Widgets__should_allow_RangeSlider.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Slider.png
  bokehjs/test/baselines/macos/Bug__in_issue_holoviews#4589__disallows_rendering_two_glyphs_sharing_a_source_and_view.png
  bokehjs/test/baselines/macos/Widgets__should_allow_DateRangeSlider.png
  bokehjs/test/baselines/macos/Widgets__should_allow_DateSlider.png
  bokehjs/test/baselines/macos/Widgets__should_allow_RangeSlider.png
  bokehjs/test/baselines/macos/Widgets__should_allow_Slider.png
  bokehjs/test/baselines/windows/Bug__in_issue_holoviews#4589__disallows_rendering_two_glyphs_sharing_a_source_and_view.png
  bokehjs/test/baselines/windows/Widgets__should_allow_DateRangeSlider.png
  bokehjs/test/baselines/windows/Widgets__should_allow_DateSlider.png
  bokehjs/test/baselines/windows/Widgets__should_allow_RangeSlider.png
  bokehjs/test/baselines/windows/Widgets__should_allow_Slider.png
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/integration/regressions.ts
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/examples.log
  environment.yml
Labels: status: accepted, type: task

#10568 Port 2.2.2 changes
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  environment.yml
  sphinx/source/docs/releases/2.2.2.rst
  sphinx/versions.json
Labels: status: accepted, type: task

#10573 Also draw slope annotation with gradient=0 (#10541)
  bokehjs/src/lib/models/annotations/slope.ts
  bokehjs/test/baselines/Bug__in_issue_#10541__prevents_Slope_with_gradient=0
  bokehjs/test/baselines/linux/Bug__in_issue_#10541__prevents_Slope_with_gradient=0.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10541__prevents_Slope_with_gradient=0.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10541__prevents_Slope_with_gradient=0.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#10577 Allow to use Whisker annotation with categorical axes
  bokeh/core/property/dataspec.py
  bokeh/models/annotations.py
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/annotations/band.ts
  bokehjs/src/lib/models/annotations/upper_lower.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/markers/marker.ts
  bokehjs/test/baselines/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range
  bokehjs/test/baselines/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range
  bokehjs/test/baselines/linux/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range.png
  bokehjs/test/integration/regressions.ts
  tests/unit/bokeh/core/property/test_dataspec.py
  tests/unit/bokeh/document/test_document.py
  tests/unit/bokeh/models/test_annotations.py
  tests/unit/bokeh/test_objects.py
Labels: status: accepted

#10549 Annotation docs edits
  sphinx/source/docs/user_guide/annotations.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10578 Fix periodic callback not stopping in Django
  bokeh/server/django/consumers.py
Labels: status: WIP

#10556 Task #10539: Jupyter notebook edits
  sphinx/source/docs/user_guide/jupyter.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10587 Issue 10581 custom js hover example
  bokeh/models/tools.py
Labels: status: accepted

#10586 Backports for 2.2.3
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/test/baselines/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values
  bokehjs/test/baselines/linux/Bug__in_issue_#10219__disallows_correct_placement_of_Rect_glyph_with_partial_categorical_ranges.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10219__disallows_correct_placement_of_Rect_glyph_with_partial_categorical_ranges.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10219__disallows_correct_placement_of_Rect_glyph_with_partial_categorical_ranges.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values.png
  bokehjs/test/integration/regressions.ts
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  environment.yml
  sphinx/source/docs/releases/2.2.3.rst
  sphinx/versions.json
Labels: status: accepted

#10562 #10539 layout.rst
  sphinx/source/docs/user_guide/layout.rst
Labels: status: ready, tag: component: docs, type: task

#10563 10539 bokehjs.rst doc edit
  sphinx/source/docs/user_guide/bokehjs.rst
Labels: status: ready, tag: component: docs, type: task

#10590 Correctly compute subset data size
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/core/util/matrix.ts
  bokehjs/src/lib/core/util/ragged_array.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/test/baselines/Bug__in_issue_#10589__prevents_correctly_filtering_out_indices_when_using_MultiLine_glyph
  bokehjs/test/baselines/linux/Bug__in_issue_#10589__prevents_correctly_filtering_out_indices_when_using_MultiLine_glyph.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10589__prevents_correctly_filtering_out_indices_when_using_MultiLine_glyph.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10589__prevents_correctly_filtering_out_indices_when_using_MultiLine_glyph.png
  bokehjs/test/integration/layouts.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/utils.ts
  bokehjs/test/unit/core/util/bitset.ts
Labels: status: accepted

#10592 Clean up usage of `requestAnimationFrame`
  bokehjs/src/lib/core/signaling.ts
  bokehjs/src/lib/core/util/callback.ts
  bokehjs/src/lib/core/util/defer.ts
  bokehjs/src/lib/core/util/throttle.ts
  bokehjs/src/lib/embed/index.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10596 Minor typo in gallery docum. (repeated word)
  examples/app/README.md
  sphinx/source/docs/gallery.rst
Labels: status: accepted

#10598 Switch sphinx-panels from pip to conda
  environment.yml
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10600 Await for DOMContentLoaded in show()
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/dom.ts
Labels: status: accepted

#10606 Don't escape raw strings in replace_placeholders() by default
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/callbacks/open_url.ts
  bokehjs/test/unit/core/util/templating.ts
Labels: status: accepted

#10608 don't use conda-forge for release buidl env
  ci/environment-release-build.yml
Labels: status: ready

#10615 use proper JS version
  bokehjs/package-lock.json
  bokehjs/package.json
  release/config.py
Labels: status: accepted

#10561 Update displayed value when Select.options changes
  bokehjs/src/lib/models/widgets/selectbox.ts
  bokehjs/test/baselines/Bug__in_issue_#10407__displays_incorrect_value_in_Select_widget_when_options_change
  bokehjs/test/baselines/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_incorrect_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10407__displays_incorrect_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10407__displays_incorrect_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready

#10618 Implement views for arrow head models
  bokeh/models/annotations.py
  bokeh/models/arrow_heads.py
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/arrow_head.ts
  bokehjs/src/lib/models/annotations/whisker.ts
  sphinx/source/docs/releases/2.3.0.rst
  tests/unit/bokeh/models/test_annotations.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10625 align webgl.rst with style guide, task #10539
  sphinx/source/docs/user_guide/webgl.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task
