Repository bokeh/bokeh, pull requests merged in 2020-11, with the labels that each got.

#10610 #10539 geo.rst doc edit
  sphinx/source/docs/user_guide/geo.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10565 10539 export.rst doc edit
  sphinx/source/docs/user_guide/export.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10605 #10539 compat.rst
  sphinx/source/docs/user_guide/compat.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10543 Fix `super` call in "contexts.py"
  bokeh/server/contexts.py
Labels: status: accepted

#10627 remove out of date info
  sphinx/source/docs/dev_guide/server.rst
Labels: status: accepted

#10602 Redesign how serialization works in bokehjs
  bokeh/models/arrow_heads.py
  bokeh/models/glyphs.py
  bokeh/models/renderers.py
  bokeh/models/sources.py
  bokeh/models/tools.py
  bokeh/models/widgets/buttons.py
  bokeh/plotting/_tools.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  bokehjs/make/tasks/generate_defaults.py
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/base.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/serializer.ts
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/core/util/cloneable.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/src/lib/core/util/pretty.ts
  bokehjs/src/lib/core/util/ragged_array.ts
  bokehjs/src/lib/core/util/refs.ts
  bokehjs/src/lib/core/util/serialization.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/document/events.ts
  bokehjs/src/lib/models/annotations/upper_lower.ts
  bokehjs/src/lib/models/plots/gmap_plot.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/polyfill.ts
  bokehjs/test/defaults/index.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/properties.ts
  bokehjs/test/unit/core/serializer.ts
  bokehjs/test/unit/core/util/cloneable.ts
  bokehjs/test/unit/core/util/eq.ts
  bokehjs/test/unit/document/events.ts
  bokehjs/test/unit/models/ranges/data_range1d.ts
  bokehjs/test/unit/models/renderers/graph_renderer.ts
  examples/app/gapminder/theme.yaml
  examples/custom/parallel_plot/parallel_reset.py
  sphinx/source/docs/releases/2.3.0.rst
  tests/unit/bokeh/models/test_glyphs.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10626 Some core/properties cleanup
  bokeh/core/property/__init__.py
  bokeh/core/property/any.py
  bokeh/core/property/auto.py
  bokeh/core/property/bases.py
  bokeh/core/property/color.py
  bokeh/core/property/container.py
  bokeh/core/property/dataspec.py
  bokeh/core/property/datetime.py
  bokeh/core/property/descriptor_factory.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/either.py
  bokeh/core/property/enum.py
  bokeh/core/property/include.py
  bokeh/core/property/instance.py
  bokeh/core/property/json.py
  bokeh/core/property/numeric.py
  bokeh/core/property/override.py
  bokeh/core/property/pandas.py
  bokeh/core/property/primitive.py
  bokeh/core/property/regex.py
  bokeh/core/property/string.py
  bokeh/core/property/struct.py
  bokeh/core/property/validation.py
  bokeh/core/property/visual.py
  bokeh/core/property/wrappers.py
  bokeh/plotting/figure.py
Labels: status: accepted

#10597 #10539 categorical.rst doc edit
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/examples/categorical_bar_basic.py
  sphinx/source/docs/user_guide/examples/categorical_bar_colormapped.py
  sphinx/source/docs/user_guide/examples/categorical_bar_colors.py
  sphinx/source/docs/user_guide/examples/categorical_bar_dodged.py
  sphinx/source/docs/user_guide/examples/categorical_bar_intervals.py
  sphinx/source/docs/user_guide/examples/categorical_bar_nested.py
  sphinx/source/docs/user_guide/examples/categorical_bar_nested_colormapped.py
  sphinx/source/docs/user_guide/examples/categorical_bar_pandas_groupby_colormapped.py
  sphinx/source/docs/user_guide/examples/categorical_bar_pandas_groupby_nested.py
  sphinx/source/docs/user_guide/examples/categorical_bar_sorted.py
  sphinx/source/docs/user_guide/examples/categorical_bar_stacked.py
  sphinx/source/docs/user_guide/examples/categorical_bar_stacked_hover.py
  sphinx/source/docs/user_guide/examples/categorical_heatmap_periodic.py
  sphinx/source/docs/user_guide/examples/categorical_heatmap_unemployment.py
  sphinx/source/docs/user_guide/examples/categorical_offset.py
  sphinx/source/docs/user_guide/examples/categorical_scatter_jitter.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10617 Invalidate computed renderers when HoverToolView.plot_model.renderers changes
  bokeh/models/ranges.py
  bokeh/models/tools.py
  bokehjs/src/lib/core/signaling.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/models/ranges/data_range.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/util.ts
  bokehjs/test/unit/_util.ts
  bokehjs/test/unit/models/util.ts
  bokehjs/test/unit/regressions.ts
  sphinx/source/docs/releases/2.3.0.rst
Labels: status: accepted

#10630 Clean up bokeh.sphinxext
  bokeh/sphinxext/__init__.py
  bokeh/sphinxext/_templates/prop_detail.rst
  bokeh/sphinxext/bokeh_autodoc.py
  bokeh/sphinxext/bokeh_color.py
  bokeh/sphinxext/bokeh_directive.py
  bokeh/sphinxext/bokeh_enum.py
  bokeh/sphinxext/bokeh_gallery.py
  bokeh/sphinxext/bokeh_github.py
  bokeh/sphinxext/bokeh_jinja.py
  bokeh/sphinxext/bokeh_model.py
  bokeh/sphinxext/bokeh_options.py
  bokeh/sphinxext/bokeh_palette.py
  bokeh/sphinxext/bokeh_palette_group.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_prop.py
  bokeh/sphinxext/bokeh_releases.py
  bokeh/sphinxext/bokeh_settings.py
  bokeh/sphinxext/bokeh_sitemap.py
  bokeh/sphinxext/bokehjs_content.py
  bokeh/sphinxext/collapsible_code_block.py
  bokeh/sphinxext/example_handler.py
  bokeh/sphinxext/sample.py
  bokeh/sphinxext/templates.py
  bokeh/sphinxext/theme.py
  bokeh/sphinxext/util.py
  tests/codebase/test_black.py
Labels: status: accepted

#10616 Add OpenGraph metadata to docs
  ci/environment-release-build.yml
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  environment.yml
  sphinx/source/conf.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10537 Factor out code from PlotView
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/annotations/slope.ts
  bokehjs/src/lib/models/annotations/tooltip.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/plots/state_manager.ts
  bokehjs/src/lib/models/tools/actions/redo_tool.ts
  bokehjs/src/lib/models/tools/actions/undo_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/unit/core/ui_events.ts
  bokehjs/test/unit/models/plots/plot.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10633 Fix new sphinx issue with bokeh.palettes
  bokeh/palettes.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10634 Update bokehjs' dependencies
  bokehjs/make/tasks/test.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/linker.ts
  bokehjs/test/codebase/index.ts
  bokehjs/test/codebase/size.ts
  bokehjs/test/codebase/tsconfig.json
  sphinx/source/docs/dev_guide/bokehjs.rst
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#10579 #10539 graph.rst doc edit
  sphinx/source/docs/user_guide/examples/graph_customize.py
  sphinx/source/docs/user_guide/graph.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10493 Accurate color bar ticking with eqhist mapping
  bokeh/models/annotations.py
  bokeh/models/mappers.py
  bokeh/models/tickers.py
  bokehjs/make/tasks/test.ts
  bokehjs/src/lib/core/util/text.ts
  bokehjs/src/lib/es.d.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/mappers/eqhist_color_mapper.ts
  bokehjs/src/lib/models/scales/linear_interpolation_scale.ts
  bokehjs/src/lib/models/tickers/binned_ticker.ts
  bokehjs/src/lib/models/tickers/index.ts
  bokehjs/test/baselines/Color_mapping__with_histogram_equalization__should_support_gaussian_distributed_data
  bokehjs/test/baselines/Color_mapping__with_histogram_equalization__should_support_pipeline_data
  bokehjs/test/baselines/Color_mapping__with_histogram_equalization__should_support_sparse_cells_data
  bokehjs/test/baselines/Color_mapping__with_histogram_equalization__should_support_sparse_squares_data
  bokehjs/test/baselines/Color_mapping__with_histogram_equalization__should_support_uniformly_distributed_data
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_gaussian_distributed_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_pipeline_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_sparse_cells_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_sparse_squares_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_uniformly_distributed_data.png
  bokehjs/test/baselines/macos/Color_mapping__with_histogram_equalization__should_support_gaussian_distributed_data.png
  bokehjs/test/baselines/macos/Color_mapping__with_histogram_equalization__should_support_pipeline_data.png
  bokehjs/test/baselines/macos/Color_mapping__with_histogram_equalization__should_support_sparse_cells_data.png
  bokehjs/test/baselines/macos/Color_mapping__with_histogram_equalization__should_support_sparse_squares_data.png
  bokehjs/test/baselines/macos/Color_mapping__with_histogram_equalization__should_support_uniformly_distributed_data.png
  bokehjs/test/baselines/windows/Color_mapping__with_histogram_equalization__should_support_gaussian_distributed_data.png
  bokehjs/test/baselines/windows/Color_mapping__with_histogram_equalization__should_support_pipeline_data.png
  bokehjs/test/baselines/windows/Color_mapping__with_histogram_equalization__should_support_sparse_cells_data.png
  bokehjs/test/baselines/windows/Color_mapping__with_histogram_equalization__should_support_sparse_squares_data.png
  bokehjs/test/baselines/windows/Color_mapping__with_histogram_equalization__should_support_uniformly_distributed_data.png
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/devtools/test.html
  bokehjs/test/integration/color_mapping.ts
  bokehjs/test/unit/models/annotations/color_bar.ts
Labels: reso: completed, status: accepted, tag: API: models, type: feature

#10635 Fix custom/latex_extension_* examples
  examples/custom/latex_extension_base/latex_extension_base.py
  examples/custom/latex_extension_base/latex_label/latex_label.ts
  examples/custom/latex_extension_full/latex_extension_full.py
  examples/custom/latex_extension_full/latex_label/latex_label.ts
Labels: status: accepted

#10638 Add EdgesOnly selection policy
  bokeh/models/graphs.py
  bokehjs/src/lib/models/graphs/graph_hit_test_policy.ts
  bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts
Labels: status: accepted

#10560 Modifying a HoverTool tooltip leads to errors if the new tooltip list is bigger.
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/unit/models/tools/inspectors/hover_tool.ts
Labels: status: accepted

#10510 Adds a button_type similar to default but with no border to support menu-buttons, link-buttons, icon-buttons etc.
  bokeh/core/enums.py
  bokehjs/src/less/buttons.less
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/styles/buttons.ts
  bokehjs/test/baselines/Widgets__should_allow_Button
  bokehjs/test/baselines/linux/Widgets__should_allow_Button.png
  bokehjs/test/baselines/macos/Widgets__should_allow_Button.png
  bokehjs/test/baselines/windows/Widgets__should_allow_Button.png
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/core/enums.ts
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#10640 Implement grad and turn CSS-based angle units
  bokeh/core/enums.py
  bokeh/core/property/dataspec.py
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/util/math.ts
  bokehjs/src/lib/models/annotations/label.ts
  bokehjs/test/baselines/Glyph_models__should_support_rotation_with_all_angle_units
  bokehjs/test/baselines/linux/Glyph_models__should_support_rotation_with_all_angle_units.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_rotation_with_all_angle_units.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_rotation_with_all_angle_units.png
  bokehjs/test/integration/glyphs/glyphs.ts
  bokehjs/test/unit/core/enums.ts
  tests/unit/bokeh/core/test_enums.py
Labels: reso: completed, status: accepted, tag: API: models, type: feature

#10645 Allow serialization of circular objects
  bokehjs/src/lib/core/serializer.ts
  bokehjs/test/unit/core/serializer.ts
Labels: status: accepted

#10646 Use the correct variant of hasOwnProperty check
  bokeh/core/_templates/autoload_nb_js.js
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/object.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/models/sources/geojson_data_source.ts
  tests/unit/bokeh/core/test_templates.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10650 Upgrade to TypeScript 4.1 RC
  .lgtm.yml
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/lib/core/property_mixins.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10653 Split visuals into scalar and vector
  bokeh/models/glyphs.py
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/property_mixins.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/arrow_head.ts
  bokehjs/src/lib/models/annotations/band.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/src/lib/models/annotations/slope.ts
  bokehjs/src/lib/models/annotations/span.ts
  bokehjs/src/lib/models/annotations/text_annotation.ts
  bokehjs/src/lib/models/annotations/title.ts
  bokehjs/src/lib/models/annotations/whisker.ts
  bokehjs/src/lib/models/glyphs/annular_wedge.ts
  bokehjs/src/lib/models/glyphs/annulus.ts
  bokehjs/src/lib/models/glyphs/arc.ts
  bokehjs/src/lib/models/glyphs/area.ts
  bokehjs/src/lib/models/glyphs/bezier.ts
  bokehjs/src/lib/models/glyphs/box.ts
  bokehjs/src/lib/models/glyphs/center_rotatable.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/harea.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/patch.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/src/lib/models/glyphs/quadratic.ts
  bokehjs/src/lib/models/glyphs/ray.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/src/lib/models/glyphs/segment.ts
  bokehjs/src/lib/models/glyphs/step.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/src/lib/models/glyphs/utils.ts
  bokehjs/src/lib/models/glyphs/varea.ts
  bokehjs/src/lib/models/glyphs/wedge.ts
  bokehjs/src/lib/models/grids/grid.ts
  bokehjs/src/lib/models/markers/defs.ts
  bokehjs/src/lib/models/markers/marker.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/visuals.ts
  examples/custom/gears/gear.ts
  sphinx/source/docs/releases/2.3.0.rst
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10655 Unify initialization of visuals and data
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/models/annotations/annotation.ts
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/arrow_head.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/annotations/label.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/annotations/title.ts
  bokehjs/src/lib/models/annotations/upper_lower.ts
  bokehjs/src/lib/models/glyphs/center_rotatable.ts
  bokehjs/src/lib/models/glyphs/ellipse_oval.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/src/lib/models/glyphs/segment.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/visuals.ts
  bokehjs/test/unit/models/annotations/annotation.ts
Labels: status: ready, tag: component: bokehjs, type: task

#10672 Add docstring to `on_event`
  bokeh/util/callback_manager.py
Labels: status: accepted

#10674 Require npm@7 and nodejs 14.*
  .github/workflows/bokehjs-ci.yml
  bokehjs/package-lock.json
  bokehjs/package.json
  ci/environment-build.yml
  ci/environment-release-build.yml
  ci/environment-release-deploy.yml
  ci/environment-test-3.6.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/install_node_modules.sh
  docker-tools/alpine/Dockerfile-from-source
  examples/custom/latex_extension_full/latex_label/package-lock.json
  sphinx/source/docs/dev_guide/bokehjs.rst
  sphinx/source/docs/dev_guide/setup.rst
  tests/unit/bokeh/embed/ext_package_no_main/package-lock.json
  tests/unit/bokeh/embed/latex_label/package-lock.json
Labels: status: accepted

#10681 Add an actual webgl backend test
  bokehjs/test/baselines/Marker_glyph__should_support_glyph_methods_and_rotation
  bokehjs/test/baselines/linux/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/macos/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/windows/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/integration/glyphs/markers.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: webgl, type: task

#10687 Fix scientific format for 0
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
Labels: status: ready

#10699 Migrate CI {goanpeca->conda-incubator}/setup-miniconda
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
Labels: status: accepted, tag: component: build, type: task

#10701 Fix backwards compatibility alias for InspectTool
  bokeh/models/tools.py
Labels: reso: completed, status: accepted, tag: API: models, tag: regression, type: bug

#10700 Follow up of #10687
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
Labels: status: accepted

#10660 Update glossary
  sphinx/source/docs/user_guide/concepts.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10679 #10539 embed.rst
  sphinx/source/docs/user_guide/embed.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10704 Adjust z-index of MultiChoice widget's dropdown menu
  bokehjs/src/less/widgets/choices.less
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/baselines/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu
  bokehjs/test/baselines/linux/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#10703 Unify TextInput and TextAreaInput widgets
  bokeh/models/widgets/inputs.py
  bokehjs/src/lib/models/widgets/text_input.ts
  bokehjs/src/lib/models/widgets/text_like_input.ts
  bokehjs/src/lib/models/widgets/textarea_input.ts
  bokehjs/test/baselines/Widgets__should_allow_TextAreaInput
  bokehjs/test/baselines/linux/Widgets__should_allow_TextAreaInput.png
  bokehjs/test/baselines/macos/Widgets__should_allow_TextAreaInput.png
  bokehjs/test/baselines/windows/Widgets__should_allow_TextAreaInput.png
  bokehjs/test/integration/widgets.ts
  examples/models/file/widgets.py
Labels: status: accepted

#10708 Upgrade to TypeScript 4.1 and upgrade other dependencies
  bokehjs/package-lock.json
  bokehjs/package.json
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#10696 Update data.rst
  sphinx/source/docs/user_guide/data.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10711 Use bokehjs' test framework to start chrome in examples' tests
  .github/workflows/bokeh-ci.yml
  bokehjs/make/tasks/test.ts
Labels: status: accepted

#10713 Fix bokehjs' SVG export when ToolbarBox is present
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/core/visuals.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/tools/toolbar_base.ts
  bokehjs/test/integration/layouts.ts
  bokehjs/test/unit/assertions.ts
Labels: status: accepted

#10705 Allow to configure TapTool with a gesture (tap or doubletap)
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/test/unit/models/tools/gestures/tap_tool.ts
Labels: status: accepted

#10707 Detect dependency cycles in build and fix existing cycles
  bokehjs/make/tasks/compiler.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/tasks/test.ts
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/graph.ts
  bokehjs/src/compiler/linker.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/selection_manager.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/src/lib/core/util/buffer.ts
  bokehjs/src/lib/core/util/platform.ts
  bokehjs/src/lib/core/util/serialization.ts
  bokehjs/src/lib/models/glyphs/annulus.ts
  bokehjs/src/lib/models/graphs/graph_hit_test_policy.ts
  bokehjs/src/lib/models/mappers/color_mapper.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/src/lib/models/selections/interaction_policy.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/widgets/tables/cell_editors.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/src/lib/models/widgets/tables/definitions.ts
  bokehjs/src/lib/models/widgets/tables/table_column.ts
  bokehjs/test/unit/core/serializer.ts
  bokehjs/test/unit/core/util/buffer.ts
  bokehjs/test/unit/core/util/serialization.ts
  bokehjs/test/unit/models/widgets/tables/data_table.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#10710 Add information about themes
  sphinx/source/_images/themes_caliber.png
  sphinx/source/_images/themes_contrast.png
  sphinx/source/_images/themes_dark_minimal.png
  sphinx/source/_images/themes_light_minimal.png
  sphinx/source/_images/themes_night_sky.png
  sphinx/source/bokeh/static/custom.css
  sphinx/source/docs/user_guide/styling.rst
Labels: status: accepted

#10722 exit build steps on error
  ci/build_bokehjs.sh
  ci/build_conda_pacakge.sh
  ci/environment-build.yml
  ci/environment-release-build.yml
  ci/environment-test-3.6.yml
Labels: status: accepted

#10720 Add support for ESM bundles
  bokehjs/examples/anscombe/anscombe.html
  bokehjs/examples/anscombe/anscombe.ts
  bokehjs/examples/bokehjs.d.ts
  bokehjs/examples/burtin/burtin.html
  bokehjs/examples/burtin/burtin.ts
  bokehjs/examples/categorical/categorical.html
  bokehjs/examples/categorical/categorical.ts
  bokehjs/examples/charts/charts.html
  bokehjs/examples/charts/charts.ts
  bokehjs/examples/donut/donut.html
  bokehjs/examples/donut/donut.ts
  bokehjs/examples/hierarchical/hierarchical.html
  bokehjs/examples/hierarchical/hierarchical.ts
  bokehjs/examples/hover/hover.html
  bokehjs/examples/hover/hover.ts
  bokehjs/examples/legends/legends.html
  bokehjs/examples/legends/legends.ts
  bokehjs/examples/linked/linked.html
  bokehjs/examples/linked/linked.ts
  bokehjs/examples/stocks/stocks.html
  bokehjs/examples/stocks/stocks.ts
  bokehjs/examples/tap/tap.html
  bokehjs/examples/tap/tap.ts
  bokehjs/examples/tsconfig.json
  bokehjs/make/paths.ts
  bokehjs/make/tasks/compiler.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/tasks/test.ts
  bokehjs/make/tsconfig.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/prelude.ts
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/compiler/tsconfig.json
  bokehjs/src/lib/embed/notebook.ts
  bokehjs/src/lib/external/colab.d.ts
  bokehjs/src/lib/external/jupyter.d.ts
  bokehjs/src/lib/tsconfig.json
  bokehjs/test/codebase/size.ts
  bokehjs/test/codebase/tsconfig.json
  bokehjs/test/devtools/server.ts
  bokehjs/test/devtools/tsconfig.json
Labels: status: accepted

#10726 Correctly apply transformation matrix in SVG.drawImage()
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/Bug__in_issue_#10725__renders_image_glyphs_in_wrong_orientation_using_SVG_backend
  bokehjs/test/baselines/linux/Bug__in_issue_#10725__renders_image_glyphs_in_wrong_orientation_using_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10725__renders_image_glyphs_in_wrong_orientation_using_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10725__renders_image_glyphs_in_wrong_orientation_using_SVG_backend.png
  bokehjs/test/integration/regressions.ts
  tests/unit/bokeh/io/test_export.py
Labels: status: accepted

#10724 Fix rendering of webgl line containing NaN (#8489)
  bokehjs/src/lib/models/glyphs/webgl/line.ts
  bokehjs/test/baselines/linux/webgl__should_support_nan_in_line.png
  bokehjs/test/baselines/macos/webgl__should_support_nan_in_line.png
  bokehjs/test/baselines/webgl__should_support_nan_in_line
  bokehjs/test/baselines/windows/webgl__should_support_nan_in_line.png
  bokehjs/test/integration/glyphs/webgl.ts
Labels: status: accepted

#10718 Add support for Tool.description property
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/actions/custom_action.ts
  bokehjs/src/lib/models/tools/actions/help_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/src/lib/models/tools/button_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/line_edit_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts
  bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts
  bokehjs/test/unit/models/tools/edit/box_edit_tool.ts
  bokehjs/test/unit/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/point_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/poly_edit_tool.ts
  bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
  sphinx/source/docs/releases/2.3.0.rst
Labels: status: accepted

#10727 Add support for user supplied licenses to extensions
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/prelude.ts
  examples/custom/latex_extension_full/latex_label/LICENSE.txt
  examples/custom/latex_extension_full/latex_label/bokeh.ext.json
Labels: status: accepted

#10730 Add support for publishing npm packages
  release/build.py
  release/deploy.py
  release/remote.py
  release/stages.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#10736 Fix `renderers` properties' types across bokeh
  bokeh/models/ranges.py
  bokeh/models/tools.py
Labels: status: accepted

#10737 Add an integration test for PR #8256
  bokehjs/src/lib/api/plotting.ts
  bokehjs/test/baselines/Bug__in_issue_#589__disallows_updating_legend_when_glyphs_change
  bokehjs/test/baselines/linux/Bug__in_issue_#589__disallows_updating_legend_when_glyphs_change.png
  bokehjs/test/baselines/macos/Bug__in_issue_#589__disallows_updating_legend_when_glyphs_change.png
  bokehjs/test/baselines/windows/Bug__in_issue_#589__disallows_updating_legend_when_glyphs_change.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#10739 Fix overlapping arrows' clipping issues
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/arrow_head.ts
  bokehjs/test/baselines/Bug__in_issue_#10136__prevents_correct_rendering_of_overlapping_arrows
  bokehjs/test/baselines/linux/Bug__in_issue_#10136__prevents_correct_rendering_of_overlapping_arrows.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10136__prevents_correct_rendering_of_overlapping_arrows.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10136__prevents_correct_rendering_of_overlapping_arrows.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted
