Repository bokeh/bokeh, pull requests merged in 2021-01, with the labels that each got.

#10734 Add support for Less/CSS to extensions
  bokehjs/make/tasks/styles.ts
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/styles.ts
  bokehjs/src/compiler/tsconfig.ext.json
  bokehjs/src/lib/tsconfig.json
  examples/custom/latex_extension_base/latex_extension_base.py
  examples/custom/latex_extension_base/latex_label/latex_label.ts
  examples/custom/latex_extension_base/latex_label/styles/css.d.ts
  examples/custom/latex_extension_base/latex_label/styles/latex_label.less
  examples/custom/latex_extension_full/latex_extension_full.py
  examples/custom/latex_extension_full/latex_label/latex_label.ts
  examples/custom/latex_extension_full/latex_label/styles/css.d.ts
  examples/custom/latex_extension_full/latex_label/styles/latex_label.less
  examples/custom/latex_extension_full/latex_label/tsconfig.json
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: feature

#10810 Repaint resized layoutable renderers
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/Bug__in_issue_#10809__prevents_repaint_of_resized_layoutable_renderers
  bokehjs/test/baselines/linux/Bug__in_issue_#10809__prevents_repaint_of_resized_layoutable_renderers.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10809__prevents_repaint_of_resized_layoutable_renderers.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10809__prevents_repaint_of_resized_layoutable_renderers.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#10743 Decouple Color Swatch
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/unit/models/tools/inspectors/hover_tool.ts
  sphinx/source/docs/user_guide/tools.rst
Labels: status: accepted

#10815 Replace CSS based font metrics with canvas based
  bokehjs/src/lib/core/layout/side_panel.ts
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/core/util/platform.ts
  bokehjs/src/lib/core/util/text.ts
  bokehjs/src/lib/models/annotations/label.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/annotations/text_annotation.ts
  bokehjs/src/lib/models/annotations/title.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/test/baselines/Bug__in_issue_#10042__disallows_to_set_subgroup_label_orientation_=_0
  bokehjs/test/baselines/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range
  bokehjs/test/baselines/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range
  bokehjs/test/baselines/linux/Bug__in_issue_#10042__disallows_to_set_subgroup_label_orientation_=_0.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10042__disallows_to_set_subgroup_label_orientation_=_0.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10042__disallows_to_set_subgroup_label_orientation_=_0.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_x-range.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10575__disallows_rendering_Whisker_annotation_with_a_categorical_y-range.png
  bokehjs/test/unit/core/layout/side_panel.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#10791 10539 server.rst
  sphinx/source/docs/user_guide/server.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10797 Check docs with CI (individual pull requests)
  .github/styles/Bokeh/AmericanEnglish.yml
  .github/styles/Bokeh/CountCommas.yml
  .github/styles/Bokeh/Headings.yml
  .github/styles/Bokeh/InclusiveLanguage.yml
  .github/styles/Bokeh/Units.yml
  .github/styles/Bokeh/WordList.yml
  .github/styles/vocab.txt
  .github/workflows/bokeh-ci.yml
  .vale.ini
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/user_guide/styling.rst
Labels: status: accepted

#10323 Add support for smooth curve glyphs
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/util/interpolation.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/spline.ts
  bokehjs/test/baselines/Spline_glyph__should_allow_to_paint_a_closed_spline
  bokehjs/test/baselines/Spline_glyph__should_allow_to_paint_a_spline_where_start_==_end
  bokehjs/test/baselines/Spline_glyph__should_allow_to_paint_an_open_spline
  bokehjs/test/baselines/linux/Spline_glyph__should_allow_to_paint_a_closed_spline.png
  bokehjs/test/baselines/linux/Spline_glyph__should_allow_to_paint_a_spline_where_start_==_end.png
  bokehjs/test/baselines/linux/Spline_glyph__should_allow_to_paint_an_open_spline.png
  bokehjs/test/baselines/macos/Spline_glyph__should_allow_to_paint_a_closed_spline.png
  bokehjs/test/baselines/macos/Spline_glyph__should_allow_to_paint_a_spline_where_start_==_end.png
  bokehjs/test/baselines/macos/Spline_glyph__should_allow_to_paint_an_open_spline.png
  bokehjs/test/baselines/windows/Spline_glyph__should_allow_to_paint_a_closed_spline.png
  bokehjs/test/baselines/windows/Spline_glyph__should_allow_to_paint_a_spline_where_start_==_end.png
  bokehjs/test/baselines/windows/Spline_glyph__should_allow_to_paint_an_open_spline.png
  bokehjs/test/defaults/index.ts
  bokehjs/test/integration/glyphs/spline.ts
  bokehjs/test/unit/core/util/interpolation.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: feature

#10823 Remove Vale
  .github/styles/Bokeh/AmericanEnglish.yml
  .github/styles/Bokeh/CountCommas.yml
  .github/styles/Bokeh/Headings.yml
  .github/styles/Bokeh/InclusiveLanguage.yml
  .github/styles/Bokeh/Units.yml
  .github/styles/Bokeh/WordList.yml
  .github/styles/vocab.txt
  .github/workflows/bokeh-ci.yml
  .vale.ini
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/user_guide/styling.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10820 Fix example of LabelSet in user manual
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/examples/plotting_label.py
Labels: status: accepted

#10825 Implement hatch patterns for all area glyphs
  bokeh/models/glyphs.py
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/models/glyphs/annular_wedge.ts
  bokehjs/src/lib/models/glyphs/annulus.ts
  bokehjs/src/lib/models/glyphs/center_rotatable.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/defs.ts
  bokehjs/src/lib/models/glyphs/ellipse.ts
  bokehjs/src/lib/models/glyphs/ellipse_oval.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/marker.ts
  bokehjs/src/lib/models/glyphs/oval.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/src/lib/models/glyphs/scatter.ts
  bokehjs/src/lib/models/glyphs/utils.ts
  bokehjs/src/lib/models/glyphs/wedge.ts
  bokehjs/test/baselines/Glyph_models__should_support_AnnularWedge
  bokehjs/test/baselines/Glyph_models__should_support_Annulus
  bokehjs/test/baselines/Glyph_models__should_support_Circle
  bokehjs/test/baselines/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns
  bokehjs/test/baselines/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns
  bokehjs/test/baselines/linux/Bug__in_issue_#10219__disallows_correct_placement_of_Rect_glyph_with_partial_categorical_ranges.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10454__disallows_using_categorical_coordinates_with_Arrow_annotation.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10454__disallows_using_categorical_coordinates_with_LabelSet_annotation.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_AnnularWedge.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Annulus.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Circle.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Rect.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_fill_with_hatch_patterns.png
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10219__disallows_correct_placement_of_Rect_glyph_with_partial_categorical_ranges.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10454__disallows_using_categorical_coordinates_with_Arrow_annotation.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10454__disallows_using_categorical_coordinates_with_LabelSet_annotation.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_AnnularWedge.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_Annulus.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_Circle.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_Rect.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_fill_with_hatch_patterns.png
  bokehjs/test/baselines/macos/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/macos/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10219__disallows_correct_placement_of_Rect_glyph_with_partial_categorical_ranges.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10454__disallows_using_categorical_coordinates_with_Arrow_annotation.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10454__disallows_using_categorical_coordinates_with_LabelSet_annotation.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10488__disallows_correct_placement_of_Rect_glyph_with_datetime_values.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_AnnularWedge.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_Annulus.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_Circle.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_Rect.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_fill_with_hatch_patterns.png
  bokehjs/test/baselines/windows/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/windows/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns.png
  bokehjs/test/integration/glyphs/glyphs.ts
  bokehjs/test/integration/glyphs/hex_tile.ts
  tests/codebase/test_js_license_set.py
  tests/unit/bokeh/models/test_glyphs.py
Labels: status: accepted

#10827 Updated DataTable fit_columns docstring
  bokeh/models/widgets/tables.py
Labels: status: accepted

#10829 Fix minor typos and inconsistencies
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/compat.rst
  sphinx/source/docs/user_guide/extensions.rst
  sphinx/source/docs/user_guide/extensions_gallery/latex.rst
  sphinx/source/docs/user_guide/extensions_gallery/ticking.rst
  sphinx/source/docs/user_guide/extensions_gallery/tool.rst
  sphinx/source/docs/user_guide/extensions_gallery/widget.rst
  sphinx/source/docs/user_guide/extensions_gallery/wrapping.rst
  sphinx/source/docs/user_guide/interaction.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/styling.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10832 Update concepts.rst and cli.rst
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/user_guide/cli.rst
  sphinx/source/docs/user_guide/concepts.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10830 User Guide: add links to widget class references
  sphinx/source/docs/user_guide/interaction/widgets.rst
Labels: status: accepted

#10833 Add hatch pattern support to box and poly annotations
  bokeh/model.py
  bokeh/models/annotations.py
  bokeh/models/tools.py
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/test/baselines/BoxAnnotation_annotation__should_support_positioning_in_data_space
  bokehjs/test/baselines/PolyAnnotation_annotation__should_support_positioning_in_data_space
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/linux/PolyAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/macos/BoxAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/macos/PolyAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/windows/BoxAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/windows/PolyAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/integration/annotations/box_annotation.ts
  bokehjs/test/integration/annotations/poly_annotation.ts
  bokehjs/test/unit/core/util/bbox.ts
  tests/unit/bokeh/models/_util_models.py
  tests/unit/bokeh/models/test_annotations.py
  tests/unit/bokeh/test_objects.py
Labels: status: accepted

#10835 Infer viewport size in bokehjs integration tests
  bokehjs/test/baselines/linux/Rows_of_widgets__should_allow_different_content_and_fixed_height.png
  bokehjs/test/baselines/macos/Rows_of_widgets__should_allow_different_content_and_fixed_height.png
  bokehjs/test/baselines/windows/Rows_of_widgets__should_allow_different_content_and_fixed_height.png
  bokehjs/test/framework.ts
  bokehjs/test/integration/annotations/arrows.ts
  bokehjs/test/integration/annotations/box_annotation.ts
  bokehjs/test/integration/annotations/legend.ts
  bokehjs/test/integration/annotations/poly_annotation.ts
  bokehjs/test/integration/color_mapping.ts
  bokehjs/test/integration/glyphs/glyphs.ts
  bokehjs/test/integration/glyphs/hex_tile.ts
  bokehjs/test/integration/glyphs/markers.ts
  bokehjs/test/integration/glyphs/spline.ts
  bokehjs/test/integration/glyphs/text.ts
  bokehjs/test/integration/glyphs/webgl.ts
  bokehjs/test/integration/layouts.ts
  bokehjs/test/integration/plots.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/models/tools/gestures/tap_tool.ts
  bokehjs/test/unit/regressions.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: tests, type: task

#10838 Don't use explicit module names in styles/**/*.d.ts
  bokehjs/make/tasks/scripts.ts
Labels: status: accepted

#10719 Update vertex_renderer properly in PolyEditTool
  bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts
  tests/integration/tools/test_poly_edit_tool.py
Labels: status: accepted

#10814 Fix CustomJSFilter args dict: warn if disallowed key is passed
  bokeh/core/properties.py
  bokeh/core/property/container.py
  bokeh/models/filters.py
  tests/unit/bokeh/core/property/test_container.py
  tests/unit/bokeh/core/test_properties.py
Labels: status: accepted

#10846 Add star and star_dot markers
  bokeh/core/enums.py
  bokeh/models/markers.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/glyphs/defs.ts
  bokehjs/test/baselines/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges
  bokehjs/test/baselines/Marker_glyph__should_support_'star'_marker_type
  bokehjs/test/baselines/Marker_glyph__should_support_'star_dot'_marker_type
  bokehjs/test/baselines/linux/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges.png
  bokehjs/test/baselines/macos/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/macos/Marker_glyph__should_support_'star_dot'_marker_type.png
  bokehjs/test/baselines/macos/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10457__prevents_rendering_marker_glyphs_with_reversed_ranges.png
  bokehjs/test/baselines/windows/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/windows/Marker_glyph__should_support_'star_dot'_marker_type.png
  bokehjs/test/baselines/windows/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/integration/glyphs/markers.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/enums.ts
  sphinx/source/docs/user_guide/plotting.rst
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#10847 Add star marker - webgl extension
  bokehjs/src/lib/models/glyphs/webgl/markers.frag
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/test/baselines/Marker_glyph__should_support_'star'_marker_type
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/macos/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/macos/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/windows/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/windows/Marker_glyph__should_support_glyph_methods_and_rotation.png
  sphinx/source/docs/user_guide/webgl.rst
Labels: status: ready, tag: component: bokehjs, tag: webgl, type: feature

#10848 Incorrect Example updated
  bokeh/models/sources.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#10757 2230 expose hit radius
  bokeh/models/glyphs.py
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/marker.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  tests/unit/bokeh/models/_util_models.py
Labels: status: accepted

#10799 Make Websocket compression configurable on Tornado server
  bokeh/command/subcommands/serve.py
  bokeh/server/tornado.py
  bokeh/server/views/ws.py
  tests/unit/bokeh/command/subcommands/test_serve.py
  tests/unit/bokeh/server/test_tornado__server.py
Labels: status: accepted

#10854 Work around in-place updates in LassoSelectTool
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
Labels: status: accepted

#10856 Connect change signals for secondary glyphs of GlyphRenderer
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/baselines/Bug__in_issue_#10856__makes_GlyphRenderer_ignore_changes_to_secondary_glyphs
  bokehjs/test/baselines/linux/Bug__in_issue_#10856__makes_GlyphRenderer_ignore_changes_to_secondary_glyphs.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10856__makes_GlyphRenderer_ignore_changes_to_secondary_glyphs.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10856__makes_GlyphRenderer_ignore_changes_to_secondary_glyphs.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#10858 Properly derive `WebDataSource` from `ColumnDataSource`
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/sources/web_data_source.ts
  bokehjs/test/unit/models/sources/ajax_data_source.ts
  bokehjs/test/unit/regressions.ts
  examples/howto/ajax_source.py
Labels: status: accepted

#10862 Add Bokeh8 palette
  bokeh/palettes.py
Labels: reso: completed, status: accepted, type: task

#10865 Miscellaneous bokehjs build changes
  bokehjs/make/index.js
  bokehjs/package-lock.json
  bokehjs/package.json
  release/build.py
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#10860 Resolve IE compatibility issues
  bokeh/core/has_props.py
  bokeh/core/properties.py
  bokeh/core/property/alias.py
  bokeh/model.py
  bokeh/models/plots.py
  bokehjs/make/tasks/test.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/serializer.ts
  bokehjs/src/lib/core/util/cloneable.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/src/lib/core/util/platform.ts
  bokehjs/src/lib/core/util/pretty.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/external/ie.d.ts
  bokehjs/src/lib/polyfill.ts
  bokehjs/test/defaults/index.ts
  bokehjs/test/devtools/server.ts
  bokehjs/test/devtools/test.html
  tests/integration/tools/test_poly_edit_tool.py
  tests/unit/bokeh/core/property/test_alias.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/core/test_properties.py
Labels: plat: ie, status: ready, tag: component: bokehjs, type: bug

#10869 explose client side max message size
  bokeh/client/connection.py
  bokeh/client/session.py
  bokeh/client/states.py
  tests/unit/bokeh/client/test_states.py
  tests/unit/bokeh/test_client_server.py
Labels: status: accepted

#10871 remote toctree from releases.rst
  sphinx/source/docs/releases.rst
Labels: status: accepted

#10873 Update URL for numpy intersphinx inventory
  sphinx/source/conf.py
Labels: reso: completed, status: accepted, tag: component: docs, type: task
