Repository bokeh/bokeh, pull requests merged in 2021-07, with the labels that each got.

#11397 Restore support for relative font size units
  bokehjs/src/lib/core/graphics.ts
  bokehjs/src/lib/core/util/text.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/formatters/log_tick_formatter.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11110__doesn't_correctly_measure_fonts_if_font_size_is_provided_in_relative_units.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11110__doesn't_correctly_measure_fonts_if_font_size_is_provided_in_relative_units.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11110__doesn't_correctly_measure_fonts_if_font_size_is_provided_in_relative_units.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11110__doesn't_correctly_measure_fonts_if_font_size_is_provided_in_relative_units.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11110__doesn't_correctly_measure_fonts_if_font_size_is_provided_in_relative_units.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11110__doesn't_correctly_measure_fonts_if_font_size_is_provided_in_relative_units.png
  bokehjs/test/integration/regressions.ts
Labels: NEEDS BACK PORT, status: accepted

#11388 Don't configure `z-index` on root elements
  bokehjs/src/less/root.less
  bokehjs/test/baselines/linux/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
  bokehjs/test/integration/regressions.ts
Labels: NEEDS BACK PORT, status: accepted

#11302 Drop Cookie header and compress token payloads
  bokeh/server/contexts.py
  bokeh/server/views/session_handler.py
  bokeh/util/token.py
  tests/unit/bokeh/util/test_token.py
Labels: status: accepted

#11399 Increase session_token_expiration
  tests/unit/bokeh/server/test_server__server.py
Labels: reso: completed, status: accepted, tag: component: tests, type: task

#11394 Revert layout to pre PR #10779 state
  bokehjs/src/lib/core/layout/grid.ts
  bokehjs/src/lib/core/layout/layoutable.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
Labels: NEEDS BACK PORT, status: accepted

#11406 Bryanv/2 3 3 release notes
  sphinx/source/docs/releases/2.3.3.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#11398 Add intro for categorical chapter
  sphinx/source/docs/user_guide/categorical.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/examples/categorical_scatter_jitter.py
  sphinx/source/docs/user_guide/plotting.rst
  sphinx/source/docs/user_guide/styling.rst
  sphinx/source/rst_epilog.txt
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#11400 Change jitter caching to only cache offsets instead of values
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/glyphs/step.ts
  bokehjs/src/lib/models/transforms/jitter.ts
  bokehjs/src/lib/models/transforms/range_transform.ts
  bokehjs/test/unit/models/transforms/jitter.ts
Labels: status: ready

#11417 Consolidate pip dependencies
  ci/environment-release-build.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
Labels: reso: completed, status: accepted, type: task

#11419 Remove OrderedDict
  bokeh/embed/util.py
  bokeh/models/tools.py
  bokeh/util/compiler.py
  examples/app/fourier_animated.py
  examples/embed/embed_multiple.py
  examples/plotting/file/burtin.py
  scripts/sri.py
  tests/unit/bokeh/embed/test_standalone.py
Labels: status: accepted, type: task

#11421 Add legend item visibility to user guide
  bokeh/models/annotations.py
  bokeh/plotting/_docstring.py
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/examples/plotting_legends_item_visibility.py
Labels: status: accepted, tag: component: docs

#11426 Fix pandas future warning
  bokeh/sampledata/commits.py
Labels: status: accepted

#11433 Parse docstrings in examples for gallery detail pages
  bokeh/application/handlers/code_runner.py
  bokeh/sphinxext/_templates/gallery_detail.rst
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/example_handler.py
  examples/plotting/file/iris.py
  sphinx/source/docs/user_guide/examples/js_events.py
  tests/unit/bokeh/application/handlers/test_code_runner.py
Labels: status: accepted

#11438 Sprinters example: updated CustomJS; some PEP8 cleanup
  examples/plotting/file/sprint.py
Labels: reso: completed, status: accepted, tag: component: examples, type: task

#11443 Update wording around output_file()
  bokeh/io/notebook.py
  bokeh/io/output.py
  bokeh/io/showing.py
  bokeh/io/state.py
  sphinx/source/docs/first_steps/first_steps_1.rst
  sphinx/source/docs/first_steps/first_steps_7.rst
  sphinx/source/docs/first_steps/first_steps_9.rst
  sphinx/source/docs/reference.rst
  sphinx/source/docs/user_guide/cli.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/embed.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/rst_epilog.txt
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#11445 publish dev docs with release level
  release/deploy.py
Labels: reso: completed, status: accepted, tag: CI

#11451 License tests compatible with Windows
  tests/codebase/test_js_license_set.py
  tests/codebase/test_license.py
Labels: status: accepted

#11454 Fix spec.py and cleanup scripts cruft
  docker-tools/.dockerignore
  docker-tools/Dockerfile-from-travis
  docker-tools/README.md
  docker-tools/alpine/Dockerfile-conda
  docker-tools/alpine/Dockerfile-from-source
  docker-tools/base.sh
  docker-tools/bash.sh
  docker-tools/debian/Dockerfile
  docker-tools/debian/Dockerfile-pip
  docker-tools/debian/app.yaml
  docker-tools/debian/environment.yml
  docker-tools/debian/requirements.txt
  docker-tools/hello_nodejs.py
  docker-tools/hello_world.py
  docker-tools/make.sh
  docker-tools/npm-install.sh
  docker-tools/pytest.sh
  docker-tools/quality.sh
  scripts/deps.py
  scripts/spec.py
Labels: reso: completed, status: accepted, type: task

#11450 Cleanup bokeh.sphinxext
  bokeh/model.py
  bokeh/models/layouts.py
  bokeh/sphinxext/_templates/sri_table.html
  bokeh/sphinxext/bokeh_directive.py
  bokeh/sphinxext/bokeh_enum.py
  bokeh/sphinxext/bokeh_gallery.py
  bokeh/sphinxext/bokeh_jinja.py
  bokeh/sphinxext/bokeh_model.py
  bokeh/sphinxext/bokeh_options.py
  bokeh/sphinxext/bokeh_palette_group.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_prop.py
  bokeh/sphinxext/bokeh_releases.py
  bokeh/sphinxext/bokeh_settings.py
  bokeh/sphinxext/bokehjs_content.py
  bokeh/sphinxext/collapsible_code_block.py
  bokeh/sphinxext/templates.py
  sphinx/source/_static/custom.css
  sphinx/source/_templates/scripts.html
Labels: status: accepted

#11463 Skip svg export test
  tests/unit/bokeh/io/test_export.py
Labels: reso: completed, status: accepted, type: task

#11459 Update file_input.py
  examples/plotting/file/file_input.py
Labels: reso: completed, status: accepted, tag: component: examples, type: task
