Repository bokeh/bokeh, pull requests merged in 2021-03, with the labels that each got.

#10973 Add missing comma in example code
  sphinx/source/docs/first_steps/first_steps_9.rst
Labels: NEEDS FORWARD PORT, reso: completed, status: accepted

#10967 Mention jupyter-server-proxy instead of nbserverproxy in docs
  sphinx/source/docs/user_guide/jupyter.rst
Labels: NEEDS BACK PORT, status: accepted, status: ready

#10972 replaced old-style string substitution
  bokeh/sphinxext/bokeh_releases.py
Labels: reso: completed, status: accepted, type: task

#10979 Add dask/dask to downstream tests
  ci/install_downstream_packages.sh
  ci/run_downstream_tests.sh
Labels: reso: completed, status: accepted, tag: component: tests, type: task

#10982 remove SRI hashes from Bokeh output
  bokeh/core/_templates/autoload_js.js
  bokeh/core/_templates/js_resources.html
  bokeh/sphinxext/_templates/bokehjs_html_template.html
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/test_resources.py
Labels: status: ready

#10986 Bryanv/2 3 1 backports
  bokeh/sphinxext/bokeh_releases.py
  bokehjs/src/lib/models/widgets/file_input.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_FileInput.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_FileInput.png
  bokehjs/test/baselines/macos/Widgets__should_allow_FileInput.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_FileInput.png
  bokehjs/test/baselines/windows/Widgets__should_allow_FileInput.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_FileInput.png
  bokehjs/test/devtools/test.html
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/models/widgets/file_input.ts
  sphinx/source/docs/user_guide/jupyter.rst
Labels: reso: completed, status: accepted, type: task

#10987 Bryanv/2 3 1 forwardports
  bokeh/_version.py
  bokeh/models/widgets/inputs.py
  sphinx/source/docs/first_steps/first_steps_9.rst
  sphinx/source/docs/first_steps/installation.rst
  versioneer.py
Labels: reso: completed, status: accepted, type: task

#10917 register "freehand_draw" as alias
  bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
Labels: NEEDS FORWARD PORT, status: accepted

#10988 register "freehand_draw" as an alias in python
  bokeh/models/tools.py
Labels: NEEDS FORWARD PORT, status: accepted

#10999 Fix examples/app/spectrogram
  examples/app/spectrogram/audio.py
  examples/app/spectrogram/waterfall.py
  examples/app/spectrogram/waterfall.ts
Labels: NEEDS FORWARD PORT, status: ready

#11001 Clean up after PR #10939
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/regressions.ts
Labels: NEEDS FORWARD PORT, status: accepted

#10997 Clarify explanation in First Steps 1
  sphinx/source/docs/first_steps/first_steps_1.rst
Labels: NEEDS FORWARD PORT, status: accepted, tag: component: docs, type: task

#11005 Make sure FuncTickFormatter always produces string labels
  bokehjs/src/lib/models/formatters/func_tick_formatter.ts
  bokehjs/test/unit/models/formatters/func_tick_formatter.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11003 Add PolyAnnotation to user guide
  sphinx/source/docs/user_guide/annotations.rst
  sphinx/source/docs/user_guide/examples/plotting_polygon_annotation.py
Labels: NEEDS FORWARD PORT, status: accepted

#11010 PolyAnnotation: link reference guide to user guide
  bokeh/models/annotations.py
Labels: NEEDS FORWARD PORT, status: ready

#11019 Improve speed by comparing whole buffers first
  bokehjs/test/devtools/devtools.ts
Labels: status: accepted, tag: component: bokehjs, tag: component: tests, type: task

#11011 Properties cleanup (pt 2)
  bokeh/core/properties.py
  bokeh/core/property/bases.py
  bokeh/core/property/dataspec.py
  bokeh/core/property/descriptors.py
  bokeh/models/annotations.py
  bokeh/models/glyphs.py
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/marker.ts
  sphinx/source/conf.py
  sphinx/source/docs/releases/2.4.0.rst
  tests/unit/bokeh/core/property/test_dataspec.py
  tests/unit/bokeh/core/property/test_validation__property.py
  tests/unit/bokeh/core/test_properties.py
Labels: status: accepted

#11030 Make EditTool.custom_icon nullable
  bokeh/models/tools.py
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11024 Simplify rendering of Line and MultiLine glyphs
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/integration/regressions.ts
  tests/examples.yaml
  tests/test_examples.py
Labels: status: ready, tag: component: bokehjs, type: task

#11014 adding bokehjs known issues, v2.3
  sphinx/source/docs/releases/2.3.0.rst
  sphinx/source/docs/user_guide/bokehjs.rst
Labels: status: accepted

#11043 Backport: Simplify rendering of Line and MultiLine glyphs (#11024)
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#10305__disallows_to_render_multi-lines_with_NaNs_using_SVG_backend.png
  bokehjs/test/integration/regressions.ts
  tests/examples.yaml
  tests/test_examples.py
Labels: status: accepted, type: task

#11046 Clone child SVG nodes before composing them
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11045__prevents_correct_paint_of_glyphs_using_hatch_patters_in_SVG_backend_after_pan.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11045__prevents_correct_paint_of_glyphs_using_hatch_patters_in_SVG_backend_after_pan.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11045__prevents_correct_paint_of_glyphs_using_hatch_patters_in_SVG_backend_after_pan.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11045__prevents_correct_paint_of_glyphs_using_hatch_patters_in_SVG_backend_after_pan.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11045__prevents_correct_paint_of_glyphs_using_hatch_patters_in_SVG_backend_after_pan.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11045__prevents_correct_paint_of_glyphs_using_hatch_patters_in_SVG_backend_after_pan.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready

#11042 add note about extension defaults
  sphinx/source/docs/user_guide/extensions.rst
Labels: NEEDS FORWARD PORT, status: accepted

#11049 [Docs] Fix references in Docs section
  sphinx/source/docs/dev_guide/documentation.rst
Labels: NEEDS FORWARD PORT, status: accepted, tag: component: docs, type: task

#11055 Don't allow invalid bboxes in BoxAnnotation
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/test/unit/core/util/bbox.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11040 exposes Palettes
  bokehjs/src/lib/api/index.ts
Labels: status: accepted

#11059 FIX: Add support for line dash offset in SVG backend
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Line_glyph__should_support_dashed_lines_with_offsets.png
  bokehjs/test/baselines/macos/Line_glyph__should_support_dashed_lines_with_offsets.png
  bokehjs/test/baselines/windows/Line_glyph__should_support_dashed_lines_with_offsets.png
Labels: status: accepted

#11063 Fix snap_back for tile renderer
  bokehjs/src/lib/models/tiles/tile_renderer.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11065 Use #rrggbb for input[type=color].value
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/models/widgets/color_picker.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11073 Drop unnecessary -webkit- prefixes from flexbox
  bokehjs/src/less/_mixins.less
  bokehjs/src/less/buttons.less
  bokehjs/src/less/menus.less
  bokehjs/src/less/tabs.less
  bokehjs/src/less/toolbar.less
  bokehjs/src/less/widgets/inputs.less
Labels: status: accepted, tag: component: bokehjs, type: task

#11078 Fix regressions after PR #10930
  bokeh/core/_templates/autoload_nb_js.js
  bokeh/core/_templates/autoload_request_tag.html
  tests/unit/bokeh/core/test_templates.py
Labels: reso: completed, status: accepted, tag: regression, type: task

#11079 Use fromisoformat for date/datetime validation
  bokeh/core/property/datetime.py
  docker-tools/debian/requirements.txt
  setup.py
  sphinx/source/docs/first_steps/installation.rst
  sphinx/source/docs/releases/2.4.0.rst
  tests/unit/bokeh/core/property/test_datetime.py
Labels: status: ready

#11086 Fixed missing f in f-string
  bokeh/core/has_props.py
Labels: NEEDS BACK PORT, reso: completed, status: accepted, type: task

#11085 Support other size units when scaling superscripts
  bokehjs/src/lib/core/graphics.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11006__prevents_scaling_of_superscripts_when_using_non-px_font_size_units.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11006__prevents_scaling_of_superscripts_when_using_non-px_font_size_units.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11006__prevents_scaling_of_superscripts_when_using_non-px_font_size_units.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11006__prevents_scaling_of_superscripts_when_using_non-px_font_size_units.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11006__prevents_scaling_of_superscripts_when_using_non-px_font_size_units.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11006__prevents_scaling_of_superscripts_when_using_non-px_font_size_units.png
  bokehjs/test/integration/regressions.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11088 Add sphinx roles for versions
  .gitignore
  _setup_support.py
  bokeh/LICENSE.txt
  bokeh/sphinxext/bokeh_roles.py
  setup.py
  sphinx/source/conf.py
  sphinx/source/docs/first_steps/installation.rst
  sphinx/source/docs/reference/sphinxext.rst
  tests/codebase/test_license.py
Labels: status: accepted

#11090 Simplify rendering code with visuals.apply()
  bokehjs/src/lib/core/visuals/fill.ts
  bokehjs/src/lib/core/visuals/hatch.ts
  bokehjs/src/lib/core/visuals/line.ts
  bokehjs/src/lib/models/annotations/band.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/src/lib/models/annotations/text_annotation.ts
  bokehjs/src/lib/models/glyphs/annular_wedge.ts
  bokehjs/src/lib/models/glyphs/annulus.ts
  bokehjs/src/lib/models/glyphs/box.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/defs.ts
  bokehjs/src/lib/models/glyphs/ellipse_oval.ts
  bokehjs/src/lib/models/glyphs/harea.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/patch.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/src/lib/models/glyphs/utils.ts
  bokehjs/src/lib/models/glyphs/varea.ts
  bokehjs/src/lib/models/glyphs/wedge.ts
  bokehjs/src/lib/models/grids/grid.ts
  examples/custom/gears/gear.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, type: task

#11092 HasProps and misc cleanup
  bokeh/core/has_props.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/either.py
  bokeh/core/property/include.py
  bokeh/core/property/regex.py
  bokeh/core/property_mixins.py
  bokeh/model.py
  bokeh/models/annotations.py
  bokeh/models/arrow_heads.py
  bokeh/models/axes.py
  bokeh/models/glyphs.py
  bokeh/models/grids.py
  bokeh/models/plots.py
  bokeh/util/string.py
  examples/custom/gears/gear.py
  sphinx/source/docs/dev_guide/models.rst
  tests/unit/bokeh/core/property/test_descriptors.py
  tests/unit/bokeh/core/property/test_include.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/models/test_defaults.py
  tests/unit/bokeh/test_model.py
  tests/unit/bokeh/util/test_string.py
Labels: status: accepted, type: task

#11099 Allow to test against a provided git reference
  bokehjs/make/tasks/test.ts
  bokehjs/test/devtools/baselines.ts
  bokehjs/test/devtools/devtools.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: tests, type: feature

#11066 Serialize definitions of only newly created objects
  bokehjs/src/lib/document/document.ts
  bokehjs/test/codebase/size.ts
  bokehjs/test/unit/document/document.ts
Labels: NEEDS FORWARD PORT, status: accepted

#11018 Update bokehjs' plotting API to match bokeh
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/api/linalg.ts
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/util/object.ts
  bokehjs/src/lib/core/util/pretty.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/test/unit/core/util/pretty.ts
  bokehjs/test/unit/regressions.ts
Labels: status: ready

#11108 Fix WebGL line regression
  bokehjs/src/lib/models/glyphs/webgl/regl_line.vert
  bokehjs/test/baselines/linux/webgl__should_render_overlapping_near_parallel_lines.blf
  bokehjs/test/baselines/linux/webgl__should_render_overlapping_near_parallel_lines.png
  bokehjs/test/baselines/macos/webgl__should_render_overlapping_near_parallel_lines.blf
  bokehjs/test/baselines/macos/webgl__should_render_overlapping_near_parallel_lines.png
  bokehjs/test/baselines/windows/webgl__should_render_overlapping_near_parallel_lines.blf
  bokehjs/test/baselines/windows/webgl__should_render_overlapping_near_parallel_lines.png
  bokehjs/test/integration/glyphs/webgl.ts
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: regression, tag: webgl, type: task

#11106 Update docs for JupyterLab/jupyter_bokeh
  sphinx/source/docs/user_guide/jupyter.rst
Labels: NEEDS FORWARD PORT, status: accepted

#11113 Bryanv/11112 build job os
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
Labels: NEEDS FORWARD PORT, status: accepted
