Repository bokeh/bokeh, pull requests merged in 2021-09, with the labels that each got.

#11532 Allow extensions to modify applications in serve subcommand
  bokeh/command/subcommands/serve.py
  tests/unit/bokeh/command/subcommands/test_serve.py
Labels: status: ready, type: task, tag: component: server

#11550 Allow vectorization of `Image*.global_alpha`
  bokeh/models/glyphs.py
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageRGBA_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageRGBA_glyph.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageURL_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageURL_glyph.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_Image_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_Image_glyph.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageRGBA_glyph.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageRGBA_glyph.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageURL_glyph.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageURL_glyph.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_Image_glyph.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_Image_glyph.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageRGBA_glyph.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageRGBA_glyph.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageURL_glyph.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_ImageURL_glyph.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_Image_glyph.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11548__doesn't_allow_vectorized_global_alpha_in_Image_glyph.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/glyphs/image_url.ts
Labels: status: accepted

#11552 Respect clip paths in `SVGRenderingContext2D.drawImage()`
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11551__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_images.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11551__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_images.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11551__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_images.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11551__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_images.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11551__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_images.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11551__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_images.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#11442 Reorganize git hooks
  .pre-commit-config.yaml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
  scripts/hooks/install.py
  scripts/hooks/protect_branches.py
  scripts/hooks/uninstall.py
  sphinx/source/docs/dev_guide/setup.rst
Labels: status: accepted

#11536 Reassign value on numeric_input high-low change only if needed
  bokehjs/src/lib/models/widgets/numeric_input.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#11559 Misc docs build changes
  bokeh/layouts.py
  bokeh/models/markers.py
  bokeh/sphinxext/__init__.py
  bokeh/sphinxext/_templates/model_detail.rst
  bokeh/sphinxext/bokeh_autodoc.py
  bokeh/sphinxext/bokeh_color.py
  bokeh/sphinxext/bokeh_dataframe.py
  bokeh/sphinxext/bokeh_enum.py
  bokeh/sphinxext/bokeh_example_metadata.py
  bokeh/sphinxext/bokeh_gallery.py
  bokeh/sphinxext/bokeh_jinja.py
  bokeh/sphinxext/bokeh_model.py
  bokeh/sphinxext/bokeh_options.py
  bokeh/sphinxext/bokeh_palette.py
  bokeh/sphinxext/bokeh_palette_group.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_prop.py
  bokeh/sphinxext/bokeh_releases.py
  bokeh/sphinxext/bokeh_roles.py
  bokeh/sphinxext/bokeh_settings.py
  bokeh/sphinxext/bokeh_sitemap.py
  bokeh/sphinxext/bokehjs_content.py
  bokeh/sphinxext/collapsible_code_block.py
  sphinx/Makefile
  sphinx/source/docs/reference/layouts.rst
  sphinx/source/docs/reference/models/annotations.rst
  sphinx/source/docs/reference/models/arrow_heads.rst
  sphinx/source/docs/reference/models/axes.rst
  sphinx/source/docs/reference/models/callbacks.rst
  sphinx/source/docs/reference/models/expressions.rst
  sphinx/source/docs/reference/models/filters.rst
  sphinx/source/docs/reference/models/formatters.rst
  sphinx/source/docs/reference/models/glyphs.rst
  sphinx/source/docs/reference/models/graphs.rst
  sphinx/source/docs/reference/models/grids.rst
  sphinx/source/docs/reference/models/layouts.rst
  sphinx/source/docs/reference/models/map_plots.rst
  sphinx/source/docs/reference/models/mappers.rst
  sphinx/source/docs/reference/models/markers.rst
  sphinx/source/docs/reference/models/plots.rst
  sphinx/source/docs/reference/models/ranges.rst
  sphinx/source/docs/reference/models/renderers.rst
  sphinx/source/docs/reference/models/scales.rst
  sphinx/source/docs/reference/models/selections.rst
  sphinx/source/docs/reference/models/sources.rst
  sphinx/source/docs/reference/models/text.rst
  sphinx/source/docs/reference/models/textures.rst
  sphinx/source/docs/reference/models/tickers.rst
  sphinx/source/docs/reference/models/tiles.rst
  sphinx/source/docs/reference/models/tools.rst
  sphinx/source/docs/reference/models/transforms.rst
  sphinx/source/docs/reference/models/widgets.rst
  sphinx/source/docs/reference/models/widgets/buttons.rst
  sphinx/source/docs/reference/models/widgets/groups.rst
  sphinx/source/docs/reference/models/widgets/icons.rst
  sphinx/source/docs/reference/models/widgets/inputs.rst
  sphinx/source/docs/reference/models/widgets/markups.rst
  sphinx/source/docs/reference/models/widgets/sliders.rst
  sphinx/source/docs/reference/models/widgets/tables.rst
  sphinx/source/docs/reference/models/widgets/widget.rst
Labels: tag: component: docs, status: accepted, type: task

#11568 Fixing typo error 2
  bokeh/core/validation/errors.py
  tests/unit/bokeh/models/test_plots.py
Labels: type: bug, status: accepted, reso: completed

#11513 Update dev docs
  .github/CONTRIBUTING.md
  .pre-commit-config.yaml
  README.md
  _setup_support.py
  bokeh/server/views/app_index.html
  bokehjs/README.md
  ci/environment-release-build.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
  sphinx/source/_images/bokehjs_devtools_report.png
  sphinx/source/_images/bokehjs_devtools_test_run.png
  sphinx/source/_images/examples_test_report.png
  sphinx/source/_static/custom.css
  sphinx/source/_templates/footer.html
  sphinx/source/conf.py
  sphinx/source/docs/dev_guide.rst
  sphinx/source/docs/dev_guide/bindings.rst
  sphinx/source/docs/dev_guide/bokehjs.rst
  sphinx/source/docs/dev_guide/creating_issues.rst
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/dev_guide/env_vars.rst
  sphinx/source/docs/dev_guide/models.rst
  sphinx/source/docs/dev_guide/pull_requests.rst
  sphinx/source/docs/dev_guide/server.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
  sphinx/source/docs/dev_guide/writing_tests.rst
  sphinx/source/docs/first_steps/first_steps_7.rst
  sphinx/source/docs/first_steps/installation.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/export.rst
  sphinx/source/docs/user_guide/server.rst
  sphinx/source/index.rst
  sphinx/source/rst_epilog.txt
Labels: status: accepted

#11573 Add version as request argument to extension to avoid browser caching
  bokeh/embed/bundle.py
  tests/unit/bokeh/embed/test_bundle.py
Labels: type: bug, status: accepted, reso: completed, tag: component: server

#11569 Fix IE/legacy compatibility issues with bokeh 2.4
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/src/lib/core/util/pretty.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/widgets/button_group.ts
  bokehjs/src/lib/polyfill.ts
  bokehjs/test/unit/core/util/pretty.ts
Labels: status: accepted

#11577 Better formatting for args lists in docstrings
  sphinx/source/_static/custom.css
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#11572 Print URL with protocol inferred from config
  bokeh/command/subcommands/serve.py
Labels: status: accepted

#11580 Always convert `str` to `Title` in `Plot.title`
  bokeh/models/plots.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  tests/unit/bokeh/models/test_plots.py
Labels: status: accepted

#11581 Fix typos, line breaks, and links
  sphinx/source/_images/bokeh_app_sliders.png
  sphinx/source/_images/bokeh_iris_html.png
  sphinx/source/_images/bokeh_marker_map_html.png
  sphinx/source/docs/dev_guide.rst
  sphinx/source/docs/dev_guide/creating_issues.rst
  sphinx/source/docs/dev_guide/pull_requests.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
  sphinx/source/docs/dev_guide/writing_tests.rst
Labels: tag: component: docs, status: accepted, type: task

#11586 Add support for `legend_{label,field,group}` to bokehjs' `Figure`
  bokehjs/examples/legends/legends.ts
  bokehjs/examples/stocks/stocks.ts
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/util/array.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#6775__disallows_correct_rendering_of_legends_with_SVG_backend.png
  bokehjs/test/baselines/macos/Bug__in_issue_#6775__disallows_correct_rendering_of_legends_with_SVG_backend.png
  bokehjs/test/baselines/windows/Bug__in_issue_#6775__disallows_correct_rendering_of_legends_with_SVG_backend.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/api/plotting.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: API: plotting

#11588 Make SVG backend respect clip paths on `<text>`
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Text.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_Text.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_Text.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#11584 Mathstring conveniences for axis_labels and tick labels
  bokeh/core/property/string.py
  bokeh/embed/bundle.py
  bokeh/models/text.py
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/text/utils.ts
  bokehjs/test/unit/models/axes/axis.ts
  tests/unit/bokeh/embed/test_bundle.py
  tests/unit/bokeh/models/test_axes.py
Labels: status: accepted, type: task, tag: component: bokehjs, tag: API: models

#11590 udpate release notes
  sphinx/source/docs/releases/2.4.0.rst
  sphinx/versions.json
Labels: tag: component: docs, status: ready, type: task

#11592 Handle env vars in tests more carefully
  bokeh/_testing/util/env.py
  tests/unit/bokeh/_testing/util/test_env.py
  tests/unit/bokeh/command/subcommands/test_serve.py
  tests/unit/bokeh/embed/test_bundle.py
  tests/unit/bokeh/server/test_tornado__server.py
  tests/unit/bokeh/test_client_server.py
  tests/unit/bokeh/test_settings.py
  tests/unit/bokeh/util/test_browser.py
  tests/unit/bokeh/util/test_serialization.py
  tests/unit/bokeh/util/test_token.py
Labels: status: accepted

#11595 Require space before blocks
  bokehjs/eslint.json
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/util/object.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/formatters/log_tick_formatter.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/sources/cds_view.ts
  bokehjs/src/lib/models/widgets/numeric_input.ts
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#11547 Updateable layout_provider/graph_layout
  bokeh/models/graphs.py
  bokehjs/src/lib/models/expressions/coordinate_transform.ts
  bokehjs/src/lib/models/graphs/layout_provider.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11547__doesn't_render_changes_of_graph_layout_provider.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11547__doesn't_render_changes_of_graph_layout_provider.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11547__doesn't_render_changes_of_graph_layout_provider.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11547__doesn't_render_changes_of_graph_layout_provider.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11547__doesn't_render_changes_of_graph_layout_provider.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11547__doesn't_render_changes_of_graph_layout_provider.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/renderers/graph_renderer.ts
Labels: status: accepted

#11597 Misc MyPy work
  bokeh/client/websocket.py
  bokeh/colors/util.py
  bokeh/io/notebook.py
  bokeh/io/output.py
  bokeh/io/webdriver.py
  bokeh/protocol/__init__.py
  bokeh/protocol/message.py
  bokeh/protocol/messages/error.py
  bokeh/protocol/messages/patch_doc.py
  bokeh/protocol/receiver.py
  pyproject.toml
  tests/unit/bokeh/colors/test_util__colors.py
Labels: status: accepted, type: task, reso: completed

#11585 TeX on Markup widgets Div, Paragraph
  bokeh/embed/bundle.py
  bokeh/embed/util.py
  bokeh/models/text.py
  bokeh/models/widgets/markups.py
  bokehjs/src/lib/external/mathjax.d.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/src/lib/models/text/mathjax/index.ts
  bokehjs/src/lib/models/text/providers.ts
  bokehjs/src/lib/models/text/utils.ts
  bokehjs/src/lib/models/widgets/div.ts
  bokehjs/src/lib/models/widgets/markup.ts
  bokehjs/src/lib/models/widgets/paragraph.ts
  bokehjs/src/lib/models/widgets/pretext.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_TeX_on_Divs_with_mathstrings.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_TeX_on_Divs_with_mathstrings.png
  bokehjs/test/baselines/linux/Widgets__should_allow_TeX_on_Paragraph_with_mathstrings.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_TeX_on_Paragraph_with_mathstrings.png
  bokehjs/test/baselines/linux/Widgets__should_not_allow_TeX_on_PreText_with_mathstrings.blf
  bokehjs/test/baselines/linux/Widgets__should_not_allow_TeX_on_PreText_with_mathstrings.png
  bokehjs/test/baselines/linux/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_disable_math=true.blf
  bokehjs/test/baselines/linux/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_disable_math=true.png
  bokehjs/test/baselines/linux/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_render_as_text=true.blf
  bokehjs/test/baselines/linux/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_render_as_text=true.png
  bokehjs/test/baselines/macos/Widgets__should_allow_TeX_on_Divs_with_mathstrings.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_TeX_on_Divs_with_mathstrings.png
  bokehjs/test/baselines/macos/Widgets__should_allow_TeX_on_Paragraph_with_mathstrings.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_TeX_on_Paragraph_with_mathstrings.png
  bokehjs/test/baselines/macos/Widgets__should_not_allow_TeX_on_PreText_with_mathstrings.blf
  bokehjs/test/baselines/macos/Widgets__should_not_allow_TeX_on_PreText_with_mathstrings.png
  bokehjs/test/baselines/macos/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_disable_math=true.blf
  bokehjs/test/baselines/macos/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_disable_math=true.png
  bokehjs/test/baselines/macos/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_render_as_text=true.blf
  bokehjs/test/baselines/macos/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_render_as_text=true.png
  bokehjs/test/baselines/windows/Widgets__should_allow_TeX_on_Divs_with_mathstrings.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_TeX_on_Divs_with_mathstrings.png
  bokehjs/test/baselines/windows/Widgets__should_allow_TeX_on_Paragraph_with_mathstrings.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_TeX_on_Paragraph_with_mathstrings.png
  bokehjs/test/baselines/windows/Widgets__should_not_allow_TeX_on_PreText_with_mathstrings.blf
  bokehjs/test/baselines/windows/Widgets__should_not_allow_TeX_on_PreText_with_mathstrings.png
  bokehjs/test/baselines/windows/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_disable_math=true.blf
  bokehjs/test/baselines/windows/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_disable_math=true.png
  bokehjs/test/baselines/windows/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_render_as_text=true.blf
  bokehjs/test/baselines/windows/Widgets__should_not_process_TeX_on_Divs_with_mathstrings_and_render_as_text=true.png
  bokehjs/test/integration/widgets.ts
Labels: type: feature, status: accepted, reso: completed, tag: widgets

#11570 Add LaTeX axes examples
  examples/plotting/file/latex_blackbody_radiation.py
  examples/plotting/file/latex_normal_distribution.py
Labels: type: task, reso: completed, tag: component: examples

#11544 Update docs for math notations (LaTeX and MathML)
  bokeh/models/text.py
  bokehjs/src/lib/models/text/math_text.ts
  sphinx/source/docs/first_steps/first_steps_4.rst
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_axis_labels.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_div_widget.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_tick_labels.py
  sphinx/source/docs/user_guide/examples/styling_math_text_mathml_axis_labels.py
  sphinx/source/docs/user_guide/styling.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#11599 More 2.4 last minute docs
  examples/plotting/file/bar_intervals.py
  examples/plotting/file/box_annotation.py
  examples/plotting/file/gmap.py
  examples/plotting/file/hatch_grid_band.py
  examples/plotting/file/latex_blackbody_radiation.py
  examples/plotting/file/latex_normal_distribution.py
  examples/plotting/file/sprint.py
  examples/plotting/file/stacked_area.py
  sphinx/source/_images/gallery/anscombe.png
  sphinx/source/_images/gallery/box_annotation.png
  sphinx/source/_images/gallery/boxplot.png
  sphinx/source/_images/gallery/hatch_grid_band.png
  sphinx/source/_images/gallery/histogram.png
  sphinx/source/_images/gallery/jitter.png
  sphinx/source/_images/gallery/latex_blackbody_radiation.png
  sphinx/source/_images/gallery/latex_normal_distribution.png
  sphinx/source/_images/gallery/les_mis.png
  sphinx/source/_images/gallery/logaxis.png
  sphinx/source/_images/gallery/logplot.png
  sphinx/source/_images/gallery/lorenz.png
  sphinx/source/_images/gallery/markers.png
  sphinx/source/_images/gallery/sprint.png
  sphinx/source/_images/gallery/stacked_area.png
  sphinx/source/_images/gallery/texas.png
  sphinx/source/docs/gallery.json
  sphinx/source/docs/releases/2.4.0.rst
  sphinx/source/docs/user_guide/annotations.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#11604 Add and update examples
  examples/plotting/file/elements.py
  examples/plotting/file/network_graph.py
  sphinx/source/_images/gallery/elements.png
  sphinx/source/_images/gallery/network_graph.png
  sphinx/source/_images/gallery/periodic.png
  sphinx/source/_images/gallery/pie_chart.png
  sphinx/source/_images/gallery/unemployment.png
  sphinx/source/docs/gallery.json
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_axis_labels.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_div_widget.py
  sphinx/source/docs/user_guide/examples/styling_math_text_mathml_axis_labels.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#11611 Wrap autoload script's contents in a closure
  bokeh/core/_templates/autoload_request_tag.html
Labels: status: accepted

#11612 Define properties correctly in surface3d example
  examples/app/surface3d/surface3d.py
Labels: status: accepted

#11615 Don't use regular expressions for parsing delimited strings
  bokehjs/src/lib/core/graphics.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/text/base_text.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/src/lib/models/text/plain_text.ts
  bokehjs/src/lib/models/text/utils.ts
  bokehjs/test/unit/core/util/eq.ts
  bokehjs/test/unit/models/axes/axis.ts
  bokehjs/test/unit/models/text/utils.ts
Labels: status: accepted

#11622 Don't report successful flaky tests
  setup.cfg
Labels: tag: component: tests, status: accepted, type: task, reso: completed

#11620 Execute 3.0 deprecations
  bokeh/core/properties.py
  bokeh/core/property/dataspec.py
  bokeh/core/property/descriptors.py
  bokeh/document/document.py
  bokeh/layouts.py
  bokeh/models/__init__.py
  bokeh/models/annotations.py
  bokeh/models/glyphs.py
  bokeh/models/graphs.py
  bokeh/models/layouts.py
  bokeh/models/markers.py
  bokeh/models/plots.py
  bokeh/models/ranges.py
  bokeh/models/sources.py
  bokeh/models/tools.py
  bokeh/plotting/__init__.py
  bokeh/plotting/_decorators.py
  bokeh/plotting/_legends.py
  bokeh/plotting/glyph_api.py
  bokeh/util/session_id.py
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/models/glyphs/ellipse.ts
  bokehjs/src/lib/models/glyphs/ellipse_oval.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/oval.ts
  bokehjs/src/lib/models/layouts/index.ts
  bokehjs/src/lib/models/layouts/widget_box.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/ranges/data_range.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/util.ts
  bokehjs/test/defaults/index.ts
  bokehjs/test/unit/models/util.ts
  examples/howto/export_to_png.py
  examples/howto/export_to_svg.py
  examples/models/file/glyphs.py
  examples/reference/models/Oval.py
  sphinx/source/docs/reference/layouts.rst
  sphinx/source/docs/reference/models/glyphs/oval.rst
  sphinx/source/docs/reference/models/markers.rst
  sphinx/source/docs/releases/2.2.0.rst
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/rst_epilog.txt
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/document/test_modules.py
  tests/unit/bokeh/models/test_glyphs.py
  tests/unit/bokeh/models/test_graphs.py
  tests/unit/bokeh/models/test_layouts__models.py
  tests/unit/bokeh/models/test_ranges.py
  tests/unit/bokeh/plotting/test__lengends.py
  tests/unit/bokeh/plotting/test_figure.py
  tests/unit/bokeh/test_layouts.py
Labels: status: accepted, type: task, reso: completed

#11624 Drop `@deprecated` functionality of bokehjs
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/signaling.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/object.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/canvas/cartesian_frame.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/util.ts
  bokehjs/test/unit/core/util/object.ts
  bokehjs/test/unit/document/document.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#11626 Replace unix separators instead of os.sep
  bokeh/_testing/util/project.py
Labels: status: accepted, NEEDS BACK PORT

#11628 Correct path in dev guide server instructions
  sphinx/source/docs/dev_guide/setup.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed, NEEDS BACK PORT

#11630 Resolve typing platform specific issues
  .github/workflows/bokeh-ci.yml
  bokeh/util/terminal.py
  release/ui.py
  tests/test_examples.py
Labels: status: accepted, NEEDS BACK PORT

#11631 Compute indices' set difference more efficiently
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
Labels: status: accepted, NEEDS BACK PORT

#11538 Add support for `Tool.icon`
  bokeh/core/enums.py
  bokeh/models/tools.py
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/models/tools/actions/custom_action.ts
  bokehjs/src/lib/models/tools/actions/help_tool.ts
  bokehjs/src/lib/models/tools/actions/redo_tool.ts
  bokehjs/src/lib/models/tools/actions/reset_tool.ts
  bokehjs/src/lib/models/tools/actions/save_tool.ts
  bokehjs/src/lib/models/tools/actions/undo_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/src/lib/models/tools/button_tool.ts
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/line_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/src/lib/models/tools/tool_proxy.ts
  bokehjs/test/baselines/linux/Feature__in_issue_#10914__should_allow_customizing_tool_icons.blf
  bokehjs/test/baselines/linux/Feature__in_issue_#10914__should_allow_customizing_tool_icons.png
  bokehjs/test/baselines/macos/Feature__in_issue_#10914__should_allow_customizing_tool_icons.blf
  bokehjs/test/baselines/macos/Feature__in_issue_#10914__should_allow_customizing_tool_icons.png
  bokehjs/test/baselines/windows/Feature__in_issue_#10914__should_allow_customizing_tool_icons.blf
  bokehjs/test/baselines/windows/Feature__in_issue_#10914__should_allow_customizing_tool_icons.png
  bokehjs/test/integration/features.ts
  bokehjs/test/unit/models/tools/toolbar_box.ts
  examples/custom/custom_tool.py
  examples/custom/parallel_plot/parallel_reset.ts
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/docs/user_guide/examples/extensions_example_tool.py
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#11598 Allow data models to inherit from non data models
  bokeh/core/has_props.py
  bokehjs/src/lib/base.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/util/cloneable.ts
  bokehjs/src/lib/document/defs.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/util/cloneable.ts
  bokehjs/test/unit/document/defs.ts
  bokehjs/test/unit/models/text/utils.ts
  tests/unit/bokeh/document/test_document.py
Labels: status: accepted

#11644 Actually fix clipping in SVG `<text>` nodes
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Text.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_Text.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11587__doesn't_allow_SVG_backend_to_respect_clip_paths_when_painting_text.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_Text.png
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs, tag: svg, NEEDS BACK PORT

#11650 Fix usage of external hatch patterns in visual properties
  bokehjs/src/lib/core/visuals/index.ts
  bokehjs/src/lib/core/visuals/visual.ts
  bokehjs/src/lib/models/textures/image_url_texture.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#11652 Update bokehjs' dependencies
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/test/baselines/windows/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.png
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs, NEEDS BACK PORT

#11659 Fix and improve output from Printer.string()
  bokehjs/src/lib/core/util/pretty.ts
  bokehjs/test/unit/core/util/pretty.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#11663 Changing MultiChoice shouldSort default to false
  bokehjs/src/lib/models/widgets/multichoice.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
  bokehjs/test/baselines/macos/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
  bokehjs/test/baselines/windows/Bug__in_issue_#10695__prevents_showing_MultiChoice's_dropdown_menu.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
Labels: status: accepted

#11122 Add support for basic glyph decorations
  bokeh/models/annotations/arrows.py
  bokeh/models/glyph.py
  bokeh/models/graphics.py
  bokeh/models/renderers.py
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/arrow_head.ts
  bokehjs/src/lib/models/annotations/whisker.ts
  bokehjs/src/lib/models/glyphs/arc.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/segment.ts
  bokehjs/src/lib/models/graphics/decoration.ts
  bokehjs/src/lib/models/graphics/index.ts
  bokehjs/src/lib/models/graphics/marking.ts
  bokehjs/src/lib/models/index.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/baselines/linux/Examples__should_support_Trefoil.blf
  bokehjs/test/baselines/linux/Examples__should_support_Trefoil.png
  bokehjs/test/baselines/macos/Examples__should_support_Trefoil.blf
  bokehjs/test/baselines/macos/Examples__should_support_Trefoil.png
  bokehjs/test/baselines/windows/Examples__should_support_Trefoil.blf
  bokehjs/test/baselines/windows/Examples__should_support_Trefoil.png
  bokehjs/test/integration/examples.ts
  bokehjs/test/integration/glyphs/markers.ts
  bokehjs/test/unit/api/plotting.ts
  bokehjs/test/unit/core/has_props.ts
  examples/plotting/file/trefoil.py
  tests/unit/bokeh/models/_util_models.py
Labels: type: feature, status: ready

#11664 Fix `Line` glyph rendering with index gaps
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#11665 Drop support for subtype from the protocol
  bokeh/core/types.py
  bokeh/document/util.py
  bokeh/model/model.py
  bokeh/model/util.py
  bokeh/plotting/figure.py
  bokeh/plotting/gmap.py
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/util/refs.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/models/plots/figure.ts
  bokehjs/src/lib/models/plots/index.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/test/defaults/index.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/util/refs.ts
  sphinx/source/docs/releases/3.0.0.rst
Labels: status: accepted, type: task, reso: completed, PROTOCOL

#11662 Support "pip install ."
  .github/workflows/bokeh-ci.yml
  _setup_support.py
  ci/verify_pip_install_from_sdist.sh
  setup.py
Labels: status: accepted, NEEDS BACK PORT

#11648 Use the new scoped bokehjs package in `bokeh init`
  bokehjs/src/compiler/build.ts
  tests/unit/bokeh/test_ext.py
Labels: status: accepted, NEEDS BACK PORT

#11605 Add `search_option_limit` to `MultiChoice` widget
  bokeh/models/widgets/inputs.py
  bokehjs/src/lib/models/widgets/multichoice.ts
Labels: status: ready

#11669 Create SECURITY.md
  SECURITY.md
Labels: status: accepted, type: task, reso: completed

#11668 Add information about mathjax bundle
  bokeh/embed/standalone.py
  sphinx/source/docs/user_guide/embed.rst
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/styling.rst
  sphinx/source/rst_epilog.txt
Labels: tag: component: docs, status: accepted, type: task, reso: completed, NEEDS BACK PORT

#11674 Handle `NaN`/`null` in `LabelSet` correctly
  bokeh/models/annotations/html/labels.py
  bokeh/models/annotations/labels.py
  bokehjs/src/lib/models/annotations/html/label_set.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/test/integration/annotations/label_set.ts
Labels: status: accepted, NEEDS BACK PORT

#11677 Redesign text rendering in `Text` glyph
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/graphics.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/test/baselines/linux/Examples__should_support_Sprint.png
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_-30_degree_angle.blf
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_-30_degree_angle.png
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_0_degree_angle.blf
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_0_degree_angle.png
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_30_degree_angle.blf
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_30_degree_angle.png
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_60_degree_angle.blf
  bokehjs/test/baselines/linux/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_60_degree_angle.png
  bokehjs/test/baselines/macos/Examples__should_support_Sprint.png
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_-30_degree_angle.blf
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_-30_degree_angle.png
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_0_degree_angle.blf
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_0_degree_angle.png
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_30_degree_angle.blf
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_30_degree_angle.png
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_60_degree_angle.blf
  bokehjs/test/baselines/macos/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_60_degree_angle.png
  bokehjs/test/baselines/windows/Examples__should_support_Sprint.png
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_-30_degree_angle.blf
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_-30_degree_angle.png
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_0_degree_angle.blf
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_0_degree_angle.png
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_30_degree_angle.blf
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_30_degree_angle.png
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_60_degree_angle.blf
  bokehjs/test/baselines/windows/Text_glyph__should_support_multi-line_rendering_with_different_alignments__at_60_degree_angle.png
  bokehjs/test/integration/glyphs/text.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#11639 Various bokehjs API improvements and new examples
  bokehjs/examples/hierarchical/hierarchical.ts
  bokehjs/src/lib/api/expr.ts
  bokehjs/src/lib/api/index.ts
  bokehjs/src/lib/api/linalg.ts
  bokehjs/src/lib/api/parser.ts
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/api/themes.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/test/baselines/linux/Examples__should_support_BlackbodyRadiation.blf
  bokehjs/test/baselines/linux/Examples__should_support_BlackbodyRadiation.png
  bokehjs/test/baselines/linux/Examples__should_support_NormalDistribution.blf
  bokehjs/test/baselines/linux/Examples__should_support_NormalDistribution.png
  bokehjs/test/baselines/macos/Examples__should_support_BlackbodyRadiation.blf
  bokehjs/test/baselines/macos/Examples__should_support_BlackbodyRadiation.png
  bokehjs/test/baselines/macos/Examples__should_support_NormalDistribution.blf
  bokehjs/test/baselines/macos/Examples__should_support_NormalDistribution.png
  bokehjs/test/baselines/windows/Examples__should_support_BlackbodyRadiation.blf
  bokehjs/test/baselines/windows/Examples__should_support_BlackbodyRadiation.png
  bokehjs/test/baselines/windows/Examples__should_support_NormalDistribution.blf
  bokehjs/test/baselines/windows/Examples__should_support_NormalDistribution.png
  bokehjs/test/codebase/size.ts
  bokehjs/test/integration/examples.ts
  bokehjs/test/integration/glyphs/text.ts
  bokehjs/test/integration/layouts.ts
  bokehjs/test/integration/plots.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/api/parser.ts
  bokehjs/test/unit/api/plotting.ts
  bokehjs/test/unit/core/util/eq.ts
  sphinx/source/docs/releases/3.0.0.rst
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#11512 Outsource tile management to xyzservices
  .github/workflows/bokeh-ci.yml
  _setup_support.py
  bokeh/models/plots.py
  bokeh/tile_providers.py
  ci/environment-release-build.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-downstream.yml
  environment.yml
  examples/plotting/file/airports_map.py
  examples/plotting/file/customjs_hover.py
  examples/plotting/file/tile_demo.py
  examples/plotting/file/tile_source.py
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/docs/user_guide/examples/geo_tile_source.py
  sphinx/source/docs/user_guide/examples/geo_xyzservices.py
  sphinx/source/docs/user_guide/geo.rst
  tests/unit/bokeh/models/test_plots.py
  tests/unit/bokeh/test_tile_providers.py
Labels: status: accepted

#11686 Fix WebGL marker count change
  bokehjs/src/lib/models/glyphs/webgl/buffer.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/glyphs/webgl/rect.ts
  bokehjs/test/baselines/linux/Rect_glyph__should_support_adding_new_data_point_to_existing_glyph.blf
  bokehjs/test/baselines/linux/Rect_glyph__should_support_adding_new_data_point_to_existing_glyph.png
  bokehjs/test/baselines/macos/Rect_glyph__should_support_adding_new_data_point_to_existing_glyph.blf
  bokehjs/test/baselines/macos/Rect_glyph__should_support_adding_new_data_point_to_existing_glyph.png
  bokehjs/test/baselines/windows/Rect_glyph__should_support_adding_new_data_point_to_existing_glyph.blf
  bokehjs/test/baselines/windows/Rect_glyph__should_support_adding_new_data_point_to_existing_glyph.png
  bokehjs/test/integration/glyphs/rect.ts
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#11690 update footer links
  bokeh/server/views/app_index.html
  sphinx/source/_templates/footer.html
Labels: status: accepted, reso: completed, NEEDS BACK PORT

#11692 replace deprecated CLIEngine eslint class and add cache for faster linting
  bokehjs/.gitignore
  bokehjs/make/tasks/lint.ts
  bokehjs/src/compiler/build.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#11680 Fix duplicate value change in autocomplete_input
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  tests/integration/widgets/test_autocomplete_input.py
Labels: status: accepted

#11697 Expose plotting subcoordinates API in bokehjs
  bokehjs/src/lib/api/expr.ts
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/api/linalg.ts
  bokehjs/src/lib/api/plotting.ts
  bokehjs/src/lib/core/class.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/util/math.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/models/canvas/coordinates.ts
  bokehjs/test/baselines/linux/Examples__should_support_PolarSubcoordinates.blf
  bokehjs/test/baselines/linux/Examples__should_support_PolarSubcoordinates.png
  bokehjs/test/baselines/macos/Examples__should_support_PolarSubcoordinates.blf
  bokehjs/test/baselines/macos/Examples__should_support_PolarSubcoordinates.png
  bokehjs/test/baselines/windows/Examples__should_support_PolarSubcoordinates.blf
  bokehjs/test/baselines/windows/Examples__should_support_PolarSubcoordinates.png
  bokehjs/test/integration/annotations/legend.ts
  bokehjs/test/integration/colors.ts
  bokehjs/test/integration/examples.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/util/color.ts
  examples/plotting/file/polar_subcoordinates.py
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#11699 Split up `api/plotting.ts` into `figure.ts` and `io.ts`
  bokehjs/src/lib/api/figure.ts
  bokehjs/src/lib/api/io.ts
  bokehjs/src/lib/api/plotting.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#11700 Add more bokehjs' examples under visual tests
  bokehjs/test/baselines/linux/Examples__should_support_Anscombe.blf
  bokehjs/test/baselines/linux/Examples__should_support_Anscombe.png
  bokehjs/test/baselines/linux/Examples__should_support_Burtin.blf
  bokehjs/test/baselines/linux/Examples__should_support_Burtin.png
  bokehjs/test/baselines/linux/Examples__should_support_Categorical.blf
  bokehjs/test/baselines/linux/Examples__should_support_Categorical.png
  bokehjs/test/baselines/macos/Examples__should_support_Anscombe.blf
  bokehjs/test/baselines/macos/Examples__should_support_Anscombe.png
  bokehjs/test/baselines/macos/Examples__should_support_Burtin.blf
  bokehjs/test/baselines/macos/Examples__should_support_Burtin.png
  bokehjs/test/baselines/macos/Examples__should_support_Categorical.blf
  bokehjs/test/baselines/macos/Examples__should_support_Categorical.png
  bokehjs/test/baselines/windows/Examples__should_support_Anscombe.blf
  bokehjs/test/baselines/windows/Examples__should_support_Anscombe.png
  bokehjs/test/baselines/windows/Examples__should_support_Burtin.blf
  bokehjs/test/baselines/windows/Examples__should_support_Burtin.png
  bokehjs/test/baselines/windows/Examples__should_support_Categorical.blf
  bokehjs/test/baselines/windows/Examples__should_support_Categorical.png
  bokehjs/test/integration/examples.ts
  bokehjs/test/integration/examples/anscombe.ts
  bokehjs/test/integration/examples/blackbody_radiation.ts
  bokehjs/test/integration/examples/burtin.ts
  bokehjs/test/integration/examples/categorical.ts
  bokehjs/test/integration/examples/normal_distribution.ts
  bokehjs/test/integration/examples/polar_subcoordinates.ts
  bokehjs/test/integration/examples/sprint.ts
  bokehjs/test/integration/examples/trefoil.ts
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: bokehjs

#11698 Fixed some typos and changed wording for better tone
  sphinx/source/docs/first_steps/examples/first_steps_4_grid_lines.py
  sphinx/source/docs/first_steps/examples/first_steps_4_resize_plot.py
  sphinx/source/docs/first_steps/first_steps_4.rst
Labels: tag: component: docs, status: accepted, type: task
