Repository bokeh/bokeh, pull requests merged in 2021-06, with the labels that each got.

#11325 Fix typo in AuthProvider._validate error message. login_url instead of logout_url
  bokeh/server/auth_provider.py
Labels: reso: completed, status: accepted, type: task

#11293 Added conda init command in Getting Set Up
  sphinx/source/docs/dev_guide/setup.rst
Labels: status: accepted

#11338 Bryanv/11298 release build deps
  ci/environment-release-build.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
Labels: status: accepted

#11340 Add version to json_items output
  bokeh/embed/standalone.py
  tests/unit/bokeh/embed/test_standalone.py
Labels: status: accepted

#11304 Update docs for BokehJS visual testing
  sphinx/source/docs/dev_guide/bokehjs.rst
  sphinx/source/docs/dev_guide/testing.rst
Labels: reso: completed, status: accepted, tag: component: docs, type: task

#11341 Statically type the return of `json_item()`
  bokeh/embed/bundle.py
  bokeh/embed/standalone.py
  bokeh/plotting/figure.py
  bokeh/plotting/glyph_api.py
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
  pyproject.toml
  tests/unit/bokeh/embed/test_standalone.py
  typings/bs4.pyi
Labels: status: accepted, tag: mypy, type: task

#11342 Refresh `bokehjs/package-lock.json`
  bokehjs/package-lock.json
Labels: reso: completed, status: accepted, tag: component: bokehjs, tag: component: build, type: task

#11322 Add 'experimental' note to extensions chapter
  sphinx/source/docs/user_guide/extensions.rst
Labels: status: accepted, tag: component: docs, type: task

#11350 Add -f option for conda env
  sphinx/source/docs/dev_guide/setup.rst
Labels: status: accepted

#11343 WebGL markers and rects reuse arrays and buffers
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/glyphs/webgl/buffer.ts
  bokehjs/src/lib/models/glyphs/webgl/line_gl.ts
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
  bokehjs/src/lib/models/glyphs/webgl/rect.ts
  bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts
  bokehjs/src/lib/models/glyphs/webgl/types.ts
  bokehjs/src/lib/models/glyphs/webgl/webgl_utils.ts
  bokehjs/test/baselines/linux/Rect_glyph__should_support_hatch_patterns_and_line_joins.blf
  bokehjs/test/baselines/linux/Rect_glyph__should_support_hatch_patterns_and_line_joins.png
  bokehjs/test/baselines/macos/Rect_glyph__should_support_hatch_patterns_and_line_joins.blf
  bokehjs/test/baselines/macos/Rect_glyph__should_support_hatch_patterns_and_line_joins.png
  bokehjs/test/baselines/windows/Rect_glyph__should_support_hatch_patterns_and_line_joins.blf
  bokehjs/test/baselines/windows/Rect_glyph__should_support_hatch_patterns_and_line_joins.png
  bokehjs/test/integration/glyphs/rect.ts
  bokehjs/test/integration/glyphs/webgl.ts
Labels: status: accepted, tag: component: bokehjs, tag: webgl, type: feature

#11368 Fix rendering of legends for ellipse glyph
  bokehjs/src/lib/models/glyphs/ellipse_oval.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.png
  bokehjs/test/integration/regressions.ts
Labels: NEEDS BACK PORT, status: accepted

#11370 Handle corner cases in LinearLinterpolationScale.v_compute()
  bokehjs/src/lib/models/scales/linear_interpolation_scale.ts
  bokehjs/test/unit/models/scales/linear_interpolation_scale.ts
Labels: NEEDS BACK PORT, reso: completed, status: accepted, tag: component: bokehjs, type: bug

#11297 Correctly initialize WebGL non-base marker/scatter glyphs
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/scatter.ts
Labels: status: ready, tag: component: bokehjs, tag: webgl, type: bug

#10931 Drop support for IE and legacy web browsers
  bokeh/resources.py
  bokeh/settings.py
  bokehjs/make/paths.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/tasks/test.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/compile.ts
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/less/logo.less
  bokehjs/src/lib/core/serializer.ts
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/core/util/cloneable.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/src/lib/core/util/platform.ts
  bokehjs/src/lib/core/util/pretty.ts
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/external/ie.d.ts
  bokehjs/src/lib/legacy.ts
  bokehjs/src/lib/models/glyphs/annulus.ts
  bokehjs/src/lib/polyfill.ts
  bokehjs/test/codebase/size.ts
  bokehjs/test/devtools/server.ts
  release/remote.py
  sphinx/source/docs/user_guide/concepts.rst
  tests/unit/bokeh/test_resources.py
  tests/unit/bokeh/test_settings.py
Labels: status: accepted

#11379 Fix data access layout `SpatialIndex.bounds()`
  bokeh/_testing/util/compare.py
  bokeh/util/hex.py
  bokehjs/src/lib/core/util/spatial.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11378__doesn't_allow_to_correctly_compute_bounds_when_using_MultiLine_Glyph_with_a_log_axis.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11378__doesn't_allow_to_correctly_compute_bounds_when_using_MultiLine_Glyph_with_a_log_axis.png
  bokehjs/test/baselines/macos/Bug__in_issue_#11378__doesn't_allow_to_correctly_compute_bounds_when_using_MultiLine_Glyph_with_a_log_axis.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#11378__doesn't_allow_to_correctly_compute_bounds_when_using_MultiLine_Glyph_with_a_log_axis.png
  bokehjs/test/baselines/windows/Bug__in_issue_#11378__doesn't_allow_to_correctly_compute_bounds_when_using_MultiLine_Glyph_with_a_log_axis.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#11378__doesn't_allow_to_correctly_compute_bounds_when_using_MultiLine_Glyph_with_a_log_axis.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/util/spatial.ts
Labels: NEEDS BACK PORT, status: accepted

#11385 app_index.html missing quotes in href attribute
  bokeh/server/views/app_index.html
Labels: NEEDS BACK PORT, status: accepted

#11387 Use an exact extension's version in a CDN URL
  bokeh/embed/bundle.py
  tests/unit/bokeh/embed/test_bundle.py
Labels: NEEDS BACK PORT, status: accepted

#11390 Add support for vertically oriented button groups
  bokeh/models/widgets/groups.py
  bokeh/models/widgets/sliders.py
  bokeh/models/widgets/widget.py
  bokehjs/src/less/buttons.less
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/src/lib/models/widgets/button_group.ts
  bokehjs/src/lib/models/widgets/oriented_control.ts
  bokehjs/src/lib/models/widgets/widget.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_CheckboxButtonGroup_in_vertical_orientation.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_CheckboxButtonGroup_in_vertical_orientation.png
  bokehjs/test/baselines/linux/Widgets__should_allow_RadioButtonGroup_in_vertical_orientation.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_RadioButtonGroup_in_vertical_orientation.png
  bokehjs/test/baselines/macos/Widgets__should_allow_CheckboxButtonGroup_in_vertical_orientation.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_CheckboxButtonGroup_in_vertical_orientation.png
  bokehjs/test/baselines/macos/Widgets__should_allow_RadioButtonGroup_in_vertical_orientation.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_RadioButtonGroup_in_vertical_orientation.png
  bokehjs/test/baselines/windows/Widgets__should_allow_CheckboxButtonGroup_in_vertical_orientation.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_CheckboxButtonGroup_in_vertical_orientation.png
  bokehjs/test/baselines/windows/Widgets__should_allow_RadioButtonGroup_in_vertical_orientation.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_RadioButtonGroup_in_vertical_orientation.png
  bokehjs/test/integration/widgets.ts
  examples/models/file/widgets.py
Labels: status: accepted

#11393 11392 address lgtm issues
  bokeh/_testing/plugins/file_server.py
  examples/embed/arguments/flask_server.py
  examples/howto/server_auth/auth.py
  tests/integration/widgets/test_range_slider.py
Labels: status: accepted
