Repository bokeh/bokeh, pull requests merged in 2021-12, with the labels that each got.

#11849 Remove temporary WebGL circle fix
  bokehjs/src/lib/models/glyphs/webgl/markers.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: webgl

#11660 Update docs for math text styling
  examples/plotting/file/latex_blackbody_radiation.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_axis_labels.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_axis_labels_titles_labels.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_tick_labels.py
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/styling.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#11815 Add support for math text to slider widgets
  bokeh/embed/bundle.py
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/src/lib/models/widgets/div.ts
  bokehjs/src/lib/models/widgets/markup.ts
  bokehjs/src/lib/models/widgets/paragraph.ts
  bokehjs/src/lib/models/widgets/widget.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_Slider_with_math_text_string_on_title.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Slider_with_math_text_string_on_title.png
  bokehjs/test/baselines/macos/Widgets__should_allow_Slider_with_math_text_string_on_title.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_Slider_with_math_text_string_on_title.png
  bokehjs/test/baselines/windows/Widgets__should_allow_Slider_with_math_text_string_on_title.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_Slider_with_math_text_string_on_title.png
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/models/widgets/markup.ts
Labels: status: accepted, type: task, reso: completed, tag: MathText

#11861 update sliders baselines
  bokehjs/test/baselines/linux/Widgets__should_allow_Slider_with_math_text_string_on_title.png
  bokehjs/test/baselines/macos/Widgets__should_allow_Slider_with_math_text_string_on_title.blf
  bokehjs/test/baselines/macos/Widgets__should_allow_Slider_with_math_text_string_on_title.png
  bokehjs/test/baselines/windows/Widgets__should_allow_Slider_with_math_text_string_on_title.blf
  bokehjs/test/baselines/windows/Widgets__should_allow_Slider_with_math_text_string_on_title.png
Labels: status: accepted, type: task, reso: completed, tag: MathText

#11867 Pin to django 3.x
  ci/environment-test-3.10.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
Labels: status: WIP

#11858 More LaTeX examples
  examples/app/duffing_oscillator.py
  examples/plotting/file/schrodinger.py
  sphinx/source/_images/gallery/schrodinger.png
  sphinx/source/docs/gallery.json
Labels: status: accepted, type: task, reso: completed, tag: component: examples, tag: MathText

#11859 Update docs for Slider, RangeSlider
  bokeh/models/widgets/sliders.py
  sphinx/source/docs/user_guide/examples/styling_math_text_latex_slider_widget_title.py
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/styling.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: MathText

#11874 Update bokeh-release-build.yml
  .github/workflows/bokeh-release-build.yml
Labels: type: task, tag: component: build, tag: CI

#11842 Add block glyph
  bokeh/models/glyphs.py
  bokeh/plotting/glyph_api.py
  bokeh/sphinxext/bokeh_plot.py
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/models/glyphs/block.ts
  bokehjs/src/lib/models/glyphs/hbar.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/lrtb.ts
  bokehjs/src/lib/models/glyphs/quad.ts
  bokehjs/src/lib/models/glyphs/vbar.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Block.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Block.png
  bokehjs/test/baselines/macos/Glyph_models__should_support_Block.blf
  bokehjs/test/baselines/macos/Glyph_models__should_support_Block.png
  bokehjs/test/baselines/windows/Glyph_models__should_support_Block.blf
  bokehjs/test/baselines/windows/Glyph_models__should_support_Block.png
  bokehjs/test/integration/glyphs/glyphs.ts
  examples/reference/models/Block.py
  sphinx/source/docs/reference/models/glyphs/block.rst
  sphinx/source/docs/user_guide/examples/plotting_rectangles_block.py
  sphinx/source/docs/user_guide/examples/plotting_rectangles_quad.py
  sphinx/source/docs/user_guide/examples/plotting_rectangles_rect.py
  sphinx/source/docs/user_guide/plotting.rst
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs, tag: API: models, tag: API: plotting, tag: API: JS

#11878 Port schrodinger example to bokehjs
  bokehjs/src/lib/api/expr.ts
  bokehjs/src/lib/api/linalg.ts
  bokehjs/src/lib/core/util/math.ts
  bokehjs/test/baselines/linux/Examples__should_support_Schrodinger.blf
  bokehjs/test/baselines/linux/Examples__should_support_Schrodinger.png
  bokehjs/test/baselines/macos/Examples__should_support_Schrodinger.blf
  bokehjs/test/baselines/macos/Examples__should_support_Schrodinger.png
  bokehjs/test/baselines/windows/Examples__should_support_Schrodinger.blf
  bokehjs/test/baselines/windows/Examples__should_support_Schrodinger.png
  bokehjs/test/integration/examples/schrodinger.ts
  bokehjs/test/unit/api/parser.ts
  bokehjs/test/unit/core/util/math.ts
Labels: status: accepted, type: task, reso: completed, tag: component: examples, tag: component: bokehjs

#11856 Docker image build and use
  .github/workflows/bokeh-docker-build.yml
  ci/docker/docker_run.sh
  ci/docker/entrypoint.sh
Labels: status: accepted

#11869 Add final 2 LaTeX examples: Bessel functions and LaTeX labels
  examples/models/file/latex_labels.py
  examples/plotting/file/bessel.py
  sphinx/source/_images/gallery/bessel.png
  sphinx/source/docs/gallery.json
Labels: status: accepted, type: task, reso: completed, tag: component: examples, tag: MathText

#11884 Add regression test for updating webgl line
  bokehjs/test/baselines/linux/Bug__in_issue_#8346__should_support_updating_line.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#8346__should_support_updating_line.png
  bokehjs/test/baselines/macos/Bug__in_issue_#8346__should_support_updating_line.blf
  bokehjs/test/baselines/macos/Bug__in_issue_#8346__should_support_updating_line.png
  bokehjs/test/baselines/windows/Bug__in_issue_#8346__should_support_updating_line.blf
  bokehjs/test/baselines/windows/Bug__in_issue_#8346__should_support_updating_line.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#11890 Update baselines on windows
  bokehjs/test/baselines/windows/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.png
Labels: status: accepted

#11864 Add policy to find adjacent nodes by selecting node
  bokeh/models/graphs.py
  bokehjs/src/lib/models/graphs/graph_hit_test_policy.ts
  bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts
  examples/models/file/graphs.py
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/docs/user_guide/examples/graph_interaction_edgeslinkednodes.py
  sphinx/source/docs/user_guide/examples/graph_interaction_nodesadjacentnodes.py
  sphinx/source/docs/user_guide/examples/graph_interaction_nodeslinkededges.py
  sphinx/source/docs/user_guide/graph.rst
Labels: status: accepted

#11888 Allow to render data URL images in one iteration
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/core/util/image.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/test/integration/glyphs/markers.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#11894 Remove katex example
  examples/custom/README.md
  examples/custom/wrapped_extension_base/README.md
  examples/custom/wrapped_extension_base/latex_extension_base.py
  examples/custom/wrapped_extension_base/latex_label/.gitignore
  examples/custom/wrapped_extension_base/latex_label/__init__.py
  examples/custom/wrapped_extension_base/latex_label/bokeh.ext.json
  examples/custom/wrapped_extension_base/latex_label/index.ts
  examples/custom/wrapped_extension_base/latex_label/latex_label.ts
  examples/custom/wrapped_extension_base/latex_label/styles/css.d.ts
  examples/custom/wrapped_extension_base/latex_label/styles/latex_label.less
  examples/custom/wrapped_extension_full/README.md
  examples/custom/wrapped_extension_full/latex_extension_full.py
  examples/custom/wrapped_extension_full/latex_label/.gitignore
  examples/custom/wrapped_extension_full/latex_label/LICENSE.txt
  examples/custom/wrapped_extension_full/latex_label/__init__.py
  examples/custom/wrapped_extension_full/latex_label/bokeh.ext.json
  examples/custom/wrapped_extension_full/latex_label/index.ts
  examples/custom/wrapped_extension_full/latex_label/latex_label.ts
  examples/custom/wrapped_extension_full/latex_label/package-lock.json
  examples/custom/wrapped_extension_full/latex_label/package.json
  examples/custom/wrapped_extension_full/latex_label/styles/css.d.ts
  examples/custom/wrapped_extension_full/latex_label/styles/latex_label.less
  examples/custom/wrapped_extension_full/latex_label/tsconfig.json
  sphinx/source/docs/user_guide/examples/extensions_example_latex.py
  sphinx/source/docs/user_guide/extensions.rst
  sphinx/source/docs/user_guide/extensions_gallery/latex.rst
Labels: tag: component: docs, status: ready, reso: completed, tag: component: examples

#11891 Improve initial import time
  bokeh/core/json_encoder.py
  bokeh/core/properties.py
  bokeh/core/property/bases.py
  bokeh/core/property/pd.py
  bokeh/core/property/wrappers.py
  bokeh/core/templates.py
  bokeh/document/events.py
  bokeh/embed/elements.py
  bokeh/embed/standalone.py
  bokeh/embed/wrappers.py
  bokeh/models/glyph.py
  bokeh/models/glyphs.py
  bokeh/models/sources.py
  bokeh/models/util/structure.py
  bokeh/plotting/_decorators.py
  bokeh/plotting/_plot.py
  bokeh/plotting/_renderer.py
  bokeh/server/tornado.py
  bokeh/util/serialization.py
  bokehjs/package-lock.json
  sphinx/source/docs/releases/3.0.0.rst
  tests/codebase/test_no_pandas_common.py
  tests/unit/bokeh/core/property/test_pd.py
  tests/unit/bokeh/models/test_defaults.py
Labels: status: accepted

#11865 Color.lighten() and Color.darken() using RGB instead of HSL
  bokeh/colors/color.py
  bokeh/colors/hsl.py
  tests/unit/bokeh/colors/test_color__colors.py
Labels: status: WIP

#11872 Added docstrings on app\examples
  examples/app/clustering/main.py
  examples/app/crossfilter/main.py
  examples/app/dash/main.py
  examples/app/export_csv/main.py
  examples/app/faces/README.md
  examples/app/faces/main.py
  examples/app/gapminder/main.py
  examples/app/image_blur.py
  examples/app/line_on_off.py
  examples/app/movies/main.py
  examples/app/ohlc/main.py
  examples/app/population.py
  examples/app/selection_histogram.py
  examples/app/simple_hdf5/main.py
  examples/app/spectrogram/main.py
  examples/app/surface3d/main.py
  examples/app/taylor.py
  examples/app/weather/main.py
Labels: status: ready

#11866 Cleaner white space/indentation in templates
  bokeh/core/_templates/autoload_request_tag.html
  bokeh/core/_templates/autoload_tag.html
  bokeh/core/_templates/css_resources.html
  bokeh/core/_templates/file.html
  bokeh/core/_templates/js_resources.html
  bokeh/core/_templates/notebook_load.html
  bokeh/core/_templates/plot_div.html
  bokeh/core/_templates/script_tag.html
  bokeh/core/templates.py
  sphinx/source/docs/user_guide/embed.rst
  tests/unit/bokeh/core/test_templates.py
Labels: status: accepted

#11905 Add metadata to widgets.py
  examples/models/file/widgets.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#11907 Fix type issues after upgrading to mypy 0.920
  bokeh/server/server.py
  ci/environment-test-3.10.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
  tests/test_examples.py
Labels: status: accepted, type: task, reso: completed, tag: mypy

#11912 Cap node version below v17
  environment.yml
Labels: status: accepted, reso: completed, tag: component: build, tag: component: bokehjs

#11913 add plot.remove_tools() method
  bokeh/models/plots.py
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/test/unit/models/plots/plot.ts
  sphinx/source/docs/first_steps/first_steps_4.rst
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/docs/user_guide/tools.rst
  tests/unit/bokeh/models/test_plots.py
Labels: status: accepted

#11896 Metadata for examples/plotting/file/airports_map.py
  examples/plotting/file/airports_map.py
Labels: status: accepted

#11903 Md files checking and updating
  examples/README.md
  examples/models/README.md
  examples/plotting/README.md
Labels: status: accepted

#11918 Make auto-hidden toolbars' behaviour more robust
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/tools/toolbar_base.ts
  bokehjs/test/unit/models/tools/toolbar_base.ts
Labels: status: accepted

#11919 Require nodejs 16.* LTS for dev and testing
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokehjs-ci.yml
  bokehjs/package.json
  ci/environment-build.yml
  ci/environment-release-build.yml
  ci/environment-release-deploy.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.7.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/install_node_modules.sh
  conda.recipe/meta.yaml
  environment.yml
  sphinx/source/docs/dev_guide/setup.rst
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs, tag: codebase

#11920 Fail bokehjs' CI jobs if repository gets dirty
  .github/workflows/bokehjs-ci.yml
  bokehjs/package-lock.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#11914 Add Tol palettes for accessibility
  bokeh/palettes.py
  bokehjs/src/lib/api/palettes.ts
  bokehjs/test/codebase/size.ts
  examples/plotting/file/bar_colormapped.py
  examples/plotting/file/bar_colors.py
  examples/plotting/file/bar_stacked.py
  examples/plotting/file/eclipse.py
  examples/plotting/file/image.py
  examples/plotting/file/image_alpha.py
  examples/plotting/file/stacked_area.py
  sphinx/source/_images/gallery/bar_colormapped.png
  sphinx/source/_images/gallery/bar_colors.png
  sphinx/source/_images/gallery/bar_stacked.png
  sphinx/source/_images/gallery/eclipse.png
  sphinx/source/_images/gallery/image.png
  sphinx/source/_images/gallery/stacked_area.png
  sphinx/source/docs/user_guide/examples/categorical_bar_colormapped.py
  sphinx/source/docs/user_guide/examples/categorical_bar_colors.py
  sphinx/source/docs/user_guide/examples/categorical_bar_stacked.py
  sphinx/source/docs/user_guide/examples/categorical_bar_stacked_hover.py
  sphinx/source/docs/user_guide/examples/plotting_image.py
Labels: status: accepted

#11921 Test bokehjs' palettes and reduce their size
  bokehjs/src/lib/api/palettes.ts
  bokehjs/src/lib/core/util/matrix.ts
  bokehjs/test/baselines/linux/Palettes__should_support_Bokeh_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_Bokeh_color_schemes.png
  bokehjs/test/baselines/linux/Palettes__should_support_Brewer_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_Brewer_color_schemes.png
  bokehjs/test/baselines/linux/Palettes__should_support_Colorblind_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_Colorblind_color_schemes.png
  bokehjs/test/baselines/linux/Palettes__should_support_D3_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_D3_color_schemes.png
  bokehjs/test/baselines/linux/Palettes__should_support_MPL_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_MPL_color_schemes.png
  bokehjs/test/baselines/linux/Palettes__should_support_Tol_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_Tol_color_schemes.png
  bokehjs/test/baselines/linux/Palettes__should_support_n=256_color_schemes.blf
  bokehjs/test/baselines/linux/Palettes__should_support_n=256_color_schemes.png
  bokehjs/test/framework.ts
  bokehjs/test/integration/palettes.ts
Labels: tag: component: tests, status: accepted, type: task, tag: component: bokehjs, tag: codebase
