Repository bokeh/bokeh, pull requests merged in 2022-08, with the labels that each got.

#12281 Respect the current theme in `bokeh.io.export` APIs
  bokeh/document/locking.py
  bokeh/io/doc.py
  bokeh/io/export.py
  pyproject.toml
  tests/unit/bokeh/document/test_callbacks__document.py
  tests/unit/bokeh/io/test_export.py
  typings/ipykernel/__init__.pyi
  typings/jupyter_core/__init__.pyi
  typings/selenium/__init__.pyi
  typings/selenium/webdriver/__init__.pyi
  typings/selenium/webdriver/chrome/__init__.pyi
  typings/selenium/webdriver/common/__init__.pyi
  typings/selenium/webdriver/firefox/__init__.pyi
  typings/selenium/webdriver/remote/__init__.pyi
  typings/selenium/webdriver/safari/__init__.pyi
  typings/selenium/webdriver/support/__init__.pyi
Labels: status: accepted

#11705 Include `Circle` glyph radius in computation of bounds
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10362__disallows_updating_layout_when_changing_axis_label.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10809__prevents_repaint_of_resized_layoutable_renderers.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11367__doesn't_allow_to_render_legend_for_ellipse_glyph.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11704__doesn't_allow_computation_of_tight_bounds_for_circles.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11704__doesn't_allow_computation_of_tight_bounds_for_circles.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11704__doesn't_allow_inclusion_of_circle_radius_in_bounds_computations.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11704__doesn't_allow_inclusion_of_circle_radius_in_bounds_computations.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_above_frame_in_horizontal_(auto)_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_above_frame_in_horizontal_(auto)_orientation_with_height=50px.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_above_frame_in_vertical_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_below_frame_in_horizontal_(auto)_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_below_frame_in_horizontal_(auto)_orientation_with_height=50px.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_below_frame_in_vertical_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_left_of_frame_in_horizontal_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_left_of_frame_in_vertical_(auto)_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_left_of_frame_in_vertical_(auto)_orientation_with_width=50px.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_right_of_frame_in_horizontal_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_right_of_frame_in_vertical_(auto)_orientation.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_allow_to_be_placed_right_of_frame_in_vertical_(auto)_orientation_with_width=50px.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_CategoricalColorMapper.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_EqHistColorMapper.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_LinearColorMapper.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_LogColorMapper.png
  bokehjs/test/baselines/linux/Color_mapping__with_multiple_domains__should_work_after_selection.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#11077 Invalidate plot layout in more cases
  bokehjs/src/lib/models/annotations/base_color_bar.ts
  bokehjs/src/lib/models/canvas/cartesian_frame.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11033__prevents_an_update_of_plot_layout_after_adding_an_axis.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11033__prevents_an_update_of_plot_layout_after_adding_an_axis.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12285 Split up too long lines after flake8 upgrade
  bokeh/settings.py
Labels: type: bug, status: accepted, reso: completed, tag: codebase

#12283 Combine alpha values by multiplying together
  bokeh/colors/color.py
  bokeh/core/property/color.py
  bokeh/palettes.py
  bokehjs/src/lib/core/util/color.ts
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_#RRGGBBAA_colors.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_#RRGGBBAA_colors.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_#RRGGBB_colors.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_#RRGGBB_colors.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_32-bit_unsigned_integers.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_32-bit_unsigned_integers.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_RGBA_tuples.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_RGBA_tuples.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_RGB_tuples.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_RGB_tuples.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_named_colors.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_named_colors.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_other_CSS4_colors.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_other_CSS4_colors.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_rgb(r_g_b)_colors.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_rgb(r_g_b)_colors.png
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_rgb(r_g_b___a)_colors.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_arrays_of_rgb(r_g_b___a)_colors.png
  bokehjs/test/baselines/linux/Color_support__should_allow_float_N,_3__arrays.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_float_N,_3__arrays.png
  bokehjs/test/baselines/linux/Color_support__should_allow_float_N,_4__arrays.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_float_N,_4__arrays.png
  bokehjs/test/baselines/linux/Color_support__should_allow_object_N__arrays.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_object_N__arrays.png
  bokehjs/test/baselines/linux/Color_support__should_allow_uint32_N__arrays.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_uint32_N__arrays.png
  bokehjs/test/baselines/linux/Color_support__should_allow_uint8_N,_3__arrays.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_uint8_N,_3__arrays.png
  bokehjs/test/baselines/linux/Color_support__should_allow_uint8_N,_4__arrays.blf
  bokehjs/test/baselines/linux/Color_support__should_allow_uint8_N,_4__arrays.png
  bokehjs/test/baselines/linux/Color_support__should_combine_alpha_for_line,_fill_and_hatch_on_all_output_backends.blf
  bokehjs/test/baselines/linux/Color_support__should_combine_alpha_for_line,_fill_and_hatch_on_all_output_backends.png
  bokehjs/test/baselines/linux/ImageRGBA_glyph__should_support_combine_alpha.blf
  bokehjs/test/baselines/linux/ImageRGBA_glyph__should_support_combine_alpha.png
  bokehjs/test/integration/colors.ts
  bokehjs/test/integration/glyphs/images.ts
  bokehjs/test/unit/core/util/color.ts
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/docs/user_guide/styling.rst
  tests/unit/bokeh/colors/test_color__colors.py
  tests/unit/bokeh/core/property/test_color__property.py
  tests/unit/bokeh/test_palettes.py
Labels: status: accepted

#12286 Save CI docs as artifact
  .github/workflows/bokeh-ci.yml
  ci/build_docs.sh
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: CI

#12287 Add support for text outline color
  bokeh/core/property_mixins.py
  bokeh/models/annotations/html/labels.py
  bokehjs/src/lib/core/graphics.ts
  bokehjs/src/lib/core/property_mixins.ts
  bokehjs/src/lib/core/visuals/text.ts
  bokehjs/src/lib/models/annotations/html/label_set.ts
  bokehjs/src/lib/models/annotations/html/text_annotation.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Text_with_text_outline_color.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Text_with_text_outline_color.png
  bokehjs/test/integration/glyphs/glyphs.ts
  pyproject.toml
  tests/unit/bokeh/models/_util_models.py
Labels: status: accepted

#12289 grammatically updated the tech docs
  sphinx/source/docs/user_guide.rst
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#12290 Update codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12293 Add post install status to bokeh-release-build
  .github/workflows/bokeh-release-build.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12284 Contouring docs
  bokeh/colors/color.py
  bokeh/models/annotations/legends.py
  bokeh/models/contour_renderer.py
  bokeh/plotting/contour.py
  examples/app/README.md
  examples/app/contour_animated.py
  examples/plotting/file/contour.py
  sphinx/source/_images/gallery/contour.png
  sphinx/source/conf.py
  sphinx/source/docs/examples.rst
  sphinx/source/docs/examples/models.rst
  sphinx/source/docs/examples/plotting.rst
  sphinx/source/docs/gallery.json
  sphinx/source/docs/reference/models/contour_renderer.rst
  sphinx/source/docs/reference/plotting/contour.rst
  sphinx/source/docs/user_guide.rst
  sphinx/source/docs/user_guide/examples/contour_polar.py
  sphinx/source/docs/user_guide/examples/contour_simple.py
  sphinx/source/docs/user_guide/specialized.rst
  sphinx/source/docs/user_guide/specialized/contour.rst
Labels: tag: component: docs, status: ready, type: task, tag: contour

#12276 Introduce `canvas` coordinate units to remove `for_hover`, etc.
  bokeh/core/enums.py
  bokeh/models/annotations/arrows.py
  bokeh/models/annotations/geometry.py
  bokeh/models/annotations/html/labels.py
  bokeh/models/annotations/labels.py
  bokeh/models/tools.py
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/models/annotations/arrow.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/html/label.ts
  bokehjs/src/lib/models/annotations/html/label_set.ts
  bokehjs/src/lib/models/annotations/label.ts
  bokehjs/src/lib/models/annotations/label_set.ts
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/src/lib/models/annotations/span.ts
  bokehjs/src/lib/models/annotations/upper_lower.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts
  bokehjs/test/assets/json/issue11930.json
  bokehjs/test/unit/core/util/bbox.ts
  tests/unit/bokeh/core/test_enums.py
Labels: type: feature, status: ready

#12294 Cleanup / condense project configs
  pyproject.toml
  setup.cfg
Labels: tag: component: tests, status: accepted, type: task, tag: component: build

#12295 Resolve selenium 5.x webdriver related deprecations
  bokeh/io/webdriver.py
  typings/selenium/webdriver/firefox/webdriver.pyi
Labels: status: accepted

#12299 Make `FileInput` an input widget and style it properly
  bokeh/models/widgets/inputs.py
  bokehjs/make/tasks/test.ts
  bokehjs/src/less/buttons.less
  bokehjs/src/less/widgets/inputs.less
  bokehjs/src/lib/models/widgets/file_input.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_FileInput.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_FileInput.png
  bokehjs/test/devtools/devtools.ts
  examples/plotting/file/file_input.py
Labels: status: accepted

#12296 Add support for `AutocompleteInput(min_characters=0)`
  bokeh/models/widgets/inputs.py
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  bokehjs/src/lib/models/widgets/multichoice.ts
  bokehjs/src/lib/models/widgets/multiselect.ts
  bokehjs/src/lib/models/widgets/numeric_input.ts
  bokehjs/src/lib/models/widgets/selectbox.ts
  bokehjs/src/lib/models/widgets/text_input.ts
  bokehjs/src/lib/models/widgets/text_like_input.ts
  bokehjs/src/lib/models/widgets/textarea_input.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_AutocompleteInput_with_min_characters==0_and_completions_showed_on_focusin.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_AutocompleteInput_with_min_characters==0_and_completions_showed_on_focusin.png
  bokehjs/test/integration/widgets.ts
  examples/models/file/widgets.py
Labels: status: accepted

#12302 BokehJS maths improvements
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/src/lib/models/grids/grid.ts
  bokehjs/src/lib/models/mappers/log_color_mapper.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/scales/log_scale.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#12298 Grammatical fixes and improvisations
  README.md
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12304 Add `py.typed` marker file for mypy
  MANIFEST.in
  bokeh/py.typed
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: mypy

#12305 Remove double colons from field lists
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  environment.yml
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12307 Preserve original line endings in code quality tests
  .github/workflows/bokeh-ci.yml
  bokeh/sampledata/_data/unemployment1948.csv
  bokeh/sampledata/_data/us_marriages_divorces.csv
  bokeh/themes/_caliber.py
  bokeh/themes/_contrast.py
  bokeh/themes/_dark_minimal.py
  bokeh/themes/_light_minimal.py
  bokeh/themes/_night_sky.py
  examples/app/apply_theme.py
  examples/app/movies/razzies-clean.csv
  tests/codebase/test_code_quality.py
  tests/unit/bokeh/command/subcommands/apps/apply_theme.py
Labels: status: accepted, type: task, reso: completed, tag: codebase

#12211 Alt-text Sprint PR
  bokeh/core/property_mixins.py
  bokeh/models/tools.py
  sphinx/source/_images/ridgeplot_jupyter_lab.png
  sphinx/source/docs/gallery.json
  sphinx/source/docs/gallery.rst
  sphinx/source/docs/includes/hero.txt
  sphinx/source/docs/user_guide/compat.rst
  sphinx/source/docs/user_guide/data.rst
  sphinx/source/docs/user_guide/export.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/docs/user_guide/layout.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12306 Streamline / modernize build system
  .flake8
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
  .github/workflows/composite/test-setup/action.yml
  MANIFEST.in
  _setup_support.py
  bokeh/__init__.py
  bokeh/_version.py
  bokeh/resources.py
  bokeh/sphinxext/bokeh_roles.py
  bokeh/util/version.py
  ci/build_bokehjs.sh
  ci/build_conda_pacakge.sh
  ci/environment-build.yml
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  ci/install_bokeh_package.sh
  ci/unpack_artifacts.sh
  classifiers.txt
  conda.recipe/bld.bat
  conda.recipe/build.sh
  conda.recipe/meta.yaml
  environment.yml
  pyproject.toml
  release/config.py
  requirements.txt
  setup.py
  sphinx/source/docs/dev_guide/setup.rst
  tests/.coveragerc
  tests/conftest.py
  tests/unit/bokeh/core/test_templates.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/test___init__.py
  tests/unit/bokeh/test_resources.py
  tests/unit/bokeh/util/test_version.py
  versioneer.py
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: build, tag: CI, tag: codebase

#12317 More CI work (part 1)
  .github/workflows/bokeh-ci.yml
  ci/build_docs.sh
  ci/install_downstream_packages.sh
Labels: status: accepted, reso: completed, tag: CI

#12319 More CI work (part 2)
  .github/workflows/bokeh-ci.yml
  bokeh/__main__.py
  bokeh/sphinxext/bokeh_roles.py
  ci/build_docs.sh
  ci/environment-test-downstream.yml
  ci/examples.log
  ci/install_node_modules.sh
  release/build.py
  setup.py
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: CI

#12320 More CI work (part 3)
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-release-build.yml
  ci/build_bokehjs.sh
  release/build.py
  release/stages.py
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: CI

#12318 Update dev setup docs
  sphinx/source/docs/dev_guide/setup.rst
Labels: tag: component: docs, status: accepted, type: task

#12314 Fail gracefully when serializing unsupported builtins
  bokeh/core/serialization.py
  tests/unit/bokeh/core/test_serialization.py
Labels: status: accepted

#11949 Replace manual text handling in `Legend` with `TextBox`
  bokehjs/src/lib/models/annotations/legend.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#12324 More CI work (part 5)
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
  bokehjs/make/tasks/default.ts
  bokehjs/make/tasks/index.ts
  bokehjs/make/tasks/install.ts
  release/__main__.py
  release/build.py
  release/config.py
  release/deploy.py
  release/system.py
  release/util.py
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: CI

#12325 add deprecated FuncTickFormatter
  bokeh/models/formatters.py
  tests/unit/bokeh/models/test_formatters.py
Labels: status: accepted

#12327 Backport current sphinx theme to 2.4.3
  sphinx/Makefile
  sphinx/docserver.py
  sphinx/source/_static/custom.css
  sphinx/source/_static/custom.js
  sphinx/source/_templates/docs-navbar.html
  sphinx/source/_templates/footer.html
  sphinx/source/_templates/layout.html
  sphinx/source/_templates/navbar-logo.html
  sphinx/source/_templates/sections/footer.html
  sphinx/source/conf.py
  sphinx/source/docs/dev_guide.rst
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/first_steps.rst
  sphinx/source/docs/first_steps/installation.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/export.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/index.rst
  sphinx/switcher.json
  sphinx/versions.json
  tests/codebase/test_json.py
Labels: tag: component: docs, type: task

#12326 clean up MANIFEST.in
  MANIFEST.in
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: build

#12333 Simplify conda envs and scripts
  .dockerignore
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-docker-build.yml
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
  .github/workflows/composite/test-setup/action.yml
  conda.recipe/run_test.py
  conda/environment-build.yml
  conda/environment-release-build.yml
  conda/environment-release-deploy.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  conda/recipe/meta.yaml
  environment.yml
  pyproject.toml
  release/build.py
  scripts/__init__.py
  scripts/ci/build_conda_pacakge.sh
  scripts/ci/build_docs.sh
  scripts/ci/install_downstream_packages.sh
  scripts/ci/install_node_modules.sh
  scripts/ci/run_downstream_tests.sh
  scripts/ci/verify_pip_install_from_sdist.sh
  scripts/docker/Dockerfile
  scripts/docker/bokeh_docker_build.sh
  scripts/docker/bokeh_docker_test.sh
  scripts/docker/docker_run.sh
  scripts/docker/entrypoint.sh
  scripts/interactive_tester.py
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/dev_guide/pull_requests.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/dev_guide/testing.rst
Labels: status: accepted

#12330 Improve compatibility with Python 3.10.6 in tests
  conda/environment-test-3.10.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  tests/support/plugins/file_server.py
  tests/support/plugins/project.py
Labels: type: bug, tag: component: tests, status: ready

#12329 Provide method to modify Server before start
  .github/workflows/bokeh-ci.yml
  bokeh/command/subcommands/serve.py
Labels: type: feature, status: accepted, reso: completed, tag: component: server

#12341 Move typings under src
  pyproject.toml
  src/typings/IPython/__init__.pyi
  src/typings/IPython/core/__init__.pyi
  src/typings/IPython/core/getipython.pyi
  src/typings/IPython/core/history.pyi
  src/typings/IPython/core/interactiveshell.pyi
  src/typings/IPython/display.pyi
  src/typings/bs4.pyi
  src/typings/flaky.pyi
  src/typings/ipykernel/__init__.pyi
  src/typings/ipykernel/comm/__init__.pyi
  src/typings/ipykernel/comm/comm.pyi
  src/typings/jupyter_core/__init__.pyi
  src/typings/jupyter_core/paths.pyi
  src/typings/psutil.pyi
  src/typings/selenium/__init__.pyi
  src/typings/selenium/common/exceptions.pyi
  src/typings/selenium/webdriver/__init__.pyi
  src/typings/selenium/webdriver/chrome/__init__.pyi
  src/typings/selenium/webdriver/chrome/options.pyi
  src/typings/selenium/webdriver/chrome/webdriver.pyi
  src/typings/selenium/webdriver/common/__init__.pyi
  src/typings/selenium/webdriver/common/action_chains.pyi
  src/typings/selenium/webdriver/common/by.pyi
  src/typings/selenium/webdriver/common/keys.pyi
  src/typings/selenium/webdriver/firefox/__init__.pyi
  src/typings/selenium/webdriver/firefox/firefox_binary.pyi
  src/typings/selenium/webdriver/firefox/options.pyi
  src/typings/selenium/webdriver/firefox/webdriver.pyi
  src/typings/selenium/webdriver/remote/__init__.pyi
  src/typings/selenium/webdriver/remote/webdriver.pyi
  src/typings/selenium/webdriver/remote/webelement.pyi
  src/typings/selenium/webdriver/safari/__init__.pyi
  src/typings/selenium/webdriver/safari/webdriver.pyi
  src/typings/selenium/webdriver/support/__init__.pyi
  src/typings/selenium/webdriver/support/expected_conditions.pyi
  src/typings/selenium/webdriver/support/wait.pyi
  tests/codebase/test_isort.py
Labels: status: accepted, type: task, reso: completed

#12337 Add package validation helper
  src/bokeh/util/package.py
  tests/unit/bokeh/util/test_package.py
Labels: status: accepted, type: task, reso: completed

#12344 Fix flake8 bokeh -> src/bokeh after PR #12338
  tests/codebase/test_flake8.py
Labels: type: bug, tag: component: tests, status: accepted, reso: completed
