Repository bokeh/bokeh, pull requests merged in 2022-03, with the labels that each got.

#12027 Upgrade TypeScript to version 4.6
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/core/util/svg.ts
Labels: status: accepted, type: task, reso: completed, tag: component: build

#12028 Set up `asyncio_mode` to silence deprecation warnings
  setup.cfg
Labels: tag: component: tests, status: accepted, type: task, reso: completed

#12030 Add support for `np.array(..., dtype="bool")`
  bokeh/core/serialization.py
  bokeh/util/serialization.py
  bokehjs/src/lib/core/serialization/reps.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/buffer.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/test/unit/core/util/ndarray.ts
  tests/unit/bokeh/core/test_serialization.py
  tests/unit/bokeh/util/test_util__serialization.py
Labels: type: feature, status: accepted, reso: completed

#11992 Hover tooltips for Patch and Areas
  bokehjs/examples/hover/hover.ts
  bokehjs/src/lib/models/glyphs/harea.ts
  bokehjs/src/lib/models/glyphs/varea.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
Labels: status: accepted

#12036 Clarify RenderRoot for components
  bokeh/embed/__init__.py
  bokeh/embed/standalone.py
  bokeh/embed/util.py
  examples/plotting/file/latex_normal_distribution.py
  tests/unit/bokeh/embed/test___init___embed.py
Labels: status: accepted

#12039 Remove `use_buffers` from `PatchDoc` message
  bokeh/client/connection.py
  bokeh/protocol/__init__.py
  bokeh/protocol/messages/patch_doc.py
  tests/unit/bokeh/protocol/messages/test_patch_doc.py
  tests/unit/bokeh/test_client_server.py
Labels: status: accepted, type: task, reso: completed, tag: component: server

#12035 Add Init signatures to Bokeh models
  bokeh/core/has_props.py
  bokeh/core/properties.py
  bokeh/core/property/bases.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/instance.py
  bokeh/model/data_model.py
  bokeh/model/model.py
  bokeh/models/annotations/annotation.py
  bokeh/models/annotations/arrows.py
  bokeh/models/annotations/geometry.py
  bokeh/models/annotations/html/html_annotation.py
  bokeh/models/annotations/html/labels.py
  bokeh/models/annotations/html/toolbars.py
  bokeh/models/annotations/html/tooltips.py
  bokeh/models/annotations/labels.py
  bokeh/models/annotations/legends.py
  bokeh/models/axes.py
  bokeh/models/callbacks.py
  bokeh/models/canvas.py
  bokeh/models/css.py
  bokeh/models/dom.py
  bokeh/models/expressions.py
  bokeh/models/filters.py
  bokeh/models/formatters.py
  bokeh/models/glyph.py
  bokeh/models/glyphs.py
  bokeh/models/graphics.py
  bokeh/models/graphs.py
  bokeh/models/grids.py
  bokeh/models/labeling.py
  bokeh/models/layouts.py
  bokeh/models/map_plots.py
  bokeh/models/mappers.py
  bokeh/models/plots.py
  bokeh/models/ranges.py
  bokeh/models/renderers.py
  bokeh/models/scales.py
  bokeh/models/selections.py
  bokeh/models/sources.py
  bokeh/models/text.py
  bokeh/models/textures.py
  bokeh/models/tickers.py
  bokeh/models/tiles.py
  bokeh/models/tools.py
  bokeh/models/transforms.py
  bokeh/models/ui.py
  bokeh/models/widgets/buttons.py
  bokeh/models/widgets/groups.py
  bokeh/models/widgets/icons.py
  bokeh/models/widgets/inputs.py
  bokeh/models/widgets/markups.py
  bokeh/models/widgets/sliders.py
  bokeh/models/widgets/tables.py
  bokeh/models/widgets/widget.py
  sphinx/source/docs/user_guide/examples/extensions_putting_together_ts.py
  tests/unit/bokeh/core/property/_util_property.py
  tests/unit/bokeh/core/property/test_instance.py
  tests/unit/bokeh/core/test_properties.py
Labels: status: accepted

#12040 Unify WebGL markers and rects
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/scatter.ts
  bokehjs/src/lib/models/glyphs/webgl/buffer.ts
  bokehjs/src/lib/models/glyphs/webgl/index.ts
  bokehjs/src/lib/models/glyphs/webgl/marker.frag
  bokehjs/src/lib/models/glyphs/webgl/marker.ts
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/src/lib/models/glyphs/webgl/markers.frag
  bokehjs/src/lib/models/glyphs/webgl/markers.vert
  bokehjs/src/lib/models/glyphs/webgl/rect.frag
  bokehjs/src/lib/models/glyphs/webgl/rect.ts
  bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts
  bokehjs/src/lib/models/glyphs/webgl/types.ts
  bokehjs/src/lib/models/glyphs/webgl/webgl_utils.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10246__makes_a_plot_with_visible_==_false_throw_an_exception.png
  bokehjs/test/baselines/linux/Bug__in_issue_#5046__prevents_webgl_rendering_of_streaming_markers.png
  bokehjs/test/baselines/linux/Bug__in_issue_#9230__makes_GlyphRenderer_use_incorrect_subset_indices.png
  bokehjs/test/baselines/linux/Bug__in_issue_#9230__makes_GlyphRenderer_use_incorrect_subset_indices_after_selection.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'asterisk'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_x'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_y'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'dash'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'diamond'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'diamond_cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'diamond_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'hex'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'hex_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'inverted_triangle'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'plus'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_pin'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_x'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'triangle'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'triangle_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'triangle_pin'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'x'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'y'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_hatch.blf
  bokehjs/test/baselines/linux/Marker_glyph__should_support_hatch.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_multiple_marker_types_in_scatter.png
  bokehjs/test/baselines/linux/Plot__with_webgl_backend__should_allow_display_on_log_axis.png
  bokehjs/test/baselines/linux/Plot__with_webgl_backend__should_allow_empty_circle_glyphs.png
  bokehjs/test/integration/glyphs/markers.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: webgl

#11959 Discover unstable defaults in `HasProps.__init__()`
  bokeh/core/has_props.py
  bokeh/core/property/_sphinx.py
  bokeh/core/property/bases.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/instance.py
  bokeh/model/model.py
  tests/unit/bokeh/core/property/test_descriptors.py
  tests/unit/bokeh/core/property/test_instance.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/document/test_document.py
  tests/unit/bokeh/document/test_events__document.py
Labels: type: bug, status: accepted, reso: completed

#12034 Add DatetimeRangeSlider
  bokeh/models/widgets/sliders.py
  bokehjs/src/lib/models/widgets/datetime_range_slider.ts
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/test/unit/models/widgets/slider.ts
  sphinx/source/docs/user_guide/examples/interaction_datetimerangeslider.py
  sphinx/source/docs/user_guide/interaction/widgets.rst
  tests/integration/widgets/test_datetime_range_slider.py
Labels: type: feature, status: accepted, reso: completed, tag: widgets

#12051 Fixed typo: s/server/serve/
  sphinx/source/docs/user_guide/server.rst
Labels: tag: component: docs, status: accepted

#12052 Fix typo in timedelta conversion ValueError()
  bokeh/util/serialization.py
Labels: status: accepted

#12044 11765 add metadata to examples
  examples/plotting/file/airports_map.py
  examples/plotting/file/multi_line.py
  examples/plotting/file/rect.py
  examples/plotting/file/scatter_selection.py
  examples/plotting/file/toolbar_autohide.py
  examples/plotting/file/twin_axis.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12055 Implement WebGL marker line joins
  bokehjs/src/lib/models/glyphs/webgl/base_marker.ts
  bokehjs/src/lib/models/glyphs/webgl/circle.ts
  bokehjs/src/lib/models/glyphs/webgl/marker.frag
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/src/lib/models/glyphs/webgl/multi_marker.ts
  bokehjs/src/lib/models/glyphs/webgl/webgl_utils.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10246__makes_a_plot_with_visible_==_false_throw_an_exception.png
  bokehjs/test/baselines/linux/Bug__in_issue_#5046__prevents_webgl_rendering_of_streaming_markers.png
  bokehjs/test/baselines/linux/Bug__in_issue_#9230__makes_GlyphRenderer_use_incorrect_subset_indices.png
  bokehjs/test/baselines/linux/Bug__in_issue_#9230__makes_GlyphRenderer_use_incorrect_subset_indices_after_selection.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Quad.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'asterisk'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_x'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'circle_y'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'dash'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'diamond'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'diamond_cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'diamond_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'hex'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'hex_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'inverted_triangle'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'plus'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_cross'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_pin'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'square_x'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'star_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'triangle'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'triangle_dot'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'triangle_pin'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'x'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_'y'_marker_type.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_glyph_methods_and_rotation.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_hatch.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_line_join.blf
  bokehjs/test/baselines/linux/Marker_glyph__should_support_line_join.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_multiple_marker_types_in_scatter.png
  bokehjs/test/baselines/linux/Plot__with_webgl_backend__should_allow_display_on_log_axis.png
  bokehjs/test/baselines/linux/Plot__with_webgl_backend__should_allow_empty_circle_glyphs.png
  bokehjs/test/baselines/linux/Rect_glyph__should_support_hatch_patterns_and_line_joins.png
  bokehjs/test/integration/glyphs/markers.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: webgl

#12042 RenderRoot dataclass
  bokeh/embed/util.py
Labels: status: accepted, type: task, tag: codebase

#12057 Robustify initialization of ndarrays
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/test/unit/core/util/ndarray.ts
  bokehjs/test/unit/models/annotations/annotation.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#12060 Update docs for HexTile
  bokeh/models/glyphs.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12061 WebGL support for HBar VBar and HexTile glyphs
  bokehjs/src/lib/models/glyphs/hbar.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/quad.ts
  bokehjs/src/lib/models/glyphs/vbar.ts
  bokehjs/src/lib/models/glyphs/webgl/buffer.ts
  bokehjs/src/lib/models/glyphs/webgl/hex_tile.ts
  bokehjs/src/lib/models/glyphs/webgl/index.ts
  bokehjs/src/lib/models/glyphs/webgl/lrtb.ts
  bokehjs/src/lib/models/glyphs/webgl/marker.frag
  bokehjs/test/baselines/linux/Glyph_models__should_support_Circle.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Circle.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_HBar.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_HBar.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Rect.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Rect.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_VBar.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_VBar.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_fill_with_hatch_patterns.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_fill_with_hatch_patterns.png
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns.blf
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns.blf
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns.png
  bokehjs/test/integration/glyphs/glyphs.ts
  bokehjs/test/integration/glyphs/hex_tile.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: webgl

#12064 WebGL support for Block glyph
  bokehjs/src/lib/models/glyphs/block.ts
  bokehjs/src/lib/models/glyphs/webgl/lrtb.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Block.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Block.png
  bokehjs/test/integration/glyphs/glyphs.ts
Labels: status: ready, type: task, tag: component: bokehjs, tag: webgl

#12063 Clean up sample data attribution
  bokeh/sampledata/airport_routes.py
  bokeh/sampledata/airports.py
  bokeh/sampledata/anscombe.py
  bokeh/sampledata/antibiotics.py
  bokeh/sampledata/autompg.py
  bokeh/sampledata/autompg2.py
  bokeh/sampledata/browsers.py
  bokeh/sampledata/commits.py
  bokeh/sampledata/daylight.py
  bokeh/sampledata/degrees.py
  bokeh/sampledata/gapminder.py
  bokeh/sampledata/haar_cascade.py
  bokeh/sampledata/iris.py
  bokeh/sampledata/les_mis.py
  bokeh/sampledata/movies_data.py
  bokeh/sampledata/mtb.py
  bokeh/sampledata/olympics2014.py
  bokeh/sampledata/penguins.py
  bokeh/sampledata/perceptions.py
  bokeh/sampledata/periodic_table.py
  bokeh/sampledata/population.py
  bokeh/sampledata/sample_geojson.py
  bokeh/sampledata/sea_surface_temperature.py
  bokeh/sampledata/sprint.py
  bokeh/sampledata/stocks.py
  bokeh/sampledata/unemployment.py
  bokeh/sampledata/unemployment1948.py
  bokeh/sampledata/us_cities.py
  bokeh/sampledata/us_counties.py
  bokeh/sampledata/us_holidays.py
  bokeh/sampledata/us_marriages_divorces.py
  bokeh/sampledata/world_cities.py
  sphinx/source/rst_epilog.txt
Labels: tag: component: docs, status: accepted, type: task, reso: completed
