Repository bokeh/bokeh, pull requests merged in 2022-07, with the labels that each got.

#12197 Add context formatter for datetime axes
  bokeh/core/enums.py
  bokeh/models/formatters.py
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/test/unit/core/enums.ts
  bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts
  examples/plotting/file/hover_glyph.py
  sphinx/source/docs/user_guide/examples/styling_datetime_tick_context.py
  sphinx/source/docs/user_guide/styling.rst
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#12206 Minor 3.0 docs updates
  sphinx/source/_static/custom.css
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12210 Add support for alt tags for gallery thumbnails
  bokeh/sphinxext/_templates/gallery_page.rst
  bokeh/sphinxext/bokeh_gallery.py
  sphinx/source/docs/gallery.json
Labels: tag: component: docs, status: accepted, reso: completed

#12209 Replace panels and tabs extensions
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  environment.yml
  sphinx/source/_static/custom.css
  sphinx/source/conf.py
  sphinx/source/docs/dev_guide.rst
  sphinx/source/docs/dev_guide/documentation.rst
  sphinx/source/docs/dev_guide/setup.rst
  sphinx/source/docs/first_steps.rst
  sphinx/source/docs/first_steps/installation.rst
  sphinx/source/docs/user_guide/concepts.rst
  sphinx/source/docs/user_guide/export.rst
  sphinx/source/docs/user_guide/graph.rst
  sphinx/source/docs/user_guide/jupyter.rst
  sphinx/source/index.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12208 Improvements to image selection and highlighting
  bokeh/core/property_mixins.py
  bokeh/models/glyphs.py
  bokeh/models/selections.py
  bokehjs/src/lib/core/property_mixins.ts
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/core/visuals/image.ts
  bokehjs/src/lib/core/visuals/index.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/unit/core/util/templating.ts
Labels: status: accepted

#12221 Update readme support section
  README.md
Labels: status: ready, type: task

#12222 Bryanv/10183 token arguments
  bokeh/server/contexts.py
  bokeh/server/views/session_handler.py
  bokeh/util/token.py
  tests/unit/bokeh/server/test_server__server.py
Labels: status: ready

#12020 Add contouring
  .lgtm.yml
  bokeh/models/__init__.py
  bokeh/models/annotations/legends.py
  bokeh/models/contour_renderer.py
  bokeh/plotting/_figure.py
  bokeh/plotting/contour.py
  bokehjs/src/lib/api/themes.ts
  bokehjs/src/lib/models/annotations/base_color_bar.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/annotations/contour_color_bar.ts
  bokehjs/src/lib/models/annotations/index.ts
  bokehjs/src/lib/models/renderers/contour_renderer.ts
  bokehjs/src/lib/models/renderers/index.ts
  bokehjs/test/baselines/linux/ContourRenderer__should_support_line_fill_and_hatch_properties.blf
  bokehjs/test/baselines/linux/ContourRenderer__should_support_line_fill_and_hatch_properties.png
  bokehjs/test/integration/contour.ts
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-downstream.yml
  ci/environment-test-minimal-deps.yml
  conda.recipe/meta.yaml
  environment.yml
  tests/unit/bokeh/plotting/test_contour.py
Labels: type: feature, status: ready, tag: contour

#12224 Update docs CSS
  sphinx/source/_static/custom.css
  sphinx/source/conf.py
Labels: tag: component: docs, status: ready, type: task, reso: completed

#12229 Fix intersphinx doc reference
  sphinx/source/docs/dev_guide/documentation.rst
Labels: tag: component: docs, status: accepted, type: task

#12228 Clarify edit tool helpstring
  bokeh/models/tools.py
Labels: status: accepted

#12212 Convert DateRangeSlider/DateSlider step to days
  bokeh/models/widgets/sliders.py
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/src/lib/models/widgets/date_range_slider.ts
  bokehjs/src/lib/models/widgets/date_slider.ts
  bokehjs/test/unit/models/widgets/slider.ts
  sphinx/source/docs/user_guide/interaction/widgets.rst
  tests/integration/widgets/test_dateslider.py
Labels: status: accepted

#12233 Revert field_name rename
  bokeh/transform.py
  ci/install_downstream_packages.sh
  sphinx/source/docs/first_steps/examples/first_steps_5_color_mapping.py
  sphinx/source/docs/user_guide/examples/styling_linear_mappers.py
Labels: status: accepted, type: task, reso: completed

#12244 Add support for cross bounds to grid lines
  bokeh/models/grids.py
  bokehjs/src/lib/models/grids/grid.ts
  bokehjs/test/baselines/linux/Grid__should_support_cross_bounds.blf
  bokehjs/test/baselines/linux/Grid__should_support_cross_bounds.png
  bokehjs/test/integration/grids.ts
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#12213 Add ColorBar.display_low and display_high
  bokeh/models/annotations/legends.py
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/mappers/continuous_color_mapper.ts
  bokehjs/src/lib/models/mappers/eqhist_color_mapper.ts
  bokehjs/src/lib/models/mappers/linear_color_mapper.ts
  bokehjs/src/lib/models/mappers/log_color_mapper.ts
  bokehjs/src/lib/models/mappers/scanning_color_mapper.ts
  bokehjs/src/lib/models/tickers/log_ticker.ts
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__high_only.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__high_only.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__low_and_high.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__low_and_high.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__low_only.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__low_only.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__out_of_bounds.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__out_of_bounds.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__update_EqHist.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__update_EqHist.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__update_Linear.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__update_Linear.png
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__wrong_way_round.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_display_cutoffs__wrong_way_round.png
  bokehjs/test/codebase/size.ts
  bokehjs/test/integration/annotations/color_bar.ts
  bokehjs/test/unit/models/annotations/color_bar.ts
  sphinx/source/docs/releases/3.0.0.rst
  tests/unit/bokeh/models/test_annotations.py
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#12241 Update wording for output_file()
  sphinx/source/docs/first_steps/first_steps_7.rst
Labels: tag: component: docs, status: accepted, type: task

#12247 Update bokehjs' dependencies
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/package.json
Labels: status: accepted, type: task, reso: completed, tag: codebase

#12249 add SRI hash for vis.js
  examples/app/surface3d/templates/index.html
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#12239 Fix module selectors in mypy's module overrides
  bokeh/_testing/plugins/jupyter_notebook.py
  bokeh/core/templates.py
  bokeh/embed/standalone.py
  bokeh/embed/wrappers.py
  bokeh/io/notebook.py
  bokeh/io/webdriver.py
  bokeh/sampledata/airports.py
  bokeh/sampledata/anscombe.py
  bokeh/sampledata/antibiotics.py
  bokeh/sampledata/autompg.py
  bokeh/sampledata/autompg2.py
  bokeh/sampledata/browsers.py
  bokeh/sampledata/commits.py
  bokeh/sampledata/daylight.py
  bokeh/sampledata/population.py
  bokeh/sampledata/sea_surface_temperature.py
  bokeh/sampledata/stocks.py
  bokeh/sampledata/unemployment.py
  bokeh/sampledata/us_counties.py
  bokeh/sampledata/us_holidays.py
  bokeh/sampledata/us_marriages_divorces.py
  bokeh/sampledata/us_states.py
  bokeh/server/tornado.py
  bokeh/util/callback_manager.py
  bokeh/util/compiler.py
  bokeh/util/hex.py
  bokeh/util/sampledata.py
  bokeh/util/serialization.py
  bokeh/util/token.py
  examples/models/file/calendars.py
  pyproject.toml
  tests/unit/bokeh/util/test_util__serialization.py
  typings/selenium/webdriver/firefox/firefox_binary.pyi
  typings/selenium/webdriver/firefox/webdriver.pyi
Labels: status: accepted

#12257 Upgrade bokehjs in examples and tests
  examples/custom/gears/package-lock.json
  examples/custom/gears/package.json
  examples/custom/gears/tsconfig.json
  tests/unit/bokeh/embed/ext_package_no_main/package-lock.json
  tests/unit/bokeh/embed/ext_package_no_main/package.json
  tests/unit/bokeh/embed/latex_label/package-lock.json
  tests/unit/bokeh/embed/latex_label/package.json
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: examples

#12255 Support themes on Python side for ContourColorBar
  bokeh/themes/_caliber.py
  bokeh/themes/_contrast.py
  bokeh/themes/_dark_minimal.py
  bokeh/themes/_light_minimal.py
  bokeh/themes/_night_sky.py
  sphinx/source/docs/releases/3.0.0.rst
  tests/unit/bokeh/test_themes.py
Labels: status: accepted

#12256 Add hold_render to plot
  bokeh/models/plots.py
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/linux/Plot__in_issue_#12171__should_support_hold_render_property.blf
  bokehjs/test/baselines/linux/Plot__in_issue_#12171__should_support_hold_render_property.png
  bokehjs/test/integration/plots.ts
Labels: status: accepted

#12265 Pin sphinx to version >=5,<5.1
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  environment.yml
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#12219 Allow `SaveTool` to work with any layouts
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokehjs-ci.yml
  bokeh/layouts.py
  bokeh/models/tools.py
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/grid_plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/actions/action_tool.ts
  bokehjs/src/lib/models/tools/actions/copy_tool.ts
  bokehjs/src/lib/models/tools/actions/index.ts
  bokehjs/src/lib/models/tools/actions/plot_action_tool.ts
  bokehjs/src/lib/models/tools/actions/redo_tool.ts
  bokehjs/src/lib/models/tools/actions/reset_tool.ts
  bokehjs/src/lib/models/tools/actions/save_tool.ts
  bokehjs/src/lib/models/tools/actions/undo_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/gestures/gesture_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/tools/inspectors/inspect_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/unit/regressions.ts
  ci/install_node_modules.sh
  examples/custom/parallel_plot/parallel_reset.ts
  sphinx/source/docs/dev_guide/setup.rst
  tests/codebase/test_js_license_set.py
  tests/unit/bokeh/io/test_export.py
  tests/unit/bokeh/models/test_tools.py
  tests/unit/bokeh/test_layouts.py
Labels: status: accepted

#12260 Add random filename description
  sphinx/source/docs/first_steps/first_steps_7.rst
Labels: tag: component: docs, status: accepted, type: task

#12267 Don't defer buffer serialization in standalone mode
  bokeh/document/document.py
  bokeh/embed/standalone.py
  bokeh/embed/util.py
  tests/unit/bokeh/embed/test_standalone.py
Labels: status: accepted

#12268 Add support for async `expect().to.throw()`
  bokehjs/src/lib/core/util/types.ts
  bokehjs/test/unit/assertions.ts
  bokehjs/test/unit/core/util/types.ts
Labels: type: feature, tag: component: tests, status: accepted, reso: completed, tag: component: bokehjs

#12269 Move normal random generator from `np` to `Random`
  bokehjs/src/lib/api/linalg.ts
  bokehjs/src/lib/core/util/random.ts
  bokehjs/test/unit/core/util/random.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#12270 Allow to stop throttled functions
  bokehjs/src/lib/core/util/throttle.ts
  bokehjs/test/unit/core/util/throttle.ts
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#12271 Add parameterized `NonNegative` and `Positive` properties
  .github/workflows/bokeh-ci.yml
  bokeh/core/properties.py
  bokeh/core/property/_sphinx.py
  bokeh/core/property/alias.py
  bokeh/core/property/color.py
  bokeh/core/property/container.py
  bokeh/core/property/dataspec.py
  bokeh/core/property/datetime.py
  bokeh/core/property/either.py
  bokeh/core/property/enum.py
  bokeh/core/property/include.py
  bokeh/core/property/json.py
  bokeh/core/property/nullable.py
  bokeh/core/property/numeric.py
  bokeh/core/property/pd.py
  bokeh/core/property/primitive.py
  bokeh/core/property/readonly.py
  bokeh/core/property/required.py
  bokeh/core/property/string.py
  bokeh/core/property/text_like.py
  bokeh/core/property/visual.py
  bokeh/models/layouts.py
  bokeh/models/widgets/inputs.py
  bokehjs/src/lib/core/kinds.ts
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  environment.yml
  pyproject.toml
  tests/unit/bokeh/core/property/test_numeric.py
  tests/unit/bokeh/core/test_properties.py
Labels: type: feature, status: accepted, reso: completed, tag: mypy

#12275 Allow to run tests/lint even if build fails
  .github/workflows/bokehjs-ci.yml
Labels: status: accepted

#12196 Remove id attribute of bk-root after plotting
  bokehjs/src/lib/embed/notebook.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#12263 varying_alpha_palette helper function
  bokeh/colors/color.py
  bokeh/colors/util.py
  bokeh/palettes.py
  tests/unit/bokeh/colors/test_color__colors.py
  tests/unit/bokeh/colors/test_util__colors.py
  tests/unit/bokeh/test_palettes.py
Labels: type: feature, status: accepted, reso: completed

#12279 Don't permanently attach menus to the DOM
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/core/util/menus.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/toolbar.ts
Labels: status: accepted
