Repository bokeh/bokeh, pull requests merged in 2022-01, with the labels that each got.

#11927 Improve life cycle of `DataRange1d.plots`
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/util/iterator.ts
  bokehjs/src/lib/models/canvas/cartesian_frame.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/test/unit/core/util/iterator.ts
  bokehjs/test/unit/models/plots/plot.ts
  bokehjs/test/unit/models/ranges/data_range1d.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#11923 Add support for auto-hide to grid toolbars
  bokeh/layouts.py
  bokeh/models/tools.py
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/actions/index.ts
  bokehjs/src/lib/models/tools/edit/index.ts
  bokehjs/src/lib/models/tools/gestures/index.ts
  bokehjs/src/lib/models/tools/index.ts
  bokehjs/src/lib/models/tools/inspectors/index.ts
  bokehjs/src/lib/models/tools/proxy_toolbar.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/tools/toolbar_base.ts
  bokehjs/src/lib/models/tools/toolbar_box.ts
  bokehjs/test/unit/models/tools/proxy_toolbar.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  bokehjs/test/unit/models/tools/toolbar_box.ts
  tests/integration/tools/test_toolbar_autohide.py
Labels: status: accepted

#11928 Fix gmaps' support and remove special handling
  bokeh/models/map_plots.py
  bokehjs/src/lib/models/plots/gmap.ts
  bokehjs/src/lib/models/plots/gmap_plot.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  bokehjs/src/lib/models/plots/index.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/defaults/index.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#11926 Allow to place toolbars inside the frame
  bokeh/models/plots.py
  bokehjs/src/less/toolbar.less
  bokehjs/src/lib/core/layout/border.ts
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_above_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_above_inside_the_frame.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_below_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_below_inside_the_frame.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_left_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_left_inside_the_frame.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_right_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_right_inside_the_frame.png
  bokehjs/test/integration/plots.ts
Labels: type: feature, status: accepted, reso: completed, tag: API: models

#11929 Request render when missing fonts are finally loaded
  bokehjs/src/lib/core/graphics.ts
  bokehjs/src/lib/core/util/text.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/core/visuals/text.ts
  bokehjs/src/lib/es.d.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/assets/fonts/vujahday/VujahdayScript-Regular.ttf
  bokehjs/test/baselines/linux/Bug__in_issue_#9448__prevents_correct_text_rendering_with_lazily_loaded_fonts.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#9448__prevents_correct_text_rendering_with_lazily_loaded_fonts.png
  bokehjs/test/integration/examples/blackbody_radiation.ts
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#11931 Drop official support for Python 3.7
  .github/workflows/bokeh-ci.yml
  _setup_support.py
  bokeh/io/doc.py
  bokeh/io/notebook.py
  bokeh/io/state.py
  ci/docker/docker_run.sh
  ci/environment-build.yml
  ci/environment-release-build.yml
  ci/environment-release-deploy.yml
  ci/environment-test-3.7.yml
  classifiers.txt
  conda.recipe/meta.yaml
  environment.yml
  pyproject.toml
  setup.py
  sphinx/source/docs/first_steps.rst
  sphinx/source/docs/releases/3.0.0.rst
Labels: status: accepted, type: task, reso: completed, tag: component: build

#11932 Update versions of all packages in `package-lock.json`
  bokehjs/package-lock.json
  release/build.py
Labels: type: bug, status: accepted, reso: completed, tag: component: build

#11935 Fix typo in tools.py
  bokeh/models/tools.py
Labels: status: accepted, type: task, reso: completed

#11938 Limit tool-related tap events to the frame
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#11941 Replace `typing_extensions` with `typing` wherever possible
  bokeh/_testing/plugins/managed_server_loop.py
  bokeh/_testing/plugins/project.py
  bokeh/_testing/util/examples.py
  bokeh/_testing/util/screenshot.py
  bokeh/client/session.py
  bokeh/command/subcommand.py
  bokeh/core/enums.py
  bokeh/core/has_props.py
  bokeh/core/property/dataspec.py
  bokeh/core/types.py
  bokeh/core/validation/check.py
  bokeh/document/json.py
  bokeh/document/locking.py
  bokeh/embed/bundle.py
  bokeh/embed/server.py
  bokeh/embed/standalone.py
  bokeh/events.py
  bokeh/io/notebook.py
  bokeh/io/webdriver.py
  bokeh/models/plots.py
  bokeh/models/renderers.py
  bokeh/models/tools.py
  bokeh/plotting/_tools.py
  bokeh/protocol/__init__.py
  bokeh/protocol/message.py
  bokeh/protocol/messages/error.py
  bokeh/protocol/messages/pull_doc_reply.py
  bokeh/protocol/messages/push_doc.py
  bokeh/protocol/messages/server_info_reply.py
  bokeh/resources.py
  bokeh/settings.py
  bokeh/sphinxext/__init__.py
  bokeh/util/browser.py
  bokeh/util/serialization.py
  tests/test_examples.py
  typings/IPython/core/history.pyi
  typings/bs4.pyi
  typings/selenium/webdriver/remote/webdriver.pyi
  typings/selenium/webdriver/remote/webelement.pyi
Labels: status: accepted, type: task, reso: completed, tag: codebase

#11943 Don't rely on clicking a toolbar button for testing
  bokeh/_testing/plugins/project.py
  tests/integration/models/test_datarange1d.py
  tests/integration/models/test_sources.py
  tests/integration/tools/test_box_edit_tool.py
  tests/integration/tools/test_box_zoom_tool.py
  tests/integration/tools/test_custom_action.py
  tests/integration/tools/test_freehand_draw_tool.py
  tests/integration/tools/test_pan_tool.py
  tests/integration/tools/test_point_draw_tool.py
  tests/integration/tools/test_poly_draw_tool.py
  tests/integration/tools/test_poly_edit_tool.py
  tests/integration/tools/test_range_tool.py
  tests/integration/tools/test_reset_tool.py
  tests/integration/tools/test_tap_tool.py
  tests/integration/tools/test_wheel_pan_tool.py
  tests/integration/tools/test_wheel_zoom_tool.py
  tests/integration/tools/test_zoom_in_tool.py
  tests/integration/tools/test_zoom_out_tool.py
  tests/integration/widgets/tables/test_source_updates.py
  tests/integration/widgets/test_autocomplete_input.py
  tests/integration/widgets/test_button.py
  tests/integration/widgets/test_checkbox_button_group.py
  tests/integration/widgets/test_checkbox_group.py
  tests/integration/widgets/test_color_picker.py
  tests/integration/widgets/test_datepicker.py
  tests/integration/widgets/test_daterange_slider.py
  tests/integration/widgets/test_dateslider.py
  tests/integration/widgets/test_dropdown.py
  tests/integration/widgets/test_multi_choice.py
  tests/integration/widgets/test_numeric_input.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_radio_button_group.py
  tests/integration/widgets/test_radio_group.py
  tests/integration/widgets/test_range_slider.py
  tests/integration/widgets/test_select.py
  tests/integration/widgets/test_slider.py
  tests/integration/widgets/test_spinner.py
  tests/integration/widgets/test_text_input.py
  tests/integration/widgets/test_textarea_input.py
  tests/integration/widgets/test_toggle.py
Labels: tag: component: tests, status: accepted, type: task, reso: completed

#11902 Added metadata for examples/plotting/file/color_data_map.py and examples/plotting/file/grid.py
  examples/plotting/file/color_data_map.py
  examples/plotting/file/grid.py
Labels: status: accepted

#11945 Add support for `GridPlot` and update `gridplot()`
  bokeh/layouts.py
  bokeh/models/plots.py
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/models/plots/grid_plot.ts
  bokehjs/src/lib/models/plots/index.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/toolbar_box.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11035__doesn't_allow_to_use_non-Plot_models_in_gridplot().blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11035__doesn't_allow_to_use_non-Plot_models_in_gridplot().png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'below'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'below'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'left'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'left'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'right'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'right'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_null.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_null.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_null_to_'above'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_null_to_'above'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'below'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'below'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'left'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'left'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'right'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'right'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_null.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_null.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_null_to_'above'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_null_to_'above'.png
  bokehjs/test/baselines/linux/Examples__should_support_Anscombe.blf
  bokehjs/test/baselines/linux/gridplot()__should_align_axes_when_toolbar_location=above.blf
  bokehjs/test/baselines/linux/gridplot()__should_align_axes_when_toolbar_location=below.blf
  bokehjs/test/baselines/linux/gridplot()__should_align_axes_when_toolbar_location=left.blf
  bokehjs/test/baselines/linux/gridplot()__should_align_axes_when_toolbar_location=null.blf
  bokehjs/test/baselines/linux/gridplot()__should_align_axes_when_toolbar_location=right.blf
  bokehjs/test/framework.ts
  bokehjs/test/integration/layouts.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  bokehjs/test/unit/regressions.ts
  sphinx/source/docs/releases/3.0.0.rst
  tests/unit/bokeh/test_layouts.py
Labels: status: accepted

#11939 Make `_may_have_unstable_defaults()` more robust
  bokeh/core/property/bases.py
  bokeh/core/property/dataspec.py
  bokeh/core/property/descriptors.py
  bokeh/core/property/either.py
  bokeh/core/property/instance.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/test_objects.py
Labels: status: accepted, type: task, reso: completed

#11900 Metadata for examples/plotting/file/linked_brushing.py
  examples/plotting/file/linked_brushing.py
Labels: status: accepted

#11953 Update tests for Firefox 96
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  tests/unit/bokeh/io/test_export.py
Labels: tag: component: tests, status: accepted, type: task, reso: completed, plat: firefox

#11948 Various improvements to component styling
  bokeh/core/enums.py
  bokeh/models/layouts.py
  bokeh/models/widgets/markups.py
  bokehjs/src/less/_mixins.less
  bokehjs/src/less/base.less
  bokehjs/src/less/buttons.less
  bokehjs/src/less/caret.less
  bokehjs/src/less/dropdown.less
  bokehjs/src/less/icons.less
  bokehjs/src/less/menus.less
  bokehjs/src/less/tabs.less
  bokehjs/src/less/tool_button.less
  bokehjs/src/less/tooltips.less
  bokehjs/src/less/widgets/inputs.less
  bokehjs/src/less/widgets/nouislider.less
  bokehjs/src/less/widgets/tables.less
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/util/object.ts
  bokehjs/src/lib/es.d.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/tools/actions/save_tool.ts
  bokehjs/src/lib/models/tools/button_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/src/lib/models/widgets/markup.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_incorrect_value_in_Select_widget_when_options_change.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_incorrect_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/linux/Feature__in_issue_#10914__should_allow_customizing_tool_icons.png
  bokehjs/test/baselines/linux/Rows_of_widgets__should_allow_different_content_and_fixed_height.blf
  bokehjs/test/baselines/linux/Rows_of_widgets__should_allow_different_content_and_fixed_height.png
  bokehjs/test/baselines/linux/Widgets__should_allow_AutocompleteInput.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_AutocompleteInput.png
  bokehjs/test/baselines/linux/Widgets__should_allow_DatePicker.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_DatePicker.png
  bokehjs/test/baselines/linux/Widgets__should_allow_DatePicker_with_dialog_open.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_DatePicker_with_dialog_open.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Div_with_float_children.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Div_with_float_children.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Select.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Select.png
  bokehjs/test/baselines/linux/Widgets__should_allow_TextInput.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_TextInput.png
  bokehjs/test/codebase/size.ts
  bokehjs/test/integration/features.ts
  sphinx/source/_images/icons/Copy.png
  sphinx/source/docs/releases/3.0.0.rst
  tests/integration/widgets/test_div.py
  tests/integration/widgets/test_paragraph.py
  tests/integration/widgets/test_pretext.py
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#11933 Add support for a checkbox-like Switch widget
  bokeh/models/widgets/inputs.py
  bokehjs/src/less/widgets/switch.less
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/src/lib/models/widgets/switch.ts
  bokehjs/src/lib/models/widgets/toggle.ts
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=false.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=false.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=true.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=true.png
  bokehjs/test/integration/widgets.ts
  examples/models/file/widgets.py
  sphinx/source/docs/releases/3.0.0.rst
Labels: type: feature, status: accepted, reso: completed, tag: widgets

#11957 Update CONTRIBUTING.MD
  .github/CONTRIBUTING.md
Labels: status: accepted

#11836 Replace `setter_id` with a less verbose mechanism in bokehjs
  bokehjs/eslint.json
  bokehjs/make/paths.ts
  bokehjs/make/task.ts
  bokehjs/make/tasks/_util.ts
  bokehjs/make/tasks/build.ts
  bokehjs/make/tasks/index.ts
  bokehjs/make/tasks/lint.ts
  bokehjs/make/tasks/server.ts
  bokehjs/make/tasks/test.ts
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/lib/client/connection.ts
  bokehjs/src/lib/client/session.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/util/string.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/document/events.ts
  bokehjs/src/lib/embed/server.ts
  bokehjs/src/lib/legacy.ts
  bokehjs/src/lib/models/sources/column_data_source.ts
  bokehjs/src/server/globals.d.ts
  bokehjs/src/server/index.js
  bokehjs/src/server/message.ts
  bokehjs/src/server/package.json
  bokehjs/src/server/receiver.ts
  bokehjs/src/server/server.ts
  bokehjs/src/server/tsconfig.json
  bokehjs/test/devtools/with_server.ts
  bokehjs/test/framework.ts
  bokehjs/test/globals.d.ts
  bokehjs/test/unit/client/connection.ts
  bokehjs/test/unit/document/document.ts
  bokehjs/test/unit/document/events.ts
  release/build.py
Labels: status: accepted

#11942 Toggle button emits ButtonClick event
  bokeh/models/widgets/buttons.py
  bokeh/models/widgets/groups.py
  bokehjs/src/lib/models/widgets/button_group.ts
  bokehjs/src/lib/models/widgets/toggle.ts
  examples/app/export_csv/main.py
  examples/app/gapminder/main.py
  examples/custom/font-awesome/font-awesome.py
  examples/howto/ipywidgets/ipyvolume_camera.py
  examples/howto/server_auth/app.py
  examples/howto/using_password_input.py
  examples/models/file/buttons.py
  examples/models/file/transform_jitter.py
  examples/reference/models/button_server.py
  examples/webgl/line_compare.py
  sphinx/source/docs/releases/3.0.0.rst
  sphinx/source/docs/user_guide/examples/interaction_button.py
  sphinx/source/docs/user_guide/examples/interaction_checkbox_button_group.py
  sphinx/source/docs/user_guide/examples/interaction_checkbox_group.py
  sphinx/source/docs/user_guide/examples/interaction_radio_button_group.py
  sphinx/source/docs/user_guide/examples/interaction_radio_group.py
  sphinx/source/docs/user_guide/examples/interaction_toggle_button.py
  sphinx/source/docs/user_guide/interaction/widgets.rst
  sphinx/source/docs/user_guide/server.rst
  tests/integration/models/test_datarange1d.py
  tests/integration/models/test_sources.py
  tests/integration/widgets/tables/test_source_updates.py
  tests/integration/widgets/test_button.py
  tests/integration/widgets/test_checkbox_button_group.py
  tests/integration/widgets/test_checkbox_group.py
  tests/integration/widgets/test_radio_button_group.py
  tests/integration/widgets/test_radio_group.py
  tests/integration/widgets/test_toggle.py
  tests/unit/bokeh/document/test_document.py
Labels: status: ready

#11971 Fix new typings failures
  typings/IPython/core/history.pyi
  typings/IPython/display.pyi
  typings/bs4.pyi
  typings/flaky.pyi
  typings/ipykernel/comm/comm.pyi
  typings/selenium/webdriver/common/keys.pyi
  typings/selenium/webdriver/remote/webdriver.pyi
  typings/selenium/webdriver/remote/webelement.pyi
  typings/selenium/webdriver/support/expected_conditions.pyi
  typings/selenium/webdriver/support/wait.pyi
Labels: status: accepted, type: task, reso: completed, tag: component: build

#11970 Deprecate CDSView.source more gracefully
  bokeh/models/sources.py
  tests/unit/bokeh/models/test_sources.py
Labels: status: accepted, type: task, reso: completed

#11972 Track modified files in release build more carefully
  release/build.py
  release/config.py
  release/git.py
  release/stages.py
Labels: status: accepted

#11973 Bump min sphinx version
  bokeh/colors/__init__.py
  bokeh/colors/color.py
  bokeh/colors/hsl.py
  bokeh/colors/rgb.py
  bokeh/colors/util.py
  bokeh/core/has_props.py
  bokeh/model/model.py
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
  sphinx/source/conf.py
  sphinx/source/docs/reference/colors.rst
  tests/unit/bokeh/colors/test_color__colors.py
  tests/unit/bokeh/colors/test_hsl.py
  tests/unit/bokeh/colors/test_rgb.py
Labels: status: accepted

#11976 add functools.wraps to _needs_document_lock_wrapper
  bokeh/server/session.py
Labels: status: accepted

#11982 Upgrade bokehjs' npm packages
  bokehjs/make/package.json
  bokehjs/make/tasks/lint.ts
  bokehjs/package-lock.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/models/widgets/multichoice.ts
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/baselines/linux/Bug__in_issue_#10452__prevents_changing_MultiChoice.disabled_property.png
  bokehjs/test/package.json
  tests/integration/widgets/test_multi_choice.py
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs, tag: codebase
