Repository bokeh/bokeh, pull requests merged in 2022-11, with the labels that each got.

#12538 NotRequired needs typing_extensions >=4.0.0
  pyproject.toml
  release/action.py
  release/stages.py
  src/bokeh/application/application.py
  src/bokeh/colors/color.py
  src/bokeh/command/subcommand.py
  src/bokeh/core/has_props.py
  src/bokeh/core/property/_sphinx.py
  src/bokeh/core/property/bases.py
  src/bokeh/core/property/descriptors.py
  src/bokeh/core/property/factors.py
  src/bokeh/core/property/vectorization.py
  src/bokeh/core/query.py
  src/bokeh/core/serialization.py
  src/bokeh/core/types.py
  src/bokeh/core/validation/decorators.py
  src/bokeh/document/events.py
  src/bokeh/document/json.py
  src/bokeh/embed/notebook.py
  src/bokeh/embed/standalone.py
  src/bokeh/io/showing.py
  src/bokeh/layouts.py
  src/bokeh/models/sources.py
  src/bokeh/palettes.py
  src/bokeh/plotting/_plot.py
  src/bokeh/plotting/_tools.py
  src/bokeh/plotting/contour.py
  src/bokeh/protocol/message.py
  src/bokeh/protocol/receiver.py
  src/bokeh/resources.py
  src/bokeh/sampledata/unemployment.py
  src/bokeh/sampledata/us_counties.py
  src/bokeh/sampledata/us_states.py
  src/bokeh/server/urls.py
  src/bokeh/settings.py
  src/bokeh/transform.py
  src/bokeh/util/callback_manager.py
  src/bokeh/util/dataclasses.py
  src/bokeh/util/deprecation.py
  src/bokeh/util/serialization.py
  src/bokeh/util/token.py
  src/bokeh/util/tornado.py
  tests/support/util/compare.py
  tests/support/util/examples.py
  tests/test_examples.py
Labels: status: accepted

#12546 Apply blackbody example label edits (#12534) to the ts example as well
  bokehjs/test/baselines/linux/Examples__should_support_BlackbodyRadiation.blf
  bokehjs/test/baselines/linux/Examples__should_support_BlackbodyRadiation.png
  bokehjs/test/integration/examples/blackbody_radiation.ts
  examples/styling/mathtext/latex_blackbody_radiation.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples, tag: component: bokehjs

#12539 Remove runtime dependency on typing_extensions
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
  tests/codebase/test_no_typing_extensions_common.py
Labels: status: accepted, type: task, reso: completed, tag: component: build

#12550 Add a regression test for issue #4930
  bokehjs/test/baselines/linux/Bug__in_issue_#4930__allows_to_cut_tooltips_short_in_grid_plots.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#4930__allows_to_cut_tooltips_short_in_grid_plots.png
  bokehjs/test/baselines/linux/Bug__in_issue_#4930__allows_to_cut_tooltips_short_in_layouts.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#4930__allows_to_cut_tooltips_short_in_layouts.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12549 Update mybinder tutorial links
  README.md
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/first_steps/first_steps_7.rst
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
  docs/bokeh/source/index.rst
  examples/README.md
Labels: status: ready

#12552 updates for 3.0.1 release
  docs/bokeh/source/docs/releases/3.0.0.rst
  docs/bokeh/source/docs/releases/3.0.1.rst
  docs/bokeh/switcher.json
  examples/plotting/checkout_form.py
Labels: status: ready

#12555 Forward ports for 3.0.1
  README.md
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/baselines/linux/Examples__should_support_BlackbodyRadiation.blf
  bokehjs/test/baselines/linux/Examples__should_support_BlackbodyRadiation.png
  bokehjs/test/integration/examples/blackbody_radiation.ts
  bokehjs/test/package.json
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  docs/CHANGELOG
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/first_steps/first_steps_7.rst
  docs/bokeh/source/docs/releases/3.0.0.rst
  docs/bokeh/source/docs/releases/3.0.1.rst
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
  docs/bokeh/source/index.rst
  docs/bokeh/switcher.json
  examples/README.md
  examples/plotting/checkout_form.py
  examples/styling/mathtext/latex_blackbody_radiation.py
  pyproject.toml
  src/bokeh/_sri.json
  tests/codebase/test_no_typing_extensions_common.py
Labels: status: accepted, type: task, reso: completed

#12561 Remove mock
  conda/environment-test-3.10.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  tests/unit/bokeh/application/test_application.py
  tests/unit/bokeh/client/test_session__client.py
  tests/unit/bokeh/command/test_subcommand.py
  tests/unit/bokeh/command/test_util__command.py
  tests/unit/bokeh/core/property/test_bases.py
  tests/unit/bokeh/core/property/test_descriptors.py
  tests/unit/bokeh/core/property/test_wrappers__property.py
  tests/unit/bokeh/core/test_validation.py
  tests/unit/bokeh/document/test_callbacks__document.py
  tests/unit/bokeh/document/test_document.py
  tests/unit/bokeh/document/test_events__document.py
  tests/unit/bokeh/document/test_models.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/embed/test_util__embed.py
  tests/unit/bokeh/io/test_notebook__io.py
  tests/unit/bokeh/io/test_output.py
  tests/unit/bokeh/io/test_saving.py
  tests/unit/bokeh/io/test_showing.py
  tests/unit/bokeh/io/test_state.py
  tests/unit/bokeh/io/test_util__io.py
  tests/unit/bokeh/models/test_annotations.py
  tests/unit/bokeh/models/test_mappers.py
  tests/unit/bokeh/models/test_plots.py
  tests/unit/bokeh/models/test_ranges.py
  tests/unit/bokeh/plotting/test__decorators.py
  tests/unit/bokeh/plotting/test__renderer.py
  tests/unit/bokeh/server/test_server__server.py
  tests/unit/bokeh/server/test_session__server.py
  tests/unit/bokeh/test___main__.py
  tests/unit/bokeh/test_client_server.py
  tests/unit/bokeh/test_layouts.py
  tests/unit/bokeh/util/test_browser.py
  tests/unit/bokeh/util/test_compiler.py
  tests/unit/bokeh/util/test_deprecation.py
  tests/unit/bokeh/util/test_package.py
  tests/unit/bokeh/util/test_sampledata__util.py
  tests/unit/bokeh/util/test_token.py
  tests/unit/bokeh/util/test_version.py
Labels: status: accepted

#12563 replace python with sys.executable
  tests/support/plugins/bokeh_server.py
  tests/test_examples.py
Labels: status: accepted

#12570 Correctly grant clipboard permissions in tests
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokehjs-ci.yml
  bokehjs/test/devtools/devtools.ts
  docs/bokeh/source/docs/dev_guide/bokehjs.rst
Labels: status: accepted

#12569 Add Python 3.11 to CI
  .github/workflows/bokeh-ci.yml
  conda/environment-test-3.11.yml
  docs/bokeh/source/docs/releases/3.1.0.rst
  pyproject.toml
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: CI

#12566 Fix dates and typo in release docs for 3.0.0/3.0.1
  docs/bokeh/source/docs/releases/3.0.0.rst
  docs/bokeh/source/docs/releases/3.0.1.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12484 Correctly render nonselected line glyphs
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/glyphs/webgl/line_gl.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11661__makes_line_render_incorrectly_when_painting_with_a_subset_of_indices.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12357__and_#12429_prevents_selection_of_line_segments_using_indices.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12357__and_#12429_prevents_selection_of_line_segments_using_indices.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12357__prevents_selection_of_webgl_line_segments_using_indices.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12571 Remove flaky from integration tests
  .github/workflows/bokeh-ci.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
  src/typings/flaky.pyi
  tests/integration/models/test_plot.py
  tests/integration/models/test_sources.py
  tests/integration/tools/test_box_edit_tool.py
  tests/integration/tools/test_freehand_draw_tool.py
  tests/integration/tools/test_point_draw_tool.py
  tests/integration/tools/test_poly_draw_tool.py
  tests/integration/tools/test_poly_edit_tool.py
  tests/integration/tools/test_range_tool.py
  tests/integration/widgets/tables/test_source_updates.py
  tests/integration/widgets/test_autocomplete_input.py
  tests/integration/widgets/test_button.py
  tests/integration/widgets/test_checkbox_button_group.py
  tests/integration/widgets/test_checkbox_group.py
  tests/integration/widgets/test_color_picker.py
  tests/integration/widgets/test_datepicker.py
  tests/integration/widgets/test_daterange_slider.py
  tests/integration/widgets/test_dateslider.py
  tests/integration/widgets/test_datetime_range_slider.py
  tests/integration/widgets/test_dropdown.py
  tests/integration/widgets/test_multi_choice.py
  tests/integration/widgets/test_numeric_input.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_radio_button_group.py
  tests/integration/widgets/test_radio_group.py
  tests/integration/widgets/test_range_slider.py
  tests/integration/widgets/test_select.py
  tests/integration/widgets/test_slider.py
  tests/integration/widgets/test_spinner.py
  tests/integration/widgets/test_text_input.py
  tests/integration/widgets/test_textarea_input.py
  tests/integration/widgets/test_toggle.py
  tests/unit/bokeh/command/subcommands/test_serve.py
  tests/unit/bokeh/io/test_export.py
  tests/unit/bokeh/io/test_webdriver.py
  tests/unit/bokeh/server/test_callbacks__server.py
  tests/unit/bokeh/server/test_server__server.py
  tests/unit/bokeh/test_client_server.py
Labels: tag: component: tests, status: accepted, type: task, reso: completed

#12573 Add a regression test for issue #4888
  bokehjs/test/baselines/linux/Bug__in_issue_#4888__doesn't_allow_to_render_many_(N=50)_canvas_glyphs_efficiently.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#4888__doesn't_allow_to_render_many_(N=50)_canvas_glyphs_efficiently.png
  bokehjs/test/baselines/linux/Bug__in_issue_#4888__doesn't_allow_to_render_many_(N=50)_svg_glyphs_efficiently.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#4888__doesn't_allow_to_render_many_(N=50)_svg_glyphs_efficiently.png
  bokehjs/test/baselines/linux/Bug__in_issue_#4888__doesn't_allow_to_render_many_(N=50)_webgl_glyphs_efficiently.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#4888__doesn't_allow_to_render_many_(N=50)_webgl_glyphs_efficiently.png
  bokehjs/test/integration/regressions.ts
  src/bokeh/models/plots.py
  tests/unit/bokeh/models/test_plots.py
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: bokehjs

#12579 Upgrade to mypy 0.990
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  src/bokeh/core/templates.py
Labels: status: accepted, type: task, reso: completed, tag: mypy

#12581 Disable Selenium integration tests for now
  .github/workflows/bokeh-ci.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12580 Allow to correctly proxy action tools in grid plots
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/tool_proxy.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12578__doesn't_allow_to_use_proxied_action_tools_on_all_plots.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12578__doesn't_allow_to_use_proxied_action_tools_on_all_plots.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12588 Clean up importlib.metadata properly
  src/bokeh/__init__.py
  tests/codebase/test_importlib_metadata.py
Labels: status: accepted

#12589 upload switcher.json during release
  release/deploy.py
Labels: status: ready

#12593 Guard numpy.typing.ArrayType with `if TYPE_CHECKING`
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  src/bokeh/plotting/_figure.py
Labels: type: bug, status: WIP, dependencies, tag: mypy

#12572 Keep italics when rendering bold LaTeX variable names
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/test/baselines/linux/Examples__should_support_Schrodinger.blf
  bokehjs/test/baselines/linux/Examples__should_support_Schrodinger.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_offset=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_offset=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_standoff=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_standoff=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_offset=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_offset=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_standoff=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_standoff=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_offset=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_offset=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_standoff=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_standoff=20_and_border_line_and_background_fill.png
  bokehjs/test/integration/examples/schrodinger.ts
  docs/bokeh/source/_images/examples/styling/mathtext/latex_bessel.png
  docs/bokeh/source/_images/examples/styling/mathtext/latex_bessel@2x.png
  docs/bokeh/source/_images/examples/styling/mathtext/latex_blackbody_radiation.png
  docs/bokeh/source/_images/examples/styling/mathtext/latex_blackbody_radiation@2x.png
  docs/bokeh/source/_images/examples/styling/mathtext/latex_schrodinger.png
  docs/bokeh/source/_images/examples/styling/mathtext/latex_schrodinger@2x.png
  examples/styling/mathtext/latex_schrodinger.py
Labels: status: accepted

#12586 Restore line_policy=none for HoverTool
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12585__doesn't_allow_support_for_line_policy=none_with_mode=vline.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12585__doesn't_allow_support_for_line_policy=none_with_mode=vline.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/interactive.ts
  src/bokeh/models/tools.py
Labels: status: accepted

#12600 Updates for 3.0.2
  docs/bokeh/source/docs/releases/3.0.2.rst
  docs/bokeh/source/docs/releases/3.1.0.rst
  docs/bokeh/switcher.json
Labels: status: accepted, type: task, reso: completed

#12604 Fix docs custom.js for switcher
  docs/bokeh/source/_static/custom.js
Labels: status: accepted

#12602 Update min numpy to 1.16
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
Labels: status: accepted

#12603 Neutral POV for install instructions
  README.md
  docs/bokeh/source/docs/first_steps.rst
  docs/bokeh/source/docs/first_steps/installation.rst
Labels: status: accepted

#12606 Ignore tmp test modules for codecov
  .github/codecov.yml
Labels: status: ready

#12613 Fix export with fractional CSS lengths
  src/bokeh/io/export.py
  tests/unit/bokeh/io/test_export.py
Labels: status: accepted

#12612 Fix layout propagation in nested mixed layouts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12583__doesn't_allow_layout_propagation_in_Column(Column(GridPlot())).blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12583__doesn't_allow_layout_propagation_in_Column(Column(GridPlot())).png
  bokehjs/test/baselines/linux/Bug__in_issue_#12583__doesn't_allow_layout_propagation_in_Column(Column(GridPlot(),_Row())).blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12583__doesn't_allow_layout_propagation_in_Column(Column(GridPlot(),_Row())).png
  bokehjs/test/baselines/linux/Bug__in_issue_#12583__doesn't_allow_layout_propagation_in_Column(GridPlot,_Row).blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12583__doesn't_allow_layout_propagation_in_Column(GridPlot,_Row).png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12605 Replace flake8 with ruff
  .flake8
  .pre-commit-config.yaml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/docs/dev_guide/python.rst
  docs/bokeh/source/docs/dev_guide/setup.rst
  docs/bokeh/source/docs/dev_guide/testing.rst
  examples/basic/data/color_mappers.py
  examples/interaction/js_callbacks/color_sliders.py
  examples/models/buttons.py
  examples/models/calendars.py
  examples/models/sliders.py
  examples/models/widgets.py
  examples/plotting/sprint.py
  examples/server/app/spectrogram/audio.py
  examples/styling/mathtext/latex_axis_labels_titles_labels.py
  examples/styling/mathtext/latex_div_widget.py
  examples/topics/stats/splom.py
  pyproject.toml
  scripts/spec.py
  src/bokeh/command/subcommands/__init__.py
  src/bokeh/core/types.py
  src/bokeh/core/validation/__init__.py
  src/bokeh/document/callbacks.py
  src/bokeh/document/document.py
  src/bokeh/model/__init__.py
  src/bokeh/models/__init__.py
  src/bokeh/models/widgets/__init__.py
  src/bokeh/protocol/__init__.py
  src/bokeh/server/contexts.py
  src/bokeh/sphinxext/bokeh_example_metadata.py
  src/bokeh/sphinxext/bokeh_gallery.py
  src/bokeh/sphinxext/bokeh_plot.py
  src/bokeh/sphinxext/bokeh_sampledata_xref.py
  src/bokeh/themes/__init__.py
  src/bokeh/util/token.py
  src/typings/selenium/webdriver/common/action_chains.pyi
  src/typings/selenium/webdriver/remote/webelement.pyi
  tests/codebase/test_code_quality.py
  tests/codebase/test_ruff.py
  tests/unit/bokeh/colors/test_util__colors.py
  tests/unit/bokeh/command/subcommands/test_serve.py
  tests/unit/bokeh/core/property/test_wrappers__property.py
  tests/unit/bokeh/model/test_model.py
  tests/unit/bokeh/models/test_annotations.py
  tests/unit/bokeh/models/test_glyphs.py
  tests/unit/bokeh/test_objects.py
  tests/unit/bokeh/test_palettes.py
  tests/unit/bokeh/test_resources.py
Labels: status: ready, type: task, tag: codebase

#12620 Remove LGTM
  .lgtm.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12547 Added metadata to glyphs.py, multi_legend.py, multi_scale.py
  examples/plotting/glyphs.py
  examples/plotting/multi_legend.py
  examples/plotting/multi_scale.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12621 Forward ports from 3.0.2
  docs/CHANGELOG
  examples/plotting/glyphs.py
  src/bokeh/_sri.json
Labels: status: accepted, type: task, reso: completed

#12622 Bv/deprecated apis in tests
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  src/bokeh/io/notebook.py
  src/bokeh/models/util/structure.py
Labels: status: accepted

#12629 Exlude tmp files from coverage
  .github/codecov.yml
  pyproject.toml
  tests/unit/bokeh/test_objects.py
Labels: status: accepted

#12630 Update CodeQL action
  .github/workflows/codeql-analysis.yml
  bokehjs/src/lib/model.ts
  examples/basic/scatters/markers.py
  src/bokeh/ext.py
Labels: type: task, tag: CI

#12634 Fix application of UI element styles in Firefox
  bokehjs/src/lib/models/ui/ui_element.ts
Labels: status: accepted

#12351 Updates to Docker image building and testing
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-docker-build.yml
  .github/workflows/bokeh-docker-test.yml
  scripts/docker/Dockerfile
  scripts/docker/bokeh_docker_build.sh
  scripts/docker/bokeh_docker_from_wheel.sh
  scripts/docker/docker_run.sh
  scripts/docker/entrypoint.sh
  src/bokeh/io/webdriver.py
  tests/unit/bokeh/io/test_webdriver.py
Labels: status: ready

#12636 Add CodeQL config
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12639 Disable docker from wheel integration tests
  scripts/docker/bokeh_docker_from_wheel.sh
Labels: status: ready

#12644 Fix broken bokeh-tree links
  docs/bokeh/source/docs/dev_guide/python.rst
  docs/bokeh/source/docs/dev_guide/writing_tests.rst
  docs/bokeh/source/docs/user_guide/advanced/bokehjs.rst
  docs/bokeh/source/docs/user_guide/basic/data.rst
  docs/bokeh/source/docs/user_guide/basic/layouts.rst
  docs/bokeh/source/docs/user_guide/output/embed.rst
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
  docs/bokeh/source/docs/user_guide/server/app.rst
  docs/bokeh/source/docs/user_guide/server/library.rst
  examples/plotting/glyphs.py
  examples/plotting/multi_legend.py
  examples/plotting/multi_scale.py
  src/bokeh/application/handlers/function.py
  src/bokeh/application/handlers/script.py
  src/bokeh/application/handlers/server_lifecycle.py
  src/bokeh/application/handlers/server_request_handler.py
  src/bokeh/io/notebook.py
  src/bokeh/models/sources.py
  src/bokeh/palettes.py
  src/bokeh/sampledata/airports.py
  src/bokeh/sampledata/sample_geojson.py
  src/bokeh/util/sampledata.py
  tests/codebase/test_code_quality.py
  tests/codebase/test_no_request_host.py
  tests/support/util/examples.py
Labels: status: accepted

#12643 Add text_outline_color to documentation
  docs/bokeh/source/docs/includes/text_props.txt
Labels: status: accepted

#12650 Added find_stack_level to util.warnings
  src/bokeh/__init__.py
  src/bokeh/command/util.py
  src/bokeh/core/has_props.py
  src/bokeh/embed/bundle.py
  src/bokeh/io/export.py
  src/bokeh/io/notebook.py
  src/bokeh/io/saving.py
  src/bokeh/models/formatters.py
  src/bokeh/models/plots.py
  src/bokeh/models/sources.py
  src/bokeh/plotting/_tools.py
  src/bokeh/plotting/graph.py
  src/bokeh/settings.py
  src/bokeh/util/deprecation.py
  src/bokeh/util/token.py
  src/bokeh/util/warnings.py
  tests/unit/bokeh/command/test_util__command.py
  tests/unit/bokeh/util/test_deprecation.py
  tests/unit/bokeh/util/test_warnings.py
Labels: status: accepted

#12654 Resolve issues with code quality checks
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  src/bokeh/colors/color.py
  src/bokeh/command/subcommand.py
  src/bokeh/command/subcommands/__init__.py
  src/bokeh/core/has_props.py
  src/bokeh/core/property/_sphinx.py
  src/bokeh/core/property/bases.py
  src/bokeh/core/property/descriptors.py
  src/bokeh/core/property/either.py
  src/bokeh/core/property/include.py
  src/bokeh/core/property/instance.py
  src/bokeh/core/serialization.py
  src/bokeh/core/validation/decorators.py
  src/bokeh/document/callbacks.py
  src/bokeh/document/document.py
  src/bokeh/document/events.py
  src/bokeh/embed/bundle.py
  src/bokeh/embed/standalone.py
  src/bokeh/embed/util.py
  src/bokeh/events.py
  src/bokeh/layouts.py
  src/bokeh/model/docs.py
  src/bokeh/model/model.py
  src/bokeh/model/util.py
  src/bokeh/plotting/_plot.py
  src/bokeh/protocol/__init__.py
  src/bokeh/server/auth_provider.py
  src/bokeh/server/tornado.py
  src/bokeh/settings.py
  src/bokeh/themes/theme.py
  src/bokeh/util/callback_manager.py
  src/bokeh/util/compiler.py
  src/bokeh/util/serialization.py
  tests/support/util/filesystem.py
  tests/unit/bokeh/models/test_defaults.py
  tests/unit/bokeh/models/test_layouts__models.py
Labels: status: accepted, type: task, reso: completed, dependencies, tag: codebase

#12653 Compute layout for initially undisplayed components
  bokehjs/src/lib/core/layout/layoutable.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12640__doesn't_allow_layout_computation_for_initially_undisplayed_components.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12640__doesn't_allow_layout_computation_for_initially_undisplayed_components.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/canvas/canvas.ts
Labels: status: accepted

#12652 Add support for above/below fill/hatch to Slope
  bokehjs/src/lib/core/property_mixins.ts
  bokehjs/src/lib/models/annotations/slope.ts
  bokehjs/test/baselines/linux/Feature__in_issue_#9194__should_allow_above_and_below_fill_and_hover_in_Slope_annotation.blf
  bokehjs/test/baselines/linux/Feature__in_issue_#9194__should_allow_above_and_below_fill_and_hover_in_Slope_annotation.png
  bokehjs/test/integration/features.ts
  src/bokeh/models/annotations/geometry.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/_util_models.py
  tests/unit/bokeh/models/test_annotations.py
Labels: status: accepted
