Repository bokeh/bokeh, pull requests merged in 2022-04, with the labels that each got.

#12081 Fix passing of kwargs in Image glyph's constructor
  bokeh/models/glyphs.py
  tests/unit/bokeh/models/test_glyphs.py
Labels: status: accepted

#12094 12093 Update union syntax
  typings/flaky.pyi
  typings/ipykernel/comm/comm.pyi
  typings/selenium/webdriver/common/keys.pyi
  typings/selenium/webdriver/support/wait.pyi
Labels: status: accepted

#12092 11765 typos in metadata documentation
  bokeh/sphinxext/bokeh_plot.py
  examples/models/file/basic_plot.py
  examples/models/file/widgets.py
  examples/plotting/file/airports_map.py
  examples/plotting/file/periodic_shells.py
  examples/plotting/file/unemployment.py
  examples/plotting/file/us_marriages_divorces_hover.py
Labels: status: WIP

#12097 Missing `f` prefix on f-strings fix
  bokeh/core/property/either.py
  bokeh/sphinxext/bokeh_prop.py
  release/git.py
Labels: status: accepted

#12100 Fix Comparing singleton primitives with equality checking
  examples/app/movies/main.py
  tests/integration/tools/test_custom_action.py
  tests/unit/bokeh/application/handlers/test_directory.py
  tests/unit/bokeh/application/handlers/test_handler.py
  tests/unit/bokeh/application/handlers/test_notebook__handlers.py
  tests/unit/bokeh/application/test_application.py
  tests/unit/bokeh/client/test_connection.py
  tests/unit/bokeh/client/test_session__client.py
  tests/unit/bokeh/client/test_states.py
  tests/unit/bokeh/command/subcommands/test_sampledata__subcommands.py
  tests/unit/bokeh/core/property/test_bases.py
  tests/unit/bokeh/core/property/test_instance.py
  tests/unit/bokeh/core/property/test_singletons.py
  tests/unit/bokeh/core/property/test_wrappers__property.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/core/test_serialization.py
  tests/unit/bokeh/document/test_callbacks__document.py
  tests/unit/bokeh/document/test_document.py
  tests/unit/bokeh/document/test_events__document.py
  tests/unit/bokeh/document/test_locking.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/io/test_showing.py
  tests/unit/bokeh/io/test_state.py
  tests/unit/bokeh/io/test_util__io.py
  tests/unit/bokeh/io/test_webdriver.py
  tests/unit/bokeh/model/test_docs.py
  tests/unit/bokeh/model/test_model.py
  tests/unit/bokeh/models/test_annotations.py
  tests/unit/bokeh/models/test_layouts__models.py
  tests/unit/bokeh/models/test_ranges.py
  tests/unit/bokeh/models/test_sources.py
  tests/unit/bokeh/models/test_transforms.py
  tests/unit/bokeh/server/test_auth_provider.py
  tests/unit/bokeh/server/test_server__server.py
  tests/unit/bokeh/server/test_util.py
  tests/unit/bokeh/test_events.py
  tests/unit/bokeh/test_resources.py
  tests/unit/bokeh/test_settings.py
  tests/unit/bokeh/test_transform.py
  tests/unit/bokeh/util/test_compiler.py
  tests/unit/bokeh/util/test_options.py
  tests/unit/bokeh/util/test_string.py
Labels: status: accepted, type: task, reso: completed

#12102 Minor cleanup issues
  bokeh/client/connection.py
  bokeh/command/subcommand.py
  bokeh/embed/bundle.py
  bokeh/embed/standalone.py
  bokeh/io/state.py
  bokeh/plotting/_tools.py
  bokeh/sphinxext/bokehjs_content.py
  bokeh/util/compiler.py
  scripts/sri.py
  tests/integration/widgets/test_numeric_input.py
  tests/integration/widgets/test_spinner.py
  tests/unit/bokeh/io/test_saving.py
  tests/unit/bokeh/util/test_compiler.py
Labels: status: accepted, type: task, reso: completed

#12086 12066 sphinx extention for sampledata
  bokeh/sampledata/airport_routes.py
  bokeh/sampledata/airports.py
  bokeh/sampledata/anscombe.py
  bokeh/sampledata/antibiotics.py
  bokeh/sampledata/autompg.py
  bokeh/sampledata/autompg2.py
  bokeh/sampledata/browsers.py
  bokeh/sampledata/commits.py
  bokeh/sampledata/daylight.py
  bokeh/sampledata/degrees.py
  bokeh/sampledata/gapminder.py
  bokeh/sampledata/glucose.py
  bokeh/sampledata/haar_cascade.py
  bokeh/sampledata/iris.py
  bokeh/sampledata/les_mis.py
  bokeh/sampledata/movies_data.py
  bokeh/sampledata/mtb.py
  bokeh/sampledata/olympics2014.py
  bokeh/sampledata/penguins.py
  bokeh/sampledata/perceptions.py
  bokeh/sampledata/periodic_table.py
  bokeh/sampledata/population.py
  bokeh/sampledata/sample_geojson.py
  bokeh/sampledata/sea_surface_temperature.py
  bokeh/sampledata/sprint.py
  bokeh/sampledata/stocks.py
  bokeh/sampledata/unemployment.py
  bokeh/sampledata/unemployment1948.py
  bokeh/sampledata/us_cities.py
  bokeh/sampledata/us_counties.py
  bokeh/sampledata/us_holidays.py
  bokeh/sampledata/us_marriages_divorces.py
  bokeh/sampledata/us_states.py
  bokeh/sampledata/world_cities.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_sampledata_xref.py
  sphinx/source/conf.py
Labels: status: accepted

#12106 Fix typo in git.py
  release/git.py
Labels: type: bug, status: accepted, reso: completed, tag: codebase

#12071 Fix Wedge and AnnualWedge glyph hitboxes
  bokehjs/src/lib/models/glyphs/annular_wedge.ts
  bokehjs/src/lib/models/glyphs/wedge.ts
  bokehjs/test/unit/models/glyphs/annular_wedge.ts
  bokehjs/test/unit/models/glyphs/wedge.ts
Labels: status: accepted

#12084 Simplify EqHistColorMapper calculations
  bokehjs/src/lib/models/mappers/eqhist_color_mapper.ts
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_EqHistColorMapper.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_gaussian_distributed_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_pipeline_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_sparse_cells_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_uniformly_distributed_data.png
  bokehjs/test/unit/models/mappers/eqhist_color_mapper.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#12098 11965 fixes that null value with unspecified nan_format crashes table rendering
  bokeh/models/widgets/tables.py
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
Labels: status: accepted
