Repository bokeh/bokeh, pull requests merged in 2022-06, with the labels that each got.

#12067 Don't excessively check if fonts were loaded
  bokehjs/src/lib/core/visuals/text.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#12076 Initialize properties in definition order
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/resolvers.ts
  bokehjs/src/lib/core/serialization/deserializer.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/test/unit/core/has_props.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#12148 Resolve issues with MathJax 3.2.1
  bokehjs/make/tasks/scripts.ts
  bokehjs/package-lock.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/lib/package.json
Labels: status: accepted

#12151 fixes #12150
  README.md
Labels: status: accepted

#12137 11765 Add metadata to choropleth.py and sliders.py
  examples/models/file/choropleth.py
  examples/models/file/sliders.py
Labels: status: accepted

#12159 Add load balancing implementation for Apache in documentation
  sphinx/source/docs/user_guide/server.rst
Labels: status: accepted

#12138 Added expanduser to paths
  bokeh/command/util.py
  bokeh/io/export.py
  bokeh/io/saving.py
Labels: status: accepted

#12173 Minor bokehjs' codebase cleanup
  bokehjs/eslint.json
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/api/palettes.ts
  bokehjs/src/lib/api/parser.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/iterator.ts
  bokehjs/src/lib/core/util/menus.ts
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/es.d.ts
  bokehjs/src/lib/models/mappers/color_mapper.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/widgets/date_picker.ts
  bokehjs/src/lib/models/widgets/dropdown.ts
  bokehjs/src/lib/models/widgets/numeric_input.ts
  bokehjs/src/lib/models/widgets/spinner.ts
  bokehjs/src/lib/models/widgets/widget.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/integration/annotations/legend.ts
  bokehjs/test/integration/colors.ts
  bokehjs/test/integration/examples/polar_subcoordinates.ts
  bokehjs/test/integration/glyphs/hex_tile.ts
  bokehjs/test/unit/core/properties.ts
  bokehjs/test/unit/core/util/svg.tsx
  bokehjs/test/unit/models/plots/plot.ts
  bokehjs/test/unit/models/transforms/step_interpolator.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#12174 Fix canvas rendering of step glyph containing NaN
  bokehjs/src/lib/models/glyphs/step.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Step.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Step_with_NaN.png
  bokehjs/test/integration/glyphs/glyphs.ts
Labels: type: bug, status: ready, tag: component: bokehjs

#12188 Toggle opacity not visibility of descriptions
  bokehjs/src/less/widgets/inputs.less
  bokehjs/src/lib/models/widgets/input_widget.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#12192 use correct zoom scale factors
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts
  bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts
Labels: status: accepted

#12170 Simplify DatetimeTickFormatter scale format type
  bokeh/models/formatters.py
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts
  examples/models/file/daylight.py
  sphinx/source/docs/user_guide/examples/categorical_scatter_jitter.py
Labels: status: ready

#12114 12066 sphinx link to user guide
  bokeh/sphinxext/_templates/gallery_detail.rst
  bokeh/sphinxext/_templates/gallery_page.rst
  bokeh/sphinxext/bokeh_gallery.py
  bokeh/sphinxext/bokeh_plot.py
  bokeh/sphinxext/bokeh_sampledata_xref.py
  bokeh/sphinxext/util.py
  examples/models/file/choropleth.py
  examples/plotting/file/airports_map.py
  examples/plotting/file/choropleth.py
  examples/plotting/file/eclipse.py
  examples/plotting/file/les_mis.py
  examples/plotting/file/linked_brushing.py
  examples/plotting/file/multi_line.py
  examples/plotting/file/periodic_shells.py
  examples/plotting/file/rect.py
  examples/plotting/file/scatter_selection.py
  examples/plotting/file/toolbar_autohide.py
  sphinx/Makefile
  sphinx/source/_images/gallery/pie.png
  sphinx/source/conf.py
  sphinx/source/docs/examples.rst
  sphinx/source/docs/examples/models.rst
  sphinx/source/docs/examples/plotting.rst
  sphinx/source/docs/gallery.rst
  sphinx/source/docs/reference/sampledata.rst
Labels: status: WIP

#12199 Pin Selenium 4.2
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  environment.yml
  sphinx/.gitignore
Labels: tag: component: tests, status: accepted, reso: completed

#12200 Update for latest Sphinx and pydata theme
  bokeh/models/tiles.py
  bokeh/settings.py
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  ci/environment-test-minimal-deps.yml
  environment.yml
  sphinx/docserver.py
  sphinx/source/_static/custom.css
  sphinx/source/_static/custom.js
  sphinx/source/_templates/docs-navbar.html
  sphinx/source/_templates/footer.html
  sphinx/source/_templates/layout.html
  sphinx/source/_templates/navbar-logo.html
  sphinx/source/_templates/sections/footer.html
  sphinx/source/conf.py
  sphinx/source/docs/dev_guide.rst
  sphinx/source/docs/first_steps.rst
  sphinx/source/index.rst
  sphinx/switcher.json
  sphinx/versions.json
  tests/codebase/test_json.py
  tests/unit/bokeh/test_settings.py
Labels: tag: component: docs, status: accepted, type: task
