Repository bokeh/bokeh, pull requests merged in 2022-02, with the labels that each got.

#11986 Fix `package-lock.json` and `update_bokehjs_versions()`
  bokehjs/package-lock.json
  release/build.py
Labels: type: bug, status: accepted, reso: completed, tag: component: build

#11989 Update Sphinx template to remove whitespace
  sphinx/source/_templates/layout.html
Labels: status: accepted

#11993 Add sphinx_copybutton
  ci/environment-release-build.yml
  ci/environment-test-3.10.yml
  ci/environment-test-3.8.yml
  ci/environment-test-3.9.yml
  environment.yml
  sphinx/source/conf.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12005 Allow to update color mapper of a color bar
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12001__doesn't_allow_updating_color_mapper_of_a_color_bar.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12001__doesn't_allow_updating_color_mapper_of_a_color_bar.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12001__doesn't_allow_updating_palette_of_a_color_mapper_of_a_color_bar.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12001__doesn't_allow_updating_palette_of_a_color_mapper_of_a_color_bar.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12007 Allow passing AnyRef to CustomJSHover
  bokeh/models/tools.py
Labels: status: accepted

#12004 Don't render if inspection indices didn't change
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#12010 Remove references to gen.coroutine from docs and update without_document_lock decorator
  bokeh/document/locking.py
  sphinx/source/docs/user_guide/server.rst
  tests/unit/bokeh/document/test_locking.py
Labels: status: accepted

#12011 Silence deprecation and other warnings in integration tests
  bokeh/_testing/util/selenium.py
  tests/integration/embed/test_json_item.py
  tests/integration/widgets/test_autocomplete_input.py
  tests/integration/widgets/test_checkbox_group.py
  tests/integration/widgets/test_dateslider.py
  tests/integration/widgets/test_multi_choice.py
  tests/integration/widgets/test_radio_group.py
  tests/integration/widgets/test_select.py
  tests/unit/bokeh/embed/test_standalone.py
  typings/selenium/webdriver/common/by.pyi
  typings/selenium/webdriver/remote/webdriver.pyi
  typings/selenium/webdriver/remote/webelement.pyi
  typings/selenium/webdriver/support/expected_conditions.pyi
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: codebase

#12009 Add metadata to tile_source.py and fix various typos
  examples/app/README.md
  examples/app/gapminder/main.py
  examples/app/spectrogram/description.html
  examples/custom/parallel_plot/parallel_selection_tool.ts
  examples/embed/arguments/README.md
  examples/embed/server_session/serve.py
  examples/howto/Categorical Data.ipynb
  examples/howto/Linked panning.ipynb
  examples/howto/ipywidgets/README.md
  examples/howto/layouts/words_and_plots.py
  examples/howto/notebook_comms/Continuous Updating.ipynb
  examples/howto/notebook_comms/Numba Image Example.ipynb
  examples/howto/server_embed/flask_gunicorn_embed.py
  examples/howto/server_embed/notebook_embed.ipynb
  examples/models/file/iris_splom.py
  examples/plotting/file/bessel.py
  examples/plotting/file/box_annotation.py
  examples/plotting/file/custom_layout.py
  examples/plotting/file/latex_blackbody_radiation.py
  examples/plotting/file/les_mis.py
  examples/plotting/file/ridgeplot.py
  examples/plotting/file/tile_source.py
Labels: tag: component: docs, status: accepted, type: task, tag: component: examples

#12025 Clarify docs regarding necessity of Firefox
  sphinx/source/docs/user_guide/export.rst
Labels: status: accepted
