Repository bokeh/bokeh, pull requests merged in 2022-12, with the labels that each got.

#12659 Adapt Bokeh logo for dark theme and add docs badge in README.md
  README.md
Labels: tag: component: docs, status: ready, type: task

#12656 Add default styles to FILE template
  .gitignore
  src/bokeh/core/_templates/file.html
  tests/examples.yaml
Labels: status: accepted

#12623 Ensure change callback manipulation is threadsafe
  src/bokeh/document/callbacks.py
  tests/unit/bokeh/document/test_callbacks__document.py
Labels: type: bug, status: accepted, reso: completed

#12663 Updates for 3.0.0
  docs/bokeh/source/docs/releases/3.0.2.rst
  docs/bokeh/source/docs/releases/3.0.3.rst
  docs/bokeh/switcher.json
Labels: status: accepted, type: task, reso: completed

#12676 Remove legacy `CanvasRenderingContext2D` polyfills
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/core/visuals/line.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/annotations/html/label_set.ts
  bokehjs/src/lib/models/annotations/html/text_annotation.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/test/unit/core/visuals.ts
  examples/server/app/spectrogram/waterfall.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#12596 Don't allow hover tool's tooltips to show outside the frame
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12410__allows_positioning_of_hover_tool_tooltips_outside_the_frame.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12410__allows_positioning_of_hover_tool_tooltips_outside_the_frame.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12649 Use circle centers for rect/poly hit testing
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12592__allows_to_select_circles_outside_the_selection_geometry.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12592__allows_to_select_circles_outside_the_selection_geometry.png
  bokehjs/test/baselines/linux/Color_mapping__with_multiple_domains__should_work_after_selection.png
  bokehjs/test/integration/color_mapping.ts
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12685 Add support for CSS modules to extensions' compiler
  bokehjs/make/package.json
  bokehjs/make/tasks/scripts.ts
  bokehjs/package-lock.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/compiler/styles.ts
Labels: status: accepted, type: task, reso: completed, tag: component: build

#12688 Expose stylesheet model API publicly
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/core/util/menus.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/dom/index.ts
  bokehjs/src/lib/models/dom/stylesheets.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/ui/icons/builtin_icon.ts
  bokehjs/src/lib/models/ui/icons/svg_icon.ts
  bokehjs/src/lib/models/ui/icons/tabler_icon.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  examples/advanced/extensions/font-awesome/fontawesome_icon.ts
  src/bokeh/models/css.py
  src/bokeh/models/ui/ui_element.py
  tests/baselines/defaults.json5
Labels: type: feature, status: accepted, reso: completed, tag: API: models

#12690 Replace numpy.bool8 with numpy.bool_
  src/bokeh/core/property/primitive.py
  tests/unit/bokeh/core/property/test_primitive.py
Labels: status: accepted

#12698 Fix typo.
  docs/bokeh/source/docs/user_guide/topics/timeseries.rst
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#12694 Fix tooltip ug entry
  docs/bokeh/source/docs/reference/models/widgets.rst
  docs/bokeh/source/docs/user_guide/interaction/widgets.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed
