Repository bokeh/bokeh, pull requests merged in 2023-03, with the labels that each got.

#12874 Improve layout of `GridPlot` with expanding children
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/models/common/kinds.ts
  bokehjs/src/lib/models/layouts/css_grid_box.ts
  bokehjs/src/lib/models/layouts/grid_box.ts
  bokehjs/src/lib/models/layouts/hbox.ts
  bokehjs/src/lib/models/layouts/vbox.ts
  bokehjs/src/lib/models/plots/grid_plot.ts
  bokehjs/test/baselines/linux/3x3_GridBox__fixed_and_3_x-max_spacers,_c2_size=100px_and_align=end.blf
  bokehjs/test/baselines/linux/3x3_GridBox__fixed_and_3_x-max_spacers,_c2_size=100px_and_align=end.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12863__doesn't_allow_GridPlot_with_plots_all_with_sizing_mode='stretch_width'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12863__doesn't_allow_GridPlot_with_plots_all_with_sizing_mode='stretch_width'.png
  bokehjs/test/baselines/linux/HBox__should_allow_to_expand_horizontally_when_width_policy_is_'max'.blf
  bokehjs/test/baselines/linux/HBox__should_allow_to_expand_horizontally_when_width_policy_is_'max'.png
  bokehjs/test/baselines/linux/VBox__should_allow_to_expand_vertically_when_height_policy_is_'max'.blf
  bokehjs/test/baselines/linux/VBox__should_allow_to_expand_vertically_when_height_policy_is_'max'.png
  bokehjs/test/integration/layouts.ts
  bokehjs/test/integration/regressions.ts
  src/bokeh/core/property_aliases.py
  src/bokeh/models/layouts.py
  src/bokeh/models/plots.py
  tests/baselines/defaults.json5
Labels: status: accepted

#12635 Ship `*.js` and `*.d.ts` together under `build/js/lib`
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokehjs-ci.yml
  .github/workflows/composite/test-setup/action.yml
  MANIFEST.in
  bokehjs/examples/tsconfig.json
  bokehjs/make/paths.ts
  bokehjs/make/tasks/build.ts
  bokehjs/make/tasks/index.ts
  bokehjs/make/tasks/pack.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/package.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/compile.ts
  bokehjs/src/compiler/compiler.ts
  bokehjs/src/compiler/main.ts
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/lib/document/defs.ts
  bokehjs/src/lib/tsconfig.json
  bokehjs/src/server/tsconfig.json
  bokehjs/test/defaults/tsconfig.json
  bokehjs/test/integration/tsconfig.json
  bokehjs/test/unit/tsconfig.json
  examples/advanced/extensions/gears/package.json
  examples/advanced/extensions/gears/tsconfig.json
  src/bokeh/util/compiler.py
  tests/examples.yaml
  tests/test_examples.py
  tests/unit/bokeh/embed/ext_package_no_main/index.ts
  tests/unit/bokeh/embed/ext_package_no_main/package-lock.json
  tests/unit/bokeh/embed/ext_package_no_main/package.json
  tests/unit/bokeh/embed/ext_package_no_main/tsconfig.json
  tests/unit/bokeh/embed/latex_label/latex_label.ts
  tests/unit/bokeh/embed/latex_label/package-lock.json
  tests/unit/bokeh/embed/latex_label/package.json
  tests/unit/bokeh/embed/latex_label/tsconfig.json
Labels: status: accepted

#12836 Don't re-render when `css_classes` or `stylesheets` change
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/core/util/menus.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/layouts/group_box.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/layouts/scroll_box.ts
  bokehjs/src/lib/models/layouts/tabs.ts
  bokehjs/src/lib/models/menus/menu.ts
  bokehjs/src/lib/models/menus/menu_item.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/ui/dialog.ts
  bokehjs/src/lib/models/ui/examiner.ts
  bokehjs/src/lib/models/ui/icons/builtin_icon.ts
  bokehjs/src/lib/models/ui/icons/svg_icon.ts
  bokehjs/src/lib/models/ui/icons/tabler_icon.ts
  bokehjs/src/lib/models/ui/tooltip.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/src/lib/models/widgets/abstract_button.ts
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  bokehjs/src/lib/models/widgets/checkbox.ts
  bokehjs/src/lib/models/widgets/dropdown.ts
  bokehjs/src/lib/models/widgets/file_input.ts
  bokehjs/src/lib/models/widgets/input_widget.ts
  bokehjs/src/lib/models/widgets/markup.ts
  bokehjs/src/lib/models/widgets/multi_choice.ts
  bokehjs/src/lib/models/widgets/password_input.ts
  bokehjs/src/lib/models/widgets/picker_base.ts
  bokehjs/src/lib/models/widgets/switch.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/src/lib/models/widgets/toggle_button_group.ts
  bokehjs/src/lib/models/widgets/toggle_input_group.ts
  bokehjs/test/unit/models/ui/ui_element.ts
  examples/advanced/extensions/font-awesome/fontawesome_icon.ts
  examples/advanced/extensions/ion_range_slider.ts
  src/bokeh/models/layouts.py
  src/bokeh/models/ui/ui_element.py
  tests/baselines/defaults.json5
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#12881 Make editable `BoxAnnotation` respect frame bounds
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12880__doesn't_allow_editable_BoxAnnotation_to_respect_frame_bounds.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12880__doesn't_allow_editable_BoxAnnotation_to_respect_frame_bounds.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12882 Fix alignment in `_templates/file.html`
  src/bokeh/core/_templates/file.html
Labels: type: bug, status: accepted, tag: regression, reso: completed

#12889 Fix `FullscreenTool` in Chromium and WebKit based browsers
  bokehjs/src/lib/es.d.ts
  bokehjs/src/lib/models/tools/actions/fullscreen_tool.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/test/framework.ts
  bokehjs/test/unit/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/models/ui/ui_element.ts
Labels: status: accepted

#12887 Call to_numpy when encoding series to ensure a numpy ndarray is returned
  src/bokeh/util/serialization.py
Labels: status: accepted

#12895 Allow providing websocket origin if unix-socket is enabled
  src/bokeh/command/subcommands/serve.py
  src/bokeh/server/server.py
  tests/unit/bokeh/command/subcommands/test_serve.py
Labels: status: accepted

#12884 Update `plotting/css_classes.py` to use stylesheets
  bokehjs/src/less/base.less
  examples/plotting/css_classes.py
  src/bokeh/io/saving.py
Labels: status: accepted

#12910 updated commands with correct links to executable
  docs/bokeh/source/docs/dev_guide/setup.rst
Labels: status: accepted

#12915 Warn about already known references, but don't fail
  bokehjs/src/lib/core/serialization/deserializer.ts
  src/bokeh/core/serialization.py
  tests/unit/bokeh/core/test_serialization.py
Labels: status: accepted, type: task, reso: completed

#12886 CSS styling docs / Updates for 3.1
  .pre-commit-config.yaml
  docs/bokeh/source/docs/reference/models/css.rst
  docs/bokeh/source/docs/releases/3.1.0.rst
  docs/bokeh/source/docs/user_guide/styling.rst
  docs/bokeh/source/docs/user_guide/styling/dom.rst
  docs/bokeh/switcher.json
  examples/styling/dom/css_classes.py
  examples/topics/geo/eclipse.py
  examples/topics/hierarchical/crosstab.py
  src/bokeh/models/css.py
Labels: status: accepted

#12925 Ignore NaNs when auto-ranging renderers
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12917__doesn't_allow_BoxAnnotation_to_participate_in_auto-ranging_when_its_edges_are_bound_to_the_frame.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12917__doesn't_allow_BoxAnnotation_to_participate_in_auto-ranging_when_its_edges_are_bound_to_the_frame.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12921 Misc 3.1 docs issues
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/_images/examples/interaction/widgets/date_picker.png
  docs/bokeh/source/_images/examples/interaction/widgets/date_picker@2x.png
  docs/bokeh/source/_images/examples/topics/images/image.png
  docs/bokeh/source/_images/examples/topics/images/image@2x.png
  docs/bokeh/source/_images/examples/topics/images/image_rgba.png
  docs/bokeh/source/_images/examples/topics/images/image_rgba@2x.png
Labels: status: ready

#12932 Fix server gallery by renaming `*.png` files
  docs/bokeh/source/_images/examples/server/app/gapminder.png
  docs/bokeh/source/_images/examples/server/app/movies.png
Labels: status: accepted, NEEDS FORWARD PORT

#12928 Copy files if symlinking fails in 'pack' build task
  bokehjs/make/tasks/pack.ts
Labels: status: accepted

#12899 List installed software and versions in CI
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokehjs-ci.yml
  docs/bokeh/source/docs/dev_guide/setup.rst
  scripts/ci/install_node_modules.sh
Labels: status: accepted

#12939 add ref
  src/bokeh/models/annotations/legends.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12933 Added metadata for block.py file
  examples/basic/areas/block.py
Labels: status: accepted

#12930 Added metadata to colors.py
  examples/models/colors.py
Labels: status: accepted

#12908 Added metadata to tap.py for Tap Plots
  examples/plotting/tap.py
Labels: status: accepted

#12906 added metadata to standalone examples
  examples/interaction/js_callbacks/customjs_for_hover.py
  examples/interaction/js_callbacks/customjs_for_selection.py
Labels: status: accepted

#12796 Implement VAreaStep and HAreaStep for area fills with step lines
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/core/util/flip_step_mode.ts
  bokehjs/src/lib/models/glyphs/harea_step.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/varea_step.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_HAreaStep.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_HAreaStep.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_VAreaStep.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_VAreaStep.png
  bokehjs/test/integration/glyphs/glyphs.ts
  examples/basic/areas/harea_step.py
  examples/basic/areas/varea_step.py
  src/bokeh/models/glyphs.py
  src/bokeh/plotting/_figure.py
  src/bokeh/plotting/glyph_api.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_glyphs.py
Labels: status: ready

#12944 Forward ports from 3.1
  .pre-commit-config.yaml
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/baselines/linux/Bug__in_issue_#12917__doesn't_allow_BoxAnnotation_to_participate_in_auto-ranging_when_its_edges_are_bound_to_the_frame.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12917__doesn't_allow_BoxAnnotation_to_participate_in_auto-ranging_when_its_edges_are_bound_to_the_frame.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/package.json
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  docs/CHANGELOG
  docs/bokeh/source/_images/examples/interaction/widgets/date_picker.png
  docs/bokeh/source/_images/examples/interaction/widgets/date_picker@2x.png
  docs/bokeh/source/_images/examples/server/app/gapminder.png
  docs/bokeh/source/_images/examples/server/app/movies.png
  docs/bokeh/source/_images/examples/topics/images/image.png
  docs/bokeh/source/_images/examples/topics/images/image@2x.png
  docs/bokeh/source/_images/examples/topics/images/image_rgba.png
  docs/bokeh/source/_images/examples/topics/images/image_rgba@2x.png
  docs/bokeh/source/docs/reference/models/css.rst
  docs/bokeh/source/docs/releases/3.1.0.rst
  docs/bokeh/source/docs/user_guide/styling.rst
  docs/bokeh/source/docs/user_guide/styling/dom.rst
  docs/bokeh/switcher.json
  examples/plotting/tap.py
  examples/styling/dom/css_classes.py
  examples/topics/geo/eclipse.py
  examples/topics/hierarchical/crosstab.py
  scripts/sri.py
  src/bokeh/_sri.json
  src/bokeh/models/css.py
Labels: status: accepted, type: task, reso: completed

#12900 Allow to correctly sort international strings in `DataTable`
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#12720 Drop support for Python 3.8
  .github/workflows/bokeh-ci.yml
  conda/environment-build.yml
  conda/environment-release-build.yml
  conda/environment-release-deploy.yml
  conda/environment-test-3.8.yml
  conda/environment-test-minimal-deps.yml
  conda/recipe/meta.yaml
  docs/bokeh/source/docs/first_steps.rst
  docs/bokeh/source/docs/releases/3.2.0.rst
  pyproject.toml
  scripts/docker/docker_run.sh
Labels: status: accepted, type: task, reso: completed, tag: codebase

#12953 Update to Bokeh example plot: accessible palette with new images
  docs/bokeh/source/_images/examples/basic/bars/pandas_groupby_nested.png
  docs/bokeh/source/_images/examples/basic/bars/pandas_groupby_nested@2x.png
  examples/basic/bars/pandas_groupby_nested.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#12955 Upload latest docs more cleanly
  release/deploy.py
Labels: status: ready

#12963 Temporarily disable docker_from_wheel test in CI
  .github/workflows/bokeh-ci.yml
Labels: tag: component: tests, status: ready, type: task, tag: docker

#12935 Document lack of serialization support for decimal.Decimal under Serializer class
  src/bokeh/core/serialization.py
Labels: status: accepted

#12892 Add tests for custom arrayable functions
  bokehjs/test/unit/core/util/arrayable.ts
Labels: status: accepted

#12922 Updated colors of Band Plots
  docs/bokeh/source/_images/examples/basic/annotations/band.png
  docs/bokeh/source/_images/examples/basic/annotations/band@2x.png
  examples/basic/annotations/band.py
Labels: type: task, tag: component: examples, python

#12959 Increased alpha of the circle plot
  examples/basic/annotations/slope.py
Labels: status: accepted, type: task, tag: component: examples

#12920 Added metadata to legends.py
  examples/models/legends.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12950 added metadata to twin_axis.py
  examples/models/transform_jitter.py
  examples/models/twin_axis.py
Labels: status: accepted, type: task, reso: completed

#12982 Update example metadata
  examples/basic/areas/block.py
  examples/models/twin_axis.py
Labels: tag: component: docs, status: accepted, type: task

#12902 Use CSS-safe IDs in generated HTML
  src/bokeh/embed/util.py
  src/bokeh/io/notebook.py
  src/bokeh/util/serialization.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/util/test_util__serialization.py
Labels: status: accepted

#12896 Finalize inlining of SlickGrid's images in CSS
  bokehjs/src/less/widgets/slickgrid.less
Labels: status: accepted

#12977 Upgrade to TypeScript 5.0
  bokehjs/eslint.json
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/lib/core/util/text.ts
  bokehjs/src/lib/document/defs.ts
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs, tag: typescript

#12984 Added reference for server.py file
  src/bokeh/server/server.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12975 11765 added metadata to plot
  examples/basic/annotations/legends_item_visibility.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#12923 added accessible color palette
  docs/bokeh/source/_images/examples/styling/mathtext/latex_schrodinger.png
  docs/bokeh/source/_images/examples/styling/mathtext/latex_schrodinger@2x.png
  examples/styling/mathtext/latex_schrodinger.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#12995 Updated server.py reference
  src/bokeh/server/server.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13002 Added troubleshooting for issue #13001
  docs/bokeh/source/docs/dev_guide/setup.rst
Labels: status: accepted

#13009 Add dropdowns to contributor docs troubleshooting
  docs/bokeh/source/docs/dev_guide/setup.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12990 Update text.py with metadata
  examples/plotting/text.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12998 Added metadata to band.py for Band Plots
  examples/basic/annotations/band.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12979 Add metadata to plots (#11765)
  docs/bokeh/source/docs/user_guide/basic/data.rst
  docs/bokeh/source/docs/user_guide/basic/scatters.rst
  examples/basic/scatters/image_url.py
  examples/plotting/customjs_expr.py
  examples/plotting/filtering.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13006 11765 image alpha
  examples/plotting/image_alpha.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12993 Added metadata to two plots
  examples/basic/annotations/label.py
  examples/basic/annotations/whisker.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13003 Added metadata to line_on_off.py
  examples/plotting/line_on_off.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13013 Updated colors of Slope Plots
  docs/bokeh/source/_images/examples/basic/annotations/slope.png
  docs/bokeh/source/_images/examples/basic/annotations/slope@2x.png
  examples/basic/annotations/slope.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples, tag: accessibility

#12991 Added metadata to setvalue.py
  examples/interaction/js_callbacks/setvalue.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#13024 changed span example lines from solid to dashed
  docs/bokeh/source/_images/examples/basic/annotations/span.png
  docs/bokeh/source/_images/examples/basic/annotations/span@2x.png
  examples/basic/annotations/span.py
Labels: tag: component: docs, status: accepted, type: task, tag: component: examples, tag: accessibility

#12962 Check for git tags before build
  setup.py
Labels: status: ready

#13014 Added Toolbar.py metadata
  examples/models/toolbars.py
Labels: tag: component: docs, status: accepted, reso: completed, tag: component: examples

#13026 Tile source metadata
  examples/models/tile_source.py
Labels: tag: component: docs, status: WIP, type: task, tag: component: examples

#13023 11765 maps cities
  examples/models/maps_cities.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#13022 Line select metadata
  examples/plotting/line_select.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#13012 Added metadata to examples/plotting/aspect.py
  examples/plotting/aspect.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#13021 histogram.py plot updated with more accessible colors
  examples/plotting/histogram.py
Labels: status: WIP

#13018 Updating nested_colormapped with new accessible palettes
  docs/bokeh/source/_images/examples/basic/bars/nested_colormapped.png
  docs/bokeh/source/_images/examples/basic/bars/nested_colormapped@2x.png
  examples/basic/bars/nested_colormapped.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples, tag: accessibility
