Repository bokeh/bokeh, pull requests merged in 2023-11, with the labels that each got.

#13506 Misc 3.3.1 release docs
  docs/bokeh/source/docs/releases/3.3.1.rst
  docs/bokeh/switcher.json
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13078 fix spinner precision
  bokehjs/src/lib/models/widgets/spinner.ts
  bokehjs/test/unit/models/widgets/spinner.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13510 Convert value of `BOKEH_DEFAULT_SERVER_PORT` to `int`
  src/bokeh/settings.py
  tests/unit/bokeh/test_settings.py
Labels: type: bug, status: accepted, reso: completed, python

#13497 Allow `Select` to select values of any type
  bokehjs/src/lib/models/dom/html.ts
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/src/lib/models/widgets/input_widget.ts
  bokehjs/src/lib/models/widgets/select.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#10407__displays_out-of-range_value_in_Select_widget_when_options_change.png
  bokehjs/test/baselines/linux/Widgets__should_allow_MultiChoice_with_empty_value.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_MultiChoice_with_empty_value.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Select_with_empty_value.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Select_with_empty_value.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Select_with_non-string_options.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Select_with_non-string_options.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/widgets.ts
  examples/models/widgets.py
  src/bokeh/models/dom.py
  src/bokeh/models/widgets/inputs.py
  tests/unit/bokeh/models/test_dom.py
Labels: status: ready

#13501 Fix scoping issue for box edit tool coordinates
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/test/interactive.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#13514 fix indentation in property mixins
  src/bokeh/core/property/color.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/core/property_mixins.py
  src/bokeh/models/tools.py
Labels: tag: component: docs, status: accepted, reso: completed

#13042 Improvements around `BOKEH_DEV=true` workflow
  bokehjs/package-lock.json
  bokehjs/test/devtools/server.ts
  bokehjs/test/package.json
  docs/bokeh/source/docs/dev_guide/setup.rst
  docs/bokeh/source/docs/releases/3.4.0.rst
  src/bokeh/command/subcommands/info.py
  src/bokeh/command/subcommands/static.py
  src/bokeh/core/_templates/autoload_js.js
  src/bokeh/embed/bundle.py
  src/bokeh/ext.py
  src/bokeh/resources.py
  src/bokeh/server/views/static_handler.py
  src/bokeh/settings.py
  src/bokeh/util/compiler.py
  src/bokeh/util/paths.py
  tests/test_examples.py
  tests/unit/bokeh/embed/test_bundle.py
  tests/unit/bokeh/server/test_tornado__server.py
  tests/unit/bokeh/server/views/test_multi_root_static_handler.py
Labels: status: accepted

#13534 Upgrade mypy to version 1.7 and fix type issues
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  src/bokeh/colors/color.py
  src/bokeh/embed/standalone.py
  src/bokeh/server/tornado.py
  src/bokeh/util/serialization.py
Labels: status: accepted

#13537 Rename `ColorMap` to `PaletteSelect` and improve it
  bokehjs/src/less/panes.less
  bokehjs/src/less/widgets/palette_select.less
  bokehjs/src/less/widgets/palette_select_item.less
  bokehjs/src/less/widgets/palette_select_pane.less
  bokehjs/src/lib/models/widgets/color_map.ts
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_default_settings.blf
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_default_settings.png
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_disabled=true.blf
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_disabled=true.png
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_ncols=3.blf
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_ncols=3.png
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_default_settings.blf
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_default_settings.png
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_disabled=true.blf
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_disabled=true.png
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_ncols=3.blf
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_ncols=3.png
  bokehjs/test/integration/widgets.ts
  docs/bokeh/source/docs/releases/3.4.0.rst
  examples/interaction/widgets/color_map.py
  examples/models/widgets.py
  src/bokeh/models/widgets/inputs.py
  tests/baselines/defaults.json5
Labels: status: accepted, type: task, reso: completed, tag: widgets

#13523 Enable `'use strict';`, improve error handling and update `@bokeh/slickgrid`
  bokehjs/package-lock.json
  bokehjs/src/compiler/prelude.ts
  bokehjs/src/lib/core/util/modules.ts
  bokehjs/src/lib/models/text/providers.ts
  bokehjs/src/lib/package.json
  docs/bokeh/source/docs/releases/3.4.0.rst
  src/bokeh/core/_templates/autoload_js.js
  src/bokeh/core/_templates/autoload_nb_js.js
  tests/unit/bokeh/core/test_templates.py
Labels: status: accepted

#13543 Make `assert_debug` preconditions lazy in `bisect_*()`
  bokehjs/src/lib/core/util/arrayable.ts
Labels: status: accepted

#13532 Update contour line calculations to use ContourPy's LineType.ChunkCombinedNan
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
  src/bokeh/plotting/contour.py
Labels: status: ready

#13527 Multiple density estimate plot
  docs/bokeh/source/_images/examples/topics/stats/cows.png
  docs/bokeh/source/_images/examples/topics/stats/cows@2x.png
  docs/bokeh/source/docs/gallery.json
  docs/bokeh/source/docs/user_guide/topics/stats.rst
  examples/topics/stats/density.py
  src/bokeh/sampledata/_data/cows.csv
  src/bokeh/sampledata/cows.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#13518 Add support for CDS/EditTool default values and overrides
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/test/unit/document/defs.ts
  bokehjs/test/unit/models/sources/column_data_source.ts
  bokehjs/test/unit/models/tools/edit/box_edit_tool.ts
  bokehjs/test/unit/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/point_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/poly_edit_tool.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/user_guide/interaction/tools.rst
  examples/interaction/tools/box_edit.py
  examples/interaction/tools/point_draw.py
  src/bokeh/models/sources.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
Labels: status: accepted

#13528 Restored broken API links
  docs/bokeh/source/docs/dev_guide/setup.rst
  docs/bokeh/source/docs/user_guide/basic/scatters.rst
  examples/basic/annotations/band.py
  examples/basic/annotations/box_annotation.py
  examples/basic/annotations/slope.py
  examples/basic/data/color_mappers.py
  examples/basic/scatters/elements.py
  examples/interaction/legends/legend_hide.py
  examples/interaction/linking/linked_brushing.py
  examples/styling/mathtext/latex_axis_labels_titles_labels.py
  examples/styling/mathtext/latex_bessel.py
  examples/styling/mathtext/latex_schrodinger.py
  examples/topics/categorical/heatmap_unemployment.py
  examples/topics/geo/eclipse.py
  examples/topics/stats/splom.py
Labels: status: ready

#13540 Decouple `Tool` event handlers from state/active management
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/unit/core/ui_events.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#13549 fix indentation in sphinx extentions
  src/bokeh/sphinxext/bokeh_color.py
  src/bokeh/sphinxext/bokeh_dataframe.py
  src/bokeh/sphinxext/bokeh_enum.py
  src/bokeh/sphinxext/bokeh_jinja.py
  src/bokeh/sphinxext/bokeh_model.py
  src/bokeh/sphinxext/bokeh_options.py
  src/bokeh/sphinxext/bokeh_palette.py
  src/bokeh/sphinxext/bokeh_palette_group.py
  src/bokeh/sphinxext/bokeh_prop.py
Labels: status: accepted

#13468 Set more sensible defaults in BoxAnnotation
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  src/bokeh/models/annotations/geometry.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_annotations.py
Labels: status: accepted, NEEDS BACK PORT

#13545 Add support for xor selection and inversion
  bokehjs/src/less/icons.less
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/selection_manager.ts
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/test/baselines/linux/Icons__should_support_all_icons_defined_in_less_icons.less.png
  bokehjs/test/baselines/linux/Tools__should_support_BoxSelectTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_BoxSelectTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_BoxZoomTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_BoxZoomTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_LassoSelectTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_LassoSelectTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_PanTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_PanTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_PolySelectTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_PolySelectTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_SaveTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_SaveTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_TapTool's_setup_menu.blf
  bokehjs/test/baselines/linux/Tools__should_support_TapTool's_setup_menu.png
  bokehjs/test/integration/tools/tools.ts
  bokehjs/test/unit/core/enums.ts
  bokehjs/test/unit/core/util/array.ts
  bokehjs/test/unit/models/selections/selection.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/_images/icons/InvertSelection.png
  docs/bokeh/source/_images/icons/XorMode.png
  docs/bokeh/source/docs/releases/3.4.0.rst
  src/bokeh/core/enums.py
  src/bokeh/models/selections.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#13559 Fix support for global/local imported stylesheets
  bokehjs/src/lib/core/util/defer.ts
  bokehjs/src/lib/models/dom/stylesheets.ts
  bokehjs/test/assets/css/global.css
  bokehjs/test/assets/css/local.css
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13564 Update the output type for the __new__ function in Model
  src/bokeh/model/model.py
Labels: status: accepted
