Repository bokeh/bokeh, pull requests merged in 2023-05, with the labels that each got.

#13113 Fix visual-like glyph data in derived glyphs
  bokehjs/src/lib/embed/index.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13112__doesn't_allow_to_render_Text_glyph_when_using_selection_indices.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13112__doesn't_allow_to_render_Text_glyph_when_using_selection_indices.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13094 Update docs infrastructure
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/_static/custom.css
  docs/bokeh/source/_templates/layout.html
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/first_steps.rst
  docs/bokeh/source/docs/gallery.rst
  docs/bokeh/source/docs/reference/model.rst
  docs/bokeh/source/docs/reference/plotting/figure.rst
  docs/bokeh/source/docs/reference/plotting/gmap.rst
  docs/bokeh/source/index.rst
  scripts/ci/build_docs.sh
  src/bokeh/application/application.py
  src/bokeh/application/handlers/code.py
  src/bokeh/application/handlers/code_runner.py
  src/bokeh/application/handlers/directory.py
  src/bokeh/application/handlers/document_lifecycle.py
  src/bokeh/application/handlers/function.py
  src/bokeh/application/handlers/handler.py
  src/bokeh/application/handlers/lifecycle.py
  src/bokeh/application/handlers/notebook.py
  src/bokeh/application/handlers/request_handler.py
  src/bokeh/application/handlers/script.py
  src/bokeh/application/handlers/server_lifecycle.py
  src/bokeh/application/handlers/server_request_handler.py
  src/bokeh/client/connection.py
  src/bokeh/client/session.py
  src/bokeh/core/has_props.py
  src/bokeh/document/document.py
  src/bokeh/io/state.py
  src/bokeh/server/auth_provider.py
  src/bokeh/server/connection.py
  src/bokeh/server/contexts.py
  src/bokeh/server/server.py
  src/bokeh/server/session.py
  src/bokeh/server/tornado.py
  src/bokeh/sphinxext/_templates/model_detail.rst
Labels: tag: component: docs, status: accepted, type: task

#13123 Don't require tags for sdist install
  scripts/ci/verify_pip_install_from_sdist.sh
  scripts/ci/verify_pip_install_using_sdist.sh
  setup.py
Labels: status: accepted

#12992 Update metadata to legend_hide and tile_xyzservices
  examples/interaction/legends/legend_hide.py
  examples/topics/geo/tile_xyzservices.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#13135 Fix typo
  src/bokeh/transform.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13140 Do not blit webgl canvas if width or height are zero
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/test/unit/regressions.ts
Labels: status: ready, type: task, tag: component: bokehjs, tag: webgl

#13144 Remove Ruff pyugrade keep-runtime-annotations
  pyproject.toml
Labels: status: accepted

#13032 11571 autocomplete match substring
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/models/widgets/autocomplete_input.ts
  docs/bokeh/source/docs/user_guide/interaction/widgets.rst
  examples/interaction/widgets/autocompleteinput.py
  examples/models/widgets.py
  src/bokeh/models/widgets/inputs.py
  tests/baselines/defaults.json5
Labels: status: accepted

#13085 Correctly set Scatter.max_size
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/marker.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13118 Fix unhelpful error messages in bokeh.embed.file_html
  src/bokeh/embed/standalone.py
  src/bokeh/embed/util.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/embed/test_util__embed.py
Labels: status: accepted

#13154 Pin transitive dependency urllib3 <2
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
Labels: status: accepted

#13151 Fix rendering of `GraphRenderer` when using `webgl` backend
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13150__doesn't_allow_correctly_render_GraphRenderer_with_output_backend='webgl'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13150__doesn't_allow_correctly_render_GraphRenderer_with_output_backend='webgl'.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13132 Allow to configure and report key modifiers in `TapTool` and pointer events
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/src/lib/models/annotations/span.ts
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/region_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/ui_events.ts
  bokehjs/test/unit/models/tools/edit/_util.ts
  bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts
  bokehjs/test/unit/models/tools/gestures/tap_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
  docs/bokeh/source/docs/releases/3.2.0.rst
  examples/interaction/tools/tap_inspect_keymod.py
  src/bokeh/core/enums.py
  src/bokeh/events.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#12059 Add support for TeX titles to ColorBar
  bokehjs/src/lib/core/layout/layoutable.ts
  bokehjs/src/lib/models/annotations/base_color_bar.ts
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_TeX_title.blf
  bokehjs/test/baselines/linux/ColorBar_annotation__should_support_TeX_title.png
  bokehjs/test/integration/annotations/color_bar.ts
  src/bokeh/models/annotations/legends.py
Labels: status: accepted

#13153 Allow to recover from deserialization of a previously seen ref
  src/bokeh/core/serialization.py
  src/bokeh/document/document.py
  tests/unit/bokeh/core/test_serialization.py
  tests/unit/bokeh/document/test_document.py
Labels: status: accepted, type: task, reso: completed, tag: component: server

#13137 Allow ndarrays in `IndexFilter.indices` and add "cross" tests
  .github/workflows/bokeh-ci.yml
  bokehjs/.gitignore
  bokehjs/src/lib/models/filters/index_filter.ts
  bokehjs/test/assets/json/issue11930.json
  bokehjs/test/baselines/Bug__in_issue_#10749__prevents_DataTable_from_correctly_ordering_rows_and_formatting_string_dates
  bokehjs/test/baselines/linux/Bug__in_issue_#11694__doesn't_allow_'id'_key_in_mappings_and_confuses_them_with_refs.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11930__doesn't_allow_overriding_int_major_axis_labels_with_floats.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11930__doesn't_allow_overriding_int_major_axis_labels_with_floats.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13134__doesn't_allow_using_ndarrays_in_IndexFilter.indices.blf
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/devtools/server.ts
  bokehjs/test/framework.ts
  bokehjs/test/globals.d.ts
  bokehjs/test/integration/cross.ts
  bokehjs/test/integration/regressions.ts
  docs/bokeh/source/docs/dev_guide/testing.rst
  pyproject.toml
  src/bokeh/core/has_props.py
  src/bokeh/document/document.py
  src/bokeh/document/json.py
  src/bokeh/embed/bundle.py
  src/bokeh/protocol/message.py
  tests/baselines/cross/regressions/issue_11694.json5
  tests/baselines/cross/regressions/issue_11930.json5
  tests/baselines/cross/regressions/issue_13134.json5
  tests/cross/cases/regressions/issue_11694.py
  tests/cross/cases/regressions/issue_11930.py
  tests/cross/cases/regressions/issue_13134.py
  tests/test_cross.py
Labels: status: accepted

#13169 Don't turn warnings into errors in sphinx-build
  docs/bokeh/Makefile
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13031 Updated colors of Mixed Plots
  docs/bokeh/source/_images/examples/basic/bars/mixed.png
  docs/bokeh/source/_images/examples/basic/bars/mixed@2x.png
  examples/basic/bars/mixed.py
Labels: status: accepted, type: task, reso: completed, tag: accessibility

#12812 Add support for ES module (`import`/`export` syntax) callbacks
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/models/callbacks/callback.ts
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/src/lib/models/sources/ajax_data_source.ts
  bokehjs/src/lib/models/sources/server_sent_data_source.ts
  bokehjs/src/lib/models/sources/web_data_source.ts
  bokehjs/test/unit/core/util/array.ts
  bokehjs/test/unit/core/util/types.ts
  bokehjs/test/unit/models/callbacks/customjs.ts
  bokehjs/test/unit/models/sources/ajax_data_source.ts
  docs/bokeh/source/docs/releases/3.2.0.rst
  examples/advanced/integration/d3-voronoi.mjs
  examples/advanced/integration/d3-voronoi.py
  src/bokeh/model/model.py
  src/bokeh/models/callbacks.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_callbacks__models.py
Labels: type: feature, status: accepted, reso: completed, tag: API: models

#13167 Switch out GA for Plausible
  docs/bokeh/source/conf.py
Labels: tag: component: docs, status: ready, type: task
