Repository bokeh/bokeh, pull requests merged in 2023-04, with the labels that each got.

#12983 Improve color contrast for accessibility
  examples/topics/graph/node_and_edge_attributes.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#13041 Correctly resolve custom host and port with server resources
  docs/bokeh/source/docs/releases/3.2.0.rst
  src/bokeh/embed/bundle.py
  src/bokeh/embed/standalone.py
  src/bokeh/resources.py
  src/bokeh/server/server.py
  src/bokeh/server/tornado.py
  tests/unit/bokeh/embed/test_bundle.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/server/test_tornado__server.py
  tests/unit/bokeh/test_resources.py
Labels: status: accepted

#13057 Make `autocompleteinput.py` example work with Pandas 2.0
  examples/interaction/widgets/autocompleteinput.py
Labels: status: accepted

#13054 Update In-kind sponsors list
  README.md
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13062 Fix bokeh.sphinxext.util after PR #13041
  src/bokeh/resources.py
  src/bokeh/sphinxext/util.py
Labels: type: bug, status: accepted, tag: regression, reso: completed

#13061 Use libmamba solver in CI
  .github/workflows/bokeh-ci.yml
  .github/workflows/composite/test-setup/action.yml
Labels: status: accepted

#13065 Allow `static/` symlinks in `BOKEHJS_ACTION=install pip install -e .`
  setup.py
Labels: status: accepted, type: task, reso: completed, tag: component: build

#13044 Add support for `Axis.axis_label_orientation`
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/test/baselines/linux/LinearAxis__in_horizontal_orientation__above_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LinearAxis__in_horizontal_orientation__above_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LinearAxis__in_horizontal_orientation__below_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LinearAxis__in_horizontal_orientation__below_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LinearAxis__in_vertical_orientation__left_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LinearAxis__in_vertical_orientation__left_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LinearAxis__in_vertical_orientation__right_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LinearAxis__in_vertical_orientation__right_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LogAxis__in_horizontal_orientation__above_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LogAxis__in_horizontal_orientation__above_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LogAxis__in_horizontal_orientation__below_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LogAxis__in_horizontal_orientation__below_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LogAxis__in_vertical_orientation__left_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LogAxis__in_vertical_orientation__left_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/baselines/linux/LogAxis__in_vertical_orientation__right_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.blf
  bokehjs/test/baselines/linux/LogAxis__in_vertical_orientation__right_of_a_plot__should_support_single_line_axis_label_and_axis_label_orientation=normal.png
  bokehjs/test/integration/axes.ts
  bokehjs/test/unit/core/enums.ts
  docs/bokeh/source/docs/releases/3.2.0.rst
  src/bokeh/core/enums.py
  src/bokeh/models/axes.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#13069 Disable `na_filter` instead of ignoring incorrectly parsed NaNs
  examples/interaction/widgets/autocompleteinput.py
  src/bokeh/sampledata/world_cities.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#12779 enable filterwarnings=error
  examples/server/app/clustering/main.py
  examples/server/app/export_csv/main.py
  examples/server/app/image_blur.py
  examples/server/app/movies/main.py
  pyproject.toml
  src/bokeh/application/handlers/directory.py
  src/bokeh/core/has_props.py
  src/bokeh/io/util.py
  src/bokeh/sampledata/les_mis.py
  src/bokeh/sampledata/olympics2014.py
  src/bokeh/sampledata/us_cities.py
  src/bokeh/util/sampledata.py
  tests/codebase/test_json.py
  tests/support/plugins/bokeh_server.py
  tests/support/plugins/file_server.py
  tests/support/util/screenshot.py
  tests/test_examples.py
  tests/unit/bokeh/command/subcommands/test_serve.py
  tests/unit/bokeh/command/test_util__command.py
  tests/unit/bokeh/io/test_util__io.py
  tests/unit/bokeh/models/test_sources.py
  tests/unit/bokeh/server/test_util.py
Labels: status: accepted

#13082 Disable user select globally when dragging slider handles
  bokehjs/src/lib/models/widgets/abstract_slider.ts
Labels: status: accepted

#13084 Update first_steps_1.rst
  docs/bokeh/source/docs/first_steps/first_steps_1.rst
Labels: tag: component: docs, status: accepted, type: task

#13066 updated ReadMe file of examples folder
  examples/README.md
Labels: status: accepted

#13086 fix broken docs refs
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  examples/models/tile_source.py
  examples/plotting/line_on_off.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13059 Check if sample data files are outdated when loading them
  src/bokeh/util/sampledata.py
Labels: status: accepted

#13051 Added metadata for examples/models/toolbars2.py
  examples/models/toolbars2.py
Labels: status: WIP

#13043 added metadata to tooltip_content.py, arc.py
  docs/bokeh/source/docs/user_guide/basic/lines.rst
  examples/basic/lines/arcs.py
  examples/interaction/tooltips/tooltip_content.py
  examples/interaction/tooltips/tooltip_description.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples
