Repository bokeh/bokeh, pull requests merged in 2023-06, with the labels that each got.

#13178 Add ColorBar to LaTeX docs
  docs/bokeh/source/docs/user_guide/styling/mathtext.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: MathText

#13047 Added metadata to theme_glyphs
  examples/plotting/theme_glyphs.py
Labels: tag: component: docs, status: ready, type: task, tag: component: examples

#13160 Fix a couple of typos
  docs/bokeh/source/docs/user_guide/basic/axes.rst
  src/bokeh/models/formatters.py
Labels: status: accepted

#13174 Do not resolve default descriptor value if already present in unstable defaults
  src/bokeh/core/property/descriptors.py
Labels: status: ready, type: task, tag: performance

#13181 Add a regression test for issue #11852
  tests/unit/bokeh/test_regressions.py
Labels: status: accepted

#13173 Clean up the rest of eslint warnings and refactor its config
  bokehjs/eslint.js
  bokehjs/make/tasks/lint.ts
  bokehjs/src/compiler/build.ts
  bokehjs/src/lib/core/visuals/hatch.ts
  bokehjs/src/lib/models/glyphs/image.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/glyphs/image_stack.ts
  bokehjs/src/lib/models/glyphs/webgl/base_line.ts
  bokehjs/src/lib/models/glyphs/webgl/base_marker.ts
  docs/bokeh/source/docs/dev_guide/bokehjs.rst
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#13075 Fix issues with top-level widgets' margins
  bokehjs/src/lib/models/widgets/widget.ts
  src/bokeh/core/_templates/file.html
  src/bokeh/models/widgets/widget.py
  tests/baselines/defaults.json5
Labels: status: accepted

#13188 Update dom.rst
  docs/bokeh/source/docs/user_guide/styling/dom.rst
Labels: status: accepted

#13194 Allow to clear `DatePicker.enabled_dates`
  bokehjs/src/lib/models/widgets/base_date_picker.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13192__doesn't_to_clear_DatePicker.enabled_dates.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13192__doesn't_to_clear_DatePicker.enabled_dates.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/widgets.ts
Labels: status: accepted

#13185 Update legend more aggressively to avoid stale state
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13182__doesn't_allow_update_of_legend_when_data_changes.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13182__doesn't_allow_update_of_legend_when_data_changes.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13142 Improve handling of resources in lower level embed APIs
  examples/models/basic_plot.py
  examples/models/buttons.py
  examples/models/calendars.py
  examples/models/colors.py
  examples/models/custom.py
  examples/models/customjs.py
  examples/models/dateaxis.py
  examples/models/daylight.py
  examples/models/gauges.py
  examples/models/glyphs.py
  examples/models/maps.py
  examples/models/maps_cities.py
  examples/models/sliders.py
  examples/models/tile_source.py
  examples/models/trail.py
  examples/models/twin_axis.py
  examples/models/widgets.py
  examples/output/apis/file_html.py
  src/bokeh/embed/standalone.py
  src/bokeh/io/export.py
  src/bokeh/io/saving.py
  src/bokeh/resources.py
  src/bokeh/settings.py
  tests/unit/bokeh/embed/test_standalone.py
  tests/unit/bokeh/io/test_saving.py
  tests/unit/bokeh/test_resources.py
  tests/unit/bokeh/test_settings.py
Labels: status: accepted, type: task, reso: completed

#13049 Allow to zoom secondary ranges/scales independently
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
  bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
  examples/basic/axes/twin_axes.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
Labels: status: accepted

#13190 Make legend drawing logic consider subset indices
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/annotations/legend_item.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12718__doesn't_render_Legend_correctly_when_LegendItem.index_is_filtered_out_by_CDSView.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12718__doesn't_render_Legend_correctly_when_LegendItem.index_is_filtered_out_by_CDSView.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13192__doesn't_to_clear_DatePicker.enabled_dates.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/annotations/legend.ts
Labels: status: accepted

#13202 Update theme.py
  src/bokeh/themes/theme.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13198 Traverse data classes when collecting references
  src/bokeh/model/util.py
  tests/unit/bokeh/model/test_util_model.py
Labels: status: accepted

#13208 Update bokeh 3.2.0 release notes
  docs/bokeh/source/docs/releases/3.2.0.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13199 Don't allow readonly properties in model constructors
  src/bokeh/core/has_props.py
  src/bokeh/core/property/descriptors.py
  src/bokeh/models/widgets/sliders.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/model/test_model.py
  tests/unit/bokeh/models/widgets/test_slider.py
Labels: status: accepted

#13124 Improve burtin.py appearance
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/_images/examples/topics/pie/burtin.png
  docs/bokeh/source/_images/examples/topics/pie/burtin@2x.png
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/releases/3.2.0.rst
  docs/bokeh/switcher.json
  examples/basic/annotations/whisker.py
  examples/interaction/legends/legend_hide.py
  examples/topics/pie/burtin.py
Labels: status: accepted, NEEDS FORWARD PORT

#13220 remove text duplicate in burtin.py
  examples/topics/pie/burtin.py
Labels: status: ready, type: task, tag: component: examples

#13219 Fix binding of `this` in non-module `CustomJS`
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/test/unit/models/callbacks/customjs.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted, NEEDS FORWARD PORT

#13215 Use PEP 673 `Self` type instead of `TypeVar(..., bound=...)`
  src/bokeh/colors/color.py
Labels: status: accepted, type: task, reso: completed, tag: mypy

#13221 Remove unneeded backslash in LaTeX [skip ci]
  examples/styling/mathtext/latex_axis_labels_titles_labels.py
Labels: status: ready, type: task, tag: component: examples, NEEDS FORWARD PORT, tag: MathText

#13227 Forward ports from 3.2
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/package.json
  bokehjs/test/unit/models/callbacks/customjs.ts
  bokehjs/test/unit/regressions.ts
  conda/environment-test-minimal-deps.yml
  docs/CHANGELOG
  docs/bokeh/source/_images/examples/topics/pie/burtin.png
  docs/bokeh/source/_images/examples/topics/pie/burtin@2x.png
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/dev_guide/documentation.rst
  docs/bokeh/source/docs/releases/3.2.0.rst
  docs/bokeh/switcher.json
  examples/basic/annotations/whisker.py
  examples/interaction/legends/legend_hide.py
  examples/styling/mathtext/latex_axis_labels_titles_labels.py
  examples/topics/pie/burtin.py
  src/bokeh/_sri.json
Labels: status: ready, type: task

#13193 Hover tooltip for ImageStack glyph
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/test/baselines/linux/ImageStack_glyph__should_support_hover_tooltip.blf
  bokehjs/test/baselines/linux/ImageStack_glyph__should_support_hover_tooltip.png
  bokehjs/test/integration/glyphs/image_stack.ts
Labels: status: ready, type: task, tag: component: bokehjs

#13212 Add more options for specifying contour colors
  docs/bokeh/source/docs/user_guide/topics/contour.rst
  src/bokeh/plotting/contour.py
  tests/unit/bokeh/plotting/test_contour.py
Labels: type: feature, status: ready, tag: contour
