Repository bokeh/bokeh, pull requests merged in 2023-09, with the labels that each got.

#13214 13211 allow inline math text
  bokehjs/src/lib/models/text/utils.ts
  bokehjs/test/unit/models/text/utils.ts
  docs/bokeh/source/docs/releases/3.3.0.rst
  examples/styling/mathtext/latex_axis_labels_titles_labels.py
  examples/styling/mathtext/latex_bessel.py
  examples/styling/mathtext/latex_div_widget.py
  examples/styling/mathtext/latex_schrodinger.py
  examples/styling/mathtext/latex_slider_widget_title.py
  examples/styling/mathtext/latex_tick_labels.py
  examples/styling/mathtext/mathml_axis_labels.py
Labels: status: accepted

#13322 Always respect bounds when setting `Range.start` and `Range.end`
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/ranges/data_range.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/ranges/factor_range.ts
  bokehjs/src/lib/models/ranges/numerical_range.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/src/lib/models/ranges/range1d.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13315__doesn't_allow_Range.start_and_Range.end_updates_to_respect_bounds.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13315__doesn't_allow_Range.start_and_Range.end_updates_to_respect_bounds.png
  bokehjs/test/integration/regressions.ts
  src/bokeh/models/ranges.py
  tests/baselines/defaults.json5
Labels: status: accepted, grant: CZI R5

#13269 Add support for `ColorMap` (palette selector) widget
  bokehjs/src/less/menus.less
  bokehjs/src/less/panes.less
  bokehjs/src/less/widgets/color_map.less
  bokehjs/src/less/widgets/color_map_item.less
  bokehjs/src/less/widgets/color_map_pane.less
  bokehjs/src/less/widgets/inputs.less
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/util/math.ts
  bokehjs/src/lib/core/util/menus.ts
  bokehjs/src/lib/core/util/panes.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/widgets/color_map.ts
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11946__doesn't_allow_to_persist_menus_after_a_re-render.png
  bokehjs/test/baselines/linux/Plot__should_support_toolbar's_overflow_menu__with_toolbar_located_above_a_plot.png
  bokehjs/test/baselines/linux/Plot__should_support_toolbar's_overflow_menu__with_toolbar_located_below_a_plot.png
  bokehjs/test/baselines/linux/Plot__should_support_toolbar's_overflow_menu__with_toolbar_located_left_of_a_plot.png
  bokehjs/test/baselines/linux/Plot__should_support_toolbar's_overflow_menu__with_toolbar_located_right_of_a_plot.png
  bokehjs/test/baselines/linux/Tools__should_support_BoxSelectTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_BoxZoomTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_LassoSelectTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_PanTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_PolySelectTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_SaveTool's_setup_menu.png
  bokehjs/test/baselines/linux/Tools__should_support_TapTool's_setup_menu.png
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_default_settings.blf
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_default_settings.png
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_disabled=true.blf
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_disabled=true.png
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_ncols=3.blf
  bokehjs/test/baselines/linux/Widgets__should_support_ColorMap__with_ncols=3.png
  bokehjs/test/codebase/size.ts
  bokehjs/test/integration/widgets.ts
  bokehjs/test/interactive.ts
  examples/interaction/widgets/color_map.py
  examples/models/widgets.py
  src/bokeh/models/widgets/inputs.py
  tests/baselines/defaults.json5
Labels: type: feature, status: accepted, reso: completed, tag: API: models

#13352 Upgrade to TypeScript 5.2
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/core/util/spatial.ts
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/baselines/linux/Widgets__should_allow_PasswordInput.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_PasswordInput.png
  bokehjs/test/baselines/linux/Widgets__should_allow_PasswordInput_with_password_visible.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_PasswordInput_with_password_visible.png
  bokehjs/test/codebase/tsconfig.json
  bokehjs/test/defaults/tsconfig.json
  bokehjs/test/devtools/tsconfig.json
  bokehjs/test/integration/tsconfig.json
  bokehjs/test/package.json
  bokehjs/test/setup.ts
  bokehjs/test/unit/_util.ts
  bokehjs/test/unit/core/ui_events.ts
  bokehjs/test/unit/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/tsconfig.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#13258 Fix support for well known icons in Tools
  src/bokeh/core/property/visual.py
  tests/unit/bokeh/core/property/test_visual.py
Labels: status: accepted

#13370 Fix handling of `toolbar_options` in `gridplot()`
  bokehjs/src/lib/api/gridplot.ts
  src/bokeh/layouts.py
  tests/unit/bokeh/test_layouts.py
Labels: status: accepted

#13353 13276 fix issues in documentation part two
  docs/bokeh/source/docs/user_guide/topics/graph.rst
  pyproject.toml
  src/bokeh/core/property/dataspec.py
  src/bokeh/model/model.py
  src/bokeh/models/formatters.py
  src/bokeh/models/transforms.py
  src/bokeh/plotting/_renderer.py
  src/bokeh/util/strings.py
  tests/unit/bokeh/core/test_query.py
  tests/unit/bokeh/util/test_strings.py
Labels: status: accepted

#13368 Add more examples in the gallery
  docs/bokeh/source/docs/user_guide/topics/categorical.rst
  examples/topics/categorical/slope_graph.py
  src/bokeh/sampledata/emissions.py
  src/bokeh/util/sampledata.json
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13355 Redesign tooltip around CSS position `fixed`
  bokehjs/src/less/tooltips.less
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/models/ui/tooltip.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11437__doesn't_allow_to_use_correct_subset_indices_with_image_glyph_during_inspection.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12447__make_tooltips_interfere_with_toolbars.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12585__doesn't_allow_support_for_line_policy=none_with_mode=vline.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12951__doesn't_allow_usage_of_Tooltip_in_description_context.png
  bokehjs/test/baselines/linux/Bug__in_issue_#4930__allows_to_cut_tooltips_short_in_grid_plots.png
  bokehjs/test/baselines/linux/Bug__in_issue_#4930__allows_to_cut_tooltips_short_in_layouts.png
  bokehjs/test/baselines/linux/Bug__in_issue_#8180__does_not_allow_propagation_of_UI_events_through_RangeTool's_overlay.png
  bokehjs/test/baselines/linux/ImageStack_glyph__should_support_hover_tooltip.png
Labels: status: accepted

#13366 Add stack_labels property to WeightedStackColorMapper
  bokehjs/src/lib/models/mappers/weighted_stack_color_mapper.ts
  docs/bokeh/source/docs/releases/3.3.0.rst
  src/bokeh/core/validation/errors.py
  src/bokeh/models/mappers.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_mappers.py
Labels: type: feature, status: ready, tag: API: models

#13379 Allow to serialize unset readonly properties in bokehjs
  bokehjs/src/lib/core/has_props.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13382 Add `pooch` to test dependencies (for `scipy.datasets`)
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.9.yml
Labels: status: accepted

#13351 Make it easier to reference models' views
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/embed/standalone.ts
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/test/unit/document/document.ts
  bokehjs/test/unit/embed.ts
  examples/interaction/js_callbacks/reset_plot.py
  src/bokeh/core/_templates/autoload_nb_js.js
  src/bokeh/io/export.py
  src/bokeh/io/webdriver.py
  src/bokeh/models/callbacks.py
  src/bokeh/settings.py
  src/typings/selenium/webdriver/chrome/service.pyi
  src/typings/selenium/webdriver/chrome/webdriver.pyi
  tests/support/plugins/project.py
  tests/support/util/chrome_screenshot.js
  tests/support/util/selenium.py
  tests/unit/bokeh/core/test_templates.py
  tests/unit/bokeh/test_settings.py
Labels: status: accepted

#12425 Update visible hover tooltips when ranges change
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#7671__doesn't_to_refresh_tooltips_when_plot_is_updated.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#7671__doesn't_to_refresh_tooltips_when_plot_is_updated.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/interactive.ts
Labels: status: accepted

#13277 Add support for poly hit testing to `Patches` and greedy mode
  bokehjs/src/lib/core/geometry.ts
  bokehjs/src/lib/core/util/algorithms.ts
  bokehjs/src/lib/models/annotations/poly_annotation.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/src/lib/models/glyphs/marker.ts
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/region_select_tool.ts
  bokehjs/test/devtools/server.ts
  bokehjs/test/unit/models/glyphs/_util.ts
  bokehjs/test/unit/models/glyphs/multi_polygons.ts
  bokehjs/test/unit/models/glyphs/patches.ts
  docs/bokeh/source/docs/releases/3.3.0.rst
  examples/topics/geo/choropleth.py
  src/bokeh/models/tools.py
  src/bokeh/sampledata/us_counties.py
  src/bokeh/sampledata/us_states.py
  tests/baselines/defaults.json5
Labels: status: accepted

#13390 Repaint plots when inner layout bbox changes
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13323__doesn't_allow_to_repaint_plots_in_layouts_when_only_their_inner_layout_bbox_changed.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13323__doesn't_allow_to_repaint_plots_in_layouts_when_only_their_inner_layout_bbox_changed.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13386 Add location of intersphinx mapping
  docs/bokeh/source/docs/reference.rst
Labels: status: accepted

#13393 Fix intersphinx link
  docs/bokeh/source/docs/reference.rst
Labels: status: accepted

#13391 Make server resource URLs root-relative by default
  src/bokeh/server/tornado.py
  tests/support/plugins/selenium.py
  tests/unit/bokeh/server/test_tornado__server.py
Labels: status: accepted

#13345 Add support for zooming sub-plots
  bokehjs/src/lib/core/util/math.ts
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/models/coordinates/coordinate_mapping.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/scales/composite_scale.ts
  bokehjs/src/lib/models/scales/index.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/baselines/linux/WheelZoomTool__should_support_zooming_sub-coordinates.blf
  bokehjs/test/baselines/linux/WheelZoomTool__should_support_zooming_sub-coordinates.png
  bokehjs/test/baselines/linux/ZoomInTool__should_support_zooming_sub-coordinates.blf
  bokehjs/test/baselines/linux/ZoomInTool__should_support_zooming_sub-coordinates.png
  bokehjs/test/baselines/linux/ZoomOutTool__should_support_zooming_sub-coordinates.blf
  bokehjs/test/baselines/linux/ZoomOutTool__should_support_zooming_sub-coordinates.png
  bokehjs/test/integration/annotations/color_bar.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/tools/tools.ts
  bokehjs/test/integration/tools/wheel_zoom_tool.ts
  bokehjs/test/integration/tools/zoom_in_tool.ts
  bokehjs/test/integration/tools/zoom_out_tool.ts
  bokehjs/test/unit/core/util/zoom.ts
  examples/interaction/tools/subcoordinates_zoom.py
  src/bokeh/models/scales.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
Labels: status: accepted, grant: CZI R5

#13401 Robustify asset resolution in `scale_bar_image.py`
  examples/basic/annotations/scale_bar_image.py
Labels: status: accepted
