Repository bokeh/bokeh, pull requests merged in 2023-01, with the labels that each got.

#12686 Promote note to warning in docs
  docs/bokeh/source/docs/user_guide/styling/plots.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#12703 Update first_steps_2_add_circles.py
  docs/bokeh/source/docs/first_steps/examples/first_steps_2_add_circles.py
Labels: status: ready, status: accepted

#12715 Remove legacy CSS styles
  bokehjs/src/less/logo.less
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#12721 Fix pandas related type errors
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
Labels: status: accepted

#12717 Fix coverage config
  pyproject.toml
Labels: status: ready

#12722 Resolve interference between `regl` and `source-map-support`
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/transforms.ts
Labels: status: accepted

#12723 Switch to isolated modules in TypeScript
  bokehjs/examples/tsconfig.json
  bokehjs/make/tsconfig.json
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/tsconfig.ext.json
  bokehjs/src/compiler/tsconfig.json
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/layout/index.ts
  bokehjs/src/lib/core/layout/types.ts
  bokehjs/src/lib/core/serialization/index.ts
  bokehjs/src/lib/core/visuals/index.ts
  bokehjs/src/lib/embed/index.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/src/lib/tsconfig.json
  bokehjs/src/server/tsconfig.json
  bokehjs/test/codebase/tsconfig.json
  bokehjs/test/defaults/tsconfig.json
  bokehjs/test/devtools/tsconfig.json
  bokehjs/test/integration/tsconfig.json
  bokehjs/test/unit/core/property_mixins.ts
  bokehjs/test/unit/tsconfig.json
  examples/advanced/extensions/gears/tsconfig.json
  tests/unit/bokeh/embed/ext_package_no_main/tsconfig.json
  tests/unit/bokeh/embed/latex_label/tsconfig.json
  tests/unit/bokeh/test_ext.py
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#12725 Refactor `qbb()` and `cbb()` and fix usage of `cbb()`
  bokehjs/src/lib/core/util/algorithms.ts
  bokehjs/src/lib/models/glyphs/bezier.ts
  bokehjs/src/lib/models/glyphs/quadratic.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Bezier.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Bezier.png
  bokehjs/test/unit/core/util/algorithms.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs, tag: codebase

#12724 Rename `select_every_mousemove` to `continuous`
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
  docs/bokeh/source/docs/releases/3.1.0.rst
  examples/plotting/scatter_selection.py
  examples/server/app/selection_histogram.py
  src/bokeh/core/properties.py
  src/bokeh/core/property/alias.py
  src/bokeh/core/property/descriptors.py
  src/bokeh/models/tools.py
  src/bokeh/util/deprecation.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/property/test_alias.py
  tests/unit/bokeh/core/property/test_descriptors.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/util/test_deprecation.py
Labels: status: accepted

#12741 Upgrade `actions/{checkout,cache,...}` to `v3`
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-docker-build.yml
  .github/workflows/bokeh-docker-test.yml
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
  .github/workflows/bokehjs-ci.yml
  .github/workflows/composite/test-setup/action.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12740 Fix hatch pattern drawing on high DPI displays
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/linux/Bug__in_issue_#10856__makes_GlyphRenderer_ignore_changes_to_secondary_glyphs.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11149__makes_hatch_patterns_rotate_with_glyph's_rotation.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11154__does_not_allow_the_plotting_API_to_consider_hatch_visuals.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11646__disallows_using_image_texture_as_grid_line's_band_fill.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_1.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_1.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_2.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_2.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_3.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_3.png
  bokehjs/test/baselines/linux/Color_support__should_combine_alpha_for_line,_fill_and_hatch_on_all_output_backends.png
  bokehjs/test/baselines/linux/ContourRenderer__should_support_line_fill_and_hatch_properties.png
  bokehjs/test/baselines/linux/Feature__in_issue_#9194__should_allow_above_and_below_fill_and_hover_in_Slope_annotation.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_AnnularWedge.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Annulus.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Block.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Circle.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Ellipse.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Patch.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Patches.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Wedge.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_fill_with_hatch_patterns.png
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'flattop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_with_hatch_patterns.png
  bokehjs/test/baselines/linux/Marker_glyph__should_support_hatch.png
  bokehjs/test/baselines/linux/PolyAnnotation_annotation__should_support_positioning_in_data_space.png
  bokehjs/test/baselines/linux/Rect_glyph__should_support_hatch_patterns_and_line_joins.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12679 Fix spatial indexing of image-like glyphs
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#12746 Fix rotated `Rect` point hit testing
  bokehjs/src/lib/core/util/affine.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/test/unit/core/util/affine.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#12748 Fix a few typos
  .github/workflows/bokeh-ci.yml
  bokehjs/src/lib/models/glyphs/image_base.ts
  scripts/ci/build_conda_package.sh
  src/bokeh/transform.py
Labels: status: accepted, type: task

#12631 Upgrade to TypeScript 4.9
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokehjs-ci.yml
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/compiler.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/core/util/text.ts
  bokehjs/src/lib/es.d.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/package.json
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_gaussian_distributed_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_sparse_cells_data.png
  bokehjs/test/baselines/linux/Color_mapping__with_histogram_equalization__should_support_sparse_squares_data.png
  bokehjs/test/unit/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/dev_guide/bokehjs.rst
Labels: status: ready, type: task, tag: component: build, tag: component: bokehjs, dependencies

#12565 Don't allow serialization of models with unset properties
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/serialization/deserializer.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/ranges/factor_range.ts
  bokehjs/src/lib/models/sources/data_source.ts
  bokehjs/src/lib/models/tickers/days_ticker.ts
  bokehjs/src/lib/models/tickers/months_ticker.ts
  bokehjs/src/lib/models/tickers/single_interval_ticker.ts
  bokehjs/src/lib/models/tickers/years_ticker.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/widgets/abstract_slider.ts
  bokehjs/src/lib/models/widgets/file_input.ts
  bokehjs/src/lib/models/widgets/spinner.ts
  bokehjs/test/unit/core/kinds.ts
  bokehjs/test/unit/core/properties.ts
  docs/bokeh/source/docs/releases/3.1.0.rst
  examples/advanced/extensions/font-awesome/fontawesome_icon.py
  src/bokeh/core/has_props.py
  src/bokeh/core/property/readonly.py
  src/bokeh/models/ranges.py
  src/bokeh/models/renderers/glyph_renderer.py
  src/bokeh/models/scales.py
  src/bokeh/models/tickers.py
  src/bokeh/models/tools.py
  src/bokeh/models/util/structure.py
  src/bokeh/models/widgets/inputs.py
  src/bokeh/sphinxext/bokeh_model.py
  tests/baselines/defaults.json5
  tests/integration/models/test_plot.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/core/test_serialization.py
Labels: status: accepted

#12749 Implement varying_alpha_palette in BokehJS
  bokehjs/src/lib/api/palettes.ts
  bokehjs/test/unit/api/palettes.ts
Labels: type: feature, status: ready, tag: component: bokehjs

#12751 add missing date slider to widgets page
  docs/bokeh/source/docs/user_guide/interaction/widgets.rst
  examples/interaction/widgets/dateslider.py
Labels: status: accepted

#12750 fix out of date example path
  docs/bokeh/source/_images/bokeh_transform_markers_html.png
  docs/bokeh/source/docs/dev_guide/setup.rst
Labels: status: ready

#12701 Add support for `Legend` item fill policies
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/property_mixins.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=2_and_ncols=auto.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=2_and_ncols=auto.png
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=3_and_ncols=auto.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=3_and_ncols=auto.png
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=2.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=2.png
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=3.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_horizontal_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=3.png
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=2_and_ncols=auto.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=2_and_ncols=auto.png
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=3_and_ncols=auto.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=3_and_ncols=auto.png
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=2.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=2.png
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=3.blf
  bokehjs/test/baselines/linux/Legend_annotation__in_vertical_orientation__should_support_grid_layout__with_nrows=auto_and_ncols=3.png
  bokehjs/test/baselines/linux/Legend_annotation__should_support_various_combinations_of_locations_and_orientations.blf
  bokehjs/test/baselines/linux/Legend_annotation__should_support_various_combinations_of_locations_and_orientations.png
  bokehjs/test/integration/annotations/legend.ts
  bokehjs/test/unit/core/enums.ts
  src/bokeh/core/enums.py
  src/bokeh/models/annotations/legends.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
  tests/unit/bokeh/models/test_annotations.py
Labels: status: accepted

#12754 Update Tabler icon CSS URL
  bokehjs/src/lib/models/ui/icons/tabler_icon.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#12743 Added metadata to examples
  examples/basic/lines/line_single.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#12761 improve rgb colors in examples
  examples/basic/axes/bounds.py
  examples/basic/scatters/color_scatter.py
  examples/interaction/js_callbacks/color_sliders.py
  examples/interaction/js_callbacks/customjs_for_range_update.py
  examples/interaction/js_callbacks/js_on_event.py
  examples/models/toolbars.py
  examples/models/toolbars2.py
  examples/output/apis/autoload_static_flask.py
  examples/output/apis/server_session/bokeh_app.py
  examples/plotting/hover.py
  examples/plotting/tap.py
  examples/plotting/toolbar_autohide.py
  examples/server/app/events_app.py
Labels: status: accepted

#12356 Categorical colormapping of 3D arrays
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/glyphs/image.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/glyphs/image_rgba.ts
  bokehjs/src/lib/models/glyphs/image_stack.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/mappers/color_mapper.ts
  bokehjs/src/lib/models/mappers/continuous_color_mapper.ts
  bokehjs/src/lib/models/mappers/index.ts
  bokehjs/src/lib/models/mappers/stack_color_mapper.ts
  bokehjs/src/lib/models/mappers/weighted_stack_color_mapper.ts
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_color_baseline.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_color_baseline.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_colorbar_color.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_colorbar_color.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_nan_color.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_nan_color.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_rescale_discrete_levels.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_rescale_discrete_levels.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_start_alpha.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_start_alpha.png
  bokehjs/test/integration/color_mapping.ts
  bokehjs/test/unit/models/mappers/log_color_mapper.ts
  bokehjs/test/unit/models/mappers/weighted_stack_color_mapper.ts
  src/bokeh/models/glyphs.py
  src/bokeh/models/mappers.py
  src/bokeh/plotting/glyph_api.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_glyphs.py
  tests/unit/bokeh/models/test_mappers.py
Labels: type: feature, status: accepted, reso: completed

#12753 add construct_color_bar for glyphs
  docs/bokeh/source/docs/user_guide/basic/annotations.rst
  examples/basic/annotations/colorbar_log.py
  examples/basic/data/color_mappers.py
  examples/basic/data/linear_cmap_colorbar.py
  examples/plotting/dynamic_color_mapping.py
  examples/topics/categorical/heatmap_unemployment.py
  examples/topics/geo/eclipse.py
  src/bokeh/models/renderers/glyph_renderer.py
  tests/unit/bokeh/models/test_glyph_renderer.py
  tests/unit/bokeh/models/test_graph_renderer.py
Labels: status: ready

#12766 Fix svg rotated ellipses
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Ellipse.png
  bokehjs/test/integration/glyphs/glyphs.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs, tag: svg

#12765 Add `eqhist_cmap` function to transform.py
  docs/bokeh/source/docs/user_guide/basic/data.rst
  src/bokeh/transform.py
  tests/unit/bokeh/test_transform.py
Labels: status: accepted
