Repository bokeh/bokeh, pull requests merged in 2023-12, with the labels that each got.

#13553 Backports for 3.3.2
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/docs/releases/3.3.2.rst
  src/bokeh/colors/color.py
  src/bokeh/embed/standalone.py
  src/bokeh/models/annotations/geometry.py
  src/bokeh/models/tools.py
  src/bokeh/server/tornado.py
  src/bokeh/util/serialization.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_annotations.py
Labels: status: accepted, type: task, reso: completed

#13567 Update switcher.json for 3.3.2 release
  docs/bokeh/switcher.json
Labels: status: accepted, type: task, reso: completed

#13569 Fix implementation of `Config.new` in release scripts
  release/config.py
Labels: status: accepted

#13568 Add Metadata for airports_graph.py and geojson_source.py
  examples/topics/geo/geojson_source.py
  examples/topics/graph/airports_graph.py
Labels: status: accepted

#13572 Add a regression test for issue #8890
  bokehjs/test/baselines/linux/Bug__in_issue_#8890__doesn't_allow_to_render_newly_added_Span_annotation.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#8890__doesn't_allow_to_render_newly_added_Span_annotation.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13096 Show how to reference the same field multiple times in hover tool's formatters
  examples/plotting/customjs_hover.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#13577 Don't register keyup twice in `AutocompleteInput`
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13574__doesn't_allow_to_correctly_change_active_menu_item_with_arrows_in_AutocompleteInput.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13574__doesn't_allow_to_correctly_change_active_menu_item_with_arrows_in_AutocompleteInput.png
  bokehjs/test/integration/regressions.ts
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
Labels: status: accepted

#13582 Sort defaults' baseline by fully qualified names
  bokehjs/test/defaults/index.ts
  tests/baselines/defaults.json5
  tests/support/defaults.py
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: codebase

#13557 Fix computation of image indices for inverted ranges
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13575 Added metadata to position_toolbar.py, position_toolbar_clash.py, and toolbar_autohide.py
  examples/interaction/tools/position_toolbar.py
  examples/interaction/tools/position_toolbar_clash.py
  examples/interaction/tools/toolbar_autohide.py
Labels: status: accepted

#13294 Fix _hit_point in VAreaStep (#13293)
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/annotations/scale_bar.ts
  bokehjs/src/lib/models/glyphs/harea_step.ts
  bokehjs/src/lib/models/glyphs/varea_step.ts
  bokehjs/test/unit/core/util/templating.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13588 Update Jinja2 link in app.rst
  docs/bokeh/source/docs/user_guide/server/app.rst
Labels: status: accepted

#13597 add rst-files for glyphes
  docs/bokeh/source/docs/reference/models/glyphs/harea_step.rst
  docs/bokeh/source/docs/reference/models/glyphs/hspan.rst
  docs/bokeh/source/docs/reference/models/glyphs/hstrip.rst
  docs/bokeh/source/docs/reference/models/glyphs/image_stack.rst
  docs/bokeh/source/docs/reference/models/glyphs/marker.rst
  docs/bokeh/source/docs/reference/models/glyphs/varea_step.rst
  docs/bokeh/source/docs/reference/models/glyphs/vspan.rst
  docs/bokeh/source/docs/reference/models/glyphs/vstrip.rst
  docs/bokeh/source/docs/reference/models/glyphs/xy_glyph.rst
  examples/reference/models/HAreaStep.py
  examples/reference/models/VAreaStep.py
  src/bokeh/models/glyphs.py
  src/bokeh/plotting/_figure.py
Labels: status: accepted

#13602 Robustify unit tests involving browser output
  tests/unit/bokeh/io/test_export.py
Labels: status: accepted

#13601 Upgrade TypeScript to version 5.3 and upgrade other depenencies
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/package.json
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#13586 Added `for` tag to HTML `<label>` element to reference input fields
  bokehjs/src/lib/models/widgets/text_input.ts
  bokehjs/src/lib/models/widgets/text_like_input.ts
  bokehjs/src/lib/models/widgets/textarea_input.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#13603 Link sub-coordinate and context dependent ranges in `RangesUpdate`
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/test/unit/regressions.ts
  src/bokeh/models/tools.py
Labels: status: accepted, grant: CZI R5

#13605 Relativize imports paths also in type declaration files (`*.d.ts`)
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/lib/document/defs.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/annotations/scale_bar.ts
  bokehjs/src/lib/models/common/kinds.ts
  bokehjs/src/lib/models/coordinates/node.ts
  bokehjs/src/lib/models/dom/html.ts
  bokehjs/src/lib/models/layouts/hbox.ts
  bokehjs/src/lib/models/layouts/vbox.ts
  bokehjs/src/lib/models/ranges/factor_range.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  bokehjs/src/lib/models/widgets/base_date_picker.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/src/lib/models/widgets/select.ts
  bokehjs/src/lib/models/widgets/time_picker.ts
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#13604 Implement `<label for="input"><input id="input">`
  bokehjs/src/lib/models/widgets/color_picker.ts
  bokehjs/src/lib/models/widgets/file_input.ts
  bokehjs/src/lib/models/widgets/input_widget.ts
  bokehjs/src/lib/models/widgets/multi_choice.ts
  bokehjs/src/lib/models/widgets/multiselect.ts
  bokehjs/src/lib/models/widgets/numeric_input.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/src/lib/models/widgets/picker_base.ts
  bokehjs/src/lib/models/widgets/select.ts
  bokehjs/src/lib/models/widgets/spinner.ts
  bokehjs/src/lib/models/widgets/text_input.ts
  bokehjs/src/lib/models/widgets/text_like_input.ts
  bokehjs/src/lib/models/widgets/textarea_input.ts
  bokehjs/test/unit/models/widgets/widgets.ts
  examples/advanced/extensions/ion_range_slider.ts
Labels: status: accepted

#13606 Improve handling of `NaT` and `NaN` values
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/test/unit/core/util/templating.ts
  src/bokeh/util/serialization.py
  tests/unit/bokeh/util/test_util__serialization.py
Labels: status: accepted

#13608 Robustify detection if `bokeh-mathjax.js` bundle is needed
  src/bokeh/embed/bundle.py
  tests/unit/bokeh/embed/test_bundle.py
Labels: status: accepted

#13610 Don't use implicit command-line arguments in bokehjs
  bokehjs/make/main.ts
  bokehjs/make/package.json
  bokehjs/make/paths.ts
  bokehjs/make/tasks/compiler.ts
  bokehjs/make/tasks/lint.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/make/tasks/server.ts
  bokehjs/make/tasks/test.ts
  bokehjs/package-lock.json
  bokehjs/src/compiler/main.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/server/package.json
  bokehjs/src/server/server.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/devtools/server.ts
  bokehjs/test/package.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs, tag: codebase

#13596 pyramid example plot
  docs/bokeh/source/_images/examples/topics/stats/pyramid.png
  docs/bokeh/source/_images/examples/topics/stats/pyramid@2x.png
  docs/bokeh/source/docs/gallery.json
  docs/bokeh/source/docs/user_guide/topics/stats.rst
  examples/topics/stats/kde2d.py
  examples/topics/stats/pyramid.py
  src/bokeh/sampledata/titanic.py
  src/bokeh/util/sampledata.json
Labels: status: ready

#13590 add missing sri hashes
  src/bokeh/_sri/0.1.0.json
  src/bokeh/_sri/0.10.0.json
  src/bokeh/_sri/0.11.0.json
  src/bokeh/_sri/0.11.1.json
  src/bokeh/_sri/0.12.0.json
  src/bokeh/_sri/0.12.1.json
  src/bokeh/_sri/0.12.10.json
  src/bokeh/_sri/0.12.11.json
  src/bokeh/_sri/0.12.12.json
  src/bokeh/_sri/0.12.13.json
  src/bokeh/_sri/0.12.14.json
  src/bokeh/_sri/0.12.15.json
  src/bokeh/_sri/0.12.16.json
  src/bokeh/_sri/0.12.2.json
  src/bokeh/_sri/0.12.3.json
  src/bokeh/_sri/0.12.4.json
  src/bokeh/_sri/0.12.5.json
  src/bokeh/_sri/0.12.6.json
  src/bokeh/_sri/0.12.7.json
  src/bokeh/_sri/0.12.8.json
  src/bokeh/_sri/0.12.9.json
  src/bokeh/_sri/0.13.0.json
  src/bokeh/_sri/0.2.0.json
  src/bokeh/_sri/0.3.0.json
  src/bokeh/_sri/0.4.0.json
  src/bokeh/_sri/0.4.1.json
  src/bokeh/_sri/0.4.2.json
  src/bokeh/_sri/0.4.3.json
  src/bokeh/_sri/0.4.4.json
  src/bokeh/_sri/0.5.0.json
  src/bokeh/_sri/0.5.1.json
  src/bokeh/_sri/0.5.2.json
  src/bokeh/_sri/0.6.0.json
  src/bokeh/_sri/0.6.1.json
  src/bokeh/_sri/0.7.0.json
  src/bokeh/_sri/0.7.1.json
  src/bokeh/_sri/0.8.0.json
  src/bokeh/_sri/0.8.1.json
  src/bokeh/_sri/0.8.2.json
  src/bokeh/_sri/0.9.0.json
  src/bokeh/_sri/0.9.1.json
  src/bokeh/_sri/0.9.2.json
  src/bokeh/_sri/0.9.3.json
  src/bokeh/_sri/1.0.0.json
  src/bokeh/_sri/1.0.1.json
  src/bokeh/_sri/1.0.2.json
  src/bokeh/_sri/1.0.3.json
  src/bokeh/_sri/1.0.4.json
  src/bokeh/_sri/1.1.0.json
  src/bokeh/_sri/1.2.0.json
  src/bokeh/_sri/1.3.0.json
  src/bokeh/_sri/1.3.1.json
  src/bokeh/_sri/1.3.2.json
  src/bokeh/_sri/1.3.4.json
  src/bokeh/_sri/1.4.0.json
  src/bokeh/_sri/2.2.0.json
  src/bokeh/_sri/2.2.1.json
  src/bokeh/_sri/2.2.2.json
  tests/unit/bokeh/test_resources.py
Labels: status: accepted

#13613 fix warnings caused by sampledata
  docs/bokeh/source/docs/reference/sampledata.rst
  docs/bokeh/source/docs/user_guide/interaction/tools.rst
  docs/bokeh/source/docs/user_guide/topics/stats.rst
  examples/topics/stats/density.py
  examples/topics/stats/pyramid.py
  src/bokeh/models/ranges.py
  src/bokeh/sampledata/titanic.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13539 Update server example URLs
  docs/bokeh/source/docs/gallery.json
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13612 Add support for math text glyphs
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/math_text_glyph.ts
  bokehjs/src/lib/models/glyphs/mathml_glyph.ts
  bokehjs/src/lib/models/glyphs/tex_glyph.ts
  bokehjs/src/lib/models/glyphs/text.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_MathMLGlyph.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_MathMLGlyph.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_TeXGlyph__with_display=auto.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_TeXGlyph__with_display=auto.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_TeXGlyph__with_display=block.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_TeXGlyph__with_display=block.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_TeXGlyph__with_display=inline.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_TeXGlyph__with_display=inline.png
  bokehjs/test/integration/glyphs/glyphs.ts
  bokehjs/test/unit/core/visuals.ts
  bokehjs/test/unit/models/glyphs/image_url.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/reference/models/glyphs/math_ml.rst
  docs/bokeh/source/docs/reference/models/glyphs/math_text.rst
  docs/bokeh/source/docs/reference/models/glyphs/tex.rst
  src/bokeh/embed/bundle.py
  src/bokeh/models/glyphs.py
  src/bokeh/plotting/glyph_api.py
  tests/baselines/defaults.json5
Labels: type: feature, status: ready, tag: API: models, tag: API: plotting, grant: SDG 2023

#13615 add forensic glass and emissions to sampledata.rst
  docs/bokeh/source/docs/reference/sampledata.rst
  docs/bokeh/source/docs/user_guide/topics/categorical.rst
  examples/topics/categorical/correlogram.py
  examples/topics/categorical/slope_graph.py
  src/bokeh/sampledata/emissions.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed
