Repository bokeh/bokeh, pull requests merged in 2023-02, with the labels that each got.

#12770 spelling mistake
  src/bokeh/models/tools.py
Labels: tag: component: docs, status: accepted, type: task

#12712 avoid EncodingWarning in bokeh.resources and bokeh.themes.theme
  src/bokeh/resources.py
  src/bokeh/themes/theme.py
  tests/unit/bokeh/test_themes.py
Labels: status: accepted

#12771 Add instruction to include tags in dev environment setup
  docs/bokeh/source/docs/dev_guide/setup.rst
Labels: status: accepted

#12785 Fix bokehjs interpolate to handle length 1 arrays
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/test/unit/core/util/arrayable.ts
Labels: status: ready

#12787 Traverse Map/Set/etc. in `HasProps.references()`
  bokehjs/src/lib/core/has_props.ts
  bokehjs/test/unit/core/has_props.ts
Labels: status: accepted

#12786 Emit `RangesUpdate` event for all linked plots
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/releases/3.1.0.rst
  examples/basic/layouts/dashboard.py
  src/bokeh/events.py
  src/bokeh/model/model.py
  tests/unit/bokeh/model/test_model.py
Labels: status: accepted

#12794 Fixes to mixed array and ndarray streaming
  bokehjs/src/lib/core/patching.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/src/lib/core/util/typed_array.ts
  bokehjs/test/unit/core/patching.ts
  bokehjs/test/unit/core/util/ndarray.ts
Labels: status: accepted

#12782 Add support for `ValueSubmit` event on `TextInput`
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/models/widgets/autocomplete_input.ts
  bokehjs/src/lib/models/widgets/text_input.ts
  bokehjs/test/unit/models/widgets/text_input.ts
  examples/interaction/js_callbacks/js_on_event.py
  src/bokeh/events.py
  tests/unit/bokeh/test_events.py
Labels: status: accepted

#12798 Don't allow `.` in `UIElement`'s CSS classes
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#12795 11765 metadata custom tooltips
  examples/plotting/custom_tooltip.py
Labels: status: accepted, type: task, tag: component: examples

#12806 Keep correct record of synced references
  src/bokeh/core/serialization.py
  src/bokeh/document/document.py
  src/bokeh/document/models.py
  src/bokeh/protocol/messages/patch_doc.py
  tests/unit/bokeh/document/test_document.py
  tests/unit/bokeh/document/test_models.py
  tests/unit/bokeh/protocol/messages/test_patch_doc.py
  tests/unit/bokeh/util/test_callback_manager.py
Labels: status: accepted

#12789 Add interp_palette function
  bokehjs/src/lib/api/palettes.ts
  bokehjs/src/lib/core/util/array.ts
  bokehjs/test/unit/api/palettes.ts
  bokehjs/test/unit/core/util/array.ts
  src/bokeh/palettes.py
  tests/unit/bokeh/test_palettes.py
Labels: type: feature, status: ready, tag: component: bokehjs

#12800 Do not use inefficient select() when adding legend
  src/bokeh/plotting/_legends.py
  tests/unit/bokeh/plotting/test__legends.py
Labels: status: accepted

#12816 Reuse object traversal result when bundling
  src/bokeh/embed/bundle.py
  tests/unit/bokeh/embed/test_bundle.py
Labels: status: accepted, type: task, reso: completed, tag: performance

#12820 12609 set asyncio event loop
  tests/unit/bokeh/test_server.py
Labels: status: accepted

#12810 Added metadata to hover.py
  examples/plotting/hover.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#12823 Allow to clone `HasProps` instances
  src/bokeh/core/has_props.py
  tests/unit/bokeh/core/test_properties.py
Labels: type: feature, status: accepted, reso: completed, tag: API: models

#12804 Document Rect glyph shouldn't be used on log axes
  src/bokeh/models/glyphs.py
  src/bokeh/plotting/glyph_api.py
Labels: status: ready

#12828 Use ubuntu-latest and nodejs 18.x in CI
  .github/workflows/bokehjs-ci.yml
  conda/environment-build.yml
  conda/environment-release-build.yml
  conda/environment-release-deploy.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#12801 Add tests for custom array functions in BokehJS
  bokehjs/src/lib/core/util/array.ts
  bokehjs/test/unit/core/util/array.ts
Labels: status: accepted

#12813 Activate bugbear checks in ruff
  pyproject.toml
Labels: status: accepted

#12762 Upgrade bokehjs dependencies and refresh `package-lock.json`
  bokehjs/make/package.json
  bokehjs/make/tasks/compiler.ts
  bokehjs/package-lock.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/package.json
  bokehjs/src/server/package.json
  bokehjs/test/package.json
Labels: status: ready, type: task, tag: component: bokehjs, dependencies

#12826 12821 serialize pandas typed arrays
  src/bokeh/core/serialization.py
  src/bokeh/util/serialization.py
  tests/unit/bokeh/core/test_serialization.py
Labels: status: accepted

#12809 Consider margins when using `100%` width with `max` policy
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/test/baselines/linux/LayoutDOM__should_correctly_support_margin_with_max_width_and_height_policies__for_top-level_layouts.blf
  bokehjs/test/baselines/linux/LayoutDOM__should_correctly_support_margin_with_max_width_and_height_policies__for_top-level_layouts.png
  bokehjs/test/baselines/linux/LayoutDOM__should_correctly_support_margin_with_max_width_and_height_policies__in_nested_layouts.blf
  bokehjs/test/baselines/linux/LayoutDOM__should_correctly_support_margin_with_max_width_and_height_policies__in_nested_layouts.png
  bokehjs/test/integration/layouts.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs, tag: layout

#12840 Fix checkboxgroup example
  examples/interaction/widgets/checkbox_group.py
Labels: status: accepted

#12834 Remove old dev server docs
  docs/bokeh/source/docs/dev_guide.rst
  docs/bokeh/source/docs/dev_guide/server.rst
  docs/bokeh/source/docs/user_guide/interaction/tooltips.rst
Labels: status: accepted

#12841 12839 serialize pandas numeric arrays
  src/bokeh/core/serialization.py
  src/bokeh/util/serialization.py
  tests/unit/bokeh/core/test_serialization.py
  tests/unit/bokeh/util/test_util__serialization.py
Labels: status: accepted

#12843 Encode pd.NA to None
  src/bokeh/core/serialization.py
  tests/unit/bokeh/core/test_serialization.py
Labels: status: accepted

#12775 Put Image first in Tool Either to force Image transform
  src/bokeh/models/tools.py
Labels: status: accepted

#12827 11955 update datatable by filter
  bokehjs/src/lib/models/sources/cds_view.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11955__does_not_allow_updating_DataTable_when_its_CDSView's_filters_change.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11955__does_not_allow_updating_DataTable_when_its_CDSView's_filters_change.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12832 Match the type of `Selection.indices` between bokeh and bokehjs
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/src/lib/core/util/object.ts
  bokehjs/src/lib/models/glyphs/line.ts
  bokehjs/src/lib/models/graphs/graph_hit_test_policy.ts
  bokehjs/src/lib/models/mappers/continuous_color_mapper.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/selections/selection.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/unit/core/util/array.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#12817 Enable strict boolean expressions lint rule
  bokehjs/eslint.json
  bokehjs/make/tasks/test.ts
  bokehjs/src/compiler/compiler.ts
  bokehjs/src/compiler/transforms.ts
  bokehjs/src/lib/api/parser.ts
  bokehjs/src/lib/client/connection.ts
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/graphics.ts
  bokehjs/src/lib/core/util/algorithms.ts
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/annotations/html/label_set.ts
  bokehjs/src/lib/models/annotations/html/text_annotation.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/src/lib/models/dom/html.ts
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/src/lib/models/glyphs/marker.ts
  bokehjs/src/lib/models/glyphs/rect.ts
  bokehjs/src/lib/models/glyphs/scatter.ts
  bokehjs/src/lib/models/glyphs/webgl/utils/math.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/line_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_tool.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/widgets/picker_base.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/src/lib/models/widgets/widget.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/unit/assertions.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#12830 Fix various issues with `MultiChoice` widget
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/src/lib/models/widgets/multi_choice.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12157__doesn't_allow_MultiChoice_widget's_menu_to_persist_after_selection_an_option.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12157__doesn't_allow_MultiChoice_widget's_menu_to_persist_after_selection_an_option.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12584__doesn't_allow_auto-completion_to_work_correctly_in_MultiChoice_widget.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12584__doesn't_allow_auto-completion_to_work_correctly_in_MultiChoice_widget.png
  bokehjs/test/baselines/linux/Widgets__should_allow_MultiChoice.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_MultiChoice.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/widgets.ts
Labels: status: accepted

#12847 Fix broken and fill-in missing docstrings
  src/bokeh/models/renderers/glyph_renderer.py
Labels: status: accepted

#12852 Resolve issues with testing on MacOS in CI
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
  tests/codebase/test_eslint.py
  tests/unit/bokeh/io/test_export.py
Labels: status: accepted, type: task, reso: completed, tag: CI

#12855 Update docstring of `json_encoder()`
  src/bokeh/core/json_encoder.py
Labels: status: accepted

#12856 Upgrade to ruff 0.0.252
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.8.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
  src/bokeh/core/query.py
Labels: status: accepted, type: task, reso: completed, tag: codebase

#12860 Add a regression test for issue #12709
  bokehjs/test/baselines/linux/Bug__in_issue_#12709__doesn't_allow_using_DatePicker_widget_in_complex_layouts.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12709__doesn't_allow_using_DatePicker_widget_in_complex_layouts.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12853 Enable `switch-exhaustiveness-checks` lint rule
  bokehjs/eslint.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/lib/core/util/buffer.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/test/framework.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#12859 11969 fix bitset comparison
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/test/unit/core/util/bitset.ts
Labels: status: accepted

#12848 Improve APIs and typing of `NDArray`s especially `BoolNDArray`
  bokehjs/src/lib/api/expr.ts
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/api/linalg.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/util/ndarray.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/glyphs/image.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/src/lib/models/glyphs/image_rgba.ts
  bokehjs/src/lib/models/glyphs/image_stack.ts
  bokehjs/src/lib/models/mappers/color_mapper.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/integration/examples/blackbody_radiation.ts
  bokehjs/test/unit/models/mappers/log_color_mapper.ts
  bokehjs/test/unit/models/mappers/weighted_stack_color_mapper.ts
Labels: status: accepted

#10770 Fix row ordering and date formatting in DataTable
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/baselines/Bug__in_issue_#10749__prevents_DataTable_from_correctly_ordering_rows_and_formatting_string_dates
  bokehjs/test/baselines/linux/Bug__in_issue_#10749__prevents_DataTable_from_correctly_ordering_rows_and_formatting_string_dates.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#10749__prevents_DataTable_from_correctly_ordering_rows_and_formatting_string_dates.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#12680 Fix performance regressions introduced in 3.0
  bokehjs/src/lib/external/slickgrid.d.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'below'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'below'.png
Labels: status: accepted

#12865 Check for package-lock.json v3 in release scripts
  release/build.py
Labels: status: accepted, type: task, reso: completed, tag: component: build

#12866 Build bokehjs' examples in CI and fix errors
  bokehjs/examples/tap/tap.ts
  bokehjs/make/tasks/build.ts
Labels: type: bug, status: accepted, tag: regression, reso: completed, tag: component: bokehjs

#12867 Encode numpy zero-dimensional arrays
  src/bokeh/core/serialization.py
  tests/unit/bokeh/core/test_serialization.py
Labels: status: accepted

#12851 add titles to rst-files
  docs/bokeh/source/docs/reference/models/glyphs/annular_wedge.rst
  docs/bokeh/source/docs/reference/models/glyphs/annulus.rst
  docs/bokeh/source/docs/reference/models/glyphs/arc.rst
  docs/bokeh/source/docs/reference/models/glyphs/bezier.rst
  docs/bokeh/source/docs/reference/models/glyphs/block.rst
  docs/bokeh/source/docs/reference/models/glyphs/circle.rst
  docs/bokeh/source/docs/reference/models/glyphs/ellipse.rst
  docs/bokeh/source/docs/reference/models/glyphs/harea.rst
  docs/bokeh/source/docs/reference/models/glyphs/hbar.rst
  docs/bokeh/source/docs/reference/models/glyphs/hex_tile.rst
  docs/bokeh/source/docs/reference/models/glyphs/image.rst
  docs/bokeh/source/docs/reference/models/glyphs/image_rgba.rst
  docs/bokeh/source/docs/reference/models/glyphs/image_url.rst
  docs/bokeh/source/docs/reference/models/glyphs/line.rst
  docs/bokeh/source/docs/reference/models/glyphs/multi_line.rst
  docs/bokeh/source/docs/reference/models/glyphs/multi_polygons.rst
  docs/bokeh/source/docs/reference/models/glyphs/patch.rst
  docs/bokeh/source/docs/reference/models/glyphs/patches.rst
  docs/bokeh/source/docs/reference/models/glyphs/quad.rst
  docs/bokeh/source/docs/reference/models/glyphs/quadratic.rst
  docs/bokeh/source/docs/reference/models/glyphs/ray.rst
  docs/bokeh/source/docs/reference/models/glyphs/rect.rst
  docs/bokeh/source/docs/reference/models/glyphs/scatter.rst
  docs/bokeh/source/docs/reference/models/glyphs/segment.rst
  docs/bokeh/source/docs/reference/models/glyphs/step.rst
  docs/bokeh/source/docs/reference/models/glyphs/text.rst
  docs/bokeh/source/docs/reference/models/glyphs/varea.rst
  docs/bokeh/source/docs/reference/models/glyphs/vbar.rst
  docs/bokeh/source/docs/reference/models/glyphs/wedge.rst
Labels: status: accepted

#12869 Fix emit of old-style extension bundles
  bokehjs/src/compiler/compile.ts
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/test/unit/core/enums.ts
  examples/models/popup.ts
Labels: status: accepted

#12871 Make `publish = true` the default for `BokehEvent`
  bokehjs/src/lib/core/bokeh_events.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs
