Repository bokeh/bokeh, pull requests merged in 2023-10, with the labels that each got.

#13405 fix tile_providery.py
  src/bokeh/plotting/_figure.py
  src/bokeh/tile_providers.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13398 Clarify CODE_OF_CONDUCT.md escalation section
  docs/CODE_OF_CONDUCT.md
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13410 Pin `urllib3<2` in pip dependencies as well
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
Labels: status: accepted

#13204 Add support for any box-like glyphs to `BoxEditTool`
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/core/util/arrayable.ts
  bokehjs/src/lib/core/util/assert.ts
  bokehjs/src/lib/core/util/iterator.ts
  bokehjs/src/lib/models/glyphs/hstrip.ts
  bokehjs/src/lib/models/glyphs/vstrip.ts
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/line_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/line_tool.ts
  bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/poly_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__Block_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__Block_glyph.png
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__HBar_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__HBar_glyph.png
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__HStrip_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__HStrip_glyph.png
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__Quad_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__Quad_glyph.png
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__Rect_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__Rect_glyph.png
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__VBar_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__VBar_glyph.png
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__VStrip_glyph.blf
  bokehjs/test/baselines/linux/BoxEditTool__should_support_moving__VStrip_glyph.png
  bokehjs/test/integration/tools/box_edit_tool.ts
  bokehjs/test/unit/models/glyphs/hstrip.ts
  bokehjs/test/unit/models/glyphs/vstrip.ts
  bokehjs/test/unit/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/unit/models/tools/inspectors/hover_tool.ts
  examples/interaction/tools/box_edit_various.py
  pyproject.toml
  src/bokeh/core/properties.py
  src/bokeh/core/property/constraints.py
  src/bokeh/core/property/visual.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/property/test_constraints.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/models/test_tools.py
Labels: status: accepted

#13404 Transparent operation on JupyterHub
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
  src/bokeh/io/notebook.py
  src/bokeh/io/showing.py
  tests/unit/bokeh/io/test_notebook__io.py
Labels: status: accepted

#13399 Update 3.3.0 release notes
  docs/bokeh/source/docs/releases/3.3.0.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13408 Correlogram example.
  docs/bokeh/source/_images/examples/topics/categorical/correlogram.png
  docs/bokeh/source/_images/examples/topics/categorical/correlogram@2x.png
  docs/bokeh/source/docs/gallery.json
  docs/bokeh/source/docs/user_guide/topics/categorical.rst
  examples/topics/categorical/correlogram.py
  src/bokeh/sampledata/_data/forensic_glass.csv
  src/bokeh/sampledata/forensic_glass.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#13418 Misc 3.3 docs changes
  docs/CHANGELOG
  docs/bokeh/source/docs/releases/3.2.2.rst
  docs/bokeh/source/docs/user_guide/interaction/js_callbacks.rst
  docs/bokeh/switcher.json
  src/bokeh/_sri.json
  src/bokeh/sphinxext/bokeh_autodoc.py
  src/bokeh/sphinxext/bokeh_color.py
  src/bokeh/sphinxext/bokeh_dataframe.py
  src/bokeh/sphinxext/bokeh_enum.py
  src/bokeh/sphinxext/bokeh_example_metadata.py
  src/bokeh/sphinxext/bokeh_gallery.py
  src/bokeh/sphinxext/bokeh_jinja.py
  src/bokeh/sphinxext/bokeh_model.py
  src/bokeh/sphinxext/bokeh_options.py
  src/bokeh/sphinxext/bokeh_palette.py
  src/bokeh/sphinxext/bokeh_palette_group.py
  src/bokeh/sphinxext/bokeh_plot.py
  src/bokeh/sphinxext/bokeh_prop.py
  src/bokeh/sphinxext/bokeh_releases.py
  src/bokeh/sphinxext/bokeh_roles.py
  src/bokeh/sphinxext/bokeh_sampledata_xref.py
  src/bokeh/sphinxext/bokeh_settings.py
  src/bokeh/sphinxext/bokeh_sitemap.py
  src/bokeh/sphinxext/bokehjs_content.py
Labels: status: accepted, type: task, reso: completed

#13417 Update and restructure categorical chapter
  docs/bokeh/source/docs/user_guide/topics/categorical.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13419 Add Python 3.12 to CI
  .github/workflows/bokeh-ci.yml
  conda/environment-test-3.12.yml
  pyproject.toml
  tests/unit/bokeh/core/property/test_descriptors.py
Labels: status: accepted, type: task, reso: completed

#13422 Display version of `jupyter_bokeh` in `bokeh info`
  src/bokeh/command/subcommands/info.py
  tests/unit/bokeh/command/subcommands/test_info.py
Labels: status: accepted

#13424 Recursively run `after_render()` when updating children
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/sources/column_data_source.ts
  bokehjs/src/lib/models/sources/columnar_data_source.ts
  bokehjs/src/lib/models/widgets/tables/data_table.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13264__doesn't_allow_to_correctly_update_children_in_a_complex_layout.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13264__doesn't_allow_to_correctly_update_children_in_a_complex_layout.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13420 Allow to color map non-factors to `nan_color`
  bokehjs/src/lib/models/mappers/categorical_color_mapper.ts
  bokehjs/src/lib/models/mappers/categorical_mapper.ts
  bokehjs/src/lib/models/mappers/categorical_marker_mapper.ts
  bokehjs/src/lib/models/mappers/categorical_pattern_mapper.ts
  bokehjs/src/lib/models/mappers/color_mapper.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13406 Allow document events to not be synchronized with server
  bokehjs/src/lib/client/session.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/document/events.ts
  bokehjs/src/lib/embed/standalone.ts
  bokehjs/test/unit/document/document.ts
Labels: status: accepted

#13427 Connect `change` signal in `IconView`
  bokehjs/src/lib/models/ui/icons/icon.ts
  bokehjs/src/lib/models/widgets/abstract_button.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#13415 Disable leading zero stripping by default
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts
  src/bokeh/core/enums.py
  src/bokeh/models/formatters.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#13448 Use `Never` type if function doesn't return
  src/bokeh/command/util.py
Labels: status: accepted, type: task, reso: completed, tag: mypy

#13443 Allow to set readonly properties during initialization
  src/bokeh/core/has_props.py
  src/bokeh/core/property/descriptors.py
  tests/unit/bokeh/core/test_properties.py
Labels: status: accepted

#13461 fix comment end strings in some jinja templates
  src/bokeh/core/_templates/autoload_request_tag.html
  src/bokeh/core/_templates/autoload_tag.html
  src/bokeh/core/_templates/css_resources.html
  src/bokeh/core/_templates/file.html
  src/bokeh/core/_templates/js_resources.html
  src/bokeh/core/_templates/notebook_load.html
  src/bokeh/core/_templates/plot_div.html
Labels: status: accepted, type: task, NEEDS BACK PORT

#13464 Explicit datetime format for daylight sampledata
  src/bokeh/sampledata/daylight.py
Labels: status: accepted, NEEDS BACK PORT

#13465 Robustify type expectations greatly reduce `!` usage in tests
  bokehjs/examples/hover/hover.ts
  bokehjs/examples/tap/tap.ts
  bokehjs/src/lib/model.ts
  bokehjs/test/integration/features.ts
  bokehjs/test/integration/glyphs/image_stack.ts
  bokehjs/test/integration/glyphs/markers.ts
  bokehjs/test/integration/plots.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/api/gridplot.ts
  bokehjs/test/unit/assertions.ts
  bokehjs/test/unit/core/has_props.ts
  bokehjs/test/unit/core/properties.ts
  bokehjs/test/unit/document/defs.ts
  bokehjs/test/unit/document/document.ts
  bokehjs/test/unit/model.ts
  bokehjs/test/unit/models/axes/axis.ts
  bokehjs/test/unit/models/callbacks/customjs.ts
  bokehjs/test/unit/models/canvas/cartesian_frame.ts
  bokehjs/test/unit/models/glyphs/annular_wedge.ts
  bokehjs/test/unit/models/glyphs/hspan.ts
  bokehjs/test/unit/models/glyphs/image_url.ts
  bokehjs/test/unit/models/glyphs/rect.ts
  bokehjs/test/unit/models/glyphs/vspan.ts
  bokehjs/test/unit/models/glyphs/wedge.ts
  bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts
  bokehjs/test/unit/models/grids/grid.ts
  bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts
  bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts
  bokehjs/test/unit/models/tools/edit/box_edit_tool.ts
  bokehjs/test/unit/models/tools/edit/freehand_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/point_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/poly_draw_tool.ts
  bokehjs/test/unit/models/tools/edit/poly_edit_tool.ts
  bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/test/unit/models/tools/inspectors/customjs_hover.ts
  bokehjs/test/unit/models/tools/inspectors/hover_tool.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  bokehjs/test/unit/models/widgets/checkbox_button_group.ts
  bokehjs/test/unit/models/widgets/paragraph.ts
  bokehjs/test/unit/protocol/receiver.ts
  bokehjs/test/unit/regressions.ts
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: bokehjs

#13450 Remove `bokehjs/src/lib/testing.ts`
  bokehjs/src/lib/index.ts
  bokehjs/src/lib/testing.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#13374 Add optional tooltip to tabpanels
  bokehjs/src/lib/models/layouts/tab_panel.ts
  bokehjs/src/lib/models/layouts/tabs.ts
  bokehjs/test/unit/models/layouts/tabs.ts
  examples/interaction/widgets/tab_panes.py
  src/bokeh/models/layouts.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_layouts__models.py
Labels: status: accepted

#13454 Correctly process ImageStack data for hover tooltips
  bokehjs/src/lib/models/mappers/weighted_stack_color_mapper.ts
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_color_baseline.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_colorbar_color.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_colorbar_color.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_nan_color.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_nan_color.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_rescale_discrete_levels.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_rescale_discrete_levels.png
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_start_alpha.blf
  bokehjs/test/baselines/linux/Color_mapping__with_weighted_stack_color_mapper__should_support_start_alpha.png
  bokehjs/test/baselines/linux/ImageStack_glyph__should_support_hover_tooltip.png
  bokehjs/test/integration/color_mapping.ts
  bokehjs/test/integration/glyphs/image_stack.ts
  bokehjs/test/unit/models/mappers/weighted_stack_color_mapper.ts
Labels: status: ready, NEEDS BACK PORT

#13470 simplify and use more latex ticks
  examples/styling/mathtext/latex_tick_labels.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#13472 Set minimum nodejs version to 18.x
  conda/environment-build.yml
  conda/environment-release-build.yml
  conda/environment-release-deploy.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/docs/dev_guide/bokehjs.rst
  src/bokeh/util/compiler.py
Labels: status: accepted

#13482 Render WebGL markers that have only one of width and height zero
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/test/baselines/linux/Bug__in_issue_#13478__doesn't_render_webgl_zero-width_height_vstrip_hstrip_glyphs.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13478__doesn't_render_webgl_zero-width_height_vstrip_hstrip_glyphs.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready, NEEDS BACK PORT

#13481 Fix unawaited promises and modernize interactive tests
  bokehjs/eslint.js
  bokehjs/examples/anscombe/anscombe.ts
  bokehjs/examples/burtin/burtin.ts
  bokehjs/examples/categorical/categorical.ts
  bokehjs/examples/charts/charts.ts
  bokehjs/examples/donut/donut.ts
  bokehjs/examples/hierarchical/hierarchical.ts
  bokehjs/examples/hover/hover.ts
  bokehjs/examples/legends/legends.ts
  bokehjs/examples/linked/linked.ts
  bokehjs/examples/stocks/stocks.ts
  bokehjs/examples/tap/tap.ts
  bokehjs/make/main.ts
  bokehjs/src/compiler/main.ts
  bokehjs/src/lib/client/connection.ts
  bokehjs/src/lib/core/signaling.ts
  bokehjs/src/lib/core/visuals/hatch.ts
  bokehjs/src/lib/core/visuals/text.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/embed/notebook.ts
  bokehjs/src/lib/embed/standalone.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/layouts/tabs.ts
  bokehjs/src/lib/models/plots/grid_plot.ts
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/src/lib/models/tools/actions/copy_tool.ts
  bokehjs/src/lib/models/tools/actions/custom_action.ts
  bokehjs/src/lib/models/tools/actions/fullscreen_tool.ts
  bokehjs/src/lib/models/tools/actions/save_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/src/lib/models/widgets/dropdown.ts
  bokehjs/src/lib/models/widgets/file_input.ts
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/integration/_util.ts
  bokehjs/test/integration/annotations/box_annotation.ts
  bokehjs/test/integration/glyphs/image_stack.ts
  bokehjs/test/integration/layouts.ts
  bokehjs/test/integration/plots.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/integration/tables.ts
  bokehjs/test/integration/widgets.ts
  bokehjs/test/interactive.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  bokehjs/test/unit/regressions.ts
  src/bokeh/core/_templates/doc_nb_js.js
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#13433 SinaPlot gallery example.
  docs/bokeh/source/_images/examples/topics/stats/sinaplot.png
  docs/bokeh/source/_images/examples/topics/stats/sinaplot@2x.png
  docs/bokeh/source/docs/gallery.json
  docs/bokeh/source/docs/user_guide/topics/stats.rst
  examples/topics/stats/sinaplot.py
  src/bokeh/sampledata/_data/lincoln_weather.csv
  src/bokeh/sampledata/lincoln.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: examples

#13491 Replace `Stamen*` tiles with `Stadia.Stamen*`
  docs/bokeh/source/docs/user_guide/topics/geo.rst
  examples/plotting/airports_map.py
  examples/topics/geo/tile_demo.py
  src/bokeh/models/plots.py
  src/bokeh/models/tiles.py
  src/bokeh/tile_providers.py
  tests/unit/bokeh/models/test_plots.py
  tests/unit/bokeh/test_tile_providers.py
Labels: status: accepted, NEEDS BACK PORT

#13457 Make `RangeTool` overlay's nodes unique
  bokehjs/src/lib/models/coordinates/node.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/test/unit/models/tools/gestures/range_tool.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#13496 Make `ImageURL` eventually consistent to avoid blinking
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/core/util/image.ts
  bokehjs/src/lib/models/glyphs/image_url.ts
  bokehjs/test/unit/core/util/array.ts
Labels: status: accepted, NEEDS BACK PORT

#13493 Optimize performance of loading visual baselines
  bokehjs/test/devtools/baselines.ts
  bokehjs/test/devtools/devtools.ts
  scripts/ci/install_node_modules.sh
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: bokehjs

#13495 handle negative microseconds with %f format
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts
Labels: status: ready, type: task, tag: component: bokehjs, NEEDS BACK PORT
