Repository bokeh/bokeh, pull requests merged in 2024-03, with the labels that each got.

#13730 fix jupyter.rst
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
Labels: status: accepted

#13740 Unify `putting_together` example between examples and docs
  bokehjs/test/devtools/server.ts
  docs/bokeh/source/docs/user_guide/advanced/extensions.rst
  examples/advanced/extensions/custom.ts
  examples/advanced/extensions/putting_together.py
Labels: status: accepted

#13737 Include generated TS modules in extensions' build
  bokehjs/make/tasks/styles.ts
  bokehjs/src/compiler/build.ts
  bokehjs/src/compiler/main.ts
  bokehjs/src/compiler/styles.ts
  src/bokeh/command/subcommands/build.py
  src/bokeh/ext.py
Labels: type: bug, status: accepted, reso: completed, tag: component: build

#13738 updated links in app readme
  examples/server/app/README.md
Labels: status: accepted

#13744 Update bokeh 3.4.0 release notes
  docs/bokeh/source/docs/releases/3.4.0.rst
  docs/bokeh/switcher.json
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13746 remove double space in example code
  examples/topics/categorical/scatter_jitter.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13749 replacing iris data from examples
  examples/basic/layouts/words_and_plots.py
  examples/models/widgets.py
  examples/output/apis/autoload_static.py
  examples/output/apis/components_themed.py
  examples/output/apis/json_item.py
  examples/output/apis/json_item_themed.py
Labels: status: ready, tag: component: examples

#13396 13387 deployment scenario improvements
  docs/bokeh/source/docs/user_guide/server/deploy.rst
Labels: status: accepted

#13750 Corrected single typo in documentation
  docs/bokeh/source/docs/dev_guide/writing_tests.rst
Labels: status: accepted

#13758 fix broken link in first_steps_9.rst
  docs/bokeh/source/docs/first_steps/first_steps_9.rst
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13754 Add docs and examples for non-visual overrides
  bokehjs/test/baselines/linux/Glyph_models__should_allow_to_override_Circle.radius.blf
  bokehjs/test/baselines/linux/Glyph_models__should_allow_to_override_Circle.radius.png
  bokehjs/test/baselines/linux/Glyph_models__should_allow_to_override_Circle.x_and_Circle.y.blf
  bokehjs/test/baselines/linux/Glyph_models__should_allow_to_override_Circle.x_and_Circle.y.png
  bokehjs/test/baselines/linux/Glyph_models__should_allow_to_override_Circle_with_Rect_in_a_GlyphRenderer.blf
  bokehjs/test/baselines/linux/Glyph_models__should_allow_to_override_Circle_with_Rect_in_a_GlyphRenderer.png
  bokehjs/test/integration/glyphs/glyphs.ts
  docs/bokeh/source/docs/user_guide/styling/plots.rst
  examples/styling/plots/glyph_non_visual.py
Labels: status: accepted

#13753 Add documentation for `ScaleBar` annotation
  docs/bokeh/source/docs/user_guide/basic/annotations.rst
  examples/models/calendars.py
  examples/topics/timeseries/candlestick.py
  src/bokeh/models/annotations/dimensional.py
  tests/unit/bokeh/models/test_annotations.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13748 Add documentation for new-style CustomJS
  docs/bokeh/source/docs/user_guide/interaction/js_callbacks.rst
Labels: status: accepted

#13763 Fix node positioning of `Tooltip`
  bokehjs/src/lib/models/ui/tooltip.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13756__doesn't_correctly_position_Tooltip_when_using_nodes.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13756__doesn't_correctly_position_Tooltip_when_using_nodes.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13757 13743 v box is not working in 3.4.0rc1
  src/bokeh/models/layouts.py
  tests/unit/bokeh/models/test_layouts__models.py
Labels: status: accepted

#13675 Add carbon theme
  examples/styling/themes/carbon.py
  src/bokeh/themes/__init__.py
  src/bokeh/themes/_carbon.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed, python

#13686 added metadata to spans and strips example
  examples/plotting/spans_and_strips.py
Labels: status: accepted, type: task, reso: completed, tag: component: examples

#12835 Allow to retrieve models with `Bokeh.Models.ModelName`
  bokehjs/src/lib/base.ts
  bokehjs/src/lib/core/resolvers.ts
  bokehjs/src/lib/index.ts
  bokehjs/test/unit/base.ts
Labels: status: accepted

#13747 Upgrade to TypeScript 5.4
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/src/lib/models/text/utils.ts
  bokehjs/src/server/package.json
  bokehjs/test/package.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs, tag: typescript

#13770 Remove legacy font measurement logic
  bokehjs/src/lib/core/util/text.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#13775 remove refs to twitter
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/dev_guide.rst
  docs/bokeh/source/index.rst
Labels: status: ready

#13467 Add scale up boundary to datetimetickformatter
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts
  src/bokeh/models/formatters.py
  tests/baselines/defaults.json5
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#13778 Simplify eslint's configuration
  bokehjs/.eslintrc.js
  bokehjs/eslint.js
  bokehjs/make/tasks/lint.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#13781 add sd-gutter to custom css
  docs/bokeh/source/_static/custom.css
Labels: status: accepted

#13783 Fix WebGL scaling of antialising by pixel ratio
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/glyphs/webgl/base_line.ts
  bokehjs/src/lib/models/glyphs/webgl/base_marker.ts
  bokehjs/src/lib/models/glyphs/webgl/image.ts
  bokehjs/src/lib/models/glyphs/webgl/image.vert
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/src/lib/models/glyphs/webgl/regl_line.vert
  bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts
  bokehjs/src/lib/models/glyphs/webgl/types.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_2.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_3.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_1.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_1.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_2.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_2.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_3.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_3.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready
