Repository bokeh/bokeh, pull requests merged in 2024-05, with the labels that each got.

#13860 Remove unused code from `bokeh.models.plots`
  src/bokeh/models/plots.py
  tests/unit/bokeh/models/test_plots.py
Labels: status: accepted, type: task, reso: completed, python, tag: codebase

#13862 Redesign `CartesianFrame` as an internal model/view
  bokehjs/src/lib/models/annotations/base_color_bar.ts
  bokehjs/src/lib/models/annotations/color_bar.ts
  bokehjs/src/lib/models/canvas/cartesian_frame.ts
  bokehjs/src/lib/models/coordinates/coordinate_mapping.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/test/defaults/index.ts
  bokehjs/test/unit/base.ts
  bokehjs/test/unit/models/canvas/cartesian_frame.ts
  bokehjs/test/unit/models/plots/plot.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#13876 Restore warning-less sphinx build
  docs/bokeh/Makefile
  docs/bokeh/make.bat
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/reference/command/subcommands/build.rst
  docs/bokeh/source/docs/reference/command/subcommands/init.rst
  docs/bokeh/source/index.rst
  src/bokeh/command/subcommands/build.py
  src/bokeh/command/subcommands/init.py
  src/bokeh/models/ui/dialogs.py
  src/bokeh/sphinxext/bokeh_enum.py
  src/bokeh/sphinxext/bokeh_model.py
  src/bokeh/sphinxext/bokeh_prop.py
Labels: tag: component: docs, status: ready, type: task

#13879 Fix broken example in user guide advanced bokehjs
  docs/bokeh/source/docs/user_guide/advanced/bokehjs.rst
  src/bokeh/sphinxext/bokehjs_content.py
Labels: type: bug, tag: component: docs, status: ready

#13882 Remove old deprecations
  docs/bokeh/source/docs/reference/tile_providers.rst
  src/bokeh/colors/color.py
  src/bokeh/core/properties.py
  src/bokeh/core/property/nullable.py
  src/bokeh/core/property/numeric.py
  src/bokeh/models/formatters.py
  src/bokeh/models/sources.py
  src/bokeh/themes/theme.py
  src/bokeh/tile_providers.py
  tests/unit/bokeh/core/property/test_nullable.py
  tests/unit/bokeh/core/property/test_numeric.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/models/test_formatters.py
  tests/unit/bokeh/models/test_sources.py
  tests/unit/bokeh/test_themes.py
  tests/unit/bokeh/test_tile_providers.py
Labels: status: accepted, type: task, reso: completed, python

#13884 silence warning in `theme_glyphs.py`
  examples/plotting/theme_glyphs.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/themes/theme.py
Labels: status: accepted, reso: completed

#13877 Replace `PlotView.renderer_view()` with generic `ViewQuery`
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/core/view_manager.ts
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/contour_renderer.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
  bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
  bokehjs/src/lib/models/tools/edit/edit_tool.ts
  bokehjs/src/lib/models/tools/gestures/region_select_tool.ts
  bokehjs/src/lib/models/tools/gestures/tap_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/src/lib/models/ui/tooltip.ts
  bokehjs/test/unit/core/view.ts
  bokehjs/test/unit/models/plots/plot.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#13892 Unify definitions of enums in `bokeh.core.enums`
  src/bokeh/core/enums.py
Labels: status: accepted, type: task, reso: completed, python, tag: codebase

#13891 Improve validation in bokehjs' glyph API and add tests
  bokehjs/src/lib/api/figure.ts
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/core/vectorization.ts
  bokehjs/test/unit/api/plotting.ts
Labels: status: accepted

#13896 Apply correct overflow to canvas' layers
  bokehjs/src/less/canvas.less
  bokehjs/test/baselines/linux/Bug__in_issue_#13895__allows_elements_associated_with_renderers_to_overflow_the_canvas.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13895__allows_elements_associated_with_renderers_to_overflow_the_canvas.png
  bokehjs/test/baselines/linux/LabelSet_annotation__should_support_basic_positioning_using_CSS_rendering.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#13735 Improve type safety of DOM elements on `core/dom`
  bokehjs/src/lib/core/css.ts
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/models/widgets/color_picker.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/src/lib/models/widgets/paragraph.ts
  bokehjs/src/lib/models/widgets/tables/data_cube.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: typescript

#13901 enable pydata_sphinx_theme version banner
  docs/bokeh/Makefile
  docs/bokeh/docserver.py
  docs/bokeh/source/_static/custom.css
  docs/bokeh/source/_static/custom.js
  docs/bokeh/source/_static/switcher.json
  docs/bokeh/source/conf.py
Labels: status: accepted

#13903 move switcher.json back to docs/bokeh
  docs/bokeh/docserver.py
  docs/bokeh/source/conf.py
  docs/bokeh/switcher.json
Labels: status: accepted

#13911 Pin requests at version `!=2.32.*`
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-minimal-deps.yml
Labels: status: accepted

#13917 Remove explanation from the code block and handle backslahes as raw
  src/bokeh/sphinxext/bokeh_plot.py
Labels: status: accepted

#13855 Add support for range selection to `RangeTool`
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/models/tickers/composite_ticker.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/test/baselines/linux/RangeTool__should_support_start_gesture='none'.blf
  bokehjs/test/baselines/linux/RangeTool__should_support_start_gesture='none'.png
  bokehjs/test/baselines/linux/RangeTool__should_support_start_gesture='pan'.blf
  bokehjs/test/baselines/linux/RangeTool__should_support_start_gesture='pan'.png
  bokehjs/test/baselines/linux/RangeTool__should_support_start_gesture='tap'.blf
  bokehjs/test/baselines/linux/RangeTool__should_support_start_gesture='tap'.png
  bokehjs/test/integration/tools/range_tool.ts
  docs/bokeh/source/docs/releases/3.5.0.rst
  examples/interaction/tools/range_tool.py
  src/bokeh/models/tickers.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
Labels: status: accepted, grant: CZI R5

#13909 Don't attach `Tooltip` to DOM if not positioned
  bokehjs/src/lib/models/ui/tooltip.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13756__doesn't_correctly_position_Tooltip_when_using_nodes.blf
Labels: status: accepted

#13908 Fix `CartesianFrame`'s position and generalize `rendering_target()`
  bokehjs/src/less/renderer.less
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/models/annotations/html/text_annotation.ts
  bokehjs/src/lib/models/canvas/cartesian_frame.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/composite_renderer.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/ui/pane.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#13888 Robustify activation of tools/proxies in merged toolbars
  bokehjs/src/lib/api/figure.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#8766__doesn't_allow_activation_of_proxied_box_zoom_tools.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#8766__doesn't_allow_activation_of_proxied_box_zoom_tools.png
  bokehjs/test/integration/cross.ts
  bokehjs/test/integration/tools/zoom_in_tool.ts
  bokehjs/test/integration/tools/zoom_out_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
  src/bokeh/layouts.py
  src/bokeh/models/tools.py
  tests/baselines/cross/regressions/issue_8766.json5
  tests/cross/cases/regressions/issue_8766.py
Labels: status: accepted
