Repository bokeh/bokeh, pull requests merged in 2024-09, with the labels that each got.

#14048 Add missing `abstract` modifier to classes
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/test/unit/models/axes/axis.ts
  bokehjs/test/unit/models/grids/grid.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: codebase

#14051 Use pseudo type members to avoid casting
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: typescript, tag: codebase

#14052 Make `PaletteSelect` use stylehseets instead of inline styles
  bokehjs/src/less/widgets/palette_select_item.less
  bokehjs/src/lib/core/util/color.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_swatch_height=50px.blf
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_swatch_height=50px.png
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_swatch_width=20px.blf
  bokehjs/test/baselines/linux/Widgets__should_support_PaletteSelect__with_swatch_width=20px.png
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/core/util/color.ts
  examples/interaction/widgets/color_map.py
  tests/unit/bokeh/io/test_export.py
Labels: status: ready, type: task, tag: component: bokehjs

#14055 fix some typos
  examples/basic/layouts/words_and_plots.py
  examples/basic/scatters/image_url.py
  examples/interaction/js_callbacks/slider_callback_policy.py
  examples/interaction/tools/position_toolbar.py
  examples/models/transform_jitter.py
  examples/output/apis/autoload_static.py
  examples/plotting/airports_map.py
  examples/plotting/multi_legend.py
  examples/plotting/us_marriages_divorces_hover.py
  examples/reference/models/Ngon.py
  examples/server/app/crossfilter/main.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13958 Add `size` to Scatter
  examples/advanced/extensions/parallel_plot/parallel_plot.py
  examples/advanced/extensions/parallel_plot/parallel_selection_tool.py
  examples/interaction/js_callbacks/customjs_for_tools.py
  examples/models/graphs.py
  examples/styling/plots/glyph_non_visual.py
  examples/styling/plots/glyph_selection_models.py
  examples/topics/graph/graph_interaction.py
  examples/topics/graph/interaction_edgeslinkednodes.py
  examples/topics/graph/interaction_nodesadjacentnodes.py
  examples/topics/graph/interaction_nodeslinkededges.py
  src/bokeh/plotting/_figure.py
Labels: status: accepted

#14059 Fix logic error in UI event emit code
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#14060 Add RC conda label to publish_conda_package
  release/deploy.py
Labels: status: ready

#14050 Add AxisClick event
  bokehjs/src/lib/core/bokeh_events.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/src/lib/models/axes/continuous_axis.ts
  bokehjs/src/lib/models/axes/log_axis.ts
  bokehjs/src/lib/models/axes/mercator_axis.ts
  bokehjs/test/unit/core/bokeh_events.ts
  examples/interaction/js_callbacks/js_on_event.py
  examples/server/app/events_app.py
  src/bokeh/core/property/factors.py
  src/bokeh/core/types.py
  src/bokeh/events.py
  tests/unit/bokeh/test_events.py
Labels: status: ready

#14065 Generate correct `*.d.ts` files for CSS modules
  bokehjs/src/compiler/styles.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: build, tag: component: bokehjs

#14064 Add `script:watch` task for incremental builds
  bokehjs/make/package.json
  bokehjs/make/tasks/_util.ts
  bokehjs/make/tasks/scripts.ts
  bokehjs/package-lock.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#14056 Upgrade to TypeScript 5.6
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/linker.ts
  bokehjs/src/compiler/package.json
  bokehjs/src/lib/core/util/svg.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: typescript

#14067 Upgrade `@types/node` and fix npm audit's concerns
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
  bokehjs/src/server/package.json
  bokehjs/test/package.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#14070 Allow to update `GridPlot.children`
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/models/plots/grid_plot.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14068__doesn't_allow_update_of_GridPlot.children.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14068__doesn't_allow_update_of_GridPlot.children.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#14071 fix a typo
  docs/bokeh/source/docs/user_guide/intro.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#14073 Fix handling of `wheel` events in `Spinner` wiget
  bokehjs/src/lib/models/widgets/spinner.ts
  bokehjs/test/interactive.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted

#14074 Bring 3.5.x point release notes to 3.6.0
  docs/bokeh/source/docs/releases/3.5.1.rst
  docs/bokeh/source/docs/releases/3.5.2.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#14076 Fix image hover values in custom hover templates
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
Labels: status: ready

#14075 Add release notes for bokeh 3.6.0
  docs/bokeh/source/docs/releases/3.6.0.rst
  docs/bokeh/switcher.json
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#14077 Test Bokeh with Python 3.13 rc
  .github/workflows/bokeh-ci.yml
  conda/environment-test-3.13.yml
  pyproject.toml
  tests/unit/bokeh/application/handlers/test_directory.py
  tests/unit/bokeh/application/handlers/test_notebook__handlers.py
Labels: status: accepted, type: task, reso: completed, tag: CI

#14084 Update NodeJS types
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
  bokehjs/src/server/package.json
  bokehjs/test/package.json
Labels: status: accepted

#14085 RadialGlyph should inherit from XYGlyph
  src/bokeh/models/glyph.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_glyphs.py
  tests/unit/bokeh/models/test_tools.py
Labels: status: ready, NEEDS BACK PORT
