Repository bokeh/bokeh, pull requests merged in 2024-04, with the labels that each got.

#13788 Enable RUF001 to lint confusable characters
  pyproject.toml
Labels: status: accepted, type: task, tag: codebase

#13794 Enhance boxplot example rendering (#13791)
  examples/topics/stats/boxplot.py
Labels: status: accepted

#13802 Update bokehjs' dependencies and clear dependabot alerts
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/package.json
  bokehjs/src/compiler/package.json
  bokehjs/src/server/package.json
  bokehjs/test/integration/annotations/scale_bar.ts
  bokehjs/test/package.json
  examples/advanced/extensions/gears/package.json
  tests/unit/bokeh/embed/latex_label/package.json
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#13807 Allow to update the order of `LayoutDOM.children`
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/renderers/composite_renderer.ts
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_LayoutDOM.children.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_LayoutDOM.children.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_Pane.elements.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_Pane.elements.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#13808 Correctly configure secondary glyphs in `GraphRendererView`
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13803__doesn't_allow_GraphRenderer_to_utilize_secondary_glyphs.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13803__doesn't_allow_GraphRenderer_to_utilize_secondary_glyphs.png
  bokehjs/test/integration/regressions.ts
  src/bokeh/core/has_props.py
  tests/unit/bokeh/core/test_has_props.py
Labels: status: accepted, NEEDS BACK PORT

#13776 enable docs on windows
  docs/bokeh/source/conf.py
  src/bokeh/sphinxext/bokeh_gallery.py
Labels: status: ready

#13810 Add support for `BoxAnnotation.inverted`
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_inverted_geometry.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_inverted_geometry.png
  bokehjs/test/integration/annotations/box_annotation.ts
  docs/bokeh/source/docs/releases/3.5.0.rst
  src/bokeh/models/annotations/geometry.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_annotations.py
Labels: type: feature, status: ready, tag: API: models

#13800 allow embedded server document to forward credentials
  src/bokeh/core/_templates/autoload_request_tag.html
  src/bokeh/embed/server.py
  src/bokeh/server/views/autoload_js_handler.py
  tests/unit/bokeh/embed/test_server__embed.py
Labels: status: ready

#13818 Bring 3.3.x release notes from branch-3.3
  docs/bokeh/source/docs/releases/3.3.1.rst
  docs/bokeh/source/docs/releases/3.3.2.rst
  docs/bokeh/source/docs/releases/3.3.3.rst
  docs/bokeh/source/docs/releases/3.3.4.rst
Labels: status: accepted, NEEDS BACK PORT

#13821 fix indentation of layout_function param
  src/bokeh/plotting/graph.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed, NEEDS BACK PORT

#13820 fix path and typos related to jupyter.rst
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
  examples/output/jupyter/ipywidgets/README.md
Labels: type: bug, tag: component: docs, status: accepted, reso: completed, NEEDS BACK PORT

#13816 Backports for 3.4.1
  README.md
  bokehjs/src/lib/models/glyphs/webgl/base.ts
  bokehjs/src/lib/models/glyphs/webgl/base_line.ts
  bokehjs/src/lib/models/glyphs/webgl/base_marker.ts
  bokehjs/src/lib/models/glyphs/webgl/image.ts
  bokehjs/src/lib/models/glyphs/webgl/image.vert
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/src/lib/models/glyphs/webgl/regl_line.vert
  bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts
  bokehjs/src/lib/models/glyphs/webgl/types.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/renderers/composite_renderer.ts
  bokehjs/src/lib/models/renderers/graph_renderer.ts
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/src/lib/models/widgets/input_widget.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_2.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12735__doesn't_allow_correct_rendering_of_hatch_patterns__with_devicePixelRatio_==_3.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_1.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_1.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_2.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_2.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_3.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13692__doesn't_scale_webgl_antialiasing_by_pixel_ratio__with_devicePixelRatio_==_3.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13725__doesn't_allow_DataRange1d_to_respect_min_interval_and_max_interval.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13725__doesn't_allow_DataRange1d_to_respect_min_interval_and_max_interval.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13803__doesn't_allow_GraphRenderer_to_utilize_secondary_glyphs.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13803__doesn't_allow_GraphRenderer_to_utilize_secondary_glyphs.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13804__doesn't_allow_to_update_InputWidget.title.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13804__doesn't_allow_to_update_InputWidget.title.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_LayoutDOM.children.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_LayoutDOM.children.png
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_Pane.elements.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13806__doesn't_allow_to_change_the_order_of_Pane.elements.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/ranges/data_range1d.ts
  docs/bokeh/source/_static/custom.css
  docs/bokeh/source/conf.py
  docs/bokeh/source/docs/dev_guide.rst
  docs/bokeh/source/docs/releases/3.3.1.rst
  docs/bokeh/source/docs/releases/3.3.2.rst
  docs/bokeh/source/docs/releases/3.3.3.rst
  docs/bokeh/source/docs/releases/3.3.4.rst
  docs/bokeh/source/docs/releases/3.4.1.rst
  docs/bokeh/source/docs/user_guide/output/jupyter.rst
  docs/bokeh/source/docs/user_guide/styling/plots.rst
  docs/bokeh/source/index.rst
  docs/bokeh/switcher.json
  examples/output/jupyter/ipywidgets/README.md
  pyproject.toml
  src/bokeh/core/has_props.py
  src/bokeh/models/axes.py
  src/bokeh/models/filters.py
  src/bokeh/models/formatters.py
  src/bokeh/models/plots.py
  src/bokeh/plotting/graph.py
  src/bokeh/sphinxext/bokeh_gallery.py
  tests/unit/bokeh/core/test_has_props.py
Labels: status: accepted, type: task, reso: completed

#13823 fix broken search on the start page
  docs/bokeh/source/_static/custom.css
  docs/bokeh/source/index.rst
Labels: status: ready

#13822 remove consecutive "the" and fix typos in touched files
  docs/bokeh/source/docs/user_guide/basic/bars.rst
  release/checks.py
  src/bokeh/events.py
  src/bokeh/io/notebook.py
  src/bokeh/models/css.py
  src/bokeh/models/ranges.py
  src/bokeh/sphinxext/bokeh_palette.py
  src/bokeh/sphinxext/bokeh_palette_group.py
Labels: type: bug, tag: component: docs, status: accepted, reso: completed

#13777 Hide repeats in datetimeformatter
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts
  src/bokeh/models/formatters.py
  tests/baselines/defaults.json5
Labels: status: ready

#13832 Make projection computations in glyphs aware of inherited properties
  bokehjs/src/lib/models/glyphs/bezier.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/multi_line.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/src/lib/models/glyphs/quadratic.ts
  bokehjs/src/lib/models/glyphs/segment.ts
  bokehjs/src/lib/models/glyphs/xy_glyph.ts
  bokehjs/src/lib/models/plots/gmap_plot.ts
  bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13771__doesn't_allow_to_correctly_maintain_projections_in_secondary_glyphs.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13771__doesn't_allow_to_correctly_maintain_projections_in_secondary_glyphs.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#13785 Add more examples to bokehjs
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/ui/menus/action_item.ts
  bokehjs/src/lib/models/ui/menus/menu.ts
  bokehjs/test/baselines/linux/Examples__should_support_AnnotationMenu.blf
  bokehjs/test/baselines/linux/Examples__should_support_AnnotationMenu.png
  bokehjs/test/baselines/linux/Examples__should_support_CustomAttribution.blf
  bokehjs/test/baselines/linux/Examples__should_support_CustomAttribution.png
  bokehjs/test/baselines/linux/Examples__should_support_CustomSelectionToolbar.blf
  bokehjs/test/baselines/linux/Examples__should_support_CustomSelectionToolbar.png
  bokehjs/test/baselines/linux/Examples__should_support_Dialog.blf
  bokehjs/test/baselines/linux/Examples__should_support_Dialog.png
  bokehjs/test/baselines/linux/Examples__should_support_InlineDataEntry.blf
  bokehjs/test/baselines/linux/Examples__should_support_InlineDataEntry.png
  bokehjs/test/baselines/linux/Examples__should_support_plotting_Aspect.blf
  bokehjs/test/baselines/linux/Examples__should_support_plotting_Aspect.png
  bokehjs/test/baselines/linux/Examples__should_support_topics_images_Image.blf
  bokehjs/test/baselines/linux/Examples__should_support_topics_images_Image.png
  bokehjs/test/baselines/linux/Examples__should_support_topics_images_ImageOriginAnchor.blf
  bokehjs/test/baselines/linux/Examples__should_support_topics_images_ImageOriginAnchor.png
  bokehjs/test/baselines/linux/Examples__should_support_topics_images_ImageRGBA.blf
  bokehjs/test/baselines/linux/Examples__should_support_topics_images_ImageRGBA.png
  bokehjs/test/integration/examples/annotation_menu.ts
  bokehjs/test/integration/examples/custom_attribution.ts
  bokehjs/test/integration/examples/custom_selection_toolbar.ts
  bokehjs/test/integration/examples/dialog.ts
  bokehjs/test/integration/examples/images.ts
  bokehjs/test/integration/examples/inline_data_entry.ts
  bokehjs/test/integration/examples/plotting.ts
  examples/basic/ui/annotation_menu.py
  examples/basic/ui/selection_custom_toolbar.py
Labels: status: accepted

#13731 Add metadata to the data_models.py in plotting example
  examples/plotting/data_models.py
Labels: status: accepted

#13839 remove unnecessary code from ProtocolHandler.handle
  src/bokeh/server/protocol_handler.py
Labels: status: accepted, type: task, reso: completed, tag: component: server

#13845 correct => to >=, remove duplicated networkx in environment files
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-minimal-deps.yml
Labels: status: ready

#13847 Upgrade CI actions to most recent versions
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokeh-docker-build.yml
  .github/workflows/bokeh-docker-test.yml
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
  .github/workflows/bokehjs-ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/composite/test-setup/action.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#13843 Robustify bokehjs' SVG unit tests
  bokehjs/test/unit/assertions.ts
  bokehjs/test/unit/core/util/svg.tsx
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: bokehjs

#13840 Upgrade to mypy 1.10.0 and ruff 0.4.2
  .pre-commit-config.yaml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-minimal-deps.yml
  examples/interaction/js_callbacks/customjs_for_hover.py
  examples/models/trail.py
  examples/server/app/server_auth/app.py
  pyproject.toml
  src/bokeh/application/application.py
  src/bokeh/client/connection.py
  src/bokeh/command/bootstrap.py
  src/bokeh/command/subcommands/file_output.py
  src/bokeh/command/subcommands/serve.py
  src/bokeh/command/util.py
  src/bokeh/core/property/container.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/core/property/descriptors.py
  src/bokeh/core/property/instance.py
  src/bokeh/core/property/visual.py
  src/bokeh/core/property/wrappers.py
  src/bokeh/core/serialization.py
  src/bokeh/document/callbacks.py
  src/bokeh/document/document.py
  src/bokeh/embed/bundle.py
  src/bokeh/embed/standalone.py
  src/bokeh/embed/util.py
  src/bokeh/events.py
  src/bokeh/layouts.py
  src/bokeh/model/model.py
  src/bokeh/model/util.py
  src/bokeh/models/map_plots.py
  src/bokeh/models/plots.py
  src/bokeh/models/ranges.py
  src/bokeh/models/renderers/glyph_renderer.py
  src/bokeh/models/renderers/graph_renderer.py
  src/bokeh/models/sources.py
  src/bokeh/plotting/_figure.py
  src/bokeh/plotting/_legends.py
  src/bokeh/plotting/_plot.py
  src/bokeh/plotting/_stack.py
  src/bokeh/plotting/contour.py
  src/bokeh/plotting/graph.py
  src/bokeh/server/contexts.py
  src/bokeh/server/tornado.py
  src/bokeh/server/util.py
  src/bokeh/settings.py
  src/bokeh/sphinxext/bokeh_palette.py
  src/bokeh/util/compiler.py
  src/bokeh/util/serialization.py
  tests/integration/widgets/test_color_picker.py
  tests/support/util/compare.py
  tests/support/util/selenium.py
  tests/test_examples.py
  tests/unit/bokeh/core/property/test_visual.py
  tests/unit/bokeh/core/test_json_encoder.py
  tests/unit/bokeh/document/test_modules.py
  tests/unit/bokeh/model/test_model.py
  tests/unit/bokeh/server/test_auth_provider.py
  tests/unit/bokeh/test_client_server.py
Labels: status: accepted, type: task, reso: completed, tag: codebase

#13851 Robustify `node make pack` and display versions
  .github/workflows/bokeh-ci.yml
  .github/workflows/composite/test-setup/action.yml
  bokehjs/make/index.js
  bokehjs/make/main.ts
  bokehjs/make/tasks/pack.ts
  bokehjs/src/compiler/build.ts
  conda/environment-test-downstream.yml
Labels: status: accepted

#13850 Fix TextAreaInput resizable=False
  bokehjs/src/less/widgets/inputs.less
  bokehjs/test/baselines/linux/Widgets__should_allow_TextAreaInput.png
  bokehjs/test/baselines/linux/Widgets__should_allow_TextAreaInput_with_resizable=true.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_TextAreaInput_with_resizable=true.png
  bokehjs/test/integration/widgets.ts
Labels: status: accepted

#13853 Don't configure `font-weight` in tooltips
  bokehjs/src/less/tooltips.less
Labels: status: accepted
