Repository bokeh/bokeh, pull requests merged in 2024-08, with the labels that each got.

#14008 Don't use `OffscreenCanvas` if unavailable
  bokehjs/src/lib/core/util/text.ts
Labels: status: accepted, NEEDS BACK PORT

#14003 Fix rendering on JupyterHub 4.1: respect `absolute_url` for protocol determination, support `data-absolute-url`
  bokehjs/src/lib/embed/server.ts
  examples/server/api/iframe_embed/README.md
  examples/server/api/iframe_embed/bokeh_server.py
  examples/server/api/iframe_embed/main.py
  tests/examples.yaml
Labels: status: accepted

#14016 Fix `PatchesView._mask_data()` for secondary ranges
  bokehjs/src/lib/models/glyphs/multi_polygons.ts
  bokehjs/src/lib/models/glyphs/patches.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14013__doesn't_allow_to_respect_secondary_ranges_when_masking_data_in_MultiPolygons_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14013__doesn't_allow_to_respect_secondary_ranges_when_masking_data_in_MultiPolygons_glyph.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14013__doesn't_allow_to_respect_secondary_ranges_when_masking_data_in_Patches_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14013__doesn't_allow_to_respect_secondary_ranges_when_masking_data_in_Patches_glyph.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#14023 Remove outdated known issues list from BokehJS docs
  docs/bokeh/source/docs/user_guide/advanced/bokehjs.rst
Labels: tag: component: docs, status: accepted, type: task, reso: completed, tag: component: bokehjs

#14019 Python docstring argument fixes
  .gitignore
  src/bokeh/core/enums.py
  src/bokeh/core/has_props.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/core/property/descriptors.py
  src/bokeh/core/property/wrappers.py
  src/bokeh/core/query.py
  src/bokeh/document/document.py
  src/bokeh/driving.py
  src/bokeh/plotting/_tools.py
  src/bokeh/protocol/message.py
  src/bokeh/server/server.py
  src/bokeh/util/callback_manager.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#14021 Fix HTML/CSS warning for palette group detail
  src/bokeh/server/views/app_index.html
  src/bokeh/sphinxext/_templates/palette_group_detail.html
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#14024 Update setup and testing docs dev guide
  docs/bokeh/source/docs/dev_guide/setup.rst
  docs/bokeh/source/docs/dev_guide/testing.rst
Labels: tag: component: docs, status: accepted, type: task

#14022 Fix ValueError in get_graph_kwargs
  src/bokeh/plotting/_graph.py
  tests/unit/bokeh/plotting/test__graph.py
Labels: type: bug, status: accepted, reso: completed, python

#14017 Have StringFormatter respect nan_format
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
  src/bokeh/models/widgets/tables.py
  tests/baselines/defaults.json5
Labels: status: ready

#14020 Fix ValueError check in ColumnDataSource.patch
  src/bokeh/models/sources.py
  tests/unit/bokeh/models/test_sources.py
Labels: type: bug, status: accepted, reso: completed, python

#14031 Add "open image in a new tab" mode to save tool
  bokehjs/src/less/icons.less
  bokehjs/src/less/icons/open.svg
  bokehjs/src/lib/models/tools/actions/save_tool.ts
  bokehjs/test/baselines/linux/Icons__should_support_all_icons_defined_in_less_icons.less.png
  bokehjs/test/baselines/linux/Tools__should_support_SaveTool's_setup_menu.png
  docs/bokeh/source/docs/releases/3.6.0.rst
Labels: type: feature, status: accepted, reso: completed, tag: component: bokehjs

#14027 Add n-gon glyph
  bokehjs/src/lib/core/hittest.ts
  bokehjs/src/lib/models/glyphs/circle.ts
  bokehjs/src/lib/models/glyphs/index.ts
  bokehjs/src/lib/models/glyphs/ngon.ts
  bokehjs/src/lib/models/glyphs/radial_glyph.ts
  bokehjs/test/unit/base.ts
  bokehjs/test/unit/core/hittest.ts
  docs/bokeh/source/docs/reference/models/glyphs/ngon.rst
  examples/reference/models/Ngon.py
  src/bokeh/models/glyph.py
  src/bokeh/models/glyphs.py
  src/bokeh/plotting/_figure.py
  src/bokeh/plotting/glyph_api.py
  tests/baselines/defaults.json5
Labels: status: ready

#14034 Allow values of any type in ``GroupFilter.group``
  bokehjs/src/lib/models/filters/group_filter.ts
  bokehjs/test/unit/models/filters/group_filter.ts
  docs/bokeh/source/docs/releases/3.6.0.rst
  src/bokeh/models/filters.py
Labels: status: accepted

#14033 Add support for click-style pan tools
  bokehjs/src/less/icons.less
  bokehjs/src/less/icons/pan_down.svg
  bokehjs/src/less/icons/pan_left.svg
  bokehjs/src/less/icons/pan_right.svg
  bokehjs/src/less/icons/pan_up.svg
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/ranges/range.ts
  bokehjs/src/lib/models/tools/actions/click_pan_tool.ts
  bokehjs/src/lib/models/tools/actions/index.ts
  bokehjs/test/baselines/linux/Icons__should_support_all_icons_defined_in_less_icons.less.blf
  bokehjs/test/baselines/linux/Icons__should_support_all_icons_defined_in_less_icons.less.png
  bokehjs/test/unit/base.ts
  bokehjs/test/unit/core/enums.ts
  bokehjs/test/unit/models/tools/actions/click_pan_tools.ts
  docs/bokeh/source/docs/releases/3.6.0.rst
  src/bokeh/core/enums.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: type: feature, status: accepted, reso: completed, tag: API: models, grant: CZI R6

#14038 Allow `is_equal(0, -0)` to be true to match `===`
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/test/unit/core/util/eq.ts
Labels: type: bug, status: accepted, reso: completed, tag: component: bokehjs

#14037 Clean up factor range and add factor method
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/axes/categorical_axis.ts
  bokehjs/src/lib/models/ranges/factor_range.ts
  bokehjs/src/lib/models/tickers/categorical_ticker.ts
  bokehjs/test/unit/models/axes/axis.ts
  bokehjs/test/unit/models/ranges/factor_range.ts
Labels: status: ready, type: task, tag: component: bokehjs

#14044 WebGL rendering of Ngon glyph
  bokehjs/src/lib/api/glyph_api.ts
  bokehjs/src/lib/models/glyphs/ngon.ts
  bokehjs/src/lib/models/glyphs/webgl/circle.ts
  bokehjs/src/lib/models/glyphs/webgl/index.ts
  bokehjs/src/lib/models/glyphs/webgl/marker.frag
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/src/lib/models/glyphs/webgl/ngon.ts
  bokehjs/src/lib/models/glyphs/webgl/radial.ts
  bokehjs/src/lib/models/glyphs/webgl/types.ts
  bokehjs/src/lib/models/glyphs/webgl/webgl_utils.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Ngon.blf
  bokehjs/test/baselines/linux/Glyph_models__should_support_Ngon.png
  bokehjs/test/integration/glyphs/glyphs.ts
Labels: status: ready
