Repository bokeh/bokeh, pull requests merged in 2024-10, with the labels that each got.

#14089 Added radius parameter to circle plot.
  docs/bokeh/source/docs/user_guide/server/app.rst
Labels: status: accepted, NEEDS BACK PORT

#14094 Rename `scripts:watch` task to `watch`
  bokehjs/make/tasks/watch.ts
Labels: status: accepted, type: task, reso: completed, tag: component: build, tag: component: bokehjs

#14093 Address `CanvasRenderingContext2D.fill(rule)` regression in Chromium 130
  bokehjs/src/lib/core/visuals/fill.ts
  bokehjs/src/lib/core/visuals/hatch.ts
Labels: status: accepted, NEEDS BACK PORT

#14103 Re-run unit tests with `--last-failed` in CI
  .github/workflows/bokeh-ci.yml
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: CI

#14102 Fixed extended equality definition in defaults' tests
  bokehjs/test/defaults/index.ts
Labels: type: bug, tag: component: tests, status: accepted, reso: completed, tag: component: bokehjs

#14091 enable auto box zoom by default
  bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
  bokehjs/test/baselines/linux/Tools__should_support_BoxZoomTool's_setup_menu.png
  bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
Labels: status: accepted

#14053 Upgrade Ubuntu on GitHub actions to 24.04
  .github/workflows/bokeh-ci.yml
  .github/workflows/bokehjs-ci.yml
  .github/workflows/codeql-analysis.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#14106 Improve `PanTool`'s cursor and state handling
  bokehjs/src/less/canvas.less
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/core/util/iterator.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/test/interactive.ts
  bokehjs/test/unit/core/util/iterator.ts
  bokehjs/test/unit/models/tools/gestures/pan_tool.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: type: feature, status: accepted, reso: completed, tag: UI: gestures, grant: CZI R6

#14105 Add a workflow to test Chromium versions on demand
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokehjs-test-chromium.yml
Labels: tag: component: tests, status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: CI

#14113 Fix syntax in `bokehjs-test-chromium.yml` workflow
  .github/workflows/bokehjs-test-chromium.yml
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: CI

#14115 More syntax fixes in `bokehjs-test-chromium.yml`
  .github/workflows/bokehjs-test-chromium.yml
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: CI

#14116 More fixes to `bokehjs-test-chromium.yml`
  .github/workflows/bokehjs-test-chromium.yml
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: CI

#14118 Lock closed issues/prs
  .github/workflows/lock-threads.yml
Labels: status: ready, type: task, tag: CI

#14109 Configure `touch-action` based on active tools and their events
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: status: accepted, NEEDS BACK PORT, grant: CZI R6

#14126 show how None behaves
  docs/bokeh/source/docs/user_guide/basic/lines.rst
  examples/basic/lines/line_missing_points.py
Labels: status: ready

#14125 Temporarily disable bokehjs tests in CI on Windows and OSX
  .github/workflows/bokehjs-ci.yml
  bokehjs/make/tasks/test.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs, tag: CI

#14127 Add `process-only` to avoid failing `lock-threads` workflow
  .github/workflows/lock-threads.yml
Labels: status: accepted, type: task, reso: completed, tag: CI

#14124 Allow `CrosshairTool` and `HoverTool` to trigger from axes
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts
  bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
  bokehjs/test/baselines/linux/CrosshairTool__with_dimensions='both'__should_show_one_span_when_hovering_over_x-axis.blf
  bokehjs/test/baselines/linux/CrosshairTool__with_dimensions='both'__should_show_one_span_when_hovering_over_x-axis.png
  bokehjs/test/baselines/linux/CrosshairTool__with_dimensions='both'__should_show_one_span_when_hovering_over_y-axis.blf
  bokehjs/test/baselines/linux/CrosshairTool__with_dimensions='both'__should_show_one_span_when_hovering_over_y-axis.png
  bokehjs/test/baselines/linux/CrosshairTool__with_dimensions='both'__should_show_two_spans_when_hovering_over_the_frame.blf
  bokehjs/test/baselines/linux/CrosshairTool__with_dimensions='both'__should_show_two_spans_when_hovering_over_the_frame.png
  bokehjs/test/baselines/linux/HoverTool__support_hover_on_x-axis_when_mode=='vline'.blf
  bokehjs/test/baselines/linux/HoverTool__support_hover_on_x-axis_when_mode=='vline'.png
  bokehjs/test/baselines/linux/HoverTool__support_hover_on_y-axis_when_mode=='hline'.blf
  bokehjs/test/baselines/linux/HoverTool__support_hover_on_y-axis_when_mode=='hline'.png
  bokehjs/test/integration/tools/crosshair_tool.ts
  bokehjs/test/integration/tools/hover_tool.ts
  bokehjs/test/interactive.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: status: accepted

#14133 Repaint when viewport scale/pixel ratio changes
  bokehjs/src/lib/core/util/canvas.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
Labels: type: feature, status: ready, status: accepted, reso: completed, tag: component: bokehjs
