Repository bokeh/bokeh, pull requests merged in 2024-01, with the labels that each got.

#13627 Remove unnecessary arcTo calls in round_rect
  bokehjs/src/lib/models/common/painting.ts
Labels: status: accepted, type: task, reso: completed, tag: component: bokehjs

#13633 Use `ruff` to ban `typing_extensions` at the top-level
  .pre-commit-config.yaml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
  src/typings/bs4.pyi
  src/typings/selenium/webdriver/common/by.pyi
  src/typings/selenium/webdriver/common/keys.pyi
  src/typings/selenium/webdriver/remote/webdriver.pyi
  src/typings/selenium/webdriver/support/expected_conditions.pyi
  tests/codebase/test_no_typing_extensions_common.py
Labels: status: accepted, NEEDS BACK PORT

#13626 Force import line wrap by count and line length
  release/.isort.cfg
  release/stages.py
  src/bokeh/.isort.cfg
  src/bokeh/client/session.py
  src/bokeh/command/subcommands/serve.py
  src/bokeh/core/property/alias.py
  src/bokeh/core/property/datetime.py
  src/bokeh/embed/util.py
  src/bokeh/io/export.py
  src/bokeh/model/model.py
  src/bokeh/models/annotations/legends.py
  src/bokeh/models/layouts.py
  src/bokeh/models/map_plots.py
  src/bokeh/server/tornado.py
  src/bokeh/sphinxext/bokeh_autodoc.py
  tests/.isort.cfg
  tests/integration/widgets/test_numeric_input.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_text_input.py
  tests/unit/bokeh/core/property/test_container.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/document/test_callbacks__document.py
Labels: status: accepted, type: task, reso: completed, tag: codebase

#13636 Make all generated HTML elements have unique and safe IDs
  src/bokeh/embed/elements.py
  src/bokeh/embed/notebook.py
  src/bokeh/embed/server.py
  tests/unit/bokeh/embed/test_elements.py
Labels: status: accepted

#13639 ban PIL and other imports with ruff
  pyproject.toml
  src/bokeh/.ruff.toml
  src/bokeh/core/property/visual.py
  src/bokeh/io/export.py
  src/bokeh/io/webdriver.py
  src/bokeh/sampledata/daylight.py
  src/bokeh/sphinxext/bokeh_dataframe.py
  tests/codebase/test_no_ipython_common.py
  tests/codebase/test_no_pandas_common.py
  tests/codebase/test_no_selenium_common.py
Labels: status: ready

#13640 Correctly handle transforms in SVG arcTo
  bokehjs/src/lib/core/util/affine.ts
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Glyph_models__should_support_Quad_with_rounded_corners_where_tl=5px,_tr=10px,_br=15px_and_bl=20px.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Rect_with_large_rounded_corners_that_need_scaling.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Rect_with_rounded_corners_where_tl=5px,_tr=10px,_br=15px_and_bl=20px.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Text__with_anchors,_background,_border,_padding=10px_and_rounded_corners_where_tl=5px,_tr=10px,_br=15px_and_bl=20px.png
  bokehjs/test/baselines/linux/Label_annotation__should_support_basic_positioning_with_LaTeX_notation.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_hatch_and_padding_and_border_radius.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_hatch_and_padding_and_border_radius.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_hatch_and_padding_and_border_radius.png
  bokehjs/test/unit/core/util/affine.ts
Labels: status: accepted

#13503 Log figure render count and start/end
  bokehjs/src/lib/models/plots/plot_canvas.ts
Labels: status: accepted, grant: CZI R5

#13649 Fix rendering of web Rect with large corner radius
  bokehjs/src/lib/models/glyphs/webgl/marker.frag
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/test/baselines/linux/Glyph_models__should_support_Rect_with_large_rounded_corners_that_need_scaling.png
Labels: status: accepted

#13647 Update CoC to use reporting form
  docs/CODE_OF_CONDUCT.md
Labels: tag: component: docs, status: ready, type: task

#13641 create data table from DataTable
  src/bokeh/models/widgets/tables.py
  tests/unit/bokeh/models/test_sources.py
Labels: status: accepted

#13651 Use simpler shader for rect-like glyphs without rounded corners
  bokehjs/src/lib/models/glyphs/webgl/base_marker.ts
  bokehjs/src/lib/models/glyphs/webgl/lrtb.ts
  bokehjs/src/lib/models/glyphs/webgl/marker.frag
  bokehjs/src/lib/models/glyphs/webgl/marker.vert
  bokehjs/src/lib/models/glyphs/webgl/rect.ts
  bokehjs/src/lib/models/glyphs/webgl/single_marker.ts
  bokehjs/src/lib/models/glyphs/webgl/types.ts
Labels: status: accepted, type: task, tag: component: bokehjs, tag: webgl

#13657 Ignore pandas' deprecation warning regarding pyarrow
  pyproject.toml
  tests/unit/bokeh/models/test_sources.py
  tests/unit/bokeh/util/test_util__serialization.py
Labels: status: accepted, NEEDS BACK PORT

#13659 Fix missing User Guide sidebars
  conda/environment-release-build.yml
Labels: type: bug, tag: component: docs, status: ready, tag: component: build, NEEDS BACK PORT

#13655 Let client ping failure clean up session
  src/bokeh/server/tornado.py
  tests/unit/bokeh/server/test_tornado__server.py
Labels: status: accepted, NEEDS BACK PORT

#13661 Add Iterable kind and use it in `BooleanFilter.booleans`
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/models/filters/boolean_filter.ts
  bokehjs/src/lib/models/filters/index_filter.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13660__doesn't_allow_using_ndarrays_in_BooleanFilter.booleans.blf
  bokehjs/test/integration/cross.ts
  bokehjs/test/unit/core/kinds.ts
  tests/baselines/cross/regressions/issue_13660.json5
  tests/cross/cases/regressions/issue_13660.py
Labels: status: accepted

#13662 Backports for 3.3.4
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/models/filters/boolean_filter.ts
  bokehjs/src/lib/models/filters/index_filter.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13660__doesn't_allow_using_ndarrays_in_BooleanFilter.booleans.blf
  bokehjs/test/integration/cross.ts
  bokehjs/test/unit/core/kinds.ts
  conda/environment-release-build.yml
  docs/CODE_OF_CONDUCT.md
  docs/bokeh/source/docs/reference/models/glyphs/harea_step.rst
  docs/bokeh/source/docs/reference/models/glyphs/hspan.rst
  docs/bokeh/source/docs/reference/models/glyphs/hstrip.rst
  docs/bokeh/source/docs/reference/models/glyphs/image_stack.rst
  docs/bokeh/source/docs/reference/models/glyphs/marker.rst
  docs/bokeh/source/docs/reference/models/glyphs/varea_step.rst
  docs/bokeh/source/docs/reference/models/glyphs/vspan.rst
  docs/bokeh/source/docs/reference/models/glyphs/vstrip.rst
  docs/bokeh/source/docs/reference/models/glyphs/xy_glyph.rst
  docs/bokeh/source/docs/user_guide/server/app.rst
  docs/bokeh/switcher.json
  docs/source/docs/releases/3.3.4.rst
  examples/reference/models/HAreaStep.py
  examples/reference/models/VAreaStep.py
  examples/topics/geo/geojson_source.py
  examples/topics/graph/airports_graph.py
  pyproject.toml
  release/.isort.cfg
  release/stages.py
  src/bokeh/.isort.cfg
  src/bokeh/client/session.py
  src/bokeh/command/subcommands/serve.py
  src/bokeh/core/property/alias.py
  src/bokeh/core/property/datetime.py
  src/bokeh/embed/util.py
  src/bokeh/io/export.py
  src/bokeh/model/model.py
  src/bokeh/models/annotations/legends.py
  src/bokeh/models/glyphs.py
  src/bokeh/models/layouts.py
  src/bokeh/models/map_plots.py
  src/bokeh/plotting/_figure.py
  src/bokeh/server/tornado.py
  src/bokeh/sphinxext/bokeh_autodoc.py
  tests/.isort.cfg
  tests/baselines/cross/regressions/issue_13660.json5
  tests/cross/cases/regressions/issue_13660.py
  tests/integration/widgets/test_numeric_input.py
  tests/integration/widgets/test_password_input.py
  tests/integration/widgets/test_text_input.py
  tests/unit/bokeh/core/property/test_container.py
  tests/unit/bokeh/core/test_has_props.py
  tests/unit/bokeh/document/test_callbacks__document.py
  tests/unit/bokeh/models/test_sources.py
  tests/unit/bokeh/server/test_tornado__server.py
  tests/unit/bokeh/util/test_util__serialization.py
Labels: status: ready

#13668 Display Greek small letter mu
  examples/interaction/tools/subcoordinates_zoom.py
Labels: status: accepted

#13664 Address missing image thumbnail
  docs/bokeh/source/_images/examples/topics/stats/density.png
  docs/bokeh/source/_images/examples/topics/stats/density@2x.png
  examples/topics/stats/density.py
Labels: tag: component: docs, status: accepted, type: task, reso: completed

#13671 Swap out Stadia tiles
  docs/bokeh/source/docs/user_guide/topics/geo.rst
  examples/topics/geo/tile_demo.py
  src/bokeh/tile_providers.py
Labels: status: ready

#13635 Bump `tornado` minimum dependency to version 6.2
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.9.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  pyproject.toml
Labels: status: accepted

#13561 Make `RangeTool` respect `Range.{min,max}_interval`
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/src/lib/models/tools/gestures/range_tool.ts
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_height_when_dragging_bottom_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_height_when_dragging_bottom_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_height_when_dragging_top_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_height_when_dragging_top_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_width_when_dragging_left_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_width_when_dragging_left_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_width_when_dragging_right_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__maximum_width_when_dragging_right_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_height_when_dragging_bottom_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_height_when_dragging_bottom_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_height_when_dragging_top_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_height_when_dragging_top_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_width_when_dragging_left_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_width_when_dragging_left_edge.png
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_width_when_dragging_right_edge.blf
  bokehjs/test/baselines/linux/BoxAnnotation_annotation__should_support_constraining__minimum_width_when_dragging_right_edge.png
  bokehjs/test/integration/annotations/box_annotation.ts
  src/bokeh/models/annotations/geometry.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_annotations.py
Labels: status: accepted, grant: CZI R5

#13625 Allow users to provide custom units of measurement
  bokehjs/src/compiler/linker.ts
  bokehjs/src/lib/models/annotations/dimensional.ts
  bokehjs/src/lib/models/annotations/index.ts
  bokehjs/src/lib/models/annotations/scale_bar.ts
  bokehjs/test/baselines/linux/ScaleBar_annotation__should_support_custom_units_of_measurement.blf
  bokehjs/test/baselines/linux/ScaleBar_annotation__should_support_custom_units_of_measurement.png
  bokehjs/test/integration/annotations/scale_bar.ts
  examples/basic/annotations/scale_bar_custom_units.py
  src/bokeh/core/validation/decorators.py
  src/bokeh/core/validation/errors.py
  src/bokeh/models/annotations/dimensional.py
  src/bokeh/models/annotations/legends.py
  src/bokeh/models/layouts.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_validation.py
  tests/unit/bokeh/models/test_annotations.py
Labels: type: feature, status: accepted, reso: completed, tag: API: models, grant: CZI R5
