Repository bokeh/bokeh, pull requests merged in 2024-12, with the labels that each got.

#14170 Don't fail on partially updated `Pane`'s view storage
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14168__doesn't_allow_to_add_multiple_TileRenderer_instances_to_a_plot.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14168__doesn't_allow_to_add_multiple_TileRenderer_instances_to_a_plot.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#14155 Backports for 3.6.2
  bokehjs/src/lib/models/annotations/scale_bar.ts
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14153__doesn't_allow_correctly_position_ScaleBar_annotation.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14153__doesn't_allow_correctly_position_ScaleBar_annotation.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14168__doesn't_allow_to_add_multiple_TileRenderer_instances_to_a_plot.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14168__doesn't_allow_to_add_multiple_TileRenderer_instances_to_a_plot.png
  bokehjs/test/integration/regressions.ts
  docs/bokeh/source/_static/custom.css
  docs/bokeh/source/_templates/sections/footer.html
  docs/bokeh/source/docs/releases/3.6.2.rst
  docs/bokeh/source/docs/user_guide/server/app.rst
  docs/bokeh/switcher.json
  src/bokeh/models/glyph.py
  src/bokeh/server/views/app_index.html
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_glyphs.py
  tests/unit/bokeh/models/test_tools.py
Labels: status: accepted, type: task, reso: completed

#14174 correct help text for Block glyph coordinates
  docs/bokeh/source/docs/user_guide/basic/areas.rst
  src/bokeh/models/glyphs.py
  src/bokeh/plotting/glyph_api.py
Labels: status: ready

#14165 Add support for custom scatter markers
  bokehjs/src/lib/core/kinds.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/types.ts
  bokehjs/src/lib/core/uniforms.ts
  bokehjs/src/lib/core/util/callbacks.ts
  bokehjs/src/lib/core/visuals/fill.ts
  bokehjs/src/lib/core/visuals/hatch.ts
  bokehjs/src/lib/core/visuals/line.ts
  bokehjs/src/lib/models/callbacks/customjs.ts
  bokehjs/src/lib/models/glyphs/defs.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/hex_tile.ts
  bokehjs/src/lib/models/glyphs/image.ts
  bokehjs/src/lib/models/glyphs/image_stack.ts
  bokehjs/src/lib/models/glyphs/scatter.ts
  bokehjs/src/lib/models/glyphs/webgl/multi_marker.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/baselines/linux/Examples__should_support_CustomMarkers.blf
  bokehjs/test/baselines/linux/Examples__should_support_CustomMarkers.png
  bokehjs/test/integration/examples/custom_markers.ts
  bokehjs/test/unit/core/uniforms.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  examples/basic/scatters/custom_markers.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/models/glyphs.py
  tests/baselines/defaults.json5
Labels: type: feature, status: accepted, reso: completed, tag: API: models

#14185 Add a title attribute to the logo link to display the Bokeh version
  bokehjs/src/lib/models/tools/toolbar.ts
Labels: status: accepted

#14187 Cast numpy's number types to Python
  src/bokeh/colors/color.py
  src/bokeh/palettes.py
Labels: status: accepted

#14143 Add support for stateful action tools
  bokehjs/src/less/icons.less
  bokehjs/src/less/icons/list.svg
  bokehjs/src/lib/api/gridplot.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/properties.ts
  bokehjs/src/lib/core/util/types.ts
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/models/plots/grid_plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/tools/actions/action_tool.ts
  bokehjs/src/lib/models/tools/actions/custom_action.ts
  bokehjs/src/lib/models/tools/actions/examine_tool.ts
  bokehjs/src/lib/models/tools/actions/fullscreen_tool.ts
  bokehjs/src/lib/models/tools/click_button.ts
  bokehjs/src/lib/models/tools/on_off_button.ts
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/src/lib/models/ui/dialog.ts
  bokehjs/test/baselines/linux/Examples__should_support_LegendVisibilityTool.blf
  bokehjs/test/baselines/linux/Examples__should_support_LegendVisibilityTool.png
  bokehjs/test/baselines/linux/Icons__should_support_all_icons_defined_in_less_icons.less.png
  bokehjs/test/integration/examples/legend_visibility_tool.ts
  bokehjs/test/unit/api/gridplot.ts
  bokehjs/test/unit/core/util/types.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  examples/basic/scatters/color_scatter.py
  examples/interaction/tools/legend_visibility_tool.py
  src/bokeh/models/tools.py
  tests/baselines/defaults.json5
Labels: status: accepted

#14194 fix unclear docs useing scatter() instead of circle()
  docs/bokeh/source/docs/first_steps/first_steps_2.rst
  docs/bokeh/source/docs/first_steps/first_steps_3.rst
  docs/bokeh/source/docs/reference.rst
  docs/bokeh/source/docs/user_guide/basic/annotations.rst
  docs/bokeh/source/docs/user_guide/basic/data.rst
  docs/bokeh/source/docs/user_guide/basic/scatters.rst
  docs/bokeh/source/docs/user_guide/interaction/tools.rst
  docs/bokeh/source/docs/user_guide/output/embed.rst
  examples/basic/annotations/legends_item_visibility.py
  examples/basic/axes/logplot.py
  examples/basic/data/ajax_source.py
  examples/basic/data/server_sent_events_source.py
  examples/models/transform_jitter.py
  examples/server/app/clustering/main.py
  src/bokeh/io/notebook.py
  src/bokeh/model/model.py
  src/bokeh/models/expressions.py
  src/bokeh/models/glyphs.py
  src/bokeh/models/ranges.py
  src/bokeh/plotting/_renderer.py
  src/bokeh/plotting/glyph_api.py
  tests/unit/bokeh/embed/test_notebook__embed.py
  tests/unit/bokeh/embed/test_server__embed.py
  tests/unit/bokeh/models/test_plots.py
Labels: status: ready

#14206 Fix typing error and improve error message
  src/bokeh/command/util.py
Labels: status: accepted

#14202 Use \boldsymbol for bold math text
  bokehjs/src/lib/models/text/math_text.ts
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_hatch_and_padding_and_border_radius.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_border_line_and_background_hatch_and_padding_and_border_radius.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_offset=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_offset=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_standoff=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=center_and_standoff=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_hatch_and_padding_and_border_radius.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_border_line_and_background_hatch_and_padding_and_border_radius.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_offset=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_offset=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_standoff=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=left_and_standoff=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_hatch_and_padding_and_border_radius.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_border_line_and_background_hatch_and_padding_and_border_radius.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_offset=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_offset=20_and_border_line_and_background_fill.png
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_standoff=20_and_border_line_and_background_fill.blf
  bokehjs/test/baselines/linux/Title_annotation__should_support_positioning__with_align=right_and_standoff=20_and_border_line_and_background_fill.png
Labels: status: ready, NEEDS BACK PORT

#14197 app.rst - Fixed empty plot in the sample codes of section Updating fom unlocked callbacks
  docs/bokeh/source/docs/user_guide/server/app.rst
Labels: status: WIP

#14209 Add `BOKEH_CHROME` environment variable for BokehJS test
  bokehjs/make/tasks/test.ts
  docs/bokeh/source/docs/dev_guide/testing.rst
Labels: tag: component: tests, status: ready, type: task, tag: component: bokehjs
