Repository bokeh/bokeh, pull requests merged in 2025-09, with the labels that each got.

#14625 set minimal version of sphinxext-opengraph to 0.11.0
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.13.yml
  conda/environment-test-minimal-deps.yml
Labels: status: accepted, NEEDS BACK PORT

#14627 add copy and delete for svg icons to make.bat
  docs/bokeh/Makefile
  docs/bokeh/make.bat
Labels: status: accepted, NEEDS BACK PORT

#14624 Add `is_silenced` function to public API
  src/bokeh/core/validation/__init__.py
  src/bokeh/core/validation/check.py
Labels: status: ready

#14619 Enhance bokeh settings command
  src/bokeh/command/subcommands/settings.py
  src/bokeh/settings.py
  tests/unit/bokeh/command/subcommands/test_settings__subcommands.py
Labels: status: ready

#14636 Docs: add link to `Scatter` for the `Marker` class
  src/bokeh/models/glyphs.py
Labels: status: accepted

#14652 Restore `@$name` support and improve `replace_placeholders()`
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/test/unit/core/util/templating.ts
Labels: status: accepted
