Repository bokeh/bokeh, pull requests merged in 2025-04, with the labels that each got.

#14443 Fix Legend's glyph rendering for `dpr != 1`
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14422__doesn't_allow_to_correctly_export_image_with_Legend_annotation_with_scaling.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14422__doesn't_allow_to_correctly_export_image_with_Legend_annotation_with_scaling.png
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/framework.ts
  bokehjs/test/globals.d.ts
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#14441 expose length property of CDS
  src/bokeh/models/sources.py
  src/bokeh/models/sources.pyi
  tests/unit/bokeh/models/test_sources.py
Labels: status: accepted

#14452 update docs for DatetimeTickFormatter
  src/bokeh/models/formatters.py
  tests/baselines/cross/regressions/issue_11694.json5
  tests/baselines/cross/regressions/issue_11930.json5
  tests/baselines/cross/regressions/issue_13134.json5
  tests/baselines/cross/regressions/issue_13637.json5
  tests/baselines/cross/regressions/issue_13637_empty_map.json5
  tests/baselines/cross/regressions/issue_13660.json5
  tests/baselines/cross/regressions/issue_13964.json5
  tests/baselines/cross/regressions/issue_8766.json5
Labels: status: accepted, NEEDS BACK PORT

#14454 Fix Legend's inactive visuals in CSS mode
  bokehjs/src/less/legend.less
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14442__doesn't_allow_to_correctly_render_Legend_with_inactive_items.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14442__doesn't_allow_to_correctly_render_Legend_with_inactive_items.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#14428 Enhance bitset indices performance
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/models/axes/axis.ts
  bokehjs/src/lib/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/core/util/bitset.ts
Labels: status: accepted

#14462 Fix license spec and update ruff
  .pre-commit-config.yaml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.13.yml
  conda/environment-test-minimal-deps.yml
  examples/models/structure/ModelStructureExample.ipynb
  examples/output/jupyter/push_notebook/Basic Usage.ipynb
  examples/output/jupyter/push_notebook/Continuous Updating.ipynb
  examples/output/jupyter/push_notebook/Numba Image Example.ipynb
  examples/server/api/notebook_embed.ipynb
  examples/server/app/spectrogram/main.py
  pyproject.toml
  src/bokeh/colors/color.py
  src/bokeh/command/subcommands/file_output.py
  src/bokeh/command/subcommands/serve.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/palettes.py
  src/bokeh/plotting/_graph.py
  tests/codebase/test_ruff.py
  tests/unit/bokeh/core/property/test_primitive.py
  tests/unit/bokeh/io/test_state.py
  tests/unit/bokeh/models/test_sources.py
Labels: status: accepted

#14459 Update child views without removing their elements
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/src/lib/models/dom/dom_element.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/composite_renderer.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/ui/pane.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14458__doesn't_allow_to_update_layout_children_without_removing_them_from_DOM.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14458__doesn't_allow_to_update_layout_children_without_removing_them_from_DOM.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/util/eq.ts
  bokehjs/test/unit/core/util/templating.ts
Labels: status: accepted, NEEDS BACK PORT

#14470 Use software 2D canvas in Image-like glyphs
  bokehjs/src/lib/models/glyphs/image_base.ts
Labels: status: accepted

#14471 fix links to code pen
  src/bokeh/sphinxext/_templates/bokehjs_codepen_init.html
  src/bokeh/sphinxext/_templates/bokehjs_content_epilogue.html
  src/bokeh/sphinxext/_templates/bokehjs_html_template.html
Labels: status: ready, NEEDS BACK PORT

#14401 Fix types of splattable figure's attributes
  pyproject.toml
  src/bokeh/models/plots.py
  src/bokeh/models/plots.pyi
  tests/unit/bokeh/test_typing.py
Labels: status: accepted, NEEDS BACK PORT
