Repository bokeh/bokeh, pull requests merged in 2025-03, with the labels that each got.

#14305 fix path dependency when enforcing aspect ratio of tiles
  bokehjs/src/lib/models/tiles/mercator_tile_source.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/src/lib/models/tiles/tile_source.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14207__has_zoom_in_when_visibility_changes.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14207__has_zoom_in_when_visibility_changes.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/tiles/tile_renderer.ts
Labels: status: accepted

#14380 Downgrade syntax in `*.pyi` files to Python 3.10
  .github/workflows/bokeh-ci.yml
  src/bokeh/_specs.pyi
  src/bokeh/_types.pyi
  src/bokeh/core/has_props.pyi
  src/bokeh/core/property/visual.pyi
  src/bokeh/core/property_aliases.pyi
  src/bokeh/models/annotations/legends.pyi
  src/bokeh/models/plots.pyi
  src/bokeh/models/ranges.pyi
  src/bokeh/models/renderers/glyph_renderer.pyi
  src/bokeh/models/sources.pyi
  src/bokeh/models/widgets/inputs.pyi
  src/bokeh/plotting/_figure.pyi
Labels: status: accepted

#14112 Allow to auto activate wheel zoom tool on focus
  bokehjs/src/less/canvas.less
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11365__prevents_showing_MultiChoice's_dropdown_menu_over_subsequent_roots.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12157__doesn't_allow_MultiChoice_widget's_menu_to_persist_after_selection_an_option.png
  bokehjs/test/baselines/linux/Bug__in_issue_#12584__doesn't_allow_auto-completion_to_work_correctly_in_MultiChoice_widget.png
  bokehjs/test/baselines/linux/Widgets__should_allow_TimePicker.png
  bokehjs/test/baselines/linux/Widgets__should_allow_TimePicker_with_seconds.png
  bokehjs/test/baselines/linux/Widgets__should_allow_TimePicker_with_seconds_and_12h_clock.png
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/unit/core/dom.ts
  bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: status: accepted, grant: CZI R6

#14387 Validate test decriptions in bokehjs' tests
  bokehjs/test/devtools/devtools.ts
  bokehjs/test/unit/document/events.ts
  bokehjs/test/unit/models/annotations/box_annotation.ts
Labels: status: accepted

#14355 Fix Surface3D example type errors
  examples/server/app/surface3d/surface3d.ts
Labels: status: accepted

#14390 Various fixes to bokeh's type declarations (`*.pyi`)
  src/bokeh/_specs.pyi
  src/bokeh/model/model.pyi
  src/bokeh/plotting/_legends.py
  src/bokeh/plotting/glyph_api.pyi
Labels: status: accepted

#14353 Add support for windowed auto-ranging
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/plots/range_manager.ts
  bokehjs/src/lib/models/ranges/data_range1d.ts
  bokehjs/src/lib/models/renderers/data_renderer.ts
  bokehjs/src/lib/models/tools/gestures/pan_tool.ts
  bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11508__doesn't_allow_to_correctly_compute_log_bounds_for_data_ranging.png
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='x'_when_data_changes.blf
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='x'_when_data_changes.png
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='x'_when_range_changes.blf
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='x'_when_range_changes.png
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='y'_when_data_changes.blf
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='y'_when_data_changes.png
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='y'_when_range_changes.blf
  bokehjs/test/baselines/linux/Plot__should_support_windowed_auto-ranging__with_window_axis='y'_when_range_changes.png
  bokehjs/test/integration/plots.ts
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/glyphs/scatter.ts
  bokehjs/test/unit/models/tools/gestures/wheel_pan_tool.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  docs/bokeh/source/docs/user_guide/basic/axes.rst
  examples/interaction/tools/range_tool.py
  examples/server/app/ohlc/main.py
  src/bokeh/core/enums.py
  src/bokeh/models/plots.py
  src/bokeh/models/plots.pyi
  tests/baselines/cross/regressions/issue_13637_empty_map.json5
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#14392 Update release notes for Bokeh 3.7 release
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: status: accepted

#14395 add color_string to show rgb as string in color_sliders.py
  examples/interaction/js_callbacks/color_sliders.py
Labels: status: accepted

#14408 Update `switcher.json` for 3.7.0 release
  docs/bokeh/switcher.json
Labels: status: accepted, type: task, reso: completed

#14409 Update `switcher.json` for 3.7.0 release
  docs/bokeh/switcher.json
Labels: status: ready, type: task

#14421 optimize unique calculation
  bokehjs/src/lib/core/uniforms.ts
  bokehjs/src/lib/models/glyphs/webgl/multi_marker.ts
Labels: status: accepted, NEEDS BACK PORT

#14397 only show time of day in span example
  examples/basic/annotations/span.py
Labels: status: accepted, NEEDS BACK PORT

#14436 Work around glyph renderer with empty data sources
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#14430 Protect against `document == null` in `_doc_detached()`
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/model.ts
  bokehjs/test/unit/document/document.ts
Labels: status: accepted, NEEDS BACK PORT

#14433 Backports for 3.7.1
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/uniforms.ts
  bokehjs/src/lib/document/document.ts
  bokehjs/src/lib/model.ts
  bokehjs/src/lib/models/glyphs/glyph.ts
  bokehjs/src/lib/models/glyphs/webgl/multi_marker.ts
  bokehjs/test/unit/document/document.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/releases/3.7.1.rst
  docs/bokeh/switcher.json
  examples/basic/annotations/span.py
  examples/interaction/js_callbacks/color_sliders.py
Labels: status: ready, type: task

#14437 Fix application of layout styles when components update
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/canvas/canvas_panel.ts
  bokehjs/src/lib/models/layouts/css_grid_box.ts
  bokehjs/src/lib/models/layouts/flex_box.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/layouts/tabs.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/ui/drawer.ts
  bokehjs/src/lib/models/ui/icons/builtin_icon.ts
  bokehjs/src/lib/models/ui/icons/svg_icon.ts
  bokehjs/src/lib/models/ui/icons/tabler_icon.ts
  bokehjs/src/lib/models/ui/styled_element.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/test/unit/models/ui/ui_element.ts
  bokehjs/test/unit/regressions.ts
Labels: status: accepted, NEEDS BACK PORT

#14419 Enhance performance spatial
  bokehjs/src/lib/core/util/bitset.ts
  bokehjs/src/lib/core/util/spatial.ts
Labels: status: ready

#14438 Backports for 3.7.2
  bokehjs/src/lib/core/dom.ts
  bokehjs/src/lib/core/dom_view.ts
  bokehjs/src/lib/models/canvas/canvas.ts
  bokehjs/src/lib/models/canvas/canvas_panel.ts
  bokehjs/src/lib/models/layouts/css_grid_box.ts
  bokehjs/src/lib/models/layouts/flex_box.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/layouts/tabs.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/src/lib/models/renderers/renderer.ts
  bokehjs/src/lib/models/ui/drawer.ts
  bokehjs/src/lib/models/ui/icons/builtin_icon.ts
  bokehjs/src/lib/models/ui/icons/svg_icon.ts
  bokehjs/src/lib/models/ui/icons/tabler_icon.ts
  bokehjs/src/lib/models/ui/styled_element.ts
  bokehjs/src/lib/models/ui/ui_element.ts
  bokehjs/src/lib/models/widgets/palette_select.ts
  bokehjs/test/unit/models/ui/ui_element.ts
  bokehjs/test/unit/regressions.ts
  docs/bokeh/source/docs/releases/3.7.2.rst
  docs/bokeh/switcher.json
Labels: status: accepted, type: task, reso: completed
