Repository bokeh/bokeh, pull requests merged in 2025-02, with the labels that each got.

#14250 Assign labels instead of title in issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: status: accepted

#14273 Address DeprecationWarning from beautifulsoup4
  tests/unit/bokeh/embed/test_server__embed.py
  tests/unit/bokeh/test_resources.py
Labels: status: accepted, NEEDS BACK PORT

#14275 clamp zoom factor to prevent axis flipping
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/baselines/linux/WheelZoomTool__should_support_zooming_sub-coordinates.blf
  bokehjs/test/baselines/linux/WheelZoomTool__should_support_zooming_sub-coordinates.png
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
Labels: status: ready, NEEDS BACK PORT

#14278 Backports for 3.6.3 part 2
  bokehjs/src/lib/core/util/zoom.ts
  bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
  bokehjs/test/baselines/linux/WheelZoomTool__should_support_zooming_sub-coordinates.blf
  bokehjs/test/baselines/linux/WheelZoomTool__should_support_zooming_sub-coordinates.png
  bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
  docs/bokeh/source/docs/releases/3.6.3.rst
  tests/unit/bokeh/embed/test_server__embed.py
  tests/unit/bokeh/test_resources.py
Labels: status: ready

#14169 feat: Use Narwhals to allow PyArrow / Polars input
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.13.yml
  conda/environment-test-downstream.yml
  conda/environment-test-minimal-deps.yml
  docs/bokeh/source/docs/first_steps/first_steps_8.rst
  docs/bokeh/source/docs/user_guide/basic/data.rst
  pyproject.toml
  src/bokeh/core/properties.py
  src/bokeh/core/property/data_frame.py
  src/bokeh/models/sources.py
  src/bokeh/plotting/_figure.py
  tests/conftest.py
  tests/unit/bokeh/core/property/test_data_frame.py
  tests/unit/bokeh/core/test_properties.py
  tests/unit/bokeh/models/test_sources.py
  tests/unit/bokeh/plotting/test__graph.py
Labels: status: ready

#14284 mypy 1.15 compatibility changes
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.13.yml
  src/bokeh/core/enums.py
  src/bokeh/core/property/enum.py
  src/bokeh/models/formatters.py
  src/bokeh/models/nodes.py
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#14286 Update gallery.json for Population server example
  docs/bokeh/source/docs/gallery.json
Labels: status: accepted

#14291 fix table selection performance with with a lookup
  bokehjs/src/lib/models/widgets/tables/data_table.ts
Labels: status: accepted

#14290 Forward ports docs 3.7
  .pre-commit-config.yaml
  docs/bokeh/source/docs/releases/3.6.1.rst
  docs/bokeh/source/docs/releases/3.6.2.rst
  docs/bokeh/source/docs/releases/3.6.3.rst
Labels: status: ready, type: task

#14294 Add support for label and on/off icons to `Switch` widget
  bokehjs/src/less/_mixins.less
  bokehjs/src/less/icons.less
  bokehjs/src/less/icons/dark-theme.svg
  bokehjs/src/less/icons/light-theme.svg
  bokehjs/src/less/widgets/switch.less
  bokehjs/src/less/widgets/toggle_input.less
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/models/common/resolve.ts
  bokehjs/src/lib/models/widgets/checkbox.ts
  bokehjs/src/lib/models/widgets/switch.ts
  bokehjs/src/lib/models/widgets/toggle_input.ts
  bokehjs/test/baselines/linux/Icons__should_support_all_icons_defined_in_less_icons.less.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=false_and_off_icon.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=false_and_off_icon.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=true_and_label.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=true_and_label.png
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=true_and_on_icon.blf
  bokehjs/test/baselines/linux/Widgets__should_allow_Switch_with_active=true_and_on_icon.png
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/core/enums.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  examples/interaction/tools/subcoordinates_zoom.py
  examples/interaction/tools/tool_context_menu.py
  examples/models/widgets.py
  src/bokeh/_types.pyi
  src/bokeh/core/enums.py
  src/bokeh/core/property_aliases.py
  src/bokeh/core/property_aliases.pyi
  src/bokeh/models/tools.py
  src/bokeh/models/tools.pyi
  src/bokeh/models/ui/menus.py
  src/bokeh/models/ui/menus.pyi
  src/bokeh/models/widgets/inputs.py
  src/bokeh/models/widgets/inputs.pyi
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: accepted

#14301 use np.asarray instead of copy=False
  src/bokeh/core/property/wrappers.py
  tests/unit/bokeh/core/property/test_wrappers__property.py
Labels: status: accepted

#14269 Add type declarations for `glyph_api.py`
  docs/bokeh/source/docs/releases/3.7.0.rst
  examples/basic/scatters/color_scatter.py
  src/bokeh/_specs.pyi
  src/bokeh/_types.pyi
  src/bokeh/core/enums.py
  src/bokeh/core/properties.py
  src/bokeh/core/property/dataspec.py
  src/bokeh/core/property_aliases.pyi
  src/bokeh/core/property_mixins.py
  src/bokeh/core/property_mixins.pyi
  src/bokeh/models/glyphs.py
  src/bokeh/models/glyphs.pyi
  src/bokeh/plotting/_renderer.py
  src/bokeh/plotting/glyph_api.pyi
  tests/unit/bokeh/core/property/test_dataspec.py
  tests/unit/bokeh/core/test_enums.py
  tests/unit/bokeh/core/test_properties.py
Labels: status: accepted

#14302 Updates for spectrogram app
  examples/server/app/spectrogram/audio.py
  examples/server/app/spectrogram/waterfall.ts
  tests/examples.yaml
Labels: status: accepted

#14306 Fix image hover on log scales
  bokehjs/src/lib/core/util/array.ts
  bokehjs/src/lib/models/glyphs/image_base.ts
  bokehjs/test/unit/core/util/array.ts
  bokehjs/test/unit/regressions.ts
Labels: status: ready

#14307 Split off downstream workflow from Bokeh-CI
  .github/workflows/bokeh-ci.yml
  .github/workflows/composite/build/action.yml
  .github/workflows/downstream.yml
Labels: status: accepted

#14308 log error if multi-glyph gets invalid array
  bokehjs/src/lib/models/glyphs/glyph.ts
Labels: status: ready

#14309 Remove `defaults` channel when setting up conda in CI
  .github/workflows/bokeh-release-build.yml
  .github/workflows/bokeh-release-deploy.yml
  .github/workflows/composite/build/action.yml
  .github/workflows/composite/test-setup/action.yml
  scripts/ci/build_conda_package.sh
Labels: status: accepted

#14313 Allow to compare ArrayBuffer-like objects
  bokehjs/src/lib/core/util/eq.ts
  bokehjs/test/unit/core/util/eq.ts
Labels: status: accepted

#14259 Add support for grouping tools in plots
  bokehjs/src/less/tool_button.less
  bokehjs/src/lib/core/enums.ts
  bokehjs/src/lib/core/has_props.ts
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/tools/tool.ts
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/tool_group.ts
  bokehjs/src/lib/models/tools/tool_proxy.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/codebase/size.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  examples/interaction/tools/tool_grouping.py
  src/bokeh/core/enums.py
  src/bokeh/core/property/container.py
  src/bokeh/models/callbacks.py
  src/bokeh/models/tools.py
  src/bokeh/models/tools.pyi
  tests/baselines/cross/regressions/issue_13637_empty_map.json5
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/test_enums.py
Labels: status: ready

#14318 exclude tornado on emscripten
  conda/recipe/meta.yaml
  pyproject.toml
Labels: status: accepted

#14145 Allow `Tooltip` to show in full-screen mode
  bokehjs/src/less/tooltips.less
  bokehjs/src/lib/models/ui/tooltip.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12951__doesn't_allow_usage_of_Tooltip_in_description_context.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13756__doesn't_correctly_position_Tooltip_when_using_nodes.blf
Labels: status: accepted, grant: CZI R6

#14251 Make `Toolbar` respect `Tool` visibility
  bokehjs/src/less/tool_button.less
  bokehjs/src/lib/core/view.ts
  bokehjs/src/lib/models/tools/tool_button.ts
  bokehjs/src/lib/models/tools/tool_proxy.ts
  bokehjs/src/lib/models/tools/toolbar.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'below'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'below'.png
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'left'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_GridPlot_toolbar_from_'above'_to_'right'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14246__doesn't_allow_to_correctly_update_Toolbar_after_changing_Tool_visiblity.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14246__doesn't_allow_to_correctly_update_Toolbar_after_changing_Tool_visiblity.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/models/tools/toolbar.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: status: accepted

#14277 Address late review comments from PR #14228
  bokehjs/src/lib/api/figure.ts
  bokehjs/src/lib/models/ui/menus/menu.ts
  bokehjs/test/integration/features.ts
  src/bokeh/plotting/_figure.py
  tests/unit/bokeh/plotting/test_figure.py
Labels: status: accepted

#14335 Fix broken stocks example data fetching
  conda/environment-release-build.yml
  conda/environment-test-3.10.yml
  conda/environment-test-3.11.yml
  conda/environment-test-3.12.yml
  conda/environment-test-3.13.yml
  conda/environment-test-minimal-deps.yml
  examples/server/app/stocks/app_hooks.py
  examples/server/app/stocks/main.py
Labels: status: accepted

#14326 Fix bokehjs/examples/hover
  bokehjs/examples/hover/hover.ts
Labels: status: accepted

#14343 Ignore unreachability errors related to `TypeIs` and narwhals
  src/bokeh/core/property/data_frame.py
Labels: status: accepted

#14340 Fix SpatialIndex.bounds
  bokehjs/src/lib/core/util/bbox.ts
  bokehjs/src/lib/core/util/spatial.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11508__doesn't_allow_to_correctly_compute_log_bounds_for_data_ranging.png
  bokehjs/test/integration/regressions.ts
  bokehjs/test/unit/core/util/bbox.ts
  bokehjs/test/unit/core/util/spatial.ts
Labels: status: ready

#14356 Fix `drawImage()` with transforms and clip-path in SVG
  bokehjs/src/lib/core/util/svg.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14265__doesn't_allow_to_correctly_drawImage_in_SVG_backend_with_transform_and_clip-path.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14265__doesn't_allow_to_correctly_drawImage_in_SVG_backend_with_transform_and_clip-path.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#14281 Replace tile range assertion with warning
  bokehjs/src/lib/models/tiles/mercator_tile_source.ts
  bokehjs/src/lib/models/tiles/tile_renderer.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14280__triggers_JS_error_when_adding_tile_without_defining_range.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14280__triggers_JS_error_when_adding_tile_without_defining_range.png
  bokehjs/test/integration/regressions.ts
Labels: status: accepted

#14358 Add support for value formatting to `ValueOf(obj, attr)`
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/dom/value_of.ts
  bokehjs/test/framework.ts
  bokehjs/test/unit/models/dom/value_of.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  examples/models/widgets.py
  src/bokeh/models/dom.py
  src/bokeh/models/dom.pyi
  tests/baselines/defaults.json5
Labels: status: accepted

#14361 fixed plot linking in tile provider example (tile_demo.py)
  examples/topics/geo/tile_demo.py
Labels: status: accepted

#14362 Correct whiskers in boxplot example
  examples/topics/stats/boxplot.py
Labels: status: accepted

#14368 Improve docstrings for LOD options
  src/bokeh/models/plots.py
Labels: status: accepted

#14332 remove unnecessary tools in legends example
  examples/models/legends.py
Labels: status: ready

#13546 Add support for progress widgets
  bokehjs/src/less/base.less
  bokehjs/src/less/widgets/progress.less
  bokehjs/src/less/widgets/switch.less
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/widgets/index.ts
  bokehjs/src/lib/models/widgets/indicator.ts
  bokehjs/src/lib/models/widgets/progress.ts
  bokehjs/src/lib/models/widgets/switch.ts
  bokehjs/test/baselines/linux/Widgets__should_support_Progress_indicator_widget__in_determinate_mode__and_horizontal_orientation.blf
  bokehjs/test/baselines/linux/Widgets__should_support_Progress_indicator_widget__in_determinate_mode__and_horizontal_orientation.png
  bokehjs/test/baselines/linux/Widgets__should_support_Progress_indicator_widget__in_determinate_mode__and_vertical_orientation.blf
  bokehjs/test/baselines/linux/Widgets__should_support_Progress_indicator_widget__in_determinate_mode__and_vertical_orientation.png
  bokehjs/test/integration/widgets.ts
  bokehjs/test/unit/base.ts
  bokehjs/test/unit/core/kinds.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
  docs/bokeh/source/docs/user_guide/interaction/widgets.rst
  examples/interaction/widgets/progress.py
  examples/models/widgets.py
  src/bokeh/core/properties.py
  src/bokeh/core/property/primitive.py
  src/bokeh/models/widgets/__init__.py
  src/bokeh/models/widgets/indicators.py
  src/bokeh/models/widgets/indicators.pyi
  src/bokeh/models/widgets/inputs.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/core/property/test_primitive.py
Labels: status: accepted

#14151 Show grab/grabbing cursor when moving box selection
  bokehjs/src/lib/core/ui_events.ts
  bokehjs/src/lib/models/annotations/box_annotation.ts
  bokehjs/test/interactive.ts
  bokehjs/test/unit/models/annotations/box_annotation.ts
  docs/bokeh/source/docs/releases/3.7.0.rst
Labels: status: accepted, grant: CZI R6

#14370 make radial glyph radius value required
  bokehjs/src/lib/models/glyphs/radial_glyph.ts
  bokehjs/test/integration/glyphs/glyphs.ts
  bokehjs/test/unit/api/plotting.ts
  bokehjs/test/unit/core/visuals.ts
  bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts
  bokehjs/test/unit/models/plots/plot.ts
  bokehjs/test/unit/models/ranges/data_range1d.ts
  bokehjs/test/unit/models/renderers/glyph_renderer.ts
  bokehjs/test/unit/models/tools/edit/poly_edit_tool.ts
  bokehjs/test/unit/models/tools/inspectors/hover_tool.ts
  bokehjs/test/unit/regressions.ts
  src/bokeh/models/glyphs.py
  tests/baselines/defaults.json5
  tests/unit/bokeh/models/test_glyphs.py
Labels: status: ready

#14373 Upgrade to TypeScript 5.8 and fix `npm audit`
  bokehjs/make/package.json
  bokehjs/package-lock.json
  bokehjs/src/compiler/package.json
Labels: status: accepted

#14371 Improve `Image` property and use it in `ImageURLTexture.url`
  docs/bokeh/source/docs/releases/3.7.0.rst
  src/bokeh/_specs.pyi
  src/bokeh/_types.pyi
  src/bokeh/core/property/visual.py
  src/bokeh/core/property/visual.pyi
  src/bokeh/core/property_aliases.pyi
  src/bokeh/core/property_mixins.pyi
  src/bokeh/models/mappers.pyi
  src/bokeh/models/ranges.pyi
  src/bokeh/models/textures.py
  src/bokeh/models/textures.pyi
  tests/unit/bokeh/core/property/test_visual.py
Labels: status: accepted
