Repository bokeh/bokeh, pull requests merged in 2025-05, with the labels that each got.

#14457 Fix positioning of DOM rendered Legend annotations
  bokehjs/src/less/canvas.less
  bokehjs/src/less/cartesian_frame.less
  bokehjs/src/less/toolbar.less
  bokehjs/src/lib/models/annotations/legend.ts
  bokehjs/src/lib/models/annotations/toolbar_panel.ts
  bokehjs/src/lib/models/canvas/canvas_panel.ts
  bokehjs/src/lib/models/canvas/cartesian_frame.ts
  bokehjs/src/lib/models/layouts/layout_dom.ts
  bokehjs/src/lib/models/plots/plot.ts
  bokehjs/src/lib/models/plots/plot_canvas.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#11623__doesn't_allow_changing_location_of_a_Plot_toolbar_from_'above'_to_'below'.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__above.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__above.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__above_with_multiple_legends.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__above_with_multiple_legends.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__below.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__below.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__below_with_multiple_legends.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__below_with_multiple_legends.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__left.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__left.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__left_with_multiple_legends.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__left_with_multiple_legends.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__right.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__right.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__right_with_multiple_legends.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_correctly_position_Legend_annotation_in_side_panel__right_with_multiple_legends.png
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_keep_toolbar_visible_if_renderers_change.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14451__doesn't_allow_to_keep_toolbar_visible_if_renderers_change.png
  bokehjs/test/baselines/linux/Bug__in_issue_#589__disallows_updating_legend_when_glyphs_change.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_above_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_above_inside_the_frame.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_below_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_below_inside_the_frame.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_left_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_left_inside_the_frame.png
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_right_inside_the_frame.blf
  bokehjs/test/baselines/linux/Plot__should_allow_toolbar_placement_right_inside_the_frame.png
  bokehjs/test/integration/regressions.ts
  src/bokeh/models/plots.py
  tests/unit/bokeh/models/test_plots.py
Labels: status: accepted, NEEDS BACK PORT

#14473 Improve corner case handling in datetime formatter
  bokehjs/src/lib/core/util/templating.ts
  bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
  bokehjs/src/lib/models/widgets/sliders/date_range_slider.ts
  bokehjs/src/lib/models/widgets/sliders/date_slider.ts
  bokehjs/src/lib/models/widgets/sliders/datetime_range_slider.ts
  bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
  bokehjs/test/unit/core/util/templating.ts
Labels: status: accepted

#14483 Avoid re-appending views if order is unchanged
  bokehjs/src/lib/models/layouts/layout_dom.ts
Labels: status: accepted, type: task, reso: completed

#14477 Fix log axis range below 1
  bokehjs/src/lib/models/tickers/log_ticker.ts
  bokehjs/test/unit/models/tickers/log_ticker.ts
  bokehjs/test/unit/regressions.ts
Labels: status: ready

#14479 Correctly render brushed steps
  bokehjs/src/lib/models/glyphs/step.ts
  bokehjs/src/lib/models/glyphs/webgl/step.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#12430__doesn't_correctly_show_selected_indices_of_Step_glyph.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#12430__doesn't_correctly_show_selected_indices_of_Step_glyph.png
  bokehjs/test/baselines/linux/Glyph_models__should_support_Step_with_NaN.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready

#14498 Remove unnecessary `type: ignore`
  src/bokeh/server/tornado.py
Labels: status: accepted

#14494 improve components embed indentation
  src/bokeh/core/_templates/js_resources.html
Labels: status: ready, type: task

#14495 improve error messages for bokeh serve --dev
  src/bokeh/command/bootstrap.py
  src/bokeh/command/subcommands/serve.py
  src/bokeh/command/util.py
  tests/unit/bokeh/command/subcommands/test_serve.py
  tests/unit/bokeh/command/test_util__command.py
Labels: status: ready

#14493 Fix incomplete selection in DateTimePicker
  bokehjs/src/lib/models/widgets/base_date_picker.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#13616__doesn't_reset_value_when_picker_is_closed_mid_selection.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#13616__doesn't_reset_value_when_picker_is_closed_mid_selection.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready

#14504 Keep DatetimePicker value when closing picker.
  bokehjs/src/lib/models/widgets/base_date_picker.ts
  bokehjs/src/lib/models/widgets/date_range_picker.ts
  bokehjs/src/lib/models/widgets/datetime_range_picker.ts
  bokehjs/test/baselines/linux/Bug__in_issue_#14503__doesn't_keep_picked_datetime_value_after_closing.blf
  bokehjs/test/baselines/linux/Bug__in_issue_#14503__doesn't_keep_picked_datetime_value_after_closing.png
  bokehjs/test/integration/regressions.ts
Labels: status: ready
